/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_gtk_GtkButtonPeer */

#ifndef _Included_gnu_java_awt_peer_gtk_GtkButtonPeer
#define _Included_gnu_java_awt_peer_gtk_GtkButtonPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gnu_java_awt_peer_gtk_GtkButtonPeer
 * Method:    gtkButtonNewWithLabel
 * Signature: (Ljava/awt/peer/ComponentPeer;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkButtonPeer_gtkButtonNewWithLabel
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     gnu_java_awt_peer_gtk_GtkButtonPeer
 * Method:    gtkButtonLabelSet
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkButtonPeer_gtkButtonLabelSet
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
