/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_gtk_GtkClipboard */

#ifndef _Included_gnu_java_awt_peer_gtk_GtkClipboard
#define _Included_gnu_java_awt_peer_gtk_GtkClipboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gnu_java_awt_peer_gtk_GtkClipboard
 * Method:    initNativeState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkClipboard_initNativeState
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_gtk_GtkClipboard
 * Method:    requestStringConversion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkClipboard_requestStringConversion
  (JNIEnv *, jclass);

/*
 * Class:     gnu_java_awt_peer_gtk_GtkClipboard
 * Method:    selectionGet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkClipboard_selectionGet
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
