/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_gtk_GtkFileDialogPeer */

#ifndef _Included_gnu_java_awt_peer_gtk_GtkFileDialogPeer
#define _Included_gnu_java_awt_peer_gtk_GtkFileDialogPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gnu_java_awt_peer_gtk_GtkFileDialogPeer
 * Method:    gtkFileSelectionNew
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkFileDialogPeer_gtkFileSelectionNew
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_gtk_GtkFileDialogPeer
 * Method:    gtkFileSelectionSetFilename
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkFileDialogPeer_gtkFileSelectionSetFilename
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
