/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_gtk_GtkGenericPeer */

#ifndef _Included_gnu_java_awt_peer_gtk_GtkGenericPeer
#define _Included_gnu_java_awt_peer_gtk_GtkGenericPeer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
