/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_gtk_GtkImagePainter */

#ifndef _Included_gnu_java_awt_peer_gtk_GtkImagePainter
#define _Included_gnu_java_awt_peer_gtk_GtkImagePainter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gnu_java_awt_peer_gtk_GtkImagePainter
 * Method:    drawPixels
 * Signature: (Lgnu/java/awt/peer/gtk/GdkGraphics;IIIIIII[III)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkImagePainter_drawPixels
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jint, jint, jint, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
