/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_gtk_GtkTextFieldPeer */

#ifndef _Included_gnu_java_awt_peer_gtk_GtkTextFieldPeer
#define _Included_gnu_java_awt_peer_gtk_GtkTextFieldPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gnu_java_awt_peer_gtk_GtkTextFieldPeer
 * Method:    gtkEntryNew
 * Signature: (Ljava/awt/peer/ComponentPeer;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkTextFieldPeer_gtkEntryNew
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     gnu_java_awt_peer_gtk_GtkTextFieldPeer
 * Method:    gtkEntryGetSize
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkTextFieldPeer_gtkEntryGetSize
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     gnu_java_awt_peer_gtk_GtkTextFieldPeer
 * Method:    gtkEntrySetEchoChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkTextFieldPeer_gtkEntrySetEchoChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     gnu_java_awt_peer_gtk_GtkTextFieldPeer
 * Method:    gtkEntryGetText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gnu_java_awt_peer_gtk_GtkTextFieldPeer_gtkEntryGetText
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_gtk_GtkTextFieldPeer
 * Method:    gtkEntrySetText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkTextFieldPeer_gtkEntrySetText
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
