/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_File */

#ifndef _Included_java_io_File
#define _Included_java_io_File
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_File
 * Method:    createInternal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_createInternal
  (JNIEnv *, jclass, jstring);

/*
 * Class:     java_io_File
 * Method:    canReadInternal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_canReadInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     java_io_File
 * Method:    canWriteInternal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_canWriteInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     java_io_File
 * Method:    setReadOnlyInternal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_setReadOnlyInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     java_io_File
 * Method:    existsInternal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_existsInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     java_io_File
 * Method:    isFileInternal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_isFileInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     java_io_File
 * Method:    isDirectoryInternal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_isDirectoryInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     java_io_File
 * Method:    lengthInternal
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_java_io_File_lengthInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     java_io_File
 * Method:    lastModifiedInternal
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_java_io_File_lastModifiedInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     java_io_File
 * Method:    setLastModifiedInternal
 * Signature: (Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_setLastModifiedInternal
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     java_io_File
 * Method:    deleteInternal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_deleteInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     java_io_File
 * Method:    mkdirInternal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_mkdirInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     java_io_File
 * Method:    renameToInternal
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_renameToInternal
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     java_io_File
 * Method:    listInternal
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_java_io_File_listInternal
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
