/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_RandomAccessFile */

#ifndef _Included_java_io_RandomAccessFile
#define _Included_java_io_RandomAccessFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_RandomAccessFile
 * Method:    open
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_java_io_RandomAccessFile_open
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    closeInternal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_java_io_RandomAccessFile_closeInternal
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    getFilePointerInternal
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_java_io_RandomAccessFile_getFilePointerInternal
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    lengthInternal
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_java_io_RandomAccessFile_lengthInternal
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    seekInternal
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_java_io_RandomAccessFile_seekInternal
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    setLengthInternal
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_java_io_RandomAccessFile_setLengthInternal
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    readInternal
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_java_io_RandomAccessFile_readInternal
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    skipInternal
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_java_io_RandomAccessFile_skipInternal
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    writeInternal
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_java_io_RandomAccessFile_writeInternal
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
