/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_ObjectInputStream */

#ifndef _Included_java_io_ObjectInputStream
#define _Included_java_io_ObjectInputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_ObjectInputStream
 * Method:    currentClassLoader
 * Signature: (Ljava/lang/SecurityManager;)Ljava/lang/ClassLoader;
 */
JNIEXPORT jobject JNICALL Java_java_io_ObjectInputStream_currentClassLoader
  (JNIEnv *, jclass, jobject);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    callReadMethod
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_callReadMethod
  (JNIEnv *, jobject, jobject, jclass);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    allocateObject
 * Signature: (Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_io_ObjectInputStream_allocateObject
  (JNIEnv *, jobject, jclass);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    callConstructor
 * Signature: (Ljava/lang/Class;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_callConstructor
  (JNIEnv *, jobject, jclass, jobject);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setBooleanField
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setBooleanField
  (JNIEnv *, jobject, jobject, jstring, jboolean);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setByteField
 * Signature: (Ljava/lang/Object;Ljava/lang/String;B)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setByteField
  (JNIEnv *, jobject, jobject, jstring, jbyte);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setCharField
 * Signature: (Ljava/lang/Object;Ljava/lang/String;C)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setCharField
  (JNIEnv *, jobject, jobject, jstring, jchar);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setDoubleField
 * Signature: (Ljava/lang/Object;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setDoubleField
  (JNIEnv *, jobject, jobject, jstring, jdouble);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setFloatField
 * Signature: (Ljava/lang/Object;Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setFloatField
  (JNIEnv *, jobject, jobject, jstring, jfloat);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setIntField
 * Signature: (Ljava/lang/Object;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setIntField
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setLongField
 * Signature: (Ljava/lang/Object;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setLongField
  (JNIEnv *, jobject, jobject, jstring, jlong);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setShortField
 * Signature: (Ljava/lang/Object;Ljava/lang/String;S)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setShortField
  (JNIEnv *, jobject, jobject, jstring, jshort);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setObjectField
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setObjectField
  (JNIEnv *, jobject, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
