/* LocaleInformation_tr.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_tr extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "Oca",
    "\u015eub",
    "Mar",
    "Nis",
    "May",
    "Haz",
    "Tem",
    "A\u011fu",
    "Eyl",
    "Eki",
    "Kas",
    "Ara",
    null,
  };

  private static final String[] months = {
    "Ocak",
    "\u015eubat",
    "Mart",
    "Nisan",
    "May\u0131s",
    "Haziran",
    "Temmuz",
    "A\u011fustos",
    "Eyl\u00fcl",
    "Ekim",
    "Kas\u0131m",
    "Aral\u0131k",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "Paz",
    "Pzt",
    "Sal",
    "\u00c7ar",
    "Per",
    "Cum",
    "Cmt",
  };

  private static final String[] weekdays = {
    null,
    "Pazar",
    "Pazartesi",
    "Sal\u0131",
    "\u00c7ar\u015famba",
    "Per\u015fembe",
    "Cuma",
    "Cumartesi",
  };

  private static final String[] eras = {
    "M\u00d6",
    "MS",
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Do\u011fu Timor");
        put("TK", "Tokelau");
        put("TJ", "Tacikistan");
        put("TH", "Tayland");
        put("TG", "Togo");
        put("TF", "Frans\u0131z G\u00fcney B\u00f6lgeleri");
        put("GY", "Guyana");
        put("TD", "\u00c7ad");
        put("TC", "Turks ve Caicos Adalar\u0131");
        put("GW", "Gine-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "G\u00fcney Georgia ve G\u00fcney Sandwich Adalar\u0131");
        put("GR", "Yunanistan");
        put("GQ", "Ekvator Ginesi");
        put("GP", "Guadeloupe");
        put("SZ", "Svaziland");
        put("SY", "Suriye");
        put("GN", "Gine");
        put("GM", "Gambia");
        put("GL", "Gr\u00f6nland");
        put("SV", "El Salvador");
        put("ST", "Sao Tome ve Principe");
        put("GI", "Cebelitar\u0131k");
        put("GH", "Gana");
        put("SR", "Surinam");
        put("GF", "Frans\u0131z Guyanas\u0131");
        put("SP", "S\u0131rbistan");
        put("GE", "G\u00fcrcistan");
        put("SO", "Somali");
        put("GD", "Granada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Birle\u015fik Krall\u0131k");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Slovakya");
        put("SJ", "Svalbard ve Jan Mayen");
        put("SI", "Slovenya");
        put("SH", "Saint Helena");
        put("SG", "Singapur");
        put("SE", "\u0130sve\u00e7");
        put("SD", "Sudan");
        put("SC", "Sey\u015feller");
        put("SB", "Solomon Adalar\u0131");
        put("SA", "Suudi Arabistan");
        put("FR", "Fransa");
        put("FO", "Faroe Adalar\u0131");
        put("FM", "Mikronezya Federal Eyaletleri");
        put("RW", "Ruanda");
        put("FK", "Falkland Adalar\u0131 (Malvinalar)");
        put("RU", "Rusya Federasyonu");
        put("FJ", "Fiji");
        put("FI", "Finlandiya");
        put("RO", "Romanya");
        put("RE", "Reunion");
        put("ET", "Etiyopya");
        put("ES", "\u0130spanya");
        put("ER", "Eritre");
        put("EH", "Bat\u0131 Sahara");
        put("EG", "M\u0131s\u0131r");
        put("EE", "Estonya");
        put("EC", "Ekvator");
        put("DZ", "Cezayir");
        put("QA", "Katar");
        put("DO", "Dominik Cumhuriyeti");
        put("PY", "Paraguay");
        put("DM", "Dominik");
        put("PW", "Palau");
        put("DK", "Danimarka");
        put("DJ", "Cibuti");
        put("PT", "Portekiz");
        put("PS", "Filistin B\u00f6lgesi");
        put("PR", "Porto Riko");
        put("DE", "Almanya");
        put("PN", "Pitcairn");
        put("PM", "Saint Pierre ve Miquelon");
        put("PL", "Polonya");
        put("PK", "Pakistan");
        put("PH", "Filipinler");
        put("PG", "Papua Yeni Gine");
        put("PF", "Frans\u0131z Polinezyas\u0131");
        put("CZ", "\u00c7ek Cumhuriyeti");
        put("PE", "Peru");
        put("CY", "K\u0131br\u0131s");
        put("CX", "Christmas Adas\u0131");
        put("CV", "Cape Verde");
        put("PA", "Panama");
        put("CU", "K\u00fcba");
        put("CR", "Kosta Rika");
        put("CO", "Kolombiya");
        put("CN", "\u00c7in");
        put("CM", "Kamerun");
        put("CL", "\u015eili");
        put("CK", "Cook Adalar\u0131");
        put("CI", "Fildi\u015fi Sahilleri");
        put("CH", "\u0130svi\u00e7re");
        put("CG", "Kongo");
        put("CF", "Orta Afrika Cumhuriyeti");
        put("CD", "Kongo Demokratik Cumhuriyeti");
        put("CC", "Cocos (Keeling) Adalar\u0131");
        put("OM", "Umman");
        put("CA", "Kanada");
        put("BZ", "Belize");
        put("BY", "Beyaz Rusya");
        put("BW", "Botsvana");
        put("BV", "Bouvet Adas\u0131");
        put("BT", "Bhutan");
        put("BS", "Bahamalar");
        put("BR", "Brezilya");
        put("NZ", "Yeni Zelanda");
        put("BO", "Bolivya");
        put("BN", "Brunei");
        put("BM", "Bermuda");
        put("NU", "Niue Adalar\u0131");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahreyn");
        put("NR", "Nauru Adas\u0131");
        put("BG", "Bulgaristan");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "Bel\u00e7ika");
        put("NO", "Norve\u00e7");
        put("BD", "Banglade\u015f");
        put("BB", "Barbados");
        put("ZW", "Zimbabwe");
        put("NL", "Hollanda");
        put("BA", "Bosna Hersek");
        put("NI", "Nikaragua");
        put("NG", "Nijerya");
        put("NF", "Norfolk Adas\u0131");
        put("AZ", "Azerbaycan");
        put("NE", "Nijer");
        put("NC", "Yeni Kaledonya");
        put("AW", "Aruba");
        put("ZM", "Zambiya");
        put("NA", "Namibya");
        put("AU", "Avustralya");
        put("AT", "Avusturya");
        put("AS", "Amerikan Samoas\u0131");
        put("AR", "Arjantin");
        put("AQ", "Antarktika");
        put("MZ", "Mozambik");
        put("AO", "Angola");
        put("MY", "Malezya");
        put("AN", "Hollanda Antilleri");
        put("MX", "Meksika");
        put("AM", "Ermenistan");
        put("MW", "Malavi");
        put("AL", "Arnavutluk");
        put("MV", "Maldivler");
        put("ZA", "G\u00fcney Afrika");
        put("MU", "Mauritius");
        put("MT", "Malta");
        put("AI", "Anguilla");
        put("MS", "Montserrat");
        put("MR", "Moritanya");
        put("AG", "Antigua ve Barbuda");
        put("MQ", "Martinik");
        put("AF", "Afganistan");
        put("MP", "Kuzey Mariana Adalar\u0131");
        put("AE", "Birle\u015fik Arap Emirlikleri");
        put("MO", "Makao S.A.R. \u00c7in");
        put("AD", "Andora");
        put("MN", "Mo\u011folistan");
        put("MM", "Myanmar");
        put("ML", "Mali");
        put("MK", "Makedonya Cumhuriyeti");
        put("YU", "Yugoslavya");
        put("YT", "Mayotte");
        put("MH", "Marshall Adalar\u0131");
        put("MG", "Madagaskar");
        put("MD", "Moldovya Cumhuriyeti");
        put("MC", "Monako");
        put("MA", "Fas");
        put("YE", "Yemen");
        put("LY", "Libya");
        put("LV", "Letonya");
        put("LU", "L\u00fcksemburg");
        put("LT", "Litvanya");
        put("LS", "Lesotho");
        put("LR", "Liberya");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Saint Lucia");
        put("LB", "L\u00fcbnan");
        put("LA", "Laos");
        put("KZ", "Kazakistan");
        put("KY", "Kayman Adalar\u0131");
        put("KW", "Kuveyt");
        put("KR", "G\u00fcney Kore");
        put("KP", "Kuzey Kore");
        put("KN", "Saint Kittler ve Neviler");
        put("KM", "Komorlar");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Kambo\u00e7ya");
        put("KG", "K\u0131rg\u0131zistan");
        put("KE", "Kenya");
        put("WF", "Wallis ve Futuna");
        put("JP", "Japonya");
        put("JO", "\u00dcrd\u00fcn");
        put("JM", "Jamaika");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "ABD Virgin Adalar\u0131");
        put("VG", "\u0130ngiliz Virgin Adalar\u0131");
        put("VE", "Venezuela");
        put("VC", "Saint Vincent ve Grenadinler");
        put("VA", "Kutsal Devlet (Vatikan \u015eehir Devleti)");
        put("IT", "\u0130talya");
        put("IS", "\u0130zlanda");
        put("IR", "\u0130ran");
        put("IQ", "Irak");
        put("UZ", "\u00d6zbekistan");
        put("IO", "Hint Okyanusu \u0130ngiliz B\u00f6lgesi");
        put("UY", "Uruguay");
        put("IN", "Hindistan");
        put("IL", "\u0130srail");
        put("US", "Amerika Birle\u015fik Devletleri");
        put("IE", "\u0130rlanda");
        put("ID", "Endonezya");
        put("UM", "Amerika Birle\u015fik Devletleri K\u00fc\u00e7\u00fck D\u0131\u015f Adalar\u0131");
        put("UG", "Uganda");
        put("UA", "Ukrayna");
        put("HU", "Macaristan");
        put("HT", "Haiti");
        put("HR", "H\u0131rvatistan");
        put("TZ", "Tanzanya");
        put("HN", "Honduras");
        put("HM", "Heard Adas\u0131 ve McDonald Adalar\u0131");
        put("TW", "Tayvan");
        put("TV", "Tuvalu");
        put("HK", "Hong Kong SAR - \u00c7in");
        put("TT", "Trinidad ve Tobago");
        put("TR", "T\u00fcrkiye");
        put("TO", "Tonga");
        put("TN", "Tunus");
        put("TM", "T\u00fcrkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("es", "\u0130spanyolca");
        put("ku", "K\u00fcrt\u00e7e");
        put("eo", "Esperanto");
        put("ks", "Ke\u015fmirce");
        put("en", "\u0130ngilizce");
        put("el", "Yunanca");
        put("qu", "Quechua");
        put("ko", "Korece");
        put("kn", "Kannada");
        put("km", "Kambo\u00e7ya Dili");
        put("kl", "Gr\u00f6nland Dili");
        put("kk", "Kazak Dili");
        put("wo", "Wolof");
        put("ka", "G\u00fcrc\u00fcce");
        put("dz", "Bhutan Dili");
        put("jv", "Java Dili");
        put("pt", "Portekizce");
        put("ps", "Pe\u015ftun Dili");
        put("de", "Almanca");
        put("pl", "Polonya Dili");
        put("da", "Danca");
        put("vo", "Volapuk");
        put("ja", "Japonca");
        put("vi", "Vietnam Dili");
        put("cy", "Gal Dili");
        put("pa", "Pencap Dili");
        put("cs", "\u00c7ek\u00e7e");
        put("iu", "Inuktitut");
        put("it", "\u0130talyanca");
        put("co", "Korsika Dili");
        put("is", "\u0130zlandaca");
        put("uz", "\u00d6zbek\u00e7e");
        put("or", "Oriya");
        put("ik", "Inupiak");
        put("ur", "Urduca");
        put("om", "Oromo (Afan)");
        put("ca", "Katalan Dili");
        put("ie", "Interlingue");
        put("id", "Endonezya Dili");
        put("uk", "Ukraynaca");
        put("ia", "Interlingua");
        put("oc", "Occitan");
        put("ug", "Uygurca");
        put("hy", "Ermenice");
        put("br", "Breton Dili");
        put("hu", "Macarca");
        put("bo", "Tibet\u00e7e");
        put("bn", "Bengal Dili");
        put("hr", "H\u0131rvat\u00e7a");
        put("bi", "Bislama");
        put("tw", "Twi");
        put("bh", "Bihari");
        put("bg", "Bulgarca");
        put("tt", "Tatarca");
        put("no", "Norve\u00e7\u00e7e");
        put("be", "Beyaz Rus\u00e7a");
        put("ts", "Tsonga");
        put("hi", "Hint Dili");
        put("tr", "T\u00fcrk\u00e7e");
        put("nl", "Hollanda Dili");
        put("zu", "Zulu");
        put("ba", "Ba\u015fk\u0131rt Dili");
        put("to", "Tonga");
        put("he", "\u0130branice");
        put("tn", "Setswana");
        put("tl", "Tagalog");
        put("tk", "T\u00fcrkmence");
        put("ha", "Hausa");
        put("ne", "Nepal Dili");
        put("az", "Azerice");
        put("ti", "Tigrinya");
        put("ay", "Aymara");
        put("th", "Tay Dili");
        put("tg", "Tacik Dili");
        put("na", "Nauru");
        put("te", "Telugu");
        put("zh", "\u00c7ince");
        put("ar", "Arap\u00e7a");
        put("ta", "Tamil");
        put("gu", "Gujarati");
        put("my", "Birmanya Dili");
        put("am", "Amharik");
        put("za", "Zhuang");
        put("mt", "Malta Dili");
        put("ms", "Malay");
        put("gn", "Guarani");
        put("sw", "Swahili");
        put("mr", "Marathi");
        put("sv", "\u0130sve\u00e7\u00e7e");
        put("gl", "Gali\u00e7ya Dili");
        put("su", "Sudan Dili");
        put("af", "Afrikaan Dili");
        put("st", "Sesotho");
        put("mo", "Moldavya Dili");
        put("ss", "Siswati");
        put("mn", "Mo\u011fol Dili");
        put("sr", "S\u0131rp\u00e7a");
        put("sq", "Arnavut\u00e7a");
        put("ml", "Malayalam");
        put("ab", "Abazca");
        put("mk", "Makedonca");
        put("aa", "Afar");
        put("so", "Somali Dili");
        put("sn", "Shona");
        put("mi", "Maori");
        put("gd", "\u0130sko\u00e7 Gal Dili");
        put("sm", "Samoa Dili");
        put("sl", "Slovence");
        put("mg", "Malaga Dili");
        put("sk", "Slovak\u00e7a");
        put("ga", "\u0130rlanda Dili");
        put("yo", "Yoruba");
        put("si", "Sinhal Dili");
        put("sh", "S\u0131rp-H\u0131rvat Dili");
        put("sg", "Sangho");
        put("yi", "Yiddi\u015f");
        put("sd", "Sindhi");
        put("fy", "Frizye Dili");
        put("sa", "Sanskrit\u00e7e");
        put("fr", "Frans\u0131zca");
        put("lv", "Letonya Dili");
        put("lt", "Litvanya Dili");
        put("fo", "Faroe Dili");
        put("rw", "Kinyarwanda");
        put("ru", "Rus\u00e7a");
        put("lo", "Laos Dili");
        put("fj", "Fiji Dili");
        put("ln", "Lingala");
        put("fi", "Fince");
        put("ro", "Romence");
        put("rn", "Kirundi");
        put("rm", "Rhaeto-Roman Dili");
        put("fa", "Fars\u00e7a");
        put("la", "Latince");
        put("xh", "Xhosa");
        put("eu", "Bask Dili");
        put("ky", "K\u0131rg\u0131zca");
        put("et", "Estonya Dili");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "shortDateFormat", "dd.MM.yyyy" },
    { "mediumDateFormat", "dd.MMM.yyyy" },
    { "longDateFormat", "dd MMMM yyyy EEEE" },
    { "fullDateFormat", "dd MMMM yyyy EEEE" },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
