/* LocaleInformation_is.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_is extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "jan",
    "feb",
    "mar",
    "apr",
    "ma\u00ed",
    "j\u00fan",
    "j\u00fal",
    "\u00e1g\u00fa",
    "sep",
    "okt",
    "n\u00f3v",
    "des",
    null,
  };

  private static final String[] months = {
    "jan\u00faar",
    "febr\u00faar",
    "mars",
    "apr\u00edl",
    "ma\u00ed",
    "j\u00fan\u00ed",
    "j\u00fal\u00ed",
    "\u00e1g\u00fast",
    "september",
    "okt\u00f3ber",
    "n\u00f3vember",
    "desember",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "sun",
    "m\u00e1n",
    "\u00feri",
    "mi\u00f0",
    "fim",
    "f\u00f6s",
    "lau",
  };

  private static final String[] weekdays = {
    null,
    "sunnudagur",
    "m\u00e1nudagur",
    "\u00feri\u00f0judagur",
    "mi\u00f0vikudagur",
    "fimmtudagur",
    "f\u00f6studagur",
    "laugardagur",
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Austur-T\u00edmor");
        put("TK", "T\u00f3kel\u00e1");
        put("TJ", "Tadsjikistan");
        put("TH", "Ta\u00edland");
        put("TG", "T\u00f3g\u00f3");
        put("TF", "Fr\u00f6nsku su\u00f0l\u00e6gu landsv\u00e6\u00f0in");
        put("GY", "Gv\u00e6jana");
        put("TD", "Tsjad");
        put("TC", "Turks- og Caicoseyjar");
        put("GW", "G\u00ednea-Biss\u00e1");
        put("GU", "Gvam");
        put("GT", "Gvatemala");
        put("GS", "Su\u00f0ur-Georg\u00eda og Su\u00f0ur-Sandv\u00edkureyjar");
        put("GR", "Grikkland");
        put("GQ", "Mi\u00f0baugs-G\u00ednea");
        put("GP", "Gvadel\u00fapeyjar");
        put("SZ", "Svas\u00edland");
        put("SY", "S\u00fdrland");
        put("GN", "G\u00ednea");
        put("GM", "Gamb\u00eda");
        put("GL", "Gr\u00e6nland");
        put("SV", "El Salvador");
        put("ST", "Sa\u00f3 T\u00f3me og Prins\u00edpe");
        put("GI", "G\u00edbraltar");
        put("GH", "Gana");
        put("SR", "S\u00far\u00ednam");
        put("GF", "Franska Gv\u00e6jana");
        put("SP", "Serb\u00eda");
        put("GE", "Georg\u00eda");
        put("SO", "S\u00f3mal\u00eda");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Mar\u00edn\u00f3");
        put("GB", "Bretland");
        put("SL", "S\u00ederra Le\u00f3ne");
        put("GA", "Gabon");
        put("SK", "Sl\u00f3vak\u00eda");
        put("SJ", "Svalbar\u00f0i og Jan Mayen");
        put("SI", "Sl\u00f3ven\u00eda");
        put("SH", "Sankti Helena");
        put("SG", "Singap\u00far");
        put("SE", "Sv\u00ed\u00fej\u00f3\u00f0");
        put("SD", "S\u00fadan");
        put("SC", "Seychelleseyjar");
        put("SB", "Sal\u00f3monseyjar");
        put("SA", "S\u00e1di-Arab\u00eda");
        put("FR", "Frakkland");
        put("FO", "F\u00e6reyjar");
        put("FM", "Mikr\u00f3nes\u00eda");
        put("RW", "R\u00faanda");
        put("FK", "Falklandseyjar");
        put("RU", "R\u00fassland");
        put("FJ", "F\u00eddjieyjar");
        put("FI", "Finnland");
        put("RO", "R\u00famen\u00eda");
        put("RE", "R\u00e9union");
        put("ET", "E\u00fe\u00ed\u00f3p\u00eda");
        put("ES", "Sp\u00e1nn");
        put("ER", "Er\u00edtrea");
        put("EH", "Vestur-Sahara");
        put("EG", "Egyptaland");
        put("EE", "Eistland");
        put("EC", "Ekvador");
        put("DZ", "Als\u00edr");
        put("QA", "Katar");
        put("DO", "D\u00f3min\u00edska l\u00fd\u00f0veldi\u00f0");
        put("PY", "Paragv\u00e6");
        put("DM", "D\u00f3min\u00edka");
        put("PW", "Pal\u00e1");
        put("DK", "Danm\u00f6rk");
        put("DJ", "Dj\u00edb\u00fat\u00ed");
        put("PT", "Port\u00fagal");
        put("PS", "Palest\u00edna");
        put("PR", "P\u00faert\u00f3 R\u00edk\u00f3");
        put("DE", "\u00de\u00fdskaland");
        put("PN", "Pitcairn");
        put("PM", "Sankti Pierre og Miquelon");
        put("PL", "P\u00f3lland");
        put("PK", "Pakistan");
        put("PH", "Filippseyjar");
        put("PG", "Pap\u00faa N\u00fdja-G\u00ednea");
        put("PF", "Franska P\u00f3l\u00fdnes\u00eda");
        put("CZ", "T\u00e9kkland");
        put("PE", "Per\u00fa");
        put("CY", "K\u00fdpur");
        put("CX", "J\u00f3laey");
        put("CV", "Gr\u00e6nh\u00f6f\u00f0aeyjar");
        put("CU", "K\u00faba");
        put("CR", "Kostar\u00edka");
        put("CO", "K\u00f3lumb\u00eda");
        put("CN", "K\u00edna");
        put("CM", "Kamer\u00fan");
        put("CK", "Cookseyjar");
        put("CI", "F\u00edlabeinsstr\u00f6ndin");
        put("CH", "Sviss");
        put("CG", "Vestur-Kong\u00f3");
        put("CF", "Mi\u00f0-Afr\u00edkul\u00fd\u00f0veldi\u00f0");
        put("CD", "Austur-Kong\u00f3");
        put("CC", "K\u00f3koseyjar");
        put("OM", "\u00d3man");
        put("CA", "Kanada");
        put("BZ", "Bel\u00eds");
        put("BY", "Hv\u00edta-R\u00fassland");
        put("BW", "Botsvana");
        put("BV", "Bouveteyja");
        put("BT", "B\u00fatan");
        put("BS", "Bahamaeyjar");
        put("BR", "Brasil\u00eda");
        put("NZ", "N\u00fdja-Sj\u00e1land");
        put("BO", "B\u00f3liv\u00eda");
        put("BN", "Br\u00fanei");
        put("BM", "Berm\u00fadaeyjar");
        put("NU", "Niue");
        put("BJ", "Ben\u00edn");
        put("BI", "B\u00far\u00fand\u00ed");
        put("BH", "Barein");
        put("NR", "N\u00e1r\u00fa");
        put("BG", "B\u00falgar\u00eda");
        put("BF", "B\u00fark\u00edna Fas\u00f3");
        put("NP", "Nepal");
        put("BE", "Belg\u00eda");
        put("NO", "Noregur");
        put("BD", "Bangladess");
        put("BB", "Barbados");
        put("NL", "Ni\u00f0url\u00f6nd");
        put("BA", "Bosn\u00eda og Herseg\u00f3v\u00edna");
        put("NI", "N\u00edkaragva");
        put("NG", "N\u00edger\u00eda");
        put("NF", "Norfolkeyja");
        put("AZ", "Aserba\u00eddsjan");
        put("NE", "N\u00edger");
        put("NC", "N\u00fdja-Kaled\u00f3n\u00eda");
        put("AW", "Ar\u00faba");
        put("ZM", "Samb\u00eda");
        put("NA", "Namib\u00eda");
        put("AU", "\u00c1stral\u00eda");
        put("AT", "Austurr\u00edki");
        put("AS", "Bandar\u00edska Sam\u00f3a");
        put("AR", "Argent\u00edna");
        put("AQ", "Su\u00f0urskautslandi\u00f0");
        put("MZ", "M\u00f3samb\u00edk");
        put("AO", "Ang\u00f3la");
        put("MY", "Malas\u00eda");
        put("AN", "Hollensku Antillur");
        put("MX", "Mex\u00edk\u00f3");
        put("AM", "Armen\u00eda");
        put("MW", "Malav\u00ed");
        put("AL", "Alban\u00eda");
        put("MV", "Mald\u00edveyjar");
        put("ZA", "Su\u00f0ur-Afr\u00edka");
        put("MU", "M\u00e1rit\u00edus");
        put("MT", "Malta");
        put("AI", "Angvilla");
        put("MS", "Montserrat");
        put("MR", "M\u00e1ritan\u00eda");
        put("AG", "Ant\u00edgva og Barb\u00fada");
        put("MQ", "Martin\u00edk");
        put("AF", "Afganistan");
        put("MP", "Nor\u00f0ur-Mar\u00edanaeyjar");
        put("AE", "Sameinu\u00f0u arab\u00edsku furstad\u00e6min");
        put("MO", "Maka\u00f3");
        put("AD", "Andorra");
        put("MN", "Mong\u00f3l\u00eda");
        put("MM", "Mjanmar");
        put("ML", "Mal\u00ed");
        put("MK", "Maked\u00f3n\u00eda");
        put("YU", "J\u00fag\u00f3slav\u00eda");
        put("YT", "Mayotte");
        put("MH", "Marshalleyjar");
        put("MG", "Madagaskar");
        put("MD", "Mold\u00f3va");
        put("MC", "M\u00f3nak\u00f3");
        put("MA", "Marokk\u00f3");
        put("YE", "Jemen");
        put("LY", "L\u00edb\u00eda");
        put("LV", "Lettland");
        put("LU", "L\u00faxemborg");
        put("LT", "Lith\u00e1en");
        put("LS", "Les\u00f3t\u00f3");
        put("LR", "L\u00edber\u00eda");
        put("LK", "Sr\u00ed Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Sankti L\u00fas\u00eda");
        put("LB", "L\u00edbanon");
        put("LA", "Laos");
        put("KZ", "Kasakstan");
        put("KY", "Caymaneyjar");
        put("KW", "K\u00faveit");
        put("KR", "Su\u00f0ur-K\u00f3rea");
        put("KP", "Nor\u00f0ur-K\u00f3rea");
        put("KN", "Sankti Krist\u00f3fer og Nevis");
        put("KM", "K\u00f3moreyjar");
        put("KI", "K\u00edribat\u00ed");
        put("WS", "Sam\u00f3a");
        put("KH", "Kamb\u00f3d\u00eda");
        put("KG", "Kirgisistan");
        put("KE", "Ken\u00eda");
        put("WF", "Wallis- og F\u00fat\u00fanaeyjar");
        put("JP", "Japan");
        put("JO", "J\u00f3rdan\u00eda");
        put("JM", "Jama\u00edka");
        put("VU", "Van\u00faat\u00fa");
        put("VN", "V\u00edetnam");
        put("VI", "J\u00f3mfr\u00faaeyjar (bandar\u00edsku)");
        put("VG", "J\u00f3mfr\u00faaeyjar (bresku)");
        put("VE", "Venes\u00faela");
        put("VC", "Sankti Vinsent og Grenad\u00edneyjar");
        put("VA", "P\u00e1fagar\u00f0ur");
        put("IT", "\u00cdtal\u00eda");
        put("IS", "\u00cdsland");
        put("IR", "\u00cdran");
        put("IQ", "\u00cdrak");
        put("UZ", "\u00dasbekistan");
        put("IO", "Bresku Indlandshafseyjar");
        put("UY", "\u00dar\u00fagv\u00e6");
        put("IN", "Indland");
        put("IL", "\u00cdsrael");
        put("US", "Bandar\u00edkin");
        put("IE", "\u00cdrland");
        put("ID", "Ind\u00f3nes\u00eda");
        put("UM", "Sm\u00e1eyjar Bandar\u00edkjanna");
        put("UG", "\u00daganda");
        put("UA", "\u00dakra\u00edna");
        put("HU", "Ungverjaland");
        put("HT", "Ha\u00edt\u00ed");
        put("HR", "Kr\u00f3at\u00eda");
        put("TZ", "Tansan\u00eda");
        put("HN", "Hond\u00faras");
        put("HM", "Heard og McDonaldseyjar");
        put("TW", "Ta\u00edvan");
        put("TV", "T\u00faval\u00fa");
        put("HK", "Hong Kong");
        put("TT", "Tr\u00ednidad og T\u00f3bag\u00f3");
        put("TR", "Tyrkland");
        put("TO", "Tonga");
        put("TN", "T\u00fanis");
        put("TM", "T\u00farkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("gwi", "Gv\u00eds\u00edn");
        put("akk", "Akkad\u00edska");
        put("eka", "Ekaj\u00fak");
        put("ijo", "\u00cdj\u00f3");
        put("xh", "S\u00f3sa");
        put("sux", "S\u00famerska");
        put("sus", "S\u00fas\u00fa");
        put("mis", "\u00ddmis m\u00e1l");
        put("loz", "Los\u00ed");
        put("tog", "Tongverska");
        put("pon", "Ponpeiska");
        put("min", "M\u00ednangkab\u00e1");
        put("suk", "S\u00fak\u00fama");
        put("wo", "Volof");
        put("lol", "Mong\u00f3");
        put("kut", "K\u00fatena\u00ed");
        put("mic", "Mikmak");
        put("wa", "Vall\u00f3nska");
        put("kum", "K\u00fam\u00edk");
        put("zap", "Sap\u00f3tek");
        put("cus", "K\u00fasit\u00edsk m\u00e1l (\u00f6nnur)");
        put("jbo", "Lojban");
        put("doi", "Dogr\u00ed");
        put("vo", "Volap\u00fck");
        put("oto", "\u00d3tomm\u00e1l");
        put("vi", "V\u00edetnamska");
        put("vai", "Va\u00ed");
        put("rar", "Rar\u00f3tongska");
        put("ve", "Venda");
        put("rap", "Rapan\u00fa\u00ed");
        put("raj", "Rajastan\u00ed");
        put("ota", "Tyrkneska, ott\u00f3man (1500-1928)");
        put("nzi", "Ns\u00edma");
        put("nap", "Nap\u00f3l\u00edska");
        put("uz", "\u00dasbekska");
        put("uga", "\u00dagar\u00edt\u00edska");
        put("tmh", "Tamasjek");
        put("nai", "Ind\u00ed\u00e1nam\u00e1l Nor\u00f0ur-Amer\u00edku (\u00f6nnur)");
        put("nah", "Nah\u00faatl");
        put("ur", "\u00dard\u00fa");
        put("fat", "Fant\u00ed");
        put("uk", "\u00dakra\u00ednska");
        put("egy", "Fornegypska");
        put("ug", "\u00da\u00edg\u00far");
        put("fan", "Fang");
        put("ssa", "N\u00edl\u00f3saharam\u00e1l (\u00f6nnur)");
        put("mga", "Mi\u00f0\u00edrska (900-1200)");
        put("bat", "Baltnesk m\u00e1l (\u00f6nnur)");
        put("nyo", "Nj\u00f3r\u00f3");
        put("bas", "Basa");
        put("nyn", "Njank\u00f3le");
        put("nym", "Njamves\u00ed");
        put("hmn", "Hmong");
        put("ban", "Bal\u00edska");
        put("osa", "\u00d3sage");
        put("bal", "Bal\u00fak\u00ed");
        put("ty", "Tah\u00edt\u00edska");
        put("bai", "Bam\u00edlekem\u00e1l");
        put("tw", "Tv\u00ed");
        put("srr", "Serer");
        put("tli", "Tlingit");
        put("tt", "Tatarska");
        put("ts", "Tsonga");
        put("bad", "Banda");
        put("tr", "Tyrkneska");
        put("to", "Tongverska");
        put("tn", "Ts\u00faana");
        put("tl", "Tagalog");
        put("tk", "T\u00farkmenska");
        put("ti", "T\u00edgrinja");
        put("th", "Ta\u00edlenska");
        put("kru", "K\u00far\u00fak");
        put("tg", "Tadsjikska");
        put("byn", "Bl\u00edn");
        put("te", "Tel\u00fag\u00fa");
        put("kro", "Kr\u00fa");
        put("csb", "Kas\u00fab\u00edska");
        put("ta", "Tam\u00edlska");
        put("tkl", "T\u00f3kel\u00e1ska");
        put("efi", "Ef\u00edk");
        put("sw", "Svah\u00edl\u00ed");
        put("sv", "S\u00e6nska");
        put("su", "S\u00fandanska");
        put("krc", "Karasa\u00edbalkar");
        put("st", "Su\u00f0urs\u00f3t\u00f3");
        put("ss", "Svat\u00ed");
        put("sr", "Serbneska");
        put("sq", "Albanska");
        put("men", "Mende");
        put("crp", "Kre\u00f3l- og pidginm\u00e1l (\u00f6nnur)");
        put("so", "S\u00f3malska");
        put("afh", "Afr\u00edh\u00edl\u00ed");
        put("sn", "S\u00edn\u00f3t\u00edbesk m\u00e1l (\u00f6nnur)");
        put("sm", "Sam\u00f3ska");
        put("sl", "Sl\u00f3venska");
        put("grc", "Forngr\u00edska (til 1453)");
        put("sk", "Sl\u00f3vak\u00edska");
        put("grb", "Gerb\u00f3");
        put("si", "Singales\u00edska");
        put("sh", "Serb\u00f3kr\u00f3at\u00edska");
        put("crh", "Kr\u00edmtyrkneska");
        put("afa", "Afr\u00f3as\u00edsk m\u00e1l (\u00f6nnur)");
        put("sg", "Sang\u00f3");
        put("se", "Nor\u00f0ursam\u00edska");
        put("sd", "Sind\u00ed");
        put("udm", "\u00dadm\u00fart");
        put("sc", "Sard\u00ednska");
        put("sa", "Sanskr\u00edt");
        put("rw", "K\u00ednjarvanda");
        put("ru", "R\u00fassneska");
        put("mdr", "Mandar");
        put("ro", "R\u00famenska");
        put("rn", "R\u00fand\u00ed");
        put("rm", "Ret\u00f3r\u00f3manska");
        put("mdf", "Moksa");
        put("tiv", "T\u00edv");
        put("ady", "Ad\u00fdge");
        put("zun", "S\u00fan\u00ed");
        put("kpe", "Kpelle");
        put("qu", "Kvesj\u00faa");
        put("tig", "T\u00edgre");
        put("son", "Songha\u00ed");
        put("cpp", "Kre\u00f3l- og pidginm\u00e1l \u00e1 port\u00fag\u00f6lskum grunni");
        put("sog", "Sogd\u00eden");
        put("ada", "Adangme");
        put("kos", "Kosraska");
        put("hit", "Hettit\u00edska");
        put("cpf", "Kre\u00f3l- og pidginm\u00e1l \u00e1 fr\u00f6nskum grunni");
        put("cpe", "Kre\u00f3l- og pidginm\u00e1l \u00e1 enskum grunni");
        put("him", "H\u00edmasjal\u00ed");
        put("kok", "Konkan\u00ed");
        put("hil", "H\u00edliga\u00ednon");
        put("got", "Gotneska");
        put("gor", "Gorontal\u00f3");
        put("gon", "Gond\u00ed");
        put("din", "Dinka");
        put("nub", "N\u00fab\u00edsk m\u00e1l");
        put("pt", "Port\u00fagalska");
        put("ps", "Past\u00fa");
        put("fur", "Fr\u00ed\u00falska");
        put("phn", "F\u00f6nik\u00edska");
        put("goh", "Fornh\u00e1\u00fe\u00fdska (um 750-1050)");
        put("snk", "S\u00f3ninke");
        put("cop", "Kopt\u00edska");
        put("yap", "Jap\u00edska");
        put("ach", "Ak\u00f3l\u00ed");
        put("yao", "Ja\u00f3");
        put("phi", "Filippseysk m\u00e1l (\u00f6nnur)");
        put("pl", "P\u00f3lska");
        put("ace", "Akk\u00edska");
        put("pi", "Pal\u00ed");
        put("pa", "P\u00fanjab\u00ed");
        put("bug", "B\u00fag\u00edska");
        put("iba", "\u00cdban");
        put("sms", "Skoltesam\u00edska");
        put("bua", "B\u00far\u00edat");
        put("mas", "Masa\u00ed");
        put("smn", "Enaresam\u00edska");
        put("os", "Osset\u00edska");
        put("map", "\u00c1str\u00f3nes\u00edska");
        put("or", "\u00d3r\u00eda");
        put("man", "Manding\u00f3");
        put("smj", "L\u00falesam\u00edska");
        put("smi", "Sam\u00edsk m\u00e1l (\u00f6nnur)");
        put("mak", "Makasar");
        put("om", "\u00d3r\u00f3m\u00f3");
        put("mai", "Ma\u00edt\u00edl\u00ed");
        put("oj", "Ojibva");
        put("mag", "Magah\u00ed");
        put("mad", "Mad\u00farska");
        put("sma", "Su\u00f0ursam\u00edska");
        put("oc", "Okkit\u00edska (eftir 1500); Pr\u00f3vensalska");
        put("nso", "Nor\u00f0urs\u00f3t\u00f3");
        put("btk", "Batak");
        put("myv", "Ersja");
        put("dgr", "Dogr\u00edb");
        put("ny", "Njanja; S\u00edsjeva; Sjeva");
        put("myn", "Majam\u00e1l");
        put("nv", "Navah\u00f3");
        put("kmb", "Kimb\u00fand\u00fa");
        put("nr", "Su\u00f0urndebele");
        put("gmh", "Mi\u00f0h\u00e1\u00fe\u00fdska (um 1050-1500");
        put("no", "Norska");
        put("nn", "N\u00fdnorska");
        put("nl", "Hollenska");
        put("ng", "Ndonga");
        put("sla", "Slavnesk m\u00e1l (\u00f6nnur)");
        put("ne", "Nepalska");
        put("nd", "Nor\u00f0urndebele");
        put("cmc", "Kam\u00edsk m\u00e1l");
        put("tet", "Tet\u00fam");
        put("nb", "Norskt b\u00f3km\u00e1l");
        put("na", "N\u00e1r\u00faska");
        put("ter", "Teren\u00f3");
        put("tem", "T\u00edmne");
        put("my", "Burmneska");
        put("lez", "Lesg\u00edska");
        put("mt", "Maltneska");
        put("peo", "Fornpersneska");
        put("ms", "Mala\u00edska");
        put("mr", "Marat\u00ed");
        put("fro", "Fornfranska (842 - um 1400)");
        put("mo", "Mold\u00f3vska");
        put("frm", "Mi\u00f0franska (um 1400-1600)");
        put("mn", "Mong\u00f3lska");
        put("jrb", "Gy\u00f0ingaarab\u00edska");
        put("ml", "Malajalam");
        put("mk", "Maked\u00f3nska");
        put("mi", "Ma\u00f3r\u00ed");
        put("mh", "Marshallska");
        put("mg", "Malagas\u00edska");
        put("mwr", "Marvar\u00ed");
        put("bra", "Bra\u00ed");
        put("den", "Slav");
        put("lv", "Lettneska");
        put("lu", "L\u00fabakatanga");
        put("del", "Delaver");
        put("lt", "Lith\u00e1\u00edska");
        put("lo", "La\u00f3");
        put("ln", "Lingala");
        put("li", "Limb\u00farg\u00edska");
        put("ewo", "Evond\u00f3");
        put("lg", "Ganda");
        put("lb", "L\u00faxemborg\u00edska");
        put("la", "Lat\u00edna");
        put("jpr", "Gy\u00f0ingapersneska");
        put("vot", "Vot\u00edska");
        put("sit", "S\u00edn\u00f3t\u00edbesk m\u00e1l (\u00f6nnur)");
        put("ky", "Kirgiska");
        put("kw", "Korn\u00edska");
        put("kv", "Kom\u00edska");
        put("ku", "K\u00fardneska");
        put("sio", "S\u00ed\u00fam\u00e1l");
        put("ks", "Kasm\u00edrska");
        put("kr", "Kan\u00far\u00ed");
        put("awa", "Avad\u00ed");
        put("ko", "K\u00f3reska");
        put("kn", "Kannada");
        put("km", "Kmer");
        put("kl", "Gr\u00e6nlenska");
        put("kk", "Kasakska");
        put("rom", "Roman\u00ed");
        put("kj", "K\u00faanjama");
        put("sid", "S\u00eddam\u00f3");
        put("ki", "K\u00edk\u00faj\u00fa");
        put("kg", "Kong\u00f3");
        put("non", "Norr\u00e6na");
        put("ka", "Georg\u00edska");
        put("mus", "Kr\u00edk");
        put("roa", "R\u00f3m\u00f6nsk m\u00e1l (\u00f6nnur)");
        put("nog", "N\u00f3ga\u00ed");
        put("mun", "M\u00fandam\u00e1l");
        put("mul", "Margv\u00edsleg m\u00e1l");
        put("jv", "Javanska");
        put("gil", "Gilberska");
        put("znd", "Sande");
        put("shn", "Sjan");
        put("fon", "F\u00f3n");
        put("xal", "Kalm\u00fakska");
        put("aus", "\u00c1str\u00f6lsk m\u00e1l");
        put("kho", "Kotaska");
        put("ja", "Japanska");
        put("khi", "Ko\u00edm\u00e1l (\u00f6nnur)");
        put("pau", "Pal\u00e1ska");
        put("chy", "Sjeyen");
        put("tai", "Ta\u00edm\u00e1l (\u00f6nnur)");
        put("iu", "In\u00faktit\u00fat");
        put("pap", "Pap\u00edament\u00f3");
        put("it", "\u00cdtalska");
        put("sgn", "T\u00e1knm\u00e1l");
        put("is", "\u00cdslenska");
        put("kha", "Kas\u00ed");
        put("chr", "Sjer\u00f3k\u00ed");
        put("pam", "Pampanga");
        put("pal", "Palav\u00ed");
        put("chp", "S\u00edpev\u00edska");
        put("io", "\u00cdd\u00f3");
        put("cho", "Sjokt\u00e1");
        put("chn", "S\u00edn\u00fak");
        put("chm", "Mar\u00ed");
        put("tyv", "T\u00fav\u00ednska");
        put("bnt", "Bant\u00fam\u00e1l");
        put("pag", "Pangas\u00ednm\u00e1l");
        put("ik", "\u00cdn\u00fap\u00edak");
        put("chk", "Sj\u00fak\u00edska");
        put("ii", "S\u00eds\u00faanj\u00ed");
        put("haw", "Hava\u00edska");
        put("lam", "Lamba");
        put("ig", "\u00cdgb\u00f3");
        put("chg", "Sjagata\u00ed");
        put("sga", "Forn\u00edrska (til 900)");
        put("paa", "Pap\u00fask m\u00e1l (\u00f6nnur)");
        put("ie", "Interlingva");
        put("id", "Ind\u00f3nes\u00edska");
        put("lah", "Landa");
        put("day", "Dajak");
        put("chb", "S\u00edbsja");
        put("ia", "Interlingva");
        put("lad", "Lad\u00ednska");
        put("hz", "Herer\u00f3");
        put("hai", "Ha\u00edda");
        put("dar", "Dargva");
        put("hy", "Armenska");
        put("ath", "Atapask\u00edsk m\u00e1l");
        put("hu", "Ungverska");
        put("ht", "Ha\u00edt\u00edska");
        put("dak", "Dak\u00f3ta");
        put("hr", "Kr\u00f3at\u00edska");
        put("ho", "H\u00edr\u00edm\u00f3t\u00fa");
        put("hi", "Hind\u00ed");
        put("dyu", "Dj\u00fala");
        put("he", "Hebreska");
        put("ast", "Ast\u00far\u00edska");
        put("ha", "H\u00e1sa");
        put("wen", "Sorbnesk m\u00e1l");
        put("gv", "Manx");
        put("gu", "G\u00fajarat\u00ed");
        put("sem", "Sem\u00edsk m\u00e1l (\u00f6nnur)");
        put("sel", "Selk\u00fap");
        put("iro", "\u00cdr\u00f3kesk m\u00e1l");
        put("gn", "Gvaran\u00ed");
        put("gl", "Gallegska");
        put("arw", "Aravakska");
        put("gez", "G\u00eds");
        put("art", "Al\u00fej\u00f3\u00f0am\u00e1l (\u00f6nnur)");
        put("gd", "Skosk gel\u00edska");
        put("ira", "\u00cdranska");
        put("ga", "\u00cdrska");
        put("arp", "Arapah\u00f3");
        put("arn", "Ar\u00e1kan\u00edska");
        put("fy", "Fr\u00edsneska");
        put("bla", "Siksika");
        put("gem", "Germ\u00f6nsk m\u00e1l (\u00f6nnur)");
        put("ypk", "J\u00fap\u00edsk m\u00e1l");
        put("arc", "Arame\u00edska");
        put("fr", "Franska");
        put("fo", "F\u00e6reyska");
        put("cel", "Keltnesk (\u00f6nnur)");
        put("fj", "F\u00eddjeyska");
        put("fi", "Finnska");
        put("ff", "F\u00fala");
        put("tvl", "T\u00faval\u00faska");
        put("ceb", "Keb\u00faan\u00f3");
        put("fa", "Persneska");
        put("eu", "Baskneska");
        put("sco", "Skoska");
        put("et", "Eistneska");
        put("es", "Sp\u00e6nska");
        put("eo", "Esperant\u00f3");
        put("en", "Enska");
        put("el", "N\u00fdgr\u00edska (1453-)");
        put("tut", "Alta\u00edsk m\u00e1l (\u00f6nnur)");
        put("niu", "N\u00edveska");
        put("tup", "T\u00fap\u00edm\u00e1l");
        put("ee", "Eve");
        put("tum", "T\u00famb\u00faka");
        put("mos", "Moss\u00ed");
        put("dz", "Dsongka");
        put("nic", "N\u00edgerkord\u00f3fanm\u00e1l (\u00f6nnur)");
        put("lus", "L\u00fasa\u00ed");
        put("fiu", "Finnsk\u00fagr\u00edsk m\u00e1l (\u00f6nnur)");
        put("dv", "D\u00edveh\u00ed");
        put("nia", "N\u00edas");
        put("moh", "M\u00f3h\u00edska");
        put("luo", "L\u00fa\u00f3");
        put("lun", "L\u00fanda");
        put("apa", "Apatsjam\u00e1l");
        put("lui", "L\u00faisen\u00f3");
        put("hup", "H\u00fapa");
        put("bin", "B\u00edn\u00ed");
        put("de", "\u00de\u00fdska");
        put("lua", "L\u00fabal\u00fal\u00faa");
        put("bik", "B\u00edkol");
        put("was", "Vasj\u00f3");
        put("und", "\u00d3lj\u00f3st");
        put("war", "Vara\u00ed");
        put("da", "Danska");
        put("dum", "Mi\u00f0hollenska (um 1050-1350)");
        put("wal", "Valam\u00f3");
        put("mno", "Man\u00f3b\u00f3m\u00e1l");
        put("wak", "Vakasm\u00e1l");
        put("sat", "Santal\u00ed");
        put("cy", "Velska");
        put("sas", "Sasak");
        put("kbd", "Kabard\u00edska");
        put("cv", "Sj\u00favas");
        put("cu", "Kirkjuslavneska");
        put("mni", "Man\u00edp\u00far\u00ed");
        put("cs", "T\u00e9kkneska");
        put("sam", "Samversk arame\u00edska");
        put("cr", "Kr\u00ed");
        put("sal", "Sal\u00edsm\u00e1l");
        put("dua", "D\u00faala");
        put("co", "Kors\u00edska");
        put("sai", "Ind\u00ed\u00e1nam\u00e1l Su\u00f0ur-Amer\u00edku (\u00f6nnur)");
        put("mnc", "Mansj\u00fa");
        put("sah", "Jak\u00fat");
        put("kaw", "Kav\u00ed");
        put("inh", "Ing\u00fas");
        put("gba", "Gbaja");
        put("sad", "Sandave");
        put("ch", "Kamorr\u00f3");
        put("ine", "Ind\u00f3evr\u00f3psk m\u00e1l (\u00f6nnur)");
        put("bho", "Bojp\u00far\u00ed");
        put("enm", "Mi\u00f0enska (1100-1500)");
        put("kar", "Karen");
        put("inc", "Indversk m\u00e1l (\u00f6nnur)");
        put("ce", "Tsjetsjenska");
        put("gay", "Gaj\u00f3");
        put("ca", "Katal\u00f3nska");
        put("umb", "\u00damb\u00fand\u00fa");
        put("syr", "S\u00fdrlenska");
        put("kam", "Kamba");
        put("tsi", "Tsims\u00edska");
        put("ang", "Fornenska (um 450-1100)");
        put("kac", "Kas\u00edn");
        put("cau", "K\u00e1kasusm\u00e1l (\u00f6nnur)");
        put("kab", "Kab\u00edle");
        put("kaa", "Karakalpak");
        put("bs", "Bosn\u00edska");
        put("car", "Kar\u00edbam\u00e1l");
        put("br", "Bret\u00f3nska");
        put("bo", "T\u00edbeska");
        put("bn", "Bengalska");
        put("bm", "Bambara");
        put("gaa", "Ga");
        put("cai", "Ind\u00ed\u00e1nam\u00e1l Mi\u00f0-Amer\u00edku (\u00f6nnur)");
        put("bi", "B\u00edslama");
        put("bh", "B\u00edhar\u00ed");
        put("bg", "B\u00falgarska");
        put("be", "Hv\u00edtr\u00fassneska");
        put("cad", "Kadd\u00f3");
        put("ba", "Bask\u00edr");
        put("zu", "S\u00fal\u00fa");
        put("zen", "Senaga");
        put("pro", "Fornpr\u00f3vensalska (til 1500)");
        put("hsb", "H\u00e1sorbneska");
        put("az", "Aserska");
        put("ay", "A\u00edmara");
        put("av", "Avar\u00edska");
        put("as", "Assamska");
        put("dsb", "L\u00e1gsorbneska");
        put("ar", "Arab\u00edska");
        put("ilo", "\u00cdlok\u00f3");
        put("elx", "Elam\u00edt");
        put("zh", "K\u00ednverska");
        put("an", "Aragonska");
        put("pra", "Prakr\u00edtm\u00e1l");
        put("am", "Amhar\u00edska");
        put("new", "Nevar\u00ed");
        put("ak", "Akan");
        put("za", "S\u00faang");
        put("af", "Afr\u00edkanska");
        put("ae", "Avest\u00edska");
        put("ab", "Abkas\u00edska");
        put("yo", "J\u00f3r\u00faba");
        put("alg", "Algonkv\u00ednsk m\u00e1l");
        put("ale", "Ale\u00faska");
        put("mkh", "Monkmerm\u00e1l (\u00f6nnur)");
        put("yi", "Jidd\u00edska");
        put("dra", "Dravid\u00edsk m\u00e1l (\u00f6nnur)");
        put("ber", "Berbam\u00e1l");
        put("nds", "L\u00e1g\u00fe\u00fdska; L\u00e1gsaxneska");
        put("bem", "Bemba");
        put("bej", "Beja");
        put("tpi", "Tokpisin");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "shortDateFormat", "d.M.yyyy" },
    { "mediumDateFormat", "d.M.yyyy" },
    { "longDateFormat", "d. MMMM yyyy" },
    { "fullDateFormat", "EEEE, d. MMMM yyyy" },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
