/* LocaleInformation_zh_Hant.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_zh_Hant extends ListResourceBundle
{
  private static final String[][] zoneStrings =
  {
    { "America/Los_Angeles", "\u592a\u5e73\u6d0b\u6a19\u6e96\u6642\u9593", "", "\u592a\u5e73\u6d0b\u65e5\u5149\u7bc0\u7d04\u6642\u9593", "" },
    { "Africa/Casablanca", "\u683c\u6797\u5a01\u6cbb\u6a19\u6e96\u6642\u9593", "", "\u683c\u6797\u5a01\u6cbb\u6a19\u6e96\u6642\u9593", "" },
    { "America/New_York", "\u6771\u90e8\u6a19\u6e96\u6642\u9593", "", "\u6771\u90e8\u65e5\u5149\u7bc0\u7d04\u6642\u9593", "" },
    { "America/Anchorage", "\u963f\u62c9\u65af\u52a0\u6a19\u6e96\u6642\u9593", "", "\u963f\u62c9\u65af\u52a0\u65e5\u5149\u7bc0\u7d04\u6642\u9593", "" },
    { "Etc/GMT", "\u683c\u6797\u5a01\u6cbb\u6a19\u6e96\u6642\u9593", "", "\u683c\u6797\u5a01\u6cbb\u6a19\u6e96\u6642\u9593", "" },
    { "Asia/Shanghai", "\u4e2d\u570b\u6a19\u6e96\u6642\u9593", "", "\u4e2d\u570b\u6a19\u6e96\u6642\u9593", "" },
    { "America/Halifax", "\u5927\u897f\u6d0b\u6a19\u6e96\u6642\u9593", "", "\u5927\u897f\u6d0b\u65e5\u5149\u7bc0\u7d04\u6642\u9593", "" },
    { "Europe/Paris", "\u4e2d\u6b50\u6a19\u6e96\u6642\u9593", "", "\u4e2d\u6b50\u65e5\u5149\u7bc0\u7d04\u6642\u9593", "" },
    { "America/Denver", "\u5c71\u5340\u6a19\u6e96\u6642\u9593", "", "\u5c71\u5340\u65e5\u5149\u7bc0\u7d04\u6642\u9593", "" },
    { "Asia/Jerusalem", "\u4ee5\u8272\u5217\u6a19\u6e96\u6642\u9593", "", "\u4ee5\u8272\u5217\u65e5\u5149\u7bc0\u7d04\u6642\u9593", "" },
    { "Pacific/Honolulu", "\u590f\u5a01\u5937\u6a19\u6e96\u6642\u9593", "", "\u590f\u5a01\u5937\u6a19\u6e96\u6642\u9593", "" },
    { "America/St_Johns", "\u7d10\u82ac\u862d\u6a19\u6e96\u6642\u9593", "", "\u7d10\u82ac\u862d\u65e5\u5149\u7bc0\u7d04\u6642\u9593", "" },
    { "America/Indianapolis", "\u6771\u90e8\u6a19\u6e96\u6642\u9593", "", "\u6771\u90e8\u6a19\u6e96\u6642\u9593", "" },
    { "America/Chicago", "\u4e2d\u90e8\u6a19\u6e96\u6642\u9593", "", "\u4e2d\u90e8\u65e5\u5149\u7bc0\u7d04\u6642\u9593", "" },
    { "Europe/Bucharest", "\u6771\u6b50\u6a19\u6e96\u6642\u9593", "", "\u6771\u6b50\u65e5\u5149\u7bc0\u7d04\u6642\u9593", "" },
    { "Asia/Tokyo", "\u65e5\u672c\u6a19\u6e96\u6642\u9593", "", "\u65e5\u672c\u6a19\u6e96\u6642\u9593", "" },
    { "America/Phoenix", "\u5c71\u5340\u6a19\u6e96\u6642\u9593", "", "\u5c71\u5340\u6a19\u6e96\u6642\u9593", "" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "\u6771\u5e1d\u6587");
        put("TK", "\u6258\u514b\u52de\u7fa4\u5cf6");
        put("TJ", "\u5854\u5409\u514b");
        put("TH", "\u6cf0\u570b");
        put("TG", "\u591a\u54e5\u5171\u548c\u570b");
        put("TF", "\u6cd5\u570b\u5357\u5c6c\u5730");
        put("GY", "\u84cb\u4e9e\u7d0d");
        put("TD", "\u67e5\u5fb7");
        put("TC", "\u571f\u514b\u65af\u53ca\u958b\u79d1\u65af\u7fa4\u5cf6");
        put("GW", "\u5e7e\u5167\u4e9e\u6bd4\u7d22");
        put("GU", "\u95dc\u5cf6");
        put("GT", "\u74dc\u5730\u99ac\u62c9");
        put("GS", "\u5357\u55ac\u6cbb\u4e9e\u8207\u5357\u4e09\u660e\u6cbb\u7fa4\u5cf6");
        put("GR", "\u5e0c\u81d8");
        put("GQ", "\u8d64\u9053\u5e7e\u5167\u4e9e");
        put("GP", "\u54e5\u5fb7\u666e\u6d1b");
        put("SZ", "\u53f2\u74e6\u6fdf\u862d");
        put("SY", "\u6558\u5229\u4e9e");
        put("GN", "\u5e7e\u5167\u4e9e");
        put("GM", "\u7518\u6bd4\u4e9e");
        put("GL", "\u683c\u9675\u862d");
        put("SV", "\u85a9\u723e\u74e6\u591a");
        put("ST", "\u8056\u591a\u7f8e\u53ca\u666e\u6797\u897f\u6bd4");
        put("GI", "\u76f4\u5e03\u7f85\u9640");
        put("GH", "\u8fe6\u7d0d");
        put("SR", "\u8607\u5229\u5357");
        put("GF", "\u6cd5\u5c6c\u572d\u4e9e\u90a3");
        put("SP", "\u585e\u723e\u7dad\u4e9e");
        put("GE", "\u55ac\u6cbb\u4e9e\u5171\u548c\u570b");
        put("SO", "\u7d22\u99ac\u5229\u4e9e");
        put("GD", "\u683c\u745e\u7d0d\u9054");
        put("SN", "\u585e\u5167\u52a0\u723e");
        put("SM", "\u8056\u99ac\u5229\u8afe");
        put("GB", "\u82f1\u570b");
        put("SL", "\u7345\u5b50\u5c71");
        put("GA", "\u52a0\u5f6d");
        put("SJ", "\u51b7\u5cb8\u53ca\u592e\u9ea5\u6069\u7fa4\u5cf6");
        put("SI", "\u65af\u6d1b\u7dad\u5c3c\u4e9e");
        put("SH", "\u8056\u8d6b\u52d2\u62ff\u5cf6");
        put("SD", "\u8607\u4e39");
        put("SC", "\u585e\u5e2d\u723e");
        put("SB", "\u7d22\u7f85\u9580\u7fa4\u5cf6");
        put("SA", "\u6c99\u70cf\u5730\u963f\u62c9\u4f2f");
        put("FR", "\u6cd5\u570b");
        put("FO", "\u6cd5\u7f85\u7fa4\u5cf6");
        put("FM", "\u5bc6\u514b\u7f85\u5c3c\u897f\u4e9e\u7fa4\u5cf6");
        put("RW", "\u76e7\u5b89\u9054");
        put("FK", "\u798f\u514b\u862d\u7fa4\u5cf6");
        put("RU", "\u4fc4\u7f85\u65af");
        put("FJ", "\u6590\u6fdf");
        put("FI", "\u82ac\u862d");
        put("RO", "\u7f85\u99ac\u5c3c\u4e9e");
        put("RE", "\u7559\u5c3c\u65fa");
        put("ET", "\u8863\u7d22\u6bd4\u4e9e");
        put("ER", "\u5384\u5229\u5782\u4e9e");
        put("EE", "\u611b\u6c99\u5c3c\u4e9e");
        put("EC", "\u5384\u74dc\u591a\u723e");
        put("DZ", "\u963f\u723e\u53ca\u5229\u4e9e");
        put("QA", "\u5361\u9054");
        put("DO", "\u591a\u660e\u5c3c\u52a0\u5171\u548c\u570b");
        put("DM", "\u591a\u660e\u5c3c\u52a0");
        put("PW", "\u5e1b\u7409");
        put("DK", "\u4e39\u9ea5");
        put("DJ", "\u5409\u5e03\u5730");
        put("PS", "\u5df4\u52d2\u65af\u5766");
        put("PR", "\u73bb\u591a\u9ece\u514b");
        put("DE", "\u5fb7\u570b");
        put("PN", "\u76ae\u7279\u5eb7");
        put("PM", "\u8056\u5f7c\u5fb7\u8207\u5bc6\u555f\u5d19");
        put("PL", "\u6ce2\u862d");
        put("PH", "\u83f2\u5f8b\u8cd3");
        put("PG", "\u5df4\u5e03\u4e9e\u7d10\u5e7e\u5167\u4e9e");
        put("PF", "\u6cd5\u5c6c\u73bb\u91cc\u5c3c\u897f\u4e9e");
        put("CZ", "\u6377\u514b\u5171\u548c\u570b");
        put("PE", "\u79d8\u9b6f");
        put("CY", "\u8cfd\u666e\u52d2\u65af");
        put("CX", "\u8056\u8a95\u5cf6");
        put("CV", "\u7dad\u5fb7\u89d2");
        put("PA", "\u5df4\u62ff\u99ac");
        put("CR", "\u54e5\u65af\u5927\u9ece\u52a0");
        put("CO", "\u54e5\u502b\u6bd4\u4e9e");
        put("CN", "\u4e2d\u83ef\u4eba\u6c11\u5171\u548c\u570b");
        put("CM", "\u5580\u9ea5\u9686");
        put("CK", "\u5eab\u514b\u7fa4\u5cf6");
        put("CI", "\u79d1\u7279\u8fea\u74e6");
        put("CG", "\u525b\u679c");
        put("CF", "\u4e2d\u975e\u5171\u548c\u570b");
        put("CD", "\u525b\u679c\u6c11\u4e3b\u5171\u548c\u570b");
        put("CC", "\u53ef\u53ef\u65af\u7fa4\u5cf6");
        put("OM", "\u963f\u66fc\u738b\u570b");
        put("BZ", "\u8c9d\u91cc\u65af");
        put("BY", "\u767d\u4fc4\u7f85\u65af");
        put("BW", "\u6ce2\u672d\u90a3");
        put("BV", "\u5e03\u5a01\u5cf6");
        put("BS", "\u5df4\u54c8\u99ac");
        put("NZ", "\u7d10\u897f\u862d");
        put("BO", "\u73bb\u5229\u7dad\u4e9e");
        put("BN", "\u6c76\u840a");
        put("BM", "\u767e\u6155\u9054");
        put("NU", "\u7d10\u5a01\u5cf6");
        put("BJ", "\u8c9d\u5357");
        put("BI", "\u6d66\u9686\u5730");
        put("NR", "\u8afe\u9b6f");
        put("BG", "\u4fdd\u52a0\u5229\u4e9e");
        put("BF", "\u5e03\u57fa\u7d0d\u6cd5\u7d22");
        put("NP", "\u5c3c\u6cca\u723e");
        put("BE", "\u6bd4\u5229\u6642");
        put("BD", "\u5b5f\u52a0\u62c9");
        put("BB", "\u5df4\u8c9d\u591a");
        put("ZW", "\u8f9b\u5df4\u5a01");
        put("NL", "\u8377\u862d");
        put("BA", "\u6ce2\u58eb\u5c3c\u4e9e\u8207\u8d6b\u585e\u683c\u7dad\u7d0d");
        put("NG", "\u5948\u53ca\u5229\u4e9e");
        put("NF", "\u8afe\u798f\u514b\u5cf6");
        put("AZ", "\u4e9e\u585e\u62dc\u7136");
        put("NE", "\u5c3c\u65e5");
        put("NC", "\u65b0\u5580\u91cc\u591a\u5c3c\u4e9e\u7fa4\u5cf6");
        put("AW", "\u963f\u8def\u5df4");
        put("ZM", "\u5c1a\u6bd4\u4e9e");
        put("AU", "\u6fb3\u6d32");
        put("NA", "\u7d0d\u7c73\u6bd4\u4e9e");
        put("AT", "\u5967\u5730\u5229");
        put("AS", "\u7f8e\u5c6c\u85a9\u6469\u4e9e\u7fa4\u5cf6");
        put("AQ", "\u5357\u6975\u6d32");
        put("MZ", "\u83ab\u4e09\u6bd4\u514b");
        put("MY", "\u99ac\u4f86\u897f\u4e9e");
        put("AN", "\u8377\u5c6c\u5b89\u5730\u5217\u65af");
        put("AM", "\u4e9e\u7f8e\u5c3c\u4e9e");
        put("MW", "\u99ac\u62c9\u5a01");
        put("AL", "\u963f\u723e\u5df4\u5c3c\u4e9e");
        put("MV", "\u99ac\u723e\u5730\u592b");
        put("MU", "\u6a21\u91cc\u897f\u65af");
        put("MT", "\u99ac\u723e\u4ed6");
        put("AI", "\u5b89\u572d\u62c9\u5cf6");
        put("MS", "\u8499\u7279\u8272\u62c9\u7279\u5cf6");
        put("MR", "\u8305\u5229\u5854\u5c3c\u4e9e");
        put("AG", "\u5b89\u5730\u5361\u53ca\u5df4\u5e03\u9054");
        put("MQ", "\u99ac\u4e01\u5c3c\u514b\u5cf6");
        put("MP", "\u5317\u99ac\u91cc\u5b89\u7d0d");
        put("AE", "\u963f\u62c9\u4f2f\u806f\u5408\u5927\u516c\u570b");
        put("MO", "\u4e2d\u83ef\u4eba\u6c11\u5171\u548c\u570b\u6fb3\u9580\u7279\u5225\u884c\u653f\u5340");
        put("AD", "\u5b89\u9053\u723e");
        put("MM", "\u7dec\u7538");
        put("ML", "\u99ac\u5229");
        put("MK", "\u99ac\u5176\u9813");
        put("YT", "\u99ac\u7d04\u7279");
        put("MH", "\u99ac\u7d39\u723e\u7fa4\u5cf6");
        put("MG", "\u99ac\u9054\u52a0\u65af\u52a0");
        put("MD", "\u6469\u723e\u591a\u74e6");
        put("MC", "\u6469\u7d0d\u54e5");
        put("YE", "\u8449\u9580");
        put("LY", "\u5229\u6bd4\u4e9e");
        put("LV", "\u62c9\u812b\u7dad\u4e9e");
        put("LU", "\u76e7\u68ee\u5821");
        put("LS", "\u8cf4\u7d22\u6265");
        put("LR", "\u8cf4\u6bd4\u745e\u4e9e");
        put("LK", "\u65af\u91cc\u862d\u5361");
        put("LI", "\u5217\u652f\u6566\u65af\u767b");
        put("LC", "\u8056\u9732\u897f\u4e9e");
        put("LA", "\u5bee\u570b");
        put("KZ", "\u54c8\u85a9\u514b");
        put("KY", "\u958b\u66fc\u7fa4\u5cf6");
        put("KR", "\u5357\u97d3");
        put("KP", "\u5317\u97d3");
        put("KN", "\u8056\u514b\u91cc\u65af\u591a\u798f\u53ca\u5c3c\u7dad\u65af");
        put("KM", "\u79d1\u6469\u7f85\u7fa4\u5cf6");
        put("KI", "\u5409\u91cc\u5df4\u65af");
        put("WS", "\u85a9\u6469\u4e9e\u7fa4\u5cf6");
        put("KH", "\u9ad8\u68c9");
        put("KG", "\u5409\u723e\u5409\u65af");
        put("KE", "\u80af\u4e9e");
        put("WF", "\u74e6\u5229\u65af\u548c\u798f\u675c\u7d0d\u7fa4\u5cf6");
        put("JO", "\u7d04\u65e6");
        put("JM", "\u7259\u8cb7\u52a0");
        put("VU", "\u842c\u90a3\u675c");
        put("VI", "\u7f8e\u5c6c\u7dad\u723e\u4eac\u7fa4\u5cf6");
        put("VG", "\u82f1\u5c6c\u7dad\u723e\u4eac\u7fa4\u5cf6");
        put("VE", "\u59d4\u5167\u745e\u62c9");
        put("VC", "\u8056\u6587\u68ee\u53ca\u683c\u745e\u90a3\u4e01");
        put("VA", "\u68b5\u5e1d\u5ca1");
        put("IT", "\u7fa9\u5927\u5229");
        put("IS", "\u51b0\u5cf6");
        put("UZ", "\u70cf\u8332\u5225\u514b");
        put("IO", "\u82f1\u5c6c\u5370\u5ea6\u6d0b\u9818\u571f");
        put("UY", "\u70cf\u62c9\u572d");
        put("US", "\u7f8e\u570b");
        put("IE", "\u611b\u723e\u862d");
        put("ID", "\u5370\u5c3c");
        put("UM", "\u7f8e\u5c6c\u908a\u7586\u7fa4\u5cf6");
        put("UG", "\u70cf\u5e72\u9054");
        put("UA", "\u70cf\u514b\u862d");
        put("HR", "\u514b\u7f85\u57c3\u897f\u4e9e");
        put("TZ", "\u5766\u5c1a\u5c3c\u4e9e");
        put("HN", "\u5b8f\u90fd\u62c9\u65af");
        put("HM", "\u8d6b\u5fb7\u8207\u9ea5\u514b\u7576\u8afe\u7fa4\u5cf6");
        put("TW", "\u81fa\u7063");
        put("TV", "\u5410\u74e6\u9b6f");
        put("HK", "\u4e2d\u83ef\u4eba\u6c11\u5171\u548c\u570b\u9999\u6e2f\u7279\u5225\u884c\u653f\u5340");
        put("TT", "\u5343\u91cc\u9054\u53ca\u6258\u5df4\u54e5");
        put("TO", "\u6771\u52a0");
        put("TN", "\u7a81\u5c3c\u897f\u4e9e");
        put("TM", "\u571f\u5eab\u66fc");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("gwi", "\u572d\u5951\u6587");
        put("eka", "\u827e\u5361\u6731\u514b\u6587");
        put("ijo", "\u4f0a\u55ac\u6587");
        put("xh", "\u73ed\u5716\u6587");
        put("sux", "\u8607\u7f8e\u6587");
        put("sus", "\u8607\u8607\u6587");
        put("mis", "\u5176\u4ed6\u8a9e\u8a00");
        put("loz", "\u6d1b\u9f4a\u6587");
        put("tog", "\u6e6f\u52a0\u6587(\u5c3c\u4e9e\u85a9\u6587)");
        put("pon", "\u6ce2\u90a3\u8c9d\u6587");
        put("min", "\u7c73\u5357\u5361\u5821\u6587");
        put("suk", "\u8607\u5eab\u99ac\u6587");
        put("wo", "\u6c83\u723e\u592b\u6587");
        put("kut", "\u5eab\u7279\u5948\u6587");
        put("mic", "\u7c73\u514b\u99ac\u514b\u6587");
        put("wa", "\u74e6\u9686\u6587");
        put("kum", "\u5eab\u5bc6\u514b\u6587");
        put("zap", "\u85a9\u6ce2\u7279\u514b\u6587");
        put("cus", "\u5eab\u65bd\u7279\u8a9e\u7cfb\uff08\u5176\u4ed6\uff09");
        put("jbo", "\u908f\u8f2f\u6587");
        put("doi", "\u591a\u683c\u4f86\u6587");
        put("oto", "\u5967\u6258\u7c73\u6587");
        put("vai", "\u8d8a\u5357\u6587");
        put("rar", "\u62c9\u7f85\u901a\u52a0\u6587");
        put("ve", "\u6eab\u9054\u6587");
        put("rap", "\u5fa9\u6d3b\u5cf6\u6587");
        put("raj", "\u62c9\u8cc8\u65af\u5766\u8af8\u6587");
        put("ota", "\u9102\u5716\u66fc\u571f\u8033\u5176\u6587 (1500-1928)");
        put("nzi", "\u5c3c\u8332\u99ac\u6587");
        put("uz", "\u70cf\u8332\u5225\u514b\u6587");
        put("uga", "\u70cf\u52a0\u5217\u6587");
        put("tmh", "\u5854\u99ac\u5947\u514b\u6587");
        put("nai", "\u5176\u4ed6\u5317\u7f8e\u5370\u5730\u5b89\u6587");
        put("nah", "\u7d0d\u74e6\u7279\u6587");
        put("ur", "\u70cf\u723e\u90fd\u6587");
        put("uk", "\u70cf\u514b\u862d\u6587");
        put("egy", "\u53e4\u57c3\u53ca\u6587)");
        put("ug", "\u7dad\u543e\u723e\u6587");
        put("fan", "\u82b3\u65cf\u6587");
        put("ssa", "\u975e\u6d32\u6492\u54c8\u62c9\u6c99\u6f20\u908a\u7de3\u5730\u5e36\u6587");
        put("mga", "\u611b\u723e\u862d\u6587\uff0c\u4e2d\u53e4 (900-1200)");
        put("bat", "\u6ce2\u7f85\u7684\u6587\uff08\u5176\u4ed6\uff09");
        put("nyo", "\u5c3c\u5967\u56c9\u6587");
        put("bas", "\u5df4\u85a9\u6587");
        put("nyn", "\u5c3c\u63da\u79d1\u840a\u6587");
        put("nym", "\u5c3c\u63da\u97cb\u9f4a\u6587");
        put("hmn", "\u5b5f\u6587");
        put("ban", "\u5df4\u5398\u6587");
        put("osa", "\u6b50\u585e\u5947\u6587");
        put("ty", "\u5927\u6eaa\u5730\u6587");
        put("tw", "\u7e41\u9ad4\u4e2d\u6587");
        put("srr", "\u585e\u96f7\u723e\u6587");
        put("tli", "\u7279\u6797\u57fa\u7279\u6587");
        put("tt", "\u97c3\u977c\u6587");
        put("bad", "\u73ed\u9054\u6587");
        put("to", "\u6771\u52a0\u6587");
        put("tn", "\u7a81\u5c3c\u897f\u4e9e\u6587");
        put("tk", "\u571f\u5eab\u66fc\u6587");
        put("ti", "\u63d0\u683c\u5229\u5c3c\u4e9e\u6587");
        put("kru", "\u5eab\u9b6f\u79d1\u6587");
        put("te", "\u6cf0\u76e7\u56fa\u6587");
        put("kro", "\u514b\u9b6f\u6587");
        put("csb", "\u5361\u8212\u5e03\u6587");
        put("ta", "\u5766\u7c73\u723e\u6587");
        put("tkl", "\u6258\u514b\u52de\u6587");
        put("efi", "\u57c3\u83f2\u514b\u6587");
        put("sw", "\u53f2\u74e6\u5e0c\u91cc\u6587");
        put("su", "\u8607\u4e39\u6587");
        put("krc", "\u5361\u62c9\u67f4-\u5305\u723e\u5361\u723e\u6587");
        put("sr", "\u585e\u723e\u7dad\u4e9e\u6587");
        put("sq", "\u963f\u723e\u5df4\u5c3c\u4e9e\u6587");
        put("men", "\u9580\u5fb7\u6587");
        put("crp", "\u514b\u91cc\u5967\u723e\u6587\u548c\u76ae\u6b3d\u6587");
        put("so", "\u7d22\u99ac\u5229\u6587");
        put("sn", "\u585e\u5167\u52a0\u723e\u6587");
        put("sm", "\u85a9\u6469\u4e9e\u6587");
        put("sl", "\u65af\u6d1b\u7dad\u5c3c\u4e9e\u6587");
        put("grc", "\u53e4\u5e0c\u81d8\u6587 (\u81f3 1453)");
        put("grb", "\u54e5\u535a\u8a9e");
        put("si", "\u50e7\u4f3d\u7f85\u6587");
        put("sh", "\u585e\u723e\u7dad\u4e9e\u514b\u7f85\u57c3\u897f\u4e9e\u6587");
        put("crh", "\u514b\u91cc\u7c73\u4e9e\u534a\u5cf6\u7684\u571f\u8033\u5176\u6587\uff1b\u514b\u91cc\u7c73\u4e9e\u534a\u5cf6\u7684\u5854\u5854\u723e\u6587");
        put("afa", "\u975e\u9583\u65cf\u53ca\u975e\u4e9e\u8a9e\u8a00");
        put("se", "\u5317\u65b9\u85a9\u7c73\u6587");
        put("sd", "\u8607\u4e39\u6587");
        put("udm", "\u6c83\u8482\u827e\u514b\u6587");
        put("sc", "\u6492\u4e01\u6587");
        put("rw", "\u76e7\u5b89\u9054\u6587");
        put("mdr", "\u66fc\u9054\u6587");
        put("ro", "\u7f85\u99ac\u5c3c\u4e9e\u6587");
        put("rm", "\u91cc\u6258\u7f85\u66fc\u65af\u6587");
        put("tiv", "\u63d0\u592b\u6587");
        put("ady", "\u963f\u8fea\u5404\u6587");
        put("zun", "\u7956\u5c3c\u6587");
        put("qu", "\u84cb\u4e18\u4e9e\u6587");
        put("tig", "\u8482\u683c\u96f7\u6587");
        put("cpp", "\u6b50\u6d32\u8154\u8abf\u548c\u6d0b\u6d87\u6ff1\uff0c\u6e90\u81ea\u8461\u8404\u7259\u6587\u7684(\u5176\u4ed6)");
        put("sog", "\u7d22\u683c\u5e95\u4e9e\u7d0d\u6587");
        put("ada", "\u963f\u7576\u83ab\u6587");
        put("kos", "\u79d1\u65af\u96f7\u6069\u6587");
        put("hit", "\u8d6b\u68af\u6587");
        put("cpf", "\u6b50\u6d32\u8154\u8abf\u548c\u6d0b\u6d87\u6ff1\uff0c\u6e90\u81ea\u6cd5\u6587\u7684(\u5176\u4ed6)");
        put("cpe", "\u6b50\u6d32\u8154\u8abf\u548c\u6d0b\u6d87\u6ff1\uff0c\u6e90\u81ea\u82f1\u6587\u7684(\u5176\u4ed6)");
        put("him", "\u8d6b\u99ac\u67e5\u5229\u6587");
        put("kok", "\u8ca2\u6839\u6587");
        put("hil", "\u5e0c\u5229\u84cb\u8fb2\u6587");
        put("got", "\u54e5\u7279\u6587");
        put("gor", "\u79d1\u9686\u9054\u7f85\u6587");
        put("gon", "\u5ca1\u5fb7\u6587");
        put("nub", "\u52aa\u6bd4\u4e9e\u6587");
        put("ps", "\u666e\u4ec0\u5716\u6587");
        put("phn", "\u8153\u5c3c\u57fa\u6587");
        put("goh", "\u5fb7\u6587,\u4e0a\u53e4\u5168\u76db\u6642\u671f (ca.750-1050)");
        put("ach", "\u963f\u50d1\u5229\u6587");
        put("yao", "\u7464\u6587");
        put("phi", "\u5176\u4ed6\u83f2\u5f8b\u8cd3\u6587");
        put("ace", "\u4e9e\u9f4a\u6587");
        put("pl", "\u6ce2\u862d\u6587");
        put("pi", "\u5df4\u5229\u6587");
        put("bug", "\u5e03\u5409\u65af\u6587");
        put("sms", "\u65af\u79d1\u7279\u85a9\u7c73\u6587");
        put("bua", "\u5e03\u91cc\u963f\u7279\u6587");
        put("mas", "\u99ac\u8cfd\u6587");
        put("smn", "\u4f0a\u7d0d\u88e1\u85a9\u7c73\u6587");
        put("map", "\u5357\u5cf6\u6587");
        put("os", "\u5967\u585e\u63d0\u6587");
        put("or", "\u6b50\u91cc\u4e9e\u6587");
        put("smj", "\u9b6f\u52d2\u85a9\u7c73\u6587");
        put("smi", "\u5176\u4ed6\u85a9\u7c73\u6587");
        put("mak", "\u671b\u52a0\u932b\u6587");
        put("mai", "\u9081\u8482\u5229\u6587");
        put("mag", "\u99ac\u52a0\u4f0a\u6587");
        put("oj", "\u5967\u6770\u5e03\u74e6\u6587");
        put("mad", "\u99ac\u90fd\u62c9\u6587");
        put("sma", "\u5357\u85a9\u7c73\u6587");
        put("oc", "\u5967\u897f\u5766\u6587");
        put("myv", "\u5384\u723e\u8332\u4e9e\u6587");
        put("dgr", "\u591a\u683c\u91cc\u5e03\u6587");
        put("myn", "\u99ac\u96c5\u6587");
        put("ny", "\u5c3c\u63da\u8cc8\u6587");
        put("nv", "\u7d0d\u74e6\u7d04\u6587");
        put("nr", "\u5357\u5730\u7562\u5217\u6587");
        put("gmh", "\u5fb7\u6587, \u4e2d\u53e4\u5168\u76db\u6642\u671f (ca.1050-1500)");
        put("nn", "\u65b0\u632a\u5a01\u6587");
        put("nl", "\u8377\u862d\u6587");
        put("ng", "\u6069\u6771\u52a0\u6587");
        put("sla", "\u5176\u4ed6\u65af\u62c9\u592b\u6587");
        put("ne", "\u5c3c\u6cca\u723e\u6587");
        put("nd", "\u5317\u5730\u7562\u5217\u6587");
        put("tet", "\u6cf0\u9813\u6587");
        put("nb", "\u632a\u5a01\u6ce2\u514b\u9ed8\u723e\u6587");
        put("na", "\u8afe\u9b6f\u6587");
        put("ter", "\u6cf0\u96f7\u8afe\u6587");
        put("tem", "\u63d0\u59c6\u6587");
        put("my", "\u7dec\u7538\u6587");
        put("lez", "\u7acb\u9676\u5b9b\u6587");
        put("mt", "\u99ac\u723e\u4ed6\u6587");
        put("peo", "\u53e4\u6ce2\u65af\u6587 (ca.600-400 B.C.)");
        put("ms", "\u99ac\u4f86\u6587");
        put("mr", "\u99ac\u62c9\u5730\u6587");
        put("mo", "\u6469\u723e\u591a\u74e6\u6587");
        put("jrb", "\u7336\u592a\u6559-\u963f\u62c9\u4f2f\u6587");
        put("ml", "\u99ac\u4f86\u4e9e\u62c9\u59c6\u6587");
        put("mk", "\u99ac\u5176\u9813\u6587");
        put("mh", "\u99ac\u7d39\u723e\u6587");
        put("mg", "\u99ac\u723e\u52a0\u4ec0\u6587");
        put("mwr", "\u99ac\u723e\u5c3c\u88e1\u6587");
        put("den", "\u65af\u62c9\u592b");
        put("lu", "\u9b6f\u5df4\u52a0\u4e39\u52a0\u6587");
        put("del", "\u5fb7\u62c9\u74e6");
        put("lo", "\u5bee\u570b\u6587");
        put("li", "\u6797\u5821\u6587");
        put("ewo", "\u4f9d\u6c6a\u90fd\u6587");
        put("lg", "\u5e72\u9054\u6587");
        put("lb", "\u76e7\u68ee\u5821\u6587");
        put("jpr", "\u7336\u592a\u6559-\u6ce2\u65af\u6587");
        put("sit", "\u5176\u4ed6\u6f22\u85cf\u6587");
        put("ky", "\u5409\u723e\u5409\u65af\u6587");
        put("kw", "\u5eb7\u74e6\u8033\u6587");
        put("ku", "\u5eab\u723e\u5fb7\u6587");
        put("sio", "\u5927\u8607\u6587");
        put("ks", "\u514b\u4ec0\u7c73\u723e\u6587");
        put("kr", "\u5361\u52aa\u88e1\u6587");
        put("ko", "\u97d3\u6587");
        put("kn", "\u574e\u90a3\u9054\u6587");
        put("km", "\u9ad8\u68c9\u6587");
        put("kl", "\u683c\u9675\u862d\u6587");
        put("kk", "\u54c8\u85a9\u514b\u6587");
        put("kj", "\u5ee3\u4e9e\u99ac\u6587");
        put("rom", "\u5409\u666e\u8cfd\u6587");
        put("sid", "\u5e0c\u9054\u6469\u6587");
        put("ki", "\u5409\u5eab\u5c24\u4eba");
        put("kg", "\u525b\u679c\u6587");
        put("non", "\u53e4\u8afe\u723e\u65af\u6587");
        put("ka", "\u55ac\u6cbb\u4e9e\u6587");
        put("mus", "\u514b\u91cc\u514b\u6587");
        put("roa", "\u5176\u4ed6\u7f85\u66fc\u6587");
        put("nog", "\u8afe\u84cb\u6587");
        put("mun", "\u8499\u9054\u6587");
        put("mul", "\u591a\u7a2e\u8a9e\u8a00");
        put("gil", "\u5409\u723e\u4f2f\u7279\u7fa4\u5cf6\u6587");
        put("znd", "\u8d0a\u5fb7\u6587");
        put("shn", "\u64a3\u6587");
        put("fon", "\u8c50\u6587");
        put("xal", "\u5361\u723e\u6885\u514b\u6587");
        put("aus", "\u6fb3\u6d32\u82f1\u6587");
        put("kho", "\u548c\u95d0[\u8207\u95d0]\u6587");
        put("pau", "\u5e1b\u7409\u6587");
        put("chy", "\u6c99\u4f0a\u5b89\u6587");
        put("iu", "\u56e0\u7d10\u7279\u6587");
        put("it", "\u7fa9\u5927\u5229\u6587");
        put("pap", "\u5e15\u76ae\u963f\u9580\u6258\u6587");
        put("sgn", "\u624b\u8a9e");
        put("is", "\u51b0\u5cf6\u6587");
        put("chr", "\u67f4\u7f85\u57fa\u6587");
        put("pam", "\u6f58\u5e15\u5609\u6587");
        put("pal", "\u5df4\u5217\u7dad\u6587");
        put("chp", "\u5947\u4f69\u74e6\u63da\u6587");
        put("io", "\u4f0a\u6717\u6587");
        put("cho", "\u55ac\u514b\u6258\u6587");
        put("chn", "\u5951\u5974\u514b\u6587");
        put("chm", "\u99ac\u91cc\u6587");
        put("tyv", "\u571f\u51e1\u6587");
        put("bnt", "\u73ed\u5716\u6587");
        put("ik", "\u4f9d\u5974\u76ae\u7dad\u514b\u6587");
        put("pag", "\u6f58\u52a0\u8f9b\u6587");
        put("chk", "\u8655\u5947\u65af\u6587");
        put("ii", "\u56db\u5ddd\u8a71");
        put("lam", "\u862d\u5df4\u6587");
        put("ig", "\u4f0a\u5e03\u6587");
        put("sga", "\u53e4\u611b\u723e\u862d\u6587\uff08\u81f3 900\uff09");
        put("ie", "\u62c9\u4e01\u570b\u969b\u6587");
        put("paa", "\u5176\u4ed6\u5df4\u5e03\u4e9e\u8af8\u8a9e\u8a00");
        put("id", "\u5370\u5c3c\u6587");
        put("lah", "\u62c9\u4ea8\u9054\u6587");
        put("day", "\u8fea\u96c5\u514b\u6587");
        put("chb", "\u5947\u5e03\u67e5\u6587");
        put("ia", "\u62c9\u4e01\u570b\u969b\u6587");
        put("lad", "\u62c9\u8fea\u8afe\u6587");
        put("hz", "\u8d6b\u96f7\u7f85\u6587");
        put("hai", "\u6d77\u9054\u6587");
        put("dar", "\u9054\u723e\u683c\u74e6\u6587");
        put("hy", "\u4e9e\u7f8e\u5c3c\u4e9e\u6587");
        put("ath", "\u963f\u85a9\u5df4\u65af\u5361\u6587");
        put("ht", "\u6d77\u5730\u4eba");
        put("dak", "\u9054\u79d1\u4ed6\u6587");
        put("hr", "\u514b\u7f85\u57c3\u897f\u4e9e\u6587");
        put("ho", "\u897f\u91cc\u83ab\u5716\u571f\u6587");
        put("hi", "\u5317\u5370\u5ea6\u6587");
        put("he", "\u5e0c\u4f2f\u4f86\u6587");
        put("ast", "\u963f\u65af\u5716\u91cc\u4e9e\u6587");
        put("wen", "\u6587\u5fb7\u6587");
        put("gv", "\u66fc\u5cf6\u6587");
        put("gu", "\u5409\u4e9e\u62c9\u5854\u6587");
        put("sem", "\u5176\u4ed6\u9583\u65cf\u8a9e\u8a00");
        put("iro", "\u6613\u6d1b\u9b41\u6587");
        put("sel", "\u745f\u723e\u5361\u666e\u6587");
        put("gl", "\u52a0\u91cc\u897f\u4e9e\u6587");
        put("gez", "\u5409\u8332\u6587");
        put("art", "\u5176\u4ed6\u4eba\u5de5\u8a9e\u8a00");
        put("gd", "\u8607\u683c\u862d - \u84cb\u723e\u6587");
        put("ira", "\u4f0a\u82b3\u6717\u6587");
        put("ga", "\u611b\u723e\u862d\u6587");
        put("arn", "\u963f\u52de\u574e\u6587");
        put("fy", "\u5f17\u91cc\u65af\u862d\u6587");
        put("bla", "\u932b\u514b\u932b\u5361\u6587");
        put("gem", "\u5fb7\u570b\u7684(\u5176\u4ed6)");
        put("ypk", "\u611b\u65af\u57fa\u6469\u6587");
        put("fo", "\u6cd5\u7f85\u6587");
        put("cel", "\u514b\u723e\u7279\u6587\uff08\u5176\u4ed6\uff09");
        put("fj", "\u6590\u6fdf\u6587");
        put("fi", "\u82ac\u862d\u6587");
        put("ff", "\u5bcc\u62c9\u6587");
        put("tvl", "\u5410\u74e6\u9b6f\u6587");
        put("ceb", "\u5bbf\u52d9\u65cf\u6587");
        put("et", "\u611b\u6c99\u5c3c\u4e9e\u6587");
        put("eo", "\u4e16\u754c\u8a9e");
        put("el", "\u5e0c\u81d8\u6587");
        put("tut", "\u5176\u4ed6\u963f\u723e\u6cf0\u8af8\u6587");
        put("niu", "\u7d10\u57c3\u6587");
        put("tup", "\u5716\u76ae\u6587");
        put("ee", "\u57c3\u7def\u6587");
        put("tum", "\u5716\u59c6\u5e03\u5361\u6587");
        put("nic", "\u5176\u4ed6\u5c3c\u65e5\u525b\u679c\u8a9e\u7cfb");
        put("lus", "\u76e7\u6652\u6587");
        put("fiu", "\u82ac\u862d-\u70cf\u6208\u723e\u65cf\u6587(\u5176\u4ed6)");
        put("dv", "\u8fea\u7dad\u897f\u6587");
        put("nia", "\u5c3c\u4e9e\u65af\u6587");
        put("moh", "\u83ab\u970d\u514b\u6587");
        put("luo", "\u76e7\u5967\u6587");
        put("lun", "\u76e7\u6069\u9054\u6587");
        put("apa", "\u963f\u5e15\u5947\u8a9e\u8a00");
        put("lui", "\u8def\u6613\u585e\u8afe\u6587");
        put("lua", "\u9b6f\u5df4\u9b6f\u9b6f\u4e9e\u6587");
        put("bik", "\u6bd4\u79d1\u723e\u6587");
        put("was", "\u74e6\u7d39\u6587");
        put("und", "\u672a\u78ba\u5b9a\u7684");
        put("war", "\u74e6\u745e\u6587");
        put("da", "\u4e39\u9ea5\u6587");
        put("dum", "\u8377\u862d\uff0c\u4e2d\u53e4 (ca. 1050-1350)");
        put("mno", "\u99ac\u8afe\u6ce2\u6587");
        put("wak", "\u5938\u57fa\u6b66\u7279\u6587");
        put("sat", "\u6563\u5854\u5229\u6587");
        put("cy", "\u5a01\u723e\u58eb\u6587");
        put("sas", "\u6492\u6492\u514b\u6587");
        put("kbd", "\u5361\u5df4\u723e\u9054\u6587");
        put("cv", "\u695a\u74e6\u751a\u6587");
        put("mni", "\u66fc\u5c3c\u666e\u88e1\u6587");
        put("sam", "\u85a9\u746a\u5229\u4e9e\u963f\u62c9\u59c6\u6587");
        put("cr", "\u514b\u88e1\u6587");
        put("sal", "\u85a9\u5229\u751a\u6587");
        put("dua", "\u675c\u4e9e\u62c9\u6587");
        put("mnc", "\u6eff\u65cf\u6587");
        put("sah", "\u96c5\u5eab\u7279\u6587");
        put("gba", "\u845b\u5df4\u4e9e\u6587");
        put("sad", "\u6851\u9054\u97cb\u6587");
        put("ch", "\u67e5\u83ab\u6d1b\u6587");
        put("ine", "\u5370\u6b50\u8a9e\u7cfb\uff08\u5176\u4ed6\uff09");
        put("bho", "\u535a\u5091\u666e\u723e\u6587");
        put("enm", "\u82f1\u6587\uff0c\u4e2d\u4e16\u7d00 (1100-1500)");
        put("kar", "\u514b\u502b\u6587");
        put("inc", "\u5370\u5ea6\u8a9e\u7cfb\uff08\u5176\u4ed6\uff09");
        put("ce", "\u8eca\u81e3\u6587");
        put("gay", "\u52a0\u7d04\u6587");
        put("ca", "\u52a0\u6cf0\u7f85\u5c3c\u4e9e\u6587");
        put("umb", "\u59c6\u672c\u675c\u6587");
        put("syr", "\u53e4\u6558\u5229\u4e9e\u6587");
        put("tsi", "\u6b3d\u897f\u5b89\u6587");
        put("ang", "\u53e4\u82f1\u6587 (ca.450-1100)");
        put("cau", "\u9ad8\u52a0\u7d22\u6587\uff08\u5176\u4ed6\uff09");
        put("kab", "\u5361\u6bd4\u723e\u6587");
        put("kaa", "\u5361\u62c9\u5361\u723e\u5e15\u514b\u6587");
        put("bs", "\u6ce2\u58eb\u5c3c\u4e9e\u6587");
        put("bo", "\u85cf\u6587");
        put("gaa", "\u52a0\u65cf\u6587");
        put("cai", "\u4e2d\u7f8e\u5370\u7b2c\u5b89\u6587\uff08\u5176\u4ed6\uff09");
        put("bi", "\u6bd4\u65af\u62c9\u99ac\u6587");
        put("bh", "\u6bd4\u54c8\u723e\u6587");
        put("bg", "\u4fdd\u52a0\u5229\u4e9e\u6587");
        put("be", "\u767d\u4fc4\u7f85\u65af\u6587");
        put("ba", "\u5df4\u4ec0\u5ba2\u723e\u6587");
        put("zu", "\u7956\u9b6f\u6587");
        put("zen", "\u6fa4\u7d0d\u52a0\u6587");
        put("pro", "\u666e\u7f85\u6587\u65af\u6587 (to 1500)");
        put("az", "\u4e9e\u585e\u62dc\u7136\u6587");
        put("ay", "\u827e\u99ac\u62c9\u6587");
        put("av", "\u963f\u6cd5\u6587");
        put("as", "\u963f\u85a9\u59c6\u6587");
        put("dsb", "\u4e0b\u7d22\u5e03\u6587");
        put("ilo", "\u4f0a\u6d1b\u95ca\u6587");
        put("elx", "\u57c3\u862d\u6587");
        put("an", "\u963f\u62c9\u8ca2\u6587");
        put("pra", "\u5370\u5ea6\u53e4\u4ee3\u53ca\u4e2d\u4e16\u7d00\u4e4b\u4e2d\u90e8\u53ca\u5317\u90e8\u65b9\u8a00");
        put("new", "\u5c3c\u74e6\u723e\u6587");
        put("ak", "\u963f\u574e\u6587");
        put("za", "\u58ef\u6587");
        put("af", "\u5357\u975e\u8377\u862d\u6587");
        put("ae", "\u963f\u7def\u65af\u9640\u6587");
        put("ab", "\u963f\u5e03\u54c8\u897f\u4e9e\u6587");
        put("yo", "\u7d04\u9b6f\u5df4\u6587");
        put("alg", "\u963f\u723e\u5ca1\u6606\u6587");
        put("ale", "\u963f\u7559\u7533\u6587");
        put("mkh", "\u5176\u4ed6\u9ad8\u68c9\u8a9e\u7cfb");
        put("yi", "\u610f\u7b2c\u7dd2\u6587");
        put("dra", "\u5fb7\u62c9\u5a01\u6587\uff08\u5176\u4ed6\uff09");
        put("ber", "\u67cf\u67cf\u723e\u6587");
        put("nds", "\u5fb7\u570b\u5317\u90e8\u7684\u5fb7\u6587; \u85a9\u514b\u905c\u6587");
        put("bem", "\u5225\u59c6\u5df4\u6587");
        put("bej", "\u8c9d\u624e\u6587");
        put("tpi", "\u6258\u6bd4\u8f9b\u6587");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final class Hashtablevariants extends java.util.Hashtable
  {
    public Hashtablevariants()
      {
        super();
        put("REVISED", "\u5df2\u4fee\u8a02");
      }
  }

  private static final Object variants = new Hashtablevariants();

  private static final Object[][] contents =
  {
    { "shortDateFormat", "yyyy/M/d" },
    { "mediumDateFormat", "yyyy/M/d" },
    { "longDateFormat", "yyyy'\u5e74'M'\u6708'd'\u65e5'" },
    { "fullDateFormat", "yyyy'\u5e74'M'\u6708'd'\u65e5'EEEE" },
    { "shortTimeFormat", "a h:mm" },
    { "mediumTimeFormat", "a h:mm:ss" },
    { "longTimeFormat", "ahh'\u6642'mm'\u5206'ss'\u79d2'" },
    { "fullTimeFormat", "ahh'\u6642'mm'\u5206'ss'\u79d2' z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
    { "variants", variants },
  };

  public Object[][] getContents() { return contents; }
}
