/* LocaleInformation_mt.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_mt extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "Jan",
    "Fra",
    "Mar",
    "Apr",
    "Mej",
    "\u0120un",
    "Lul",
    "Awi",
    "Set",
    "Ott",
    "Nov",
    "Di\u010b",
    null,
  };

  private static final String[] months = {
    "Jannar",
    "Frar",
    "Marzu",
    "April",
    "Mejju",
    "\u0120unju",
    "Lulju",
    "Awissu",
    "Settembru",
    "Ottubru",
    "Novembru",
    "Di\u010bembru",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "\u0126ad",
    "Tne",
    "Tli",
    "Erb",
    "\u0126am",
    "\u0120im",
    "Sib",
  };

  private static final String[] weekdays = {
    null,
    "Il-\u0126add",
    "It-Tnejn",
    "It-Tlieta",
    "L-Erbg\u0127a",
    "Il-\u0126amis",
    "Il-\u0120img\u0127a",
    "Is-Sibt",
  };

  private static final String[] eras = {
    "QK",
    "WK",
  };

  private static final String[][] zoneStrings =
  {
    { "CET", "\u0126in \u010aentrali Ewropew", "CEST", "\u0126in \u010aentrali Ewropew tas-Sajf",  "Europe/Malta" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Timor tal-Lvant");
        put("TK", "Tokelaw");
        put("TJ", "Ta\u0121ikistan");
        put("TH", "Tajlandja");
        put("TG", "Togo");
        put("TF", "Territorji Fran\u010bi\u017ci ta' Nofsinhar");
        put("GY", "Gujana");
        put("TD", "\u010aad");
        put("TC", "Turks and Caicos Islands");
        put("GW", "Ginea-Bissaw");
        put("GU", "Gwam");
        put("GT", "Gwatemala");
        put("GS", "South Georgia and the South Sandwich Islands");
        put("GR", "Gre\u010bja");
        put("GQ", "Ginea Ekwatorjali");
        put("GP", "Gwadelupe");
        put("SZ", "Swa\u017ciland");
        put("SY", "Sirja");
        put("GN", "Gineja");
        put("GM", "Gambja");
        put("GL", "Grinlandja");
        put("SV", "El Salvador");
        put("ST", "Sao Tome and Principe");
        put("GI", "Gibraltar");
        put("GH", "Gana");
        put("SR", "Surinam");
        put("GF", "Gujana Fran\u010bi\u017ca");
        put("SP", "Serbja");
        put("GE", "\u0120or\u0121ja");
        put("SO", "Somalja");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Ingilterra");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Slovakkja");
        put("SJ", "Svalbard and Jan Mayen");
        put("SI", "Slovenja");
        put("SH", "Saint Helena");
        put("SG", "Singapor");
        put("SE", "\u017bvezja");
        put("SD", "Sudan");
        put("SC", "Seychelles");
        put("SB", "Solomon Islands");
        put("SA", "G\u0127arabja Sawdita");
        put("FR", "Franza");
        put("FO", "G\u017cejjer Faroe");
        put("FM", "Mikronesja");
        put("RW", "Rwanda");
        put("FK", "Falkland Islands");
        put("RU", "Russja");
        put("FJ", "Fi\u0121i");
        put("FI", "Finlandja");
        put("RO", "Rumanija");
        put("RE", "R\u00e9union");
        put("ET", "Etijopja");
        put("ES", "Spanja");
        put("ER", "Eritreja");
        put("EH", "Sahara tal-Punent");
        put("EG", "E\u0121ittu");
        put("EE", "Estonja");
        put("EC", "Ekwador");
        put("DZ", "Al\u0121erija");
        put("QA", "Qatar");
        put("DO", "Republikka Domenikana");
        put("PY", "Paragwaj");
        put("DM", "Dominika");
        put("PW", "Palau");
        put("DK", "Danimarka");
        put("DJ", "\u0120ibuti");
        put("PT", "Portugall");
        put("PS", "Palestinian Territory");
        put("PR", "Puerto Rico");
        put("DE", "\u0120ermanja");
        put("PN", "Pitcairn");
        put("PM", "Saint Pierre and Miquelon");
        put("PL", "Polonja");
        put("PK", "Pakistan");
        put("PH", "Filippini");
        put("PG", "Papwa-Ginea \u0120dida");
        put("PF", "Polinesja Fran\u010bi\u017ca");
        put("CZ", "Repubblika \u010aeka");
        put("PE", "Peru");
        put("CY", "\u010aipru");
        put("CX", "Christmas Island");
        put("CV", "Kape Verde");
        put("PA", "Panama");
        put("CU", "Kuba");
        put("CR", "Kosta Rika");
        put("CO", "Kolumbja");
        put("CN", "\u010aina");
        put("CM", "Kamerun");
        put("CL", "\u010aili");
        put("CK", "Cook Islands");
        put("CI", "Kosta ta' l-Avorju");
        put("CH", "Svizzera");
        put("CG", "Kongo");
        put("CF", "Repubblika Afrikana \u010aentrali");
        put("CD", "Democratic Republic of the Congo");
        put("CC", "Cocos (Keeling) Islands");
        put("OM", "Oman");
        put("CA", "Kanada");
        put("BZ", "Beli\u017ce");
        put("BY", "Bjelorussja");
        put("BW", "Botswana");
        put("BV", "Bouvet Island");
        put("BT", "Butan");
        put("BS", "Ba\u0127amas");
        put("BR", "Bra\u017cil");
        put("NZ", "New Zealand");
        put("BO", "Bolivja");
        put("BN", "Brunej");
        put("BM", "Bermuda");
        put("NU", "Niue");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Ba\u0127rajn");
        put("NR", "Nauru");
        put("BG", "Bulgarija");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "Bel\u0121ju");
        put("NO", "Norve\u0121ja");
        put("BD", "Bangladexx");
        put("BB", "Barbados");
        put("ZW", "\u017bimbabwe");
        put("NL", "Olanda");
        put("BA", "Bo\u017cnija \u0126er\u017cegovina");
        put("NI", "Nikaragwa");
        put("NG", "Ni\u0121erja");
        put("NF", "Norfolk Island");
        put("AZ", "A\u017cerbaj\u0121an");
        put("NE", "Ni\u0121er");
        put("NC", "New Caledonia");
        put("AW", "Aruba");
        put("ZM", "\u017bambja");
        put("NA", "Namibja");
        put("AU", "Awstralja");
        put("AT", "Awstrija");
        put("AS", "Samoa Amerikana");
        put("AR", "Ar\u0121entina");
        put("AQ", "Antarctica");
        put("MZ", "Mo\u017cambik");
        put("AO", "Angola");
        put("MY", "Malasja");
        put("AN", "Antilles Olandi\u017ci");
        put("MX", "Messiku");
        put("AM", "Armenja");
        put("MW", "Malawi");
        put("AL", "Albanija");
        put("MV", "Maldives");
        put("ZA", "Afrika t'Isfel");
        put("MU", "Mawrizju");
        put("MT", "Malta");
        put("AI", "Angwilla");
        put("MS", "Montserrat");
        put("MR", "Mawritanja");
        put("AG", "Antigua and Barbuda");
        put("MQ", "Martinik");
        put("AF", "Afganistan");
        put("MP", "G\u017cejjer Marjana ta' Fuq");
        put("AE", "Emirati G\u0127arab Maqg\u0127uda");
        put("MO", "Macao S.A.R., China");
        put("AD", "Andorra");
        put("MN", "Mongolja");
        put("MM", "Mjanmar");
        put("ML", "Mali");
        put("MK", "Ma\u010bedonja");
        put("YU", "Jugoslavja");
        put("YT", "Majotte");
        put("MH", "G\u017cejjer ta' Marshall");
        put("MG", "Madagaskar");
        put("MD", "Maldova");
        put("MC", "Monako");
        put("MA", "Marokk");
        put("YE", "Jemen");
        put("LY", "Libja");
        put("LV", "Latvja");
        put("LU", "Lussemburgu");
        put("LT", "Litwanja");
        put("LS", "Lesoto");
        put("LR", "Liberja");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Saint Lucia");
        put("LB", "Libanu");
        put("LA", "Laos");
        put("KZ", "Ka\u017cakstan");
        put("KY", "Cayman Islands");
        put("KW", "Kuwajt");
        put("KR", "Koreja t'Isfel");
        put("KP", "Koreja ta' Fuq");
        put("KN", "Saint Kitts and Nevis");
        put("KM", "Komoros");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Kambodja");
        put("KG", "Kirgistan");
        put("KE", "Kenja");
        put("WF", "Wallis and Futuna");
        put("JP", "\u0120appun");
        put("JO", "\u0120ordan");
        put("JM", "\u0120amajka");
        put("VU", "Vanwatu");
        put("VN", "Vjetnam");
        put("VI", "U.S. Virgin Islands");
        put("VG", "British Virgin Islands");
        put("VE", "Venezwela");
        put("VC", "Saint Vincent and the Grenadines");
        put("VA", "Vatikan");
        put("IT", "Italja");
        put("IS", "Islanda");
        put("IR", "Iran");
        put("IQ", "Iraq");
        put("UZ", "U\u017cbekistan");
        put("IO", "British Indian Ocean Territory");
        put("UY", "Urugwaj");
        put("IN", "Indja");
        put("IL", "I\u017crael");
        put("US", "Stati Uniti");
        put("IE", "Irlanda");
        put("ID", "Indone\u017cja");
        put("UM", "United States Minor Outlying Islands");
        put("UG", "Uganda");
        put("UA", "Ukraina");
        put("HU", "Ungerija");
        put("HT", "\u0126aiti");
        put("HR", "Kroazja");
        put("TZ", "Tan\u017canija");
        put("HN", "\u0126onduras");
        put("HM", "Heard Island and McDonald Islands");
        put("TW", "Tajwan");
        put("TV", "Tuvalu");
        put("HK", "\u0126ong Kong S.A.R., \u010aina");
        put("TT", "Trinidad u Tobago");
        put("TR", "Turkija");
        put("TO", "Tonga");
        put("TN", "Tune\u017c");
        put("TM", "Turkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("gwi", "Gwi\u010bin");
        put("akk", "Akkadjen");
        put("eka", "Ekajuk");
        put("ijo", "I\u0121o");
        put("xh", "\u0126o\u017ca");
        put("sux", "Sumerjan");
        put("sus", "Susu");
        put("mis", "Lingwi O\u0127ra");
        put("loz", "Lo\u017ci");
        put("tog", "Tonga (Njasa)");
        put("pon", "Ponpejan");
        put("min", "Minangkabaw");
        put("suk", "Sukuma");
        put("wo", "Wolof");
        put("lol", "Mongo");
        put("kut", "Kutenaj");
        put("mic", "Mikmek");
        put("wa", "Walloon");
        put("kum", "Kumiku");
        put("zap", "\u017bapotek");
        put("cus", "Kuxtiku (O\u0127ra)");
        put("jbo", "Lojban");
        put("doi", "Dogri");
        put("vo", "Volapuk");
        put("oto", "Lingwi Otomjani");
        put("vi", "Vjetnami\u017c");
        put("vai", "Vai");
        put("rar", "Rarotongani");
        put("ve", "Venda");
        put("rap", "Rapanwi");
        put("raj", "Ra\u0121astani");
        put("ota", "Tork (Imperu Ottoman)");
        put("nzi", "N\u017cima");
        put("nap", "Neapolitan");
        put("uz", "U\u017cbek");
        put("uga", "Ugaritiku");
        put("tmh", "Tamaxek");
        put("nai", "Indjan tal-Amerika ta' Fuq (O\u0127ra)");
        put("nah", "Na\u0127watil");
        put("ur", "Urdu");
        put("fat", "Fanti");
        put("uk", "Ukranjan");
        put("egy", "E\u0121izzjan (Antik)");
        put("ug", "Wigur");
        put("fan", "Fang");
        put("ssa", "Nilo-Sa\u0127aram");
        put("mga", "Irlandi\u017c, Medjevali (900-1200)");
        put("bat", "Baltiku (O\u0127ra)");
        put("nyo", "Njoro");
        put("bas", "Basa");
        put("nyn", "Nyankole");
        put("nym", "Njamwe\u017ci");
        put("hmn", "\u0126mong");
        put("ban", "Balini\u017c");
        put("osa", "Osa\u0121jan");
        put("bal", "Balu\u010bi");
        put("ty", "Ta\u0127itjan");
        put("bai", "Lingwi Bamileke");
        put("tw", "Twi");
        put("srr", "Serer");
        put("tli", "Tlingit");
        put("tlh", "Klingon");
        put("tt", "Tatar");
        put("ts", "Tsonga");
        put("bad", "Banda");
        put("tr", "Tork");
        put("to", "Tongan (G\u017cejjer ta' Tonga)");
        put("tn", "Zwana");
        put("tl", "Tagalog");
        put("tk", "Turkmeni");
        put("ti", "Tigrinja");
        put("th", "Tajlandi\u017c");
        put("kru", "Kurusk");
        put("tg", "Ta\u0121ik");
        put("byn", "Blin");
        put("te", "Telugu");
        put("kro", "Kru");
        put("csb", "Kashubian");
        put("ta", "Tamil");
        put("tkl", "Tokelau");
        put("efi", "Efik");
        put("sw", "Swa\u0127ili");
        put("sv", "Svedi\u017c");
        put("su", "Sundani\u017c");
        put("krc", "Karachay-Balkar");
        put("st", "Soto, t'Isfel");
        put("ss", "Swati");
        put("sr", "Serb");
        put("sq", "Albani\u017c");
        put("men", "Mende");
        put("crp", "Kreoli u Pi\u0121ini (O\u0127ra)");
        put("so", "Somali");
        put("afh", "Afri\u0127ili");
        put("sn", "Xona");
        put("sm", "Samojan");
        put("sl", "Slav");
        put("grc", "Grieg, Antik (to 1453)");
        put("sk", "Slovakk");
        put("grb", "\u0120erbo");
        put("si", "Sin\u0127ali\u017c");
        put("sh", "Serbo-Kroat");
        put("crh", "Crimean Turkish; Crimean Tatar");
        put("afa", "Afro-Asjatiku (O\u0127ra)");
        put("sg", "Sango");
        put("se", "Sami ta' Fuq");
        put("sd", "Sindi");
        put("udm", "Udmurt");
        put("sc", "Sardinjan");
        put("sa", "Sanskrit");
        put("rw", "Kinjarwanda");
        put("nwc", "Classical Newari");
        put("ru", "Russu");
        put("mdr", "Mandar");
        put("ro", "Rumen");
        put("rn", "Rundi");
        put("rm", "Reto-Romanz");
        put("mdf", "Moksha");
        put("tiv", "Tiv");
        put("ady", "Adyghe");
        put("zun", "\u017buni");
        put("kpe", "Kpelle");
        put("qu", "Ke\u010bwa");
        put("tig", "Tigre");
        put("son", "Songaj");
        put("cpp", "Creoles and pidgins, Portuguese-based (Other)");
        put("sog", "Sogdien");
        put("ada", "Adangme");
        put("kos", "Kosrejan");
        put("hit", "\u0126ittit");
        put("cpf", "Kreoli u Pi\u0121ini, Bba\u017cat fuq il-Fran\u010bi\u017c (O\u0127ra)");
        put("cpe", "Kreoli u Pi\u0121ini, Bba\u017cat fuq l-Ingli\u017c (O\u0127ra)");
        put("him", "\u0126ima\u010bali");
        put("kok", "Konkani");
        put("hil", "Hiligaynon");
        put("got", "Gotiku");
        put("gor", "Gorontalo");
        put("gon", "Gondi");
        put("din", "Dinka");
        put("nub", "Lingwi Nubjani");
        put("pt", "Portugi\u017c");
        put("ps", "Paxtun");
        put("fur", "Frijuljan");
        put("phn", "Feni\u010bju");
        put("goh", "\u0120ermaniku, Antik Pulit (ca. 750-1050)");
        put("snk", "Soninke");
        put("cop", "Koptiku");
        put("yap", "Japese");
        put("ach", "Akoli");
        put("yao", "Jao");
        put("phi", "Filippin (O\u0127ra)");
        put("pl", "Pollakk");
        put("ace", "A\u010bini\u017c");
        put("pi", "Pali");
        put("pa", "Pun\u0121abi");
        put("bug", "Bugini\u017c");
        put("iba", "Iban");
        put("sms", "Skolt Sami");
        put("bua", "Burjat");
        put("mas", "Masaj");
        put("smn", "Inari Sami");
        put("os", "Ossettiku");
        put("map", "Awstronesjan");
        put("or", "Orija");
        put("man", "Mandingwan");
        put("smj", "Lule Sami");
        put("smi", "Sami languages (Other)");
        put("mak", "Makasar");
        put("om", "Oromo (Afan)");
        put("mai", "Majtili");
        put("oj", "O\u0121ibwa");
        put("mag", "Maga\u0127i");
        put("mad", "Maduri\u017c");
        put("sma", "Southern Sami");
        put("oc", "Provenzal (wara 1500)");
        put("nso", "Soto, ta' Fuq");
        put("btk", "Batak");
        put("myv", "Erzya");
        put("dgr", "Dogrib");
        put("ny", "\u010ai\u010bewa; Njan\u0121a");
        put("myn", "Majan");
        put("nv", "Nava\u0127o");
        put("kmb", "Kimbundu");
        put("nr", "Ndebele, t'Isfel");
        put("gmh", "\u0120ermaniku, Medjevali Pulit (ca. 1050-1500)");
        put("no", "Norve\u0121i\u017c");
        put("nn", "Ninorsk Norve\u0121i\u017c");
        put("nl", "Olandi\u017c");
        put("root", "G\u0127erq");
        put("ng", "Ndonga");
        put("sla", "Slavic (Other)");
        put("ne", "Nepali\u017c");
        put("nd", "Ndebele, ta' Fuq");
        put("cmc", "Lingwi \u010aamiki");
        put("tet", "Tetum");
        put("nb", "Bokmahal Norve\u0121i\u017c");
        put("na", "Nawuru");
        put("ter", "Tereno");
        put("tem", "Timne");
        put("my", "Burmi\u017c");
        put("lez", "Le\u017cgjan");
        put("mt", "Malti");
        put("peo", "Persjan Antik (ca. 600-400 Q.K.)");
        put("ms", "Malajan");
        put("mr", "Marati");
        put("fro", "Fran\u010bi\u017c, Antik (842-ca. 1400)");
        put("mo", "Moldavjan");
        put("frm", "Fran\u010bi\u017c, Medjevali (ca. 1400-1600)");
        put("mn", "Mongoljan");
        put("jrb", "Lhudi-G\u0127arbi");
        put("ml", "Malajalam");
        put("mk", "Ma\u010bedonjan");
        put("mi", "Maori");
        put("mh", "Marxall");
        put("mg", "Malaga\u017ci");
        put("mwr", "Marwari");
        put("bra", "Braj");
        put("den", "Slav");
        put("lv", "Latvjan (Lettix)");
        put("lu", "Luba-Katanga");
        put("del", "Delawerjan");
        put("lt", "Litwanjan");
        put("lo", "Lao");
        put("ln", "Lingaljan");
        put("li", "Limburgish");
        put("ewo", "Ewondo");
        put("lg", "Ganda");
        put("lb", "Let\u017cburgi\u017c");
        put("la", "Latin");
        put("jpr", "Lhudi-Persjan");
        put("vot", "Votik");
        put("sit", "Sino-Tibetjani (O\u0127ra)");
        put("ky", "Kirgi\u017c");
        put("kw", "Korniku");
        put("kv", "Komi");
        put("ku", "Kurdi\u017c");
        put("sio", "Lingwi Suwjani");
        put("ks", "Kaxmiri");
        put("kr", "Kanuri");
        put("awa", "Awad\u0127i");
        put("ko", "Korejan");
        put("kn", "Kannada");
        put("km", "Kmer");
        put("kl", "Kalallisut");
        put("kk", "Ka\u017cak");
        put("rom", "\u017bingaru");
        put("kj", "Kuanyama");
        put("sid", "Sidamo");
        put("ki", "Kikuju");
        put("kg", "Kongo");
        put("non", "Skandinav, Antik");
        put("ka", "\u0120or\u0121jan");
        put("mus", "Kriek");
        put("roa", "Romanz (O\u0127ra)");
        put("nog", "Nogai");
        put("mun", "Lingwi tal-Munda");
        put("mul", "Lingwi Diversi");
        put("jv", "\u0120avani\u017c");
        put("gil", "Gilbertjan");
        put("znd", "\u017bande");
        put("shn", "Xan");
        put("fon", "Fon");
        put("xal", "Kalmyk");
        put("aus", "Lingwi Awstraljani");
        put("kho", "Kotani\u017c");
        put("ja", "\u0120appuni\u017c");
        put("khi", "Kojsan");
        put("pau", "Palawjan");
        put("chy", "Xajenn");
        put("tai", "Tai (O\u0127ra)");
        put("iu", "Inukitut");
        put("pap", "Papjamento");
        put("it", "Taljan");
        put("sgn", "Lingwa tas-Sinjali");
        put("is", "I\u017clandi\u017c");
        put("kha", "Kasi");
        put("chr", "\u010aerokij");
        put("pam", "Pampamga");
        put("pal", "Pa\u0127lavi");
        put("chp", "\u010aipewjan");
        put("io", "Ido");
        put("cho", "\u010aostaw");
        put("chn", "\u0120argon ta\u010b-\u010ainuk");
        put("chm", "Mari");
        put("tyv", "Tuvinjan");
        put("bnt", "Bantu");
        put("pag", "Pangasinjan");
        put("ik", "Inupjak");
        put("chk", "\u010aukese");
        put("ii", "Sichuan Yi");
        put("haw", "\u0126awajjan");
        put("lam", "Lamba");
        put("ig", "Igbo");
        put("chg", "\u010aagataj");
        put("sga", "Irlandi\u017c, Antik (sa l-900)");
        put("paa", "Papwan (O\u0127ra)");
        put("ie", "Interlingue");
        put("id", "Indone\u017cjan");
        put("lah", "Landa");
        put("day", "Dajak");
        put("chb", "\u010aib\u010ba");
        put("ia", "Interlingua");
        put("lad", "Ladino");
        put("hz", "\u0126erero");
        put("hai", "\u0126ajda");
        put("dar", "Dargwa");
        put("hy", "Armenjan");
        put("ath", "Lingwi Atabaskani");
        put("hu", "Ungeri\u017c");
        put("ht", "Haitian");
        put("dak", "Dakota");
        put("hr", "Kroat");
        put("ho", "\u0126iri Motu");
        put("hi", "\u0126indi");
        put("dyu", "Djula");
        put("he", "Ebrajk");
        put("ast", "Asturian");
        put("ha", "\u0126awsa");
        put("wen", "Lingwi Sorbjani");
        put("gv", "Manks");
        put("gu", "Gu\u0121arati");
        put("sem", "Semitiku");
        put("sel", "Selkup");
        put("iro", "Lingwi Irogwjani");
        put("gn", "Gwarani");
        put("gl", "Gallegjan");
        put("arw", "Arawak");
        put("gez", "Geez");
        put("art", "Artifi\u010bjali (O\u0127ra)");
        put("gd", "Galliku Sko\u010b\u010bi\u017c");
        put("ira", "Iranjan");
        put("ga", "Irlandi\u017c");
        put("arp", "Arapa\u0127o");
        put("arn", "Arawkanjan");
        put("fy", "Fri\u017cjan");
        put("bla", "Siksika");
        put("gem", "\u0120ermaniku (O\u0127ra)");
        put("ypk", "Lingwi Jupi\u010bi");
        put("arc", "Aramajk");
        put("fr", "Fran\u010bi\u017c");
        put("fo", "Fawri\u017c");
        put("cel", "Keltiku (O\u0127ra)");
        put("fj", "Fi\u0121i");
        put("fi", "Finlandi\u017c");
        put("ff", "Fula\u0127");
        put("tvl", "Tuvalu");
        put("ceb", "Sibwano");
        put("fa", "Persjan");
        put("eu", "Bask");
        put("sco", "Sko\u010b\u010bi\u017c");
        put("et", "Estonjan");
        put("es", "Spanjol");
        put("eo", "Esperanto");
        put("en", "Ingli\u017c");
        put("el", "Grieg");
        put("tut", "Altajk (O\u0127ra)");
        put("niu", "Nijuwejan");
        put("tup", "Tupi languages");
        put("ee", "Ewe");
        put("tum", "Tumbuka");
        put("mos", "Mossi");
        put("dz", "D\u017congka");
        put("nic", "Ni\u0121erjan - Kordofanjan");
        put("lus", "Luxaj");
        put("fiu", "Finno - Ugrijan");
        put("dv", "Dive\u0127i");
        put("nia", "Nijas");
        put("moh", "Mo\u0127ak");
        put("luo", "Luwa");
        put("lun", "Lunda");
        put("apa", "Lingwi Apa\u010bi");
        put("lui", "Luwisinu\u017c");
        put("hup", "\u0126upa");
        put("bin", "Bini");
        put("de", "\u0120ermani\u017c");
        put("lua", "Luba-Luluwa");
        put("bik", "Bikol");
        put("was", "Waxo");
        put("und", "Indeterminat");
        put("war", "Waraj");
        put("da", "Dani\u017c");
        put("dum", "Olandi\u017c, Medjevali (ca. 1050-1350)");
        put("wal", "Walamo");
        put("mno", "Lingwi Manobo");
        put("wak", "Lingwi Wakaxani");
        put("sat", "Santali");
        put("cy", "Welx");
        put("sas", "Saska");
        put("kbd", "Kabardian");
        put("cv", "\u010auvax");
        put("cu", "Slaviku tal-Knisja");
        put("mni", "Manipuri");
        put("cs", "\u010aek");
        put("sam", "Samritan");
        put("cr", "Krij");
        put("sal", "Salixan");
        put("dua", "Dwala");
        put("co", "Korsiku");
        put("sai", "Indjan tal-Amerika t'Isfel (O\u0127ra)");
        put("mnc", "Man\u010burjan");
        put("sah", "Jakut");
        put("kaw", "Kawi");
        put("inh", "Ingush");
        put("gba", "Gbaja");
        put("sad", "Sandawe");
        put("ch", "\u010aamorro");
        put("ine", "Indo-Ewropew");
        put("bho", "Bojpuri");
        put("enm", "Ingli\u017c, Medjevali (1100-1500)");
        put("kar", "Karen");
        put("inc", "Indjan (O\u0127ra)");
        put("ce", "\u010ae\u010ben");
        put("gay", "Gajo");
        put("ca", "Katalan");
        put("umb", "Umbundu");
        put("syr", "Sirjan");
        put("kam", "Kamba");
        put("tsi", "Zimxjan");
        put("ang", "Ingli\u017c, Antik (ca.450-1100)");
        put("kac", "Ka\u010bin");
        put("cau", "Kawkasu (O\u0127ra)");
        put("kab", "Kabuljan");
        put("kaa", "Kara-Kalpak");
        put("bs", "Bosnijan");
        put("car", "Karib");
        put("br", "Brenton");
        put("bo", "Tibetjan");
        put("bn", "Bengali");
        put("bm", "Bambara");
        put("gaa", "Ga");
        put("cai", "Amerika \u010aentrali (O\u0127ra)");
        put("bi", "Bislama");
        put("bh", "Bi\u0127ari");
        put("bg", "Bulgaru");
        put("be", "Belarussu");
        put("cad", "Kaddo");
        put("ba", "Baxkir");
        put("zu", "\u017bulu");
        put("zen", "\u017benaga");
        put("pro", "Provenzal, Antik (sa l-1500)");
        put("hsb", "Upper Sorbian");
        put("az", "A\u017cerbaj\u0121ani");
        put("ay", "Ajmara");
        put("av", "Avarik");
        put("as", "Assamese");
        put("dsb", "Lower Sorbian");
        put("ar", "G\u0127arbi");
        put("ilo", "Iloko");
        put("elx", "Elamit");
        put("zh", "\u010aini\u017c");
        put("an", "Aragonese");
        put("pra", "Lingwi Prakriti");
        put("am", "Am\u0127ariku");
        put("new", "Newari");
        put("ak", "Akan");
        put("za", "\u017bwang");
        put("af", "Afrikans");
        put("ae", "Avestan");
        put("ab", "Abka\u017cjan");
        put("aa", "Afar");
        put("yo", "Joruba");
        put("alg", "Lingwi Algonqwinjani");
        put("ale", "Aleut");
        put("mkh", "Mon-Kmer (O\u0127ra)");
        put("yi", "Jiddix");
        put("dra", "Dravidjan (O\u0127ra)");
        put("ber", "Beber");
        put("nds", "\u0120ermani\u017c Komuni; Sassonu Komuni");
        put("bem", "Bemba");
        put("bej", "Beja");
        put("tpi", "Tok Pisin");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final Object[][] contents =
  {
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "shortDateFormat", "dd/MM/yyyy" },
    { "mediumDateFormat", "dd MMM yyyy" },
    { "longDateFormat", "d 'ta''' MMMM yyyy" },
    { "fullDateFormat", "EEEE, d 'ta''' MMMM yyyy" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
