/* LocaleInformation_de.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_de extends ListResourceBundle
{
  private static final String collation_rules = 
    "<0<1<2<3<4<5<6<7<8<9<A,a<b,B<c,C<d,D<e,E<f,F<g,G<h,H<i,I<j,J<k,K" +
    "<l,L<m,M<n,N<o,O<p,P<q,Q<r,R<s,S<t,T<u,U<v,V<w,W<x,X<y,Y<z,Z" + 
    "&ae,\u00e4&Ae,\u00c4&oe,\u00f6&Oe,\u00d6&ue,\u00fc&Ue,\u00dc&ss,\u00df";

  private static final String[] shortMonths = {
    "Jan",
    "Feb",
    "Mrz",
    "Apr",
    "Mai",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Okt",
    "Nov",
    "Dez",
    null,
  };

  private static final String[] months = {
    "Januar",
    "Februar",
    "M\u00e4rz",
    "April",
    "Mai",
    "Juni",
    "Juli",
    "August",
    "September",
    "Oktober",
    "November",
    "Dezember",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "So",
    "Mo",
    "Di",
    "Mi",
    "Do",
    "Fr",
    "Sa",
  };

  private static final String[] weekdays = {
    null,
    "Sonntag",
    "Montag",
    "Dienstag",
    "Mittwoch",
    "Donnerstag",
    "Freitag",
    "Samstag",
  };

  private static final String[] eras = {
    "v. Chr.",
    "n. Chr.",
  };

  private static final String[] ampms = {
    "vorm.",
    "nachm.",
  };

  private static final String[][] zoneStrings =
  {
    { "WET", "Westeurop\u00e4ische Zeit", "WEZ", "Westeurop\u00e4ische Sommerzeit", "WESZ", "London" },
    { "CET", "Mitteleurop\u00e4ische Zeit", "MEZ", "Mitteleurop\u00e4ische Sommerzeit", "MESZ", "Berlin" },
    { "EET", "Osteurop\u00e4ische Zeit", "OEZ", "Mitteleurop\u00e4ische Sommerzeit", "OESZ", "Istanbul" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Osttimor");
        put("TK", "Tokelau");
        put("TJ", "Tadschikistan");
        put("TH", "Thailand");
        put("TG", "Togo");
        put("TF", "Franz\u00f6sische S\u00fcd- und Antarktisgebiete");
        put("GY", "Guyana");
        put("TD", "Tschad");
        put("TC", "Turks- und Caicosinseln");
        put("GW", "Guinea-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "S\u00fcdgeorgien und die S\u00fcdlichen Sandwichinseln");
        put("GR", "Griechenland");
        put("GQ", "\u00c4quatorialguinea");
        put("GP", "Guadeloupe");
        put("SZ", "Swasiland");
        put("SY", "Syrien");
        put("GN", "Guinea");
        put("GM", "Gambia");
        put("GL", "Gr\u00f6nland");
        put("SV", "El Salvador");
        put("ST", "S\u00e3o Tom\u00e9 und Pr\u00edncipe");
        put("GI", "Gibraltar");
        put("GH", "Ghana");
        put("SR", "Suriname");
        put("GF", "Franz\u00f6sisch-Guayana");
        put("SP", "Serbien");
        put("GE", "Georgien");
        put("SO", "Somalia");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Vereinigtes K\u00f6nigreich");
        put("SL", "Sierra Leone");
        put("GA", "Gabun");
        put("SK", "Slowakei");
        put("SJ", "Svalbard und Jan Mayen");
        put("SI", "Slowenien");
        put("SH", "St. Helena");
        put("SG", "Singapur");
        put("SE", "Schweden");
        put("SD", "Sudan");
        put("SC", "Seychellen");
        put("SB", "Salomonen");
        put("SA", "Saudi-Arabien");
        put("FR", "Frankreich");
        put("FO", "F\u00e4r\u00f6er");
        put("FM", "Mikronesien");
        put("RW", "Ruanda");
        put("FK", "Falklandinseln");
        put("RU", "Russische F\u00f6deration");
        put("FJ", "Fidschi");
        put("FI", "Finnland");
        put("RO", "Rum\u00e4nien");
        put("RE", "R\u00e9union");
        put("ET", "\u00c4thiopien");
        put("ES", "Spanien");
        put("ER", "Eritrea");
        put("EH", "Westsahara");
        put("EG", "\u00c4gypten");
        put("EE", "Estland");
        put("EC", "Ecuador");
        put("DZ", "Algerien");
        put("QA", "Katar");
        put("DO", "Dominikanische Republik");
        put("PY", "Paraguay");
        put("DM", "Dominica");
        put("PW", "Palau");
        put("DK", "D\u00e4nemark");
        put("DJ", "Dschibuti");
        put("PT", "Portugal");
        put("PS", "Pal\u00e4stinensische Gebiete");
        put("PR", "Puerto Rico");
        put("DE", "Deutschland");
        put("PN", "Pitcairn");
        put("PM", "St. Pierre und Miquelon");
        put("PL", "Polen");
        put("PK", "Pakistan");
        put("PH", "Philippinen");
        put("PG", "Papua-Neuguinea");
        put("PF", "Franz\u00f6sisch-Polynesien");
        put("CZ", "Tschechische Republik");
        put("PE", "Peru");
        put("CY", "Zypern");
        put("CX", "Weihnachtsinsel");
        put("CV", "Kap Verde");
        put("PA", "Panama");
        put("CU", "Kuba");
        put("CR", "Costa Rica");
        put("CO", "Kolumbien");
        put("CN", "China");
        put("CM", "Kamerun");
        put("CL", "Chile");
        put("CK", "Cookinseln");
        put("CI", "C\u00f4te d\u2019Ivoire");
        put("CH", "Schweiz");
        put("CG", "Kongo");
        put("CF", "Zentralafrikanische Republik");
        put("CD", "Demokratische Republik Kongo");
        put("CC", "Kokosinseln (Keeling)");
        put("OM", "Oman");
        put("CA", "Kanada");
        put("BZ", "Belize");
        put("BY", "Belarus");
        put("BW", "Botsuana");
        put("BV", "Bouvetinsel");
        put("BT", "Bhutan");
        put("BS", "Bahamas");
        put("BR", "Brasilien");
        put("NZ", "Neuseeland");
        put("BO", "Bolivien");
        put("BN", "Brunei Darussalam");
        put("BM", "Bermuda");
        put("NU", "Niue");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrain");
        put("NR", "Nauru");
        put("BG", "Bulgarien");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "Belgien");
        put("NO", "Norwegen");
        put("BD", "Bangladesch");
        put("BB", "Barbados");
        put("ZW", "Simbabwe");
        put("NL", "Niederlande");
        put("BA", "Bosnien und Herzegowina");
        put("NI", "Nicaragua");
        put("NG", "Nigeria");
        put("NF", "Norfolkinsel");
        put("AZ", "Aserbaidschan");
        put("NE", "Niger");
        put("NC", "Neukaledonien");
        put("AW", "Aruba");
        put("ZM", "Sambia");
        put("NA", "Namibia");
        put("AU", "Australien");
        put("AT", "\u00d6sterreich");
        put("AS", "Amerikanisch-Samoa");
        put("AR", "Argentinien");
        put("AQ", "Antarktis");
        put("MZ", "Mosambik");
        put("AO", "Angola");
        put("MY", "Malaysia");
        put("AN", "Niederl\u00e4ndische Antillen");
        put("MX", "Mexiko");
        put("AM", "Armenien");
        put("MW", "Malawi");
        put("AL", "Albanien");
        put("MV", "Malediven");
        put("ZA", "S\u00fcdafrika");
        put("MU", "Mauritius");
        put("MT", "Malta");
        put("AI", "Anguilla");
        put("MS", "Montserrat");
        put("MR", "Mauretanien");
        put("AG", "Antigua und Barbuda");
        put("MQ", "Martinique");
        put("AF", "Afghanistan");
        put("MP", "N\u00f6rdliche Marianen");
        put("AE", "Vereinigte Arabische Emirate");
        put("MO", "Macau S.A.R., China");
        put("AD", "Andorra");
        put("MN", "Mongolei");
        put("MM", "Myanmar");
        put("ML", "Mali");
        put("MK", "Mazedonien");
        put("YU", "Jugoslawien");
        put("YT", "Mayotte");
        put("MH", "Marshallinseln");
        put("MG", "Madagaskar");
        put("MD", "Republik Moldau");
        put("MC", "Monaco");
        put("MA", "Marokko");
        put("YE", "Jemen");
        put("LY", "Libyen");
        put("LV", "Lettland");
        put("LU", "Luxemburg");
        put("LT", "Litauen");
        put("LS", "Lesotho");
        put("LR", "Liberia");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "St. Lucia");
        put("LB", "Libanon");
        put("LA", "Laos");
        put("KZ", "Kasachstan");
        put("KY", "Kaimaninseln");
        put("KW", "Kuwait");
        put("KR", "Republik Korea");
        put("KP", "Demokratische Volksrepublik Korea");
        put("KN", "St. Kitts und Nevis");
        put("KM", "Komoren");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Kambodscha");
        put("KG", "Kirgisistan");
        put("KE", "Kenia");
        put("WF", "Wallis und Futuna");
        put("JP", "Japan");
        put("JO", "Jordanien");
        put("JM", "Jamaika");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "Amerikanische Jungferninseln");
        put("VG", "Britische Jungferninseln");
        put("VE", "Venezuela");
        put("VC", "St. Vincent und die Grenadinen");
        put("VA", "Vatikanstadt");
        put("IT", "Italien");
        put("IS", "Island");
        put("IR", "Iran");
        put("IQ", "Irak");
        put("UZ", "Usbekistan");
        put("IO", "Britisches Territorium im Indischen Ozean");
        put("UY", "Uruguay");
        put("IN", "Indien");
        put("IL", "Israel");
        put("US", "Vereinigte Staaten");
        put("IE", "Irland");
        put("ID", "Indonesien");
        put("UM", "Amerikanisch-Ozeanien");
        put("UG", "Uganda");
        put("UA", "Ukraine");
        put("HU", "Ungarn");
        put("HT", "Haiti");
        put("HR", "Kroatien");
        put("TZ", "Tansania");
        put("HN", "Honduras");
        put("HM", "Heard und McDonaldinseln");
        put("TW", "Taiwan");
        put("TV", "Tuvalu");
        put("HK", "Hong Kong S.A.R., China");
        put("TT", "Trinidad und Tobago");
        put("TR", "T\u00fcrkei");
        put("TO", "Tonga");
        put("TN", "Tunesien");
        put("TM", "Turkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("gwi", "Gwich\u02bbin");
        put("akk", "Akkadisch");
        put("eka", "Ekajuk");
        put("ijo", "Ijo");
        put("xh", "Xhosa");
        put("sux", "Sumerisch");
        put("sus", "Susu");
        put("mis", "Verschiedene Sprachen");
        put("loz", "Lozi");
        put("tog", "Tonga (Nyasa)");
        put("pon", "Ponapeanisch");
        put("min", "Minangkabau");
        put("suk", "Sukuma");
        put("wo", "Wolof");
        put("lol", "Mongo");
        put("kut", "Kutenai");
        put("mic", "Micmac");
        put("wa", "Wallonisch");
        put("kum", "Kum\u00fckisch");
        put("zap", "Zapotekisch");
        put("cus", "Kuschitische Sprachen (Andere)");
        put("jbo", "Lojban");
        put("doi", "Dogri");
        put("vo", "Volap\u00fck");
        put("oto", "Otomangue-Sprachen");
        put("vi", "Vietnamesisch");
        put("vai", "Vai");
        put("rar", "Rarotongan");
        put("ve", "Venda-Sprache");
        put("rap", "Rapanui");
        put("raj", "Rajasthani");
        put("ota", "Osmanisch");
        put("nzi", "Nzima");
        put("nap", "Neapolitanisch");
        put("uz", "Usbekisch");
        put("uga", "Ugaritisch");
        put("tmh", "Tamaseq");
        put("nai", "Indianersprachen, Nordamerika (Andere)");
        put("nah", "Nahuatl");
        put("ur", "Urdu");
        put("fat", "Fanti");
        put("uk", "Ukrainisch");
        put("egy", "\u00c4gyptisch");
        put("ug", "Uigurisch");
        put("fan", "Fang");
        put("ssa", "Nilosaharanische Sprachen");
        put("mga", "Mittelirisch");
        put("bat", "Baltische Sprachen (Andere)");
        put("nyo", "Nyoro");
        put("bas", "Basaa-Sprache");
        put("nyn", "Nyankole");
        put("nym", "Nyamwezi");
        put("hmn", "Miao-Sprachen");
        put("ban", "Balinesisch");
        put("osa", "Osage");
        put("bal", "Belutschisch");
        put("ty", "Tahitisch");
        put("bai", "Bamileke-Sprachen");
        put("tw", "Twi");
        put("srr", "Serer");
        put("tli", "Tlingit");
        put("tt", "Tatarisch");
        put("ts", "Tsonga");
        put("bad", "Banda");
        put("tr", "T\u00fcrkisch");
        put("to", "Tongaisch");
        put("tn", "Tswana-Sprache");
        put("tl", "Tagalog");
        put("tk", "Turkmenisch");
        put("ti", "Tigrinja");
        put("th", "Thai");
        put("kru", "Kurukh");
        put("tg", "Tadschikisch");
        put("byn", "Blin");
        put("te", "Telugu");
        put("kro", "Kru");
        put("csb", "Kaschubisch");
        put("ta", "Tamilisch");
        put("tkl", "Tokelauanisch");
        put("efi", "Efik");
        put("sw", "Suaheli");
        put("sv", "Schwedisch");
        put("su", "Sudanesisch");
        put("krc", "Karatschaiisch-Balkarisch");
        put("st", "S\u00fcd-Sotho-Sprache");
        put("ss", "Swazi");
        put("sr", "Serbisch");
        put("sq", "Albanisch");
        put("men", "Mende");
        put("crp", "Kreolische Sprachen");
        put("so", "Somali");
        put("afh", "Afrihili");
        put("sn", "Shona");
        put("sm", "Samoanisch");
        put("sl", "Slowenisch");
        put("grc", "Griechisch (bis 1453)");
        put("sk", "Slowakisch");
        put("grb", "Gerbo");
        put("si", "Singhalesisch");
        put("sh", "Serbo-Kroatisch");
        put("crh", "Krimtatarisch");
        put("afa", "Afro-Asiatische Sprachen  (Andere)");
        put("sg", "Sango");
        put("se", "Nord-Samisch");
        put("sd", "Sindhi");
        put("udm", "Udmurtisch");
        put("sc", "Sardisch");
        put("sa", "Sanskrit");
        put("rw", "Ruandisch");
        put("ru", "Russisch");
        put("mdr", "Mandaresisch");
        put("ro", "Rum\u00e4nisch");
        put("rn", "Rundi-Sprache");
        put("rm", "R\u00e4toromanisch");
        put("mdf", "Moksha");
        put("tiv", "Tiv");
        put("ady", "Adygai");
        put("zun", "Zuni");
        put("kpe", "Kpelle");
        put("qu", "Quechua");
        put("tig", "Tigre");
        put("son", "Songhai");
        put("cpp", "Kreolisch-Portugiesisch (Andere)");
        put("sog", "Sogdien");
        put("ada", "Adangme");
        put("kos", "Kosraeanisch");
        put("hit", "Hethitisch");
        put("cpf", "Kreolisch-Franz\u00f6sisch (Andere)");
        put("cpe", "Krio");
        put("him", "Himachali");
        put("kok", "Konkani");
        put("hil", "Hiligaynon");
        put("got", "Gotisch");
        put("gor", "Gorontalo");
        put("gon", "Gondi");
        put("din", "Dinka");
        put("nub", "Nubische Sprachen");
        put("pt", "Portugiesisch");
        put("ps", "Afghanisch (Paschtu)");
        put("fur", "Friulisch");
        put("phn", "Ph\u00f6nikisch");
        put("goh", "Althochdeutsch");
        put("snk", "Soninke");
        put("cop", "Koptisch");
        put("yap", "Yap");
        put("ach", "Acoli");
        put("yao", "Yao");
        put("phi", "Philippinen-Austronesisch (Andere)");
        put("pl", "Polnisch");
        put("ace", "Achinesisch");
        put("pi", "Pali");
        put("pa", "Pandschabisch");
        put("bug", "Buginesisch");
        put("iba", "Iban");
        put("sms", "Skolt-Lappisch");
        put("bua", "Burjatisch");
        put("mas", "Masai");
        put("smn", "Inari-Lappisch");
        put("os", "Ossetisch");
        put("map", "Austronesisch");
        put("or", "Orija");
        put("man", "Mandingo");
        put("smj", "Lule-Lappisch");
        put("smi", "Lappisch");
        put("mak", "Makassarisch");
        put("om", "Oromo");
        put("mai", "Maithili");
        put("oj", "Ojibwa-Sprache");
        put("mag", "Magahi");
        put("mad", "Maduresisch");
        put("sma", "S\u00fcd-Samisch");
        put("oc", "Okzitanisch");
        put("nso", "Sotho (Nord)");
        put("btk", "Batak");
        put("myv", "Erzya");
        put("dgr", "Dogrib");
        put("ny", "Chewa-Sprache");
        put("myn", "Maya-Sprachen");
        put("nv", "Navajo-Sprache");
        put("kmb", "Kimbundu");
        put("nr", "Ndebele-Sprache (S\u00fcd)");
        put("gmh", "Mittelhochdeutsch");
        put("no", "Norwegisch");
        put("nn", "Norwegisch Nynorsk");
        put("nl", "Niederl\u00e4ndisch");
        put("ng", "Ndonga");
        put("sla", "Slawische Sprachen (Andere)");
        put("ne", "Nepalesisch");
        put("nd", "Ndebele-Sprache (Nord)");
        put("cmc", "Cham-Sprachen");
        put("tet", "Tetum");
        put("nb", "Norwegisch Bokm\u00e5l");
        put("na", "Nauruisch");
        put("ter", "Tereno");
        put("tem", "Temne");
        put("my", "Birmanisch");
        put("lez", "Lesgisch");
        put("mt", "Maltesisch");
        put("peo", "Altpersisch");
        put("ms", "Malaiisch");
        put("mr", "Marathi");
        put("fro", "Altfranz\u00f6sisch");
        put("mo", "Moldauisch");
        put("frm", "Mittelfranz\u00f6sisch");
        put("mn", "Mongolisch");
        put("jrb", "J\u00fcdisch-Arabisch");
        put("ml", "Malayalam");
        put("mk", "Mazedonisch");
        put("mi", "Maori");
        put("mh", "Marschallesisch");
        put("mg", "Madagassisch");
        put("mwr", "Marwari");
        put("bra", "Braj");
        put("den", "Slave");
        put("lv", "Lettisch");
        put("lu", "Luba");
        put("del", "Delaware");
        put("lt", "Litauisch");
        put("lo", "Laotisch");
        put("ln", "Lingala");
        put("li", "Limburgisch");
        put("ewo", "Ewondo");
        put("lg", "Ganda-Sprache");
        put("lb", "Luxemburgisch");
        put("la", "Latein");
        put("jpr", "J\u00fcdisch-Persisch");
        put("vot", "Wotisch");
        put("sit", "Sinotibetische Sprachen (Andere)");
        put("ky", "Kirgisisch");
        put("kw", "Kornisch");
        put("kv", "Komi-Sprache");
        put("ku", "Kurdisch");
        put("sio", "Sioux-Sprachen");
        put("ks", "Kaschmirisch");
        put("kr", "Kanuri-Sprache");
        put("awa", "Awadhi");
        put("ko", "Koreanisch");
        put("kn", "Kannada");
        put("km", "Kambodschanisch");
        put("kl", "Gr\u00f6nl\u00e4ndisch");
        put("kk", "Kasachisch");
        put("rom", "Romany");
        put("kj", "Kwanyama");
        put("sid", "Sidamo");
        put("ki", "Kikuyu-Sprache");
        put("kg", "Kongo");
        put("non", "Altnordisch");
        put("ka", "Georgisch");
        put("mus", "Creek");
        put("roa", "Romance (Other)");
        put("nog", "Nogai");
        put("mun", "Munda-Sprachen");
        put("mul", "Polyglott");
        put("jv", "Javanisch");
        put("gil", "Gilbertesisch");
        put("znd", "Zande");
        put("shn", "Schan-Sprache");
        put("fon", "Fon");
        put("xal", "Kalm\u00fcckisch");
        put("aus", "Australische Sprachen");
        put("kho", "Sakisch");
        put("ja", "Japanisch");
        put("khi", "Khoisan-Sprachen (Andere)");
        put("pau", "Palau");
        put("chy", "Cheyenne");
        put("tai", "Thaisprachen (Andere)");
        put("iu", "Inukitut");
        put("pap", "Papiamento");
        put("it", "Italienisch");
        put("sgn", "Geb\u00e4rdensprache");
        put("is", "Isl\u00e4ndisch");
        put("kha", "Khasi");
        put("chr", "Cherokee");
        put("pam", "Pampanga");
        put("pal", "Mittelpersisch");
        put("chp", "Chipewyan");
        put("io", "Ido");
        put("cho", "Choctaw");
        put("chn", "Chinook");
        put("chm", "Tscheremissisch");
        put("tyv", "Tuwinisch");
        put("bnt", "Bantu");
        put("pag", "Pangasinan");
        put("ik", "Inupiak");
        put("chk", "Trukesisch");
        put("ii", "Sichuan Yi");
        put("haw", "Hawaiianisch");
        put("lam", "Banjari");
        put("ig", "Igbo-Sprache");
        put("chg", "Tschagataisch");
        put("sga", "Altirisch");
        put("paa", "Papuasprachen (Andere)");
        put("ie", "Interlingue");
        put("id", "Indonesisch");
        put("lah", "Lahnda");
        put("day", "Dajak");
        put("chb", "Chibcha");
        put("ia", "Interlingua");
        put("lad", "Ladino");
        put("hz", "Herero-Sprache");
        put("hai", "Haida");
        put("dar", "Darginisch");
        put("hy", "Armenisch");
        put("ath", "Athapaskische Sprachen");
        put("hu", "Ungarisch");
        put("ht", "Kreolisch");
        put("dak", "Dakota");
        put("hr", "Kroatisch");
        put("ho", "Hiri-Motu");
        put("hi", "Hindi");
        put("dyu", "Dyula");
        put("he", "Hebr\u00e4isch");
        put("ast", "Asturianisch");
        put("ha", "Hausa");
        put("wen", "Sorbisch");
        put("gv", "Manx");
        put("gu", "Gujarati");
        put("sem", "Semitische Sprachen (Andere)");
        put("sel", "Selkupisch");
        put("iro", "Irokesische Sprachen");
        put("gn", "Guarani");
        put("gl", "Galizisch");
        put("arw", "Arawak");
        put("gez", "Geez");
        put("art", "Kunstsprachen (Andere)");
        put("gd", "Schottisch-G\u00e4lisch");
        put("ira", "Iranisch");
        put("ga", "Irisch");
        put("arp", "Arapaho-Sprache");
        put("arn", "Araukanisch");
        put("fy", "Friesisch");
        put("bla", "Siksika");
        put("gem", "Germanische Sprachen (Andere)");
        put("ypk", "Yupik-Sprachen");
        put("arc", "Aram\u00e4isch");
        put("fr", "Franz\u00f6sisch");
        put("fo", "F\u00e4r\u00f6isch");
        put("cel", "Keltische Sprachen (Andere)");
        put("fj", "Fidschianisch");
        put("fi", "Finnisch");
        put("ff", "Ful");
        put("tvl", "Elliceanisch");
        put("ceb", "Cebuano");
        put("fa", "Persisch");
        put("eu", "Baskisch");
        put("sco", "Schottisch");
        put("et", "Estnisch");
        put("es", "Spanisch");
        put("eo", "Esperanto");
        put("en", "Englisch");
        put("el", "Griechisch");
        put("tut", "Altaische Sprachen (Andere)");
        put("niu", "Niue");
        put("tup", "Tupi-Sprachen");
        put("ee", "Ewe-Sprache");
        put("tum", "Tumbuka");
        put("mos", "Mossi");
        put("dz", "Bhutanisch");
        put("nic", "Nigerkordofanische Sprachen");
        put("lus", "Lushai");
        put("fiu", "Finnougrische Sprachen (Andere)");
        put("dv", "Maledivisch");
        put("nia", "Nias");
        put("moh", "Mohawk");
        put("luo", "Luo");
        put("lun", "Lunda");
        put("apa", "Apachen-Sprachen");
        put("lui", "Luiseno");
        put("hup", "Hupa");
        put("bin", "Bini");
        put("de", "Deutsch");
        put("lua", "Luba-Lulua");
        put("bik", "Bikol");
        put("was", "Washo");
        put("und", "Sprache nicht ermittelt");
        put("war", "Waray");
        put("da", "D\u00e4nisch");
        put("dum", "Mittelniederl\u00e4ndisch");
        put("wal", "Walamo");
        put("mno", "Manobo-Sprachen");
        put("wak", "Wakash-Sprachen");
        put("sat", "Santali");
        put("cy", "Kymrisch");
        put("sas", "Sassak");
        put("kbd", "Kabardinisch");
        put("cv", "Tschuwaschisch");
        put("cu", "Kirchenslawisch");
        put("mni", "Manipuri");
        put("cs", "Tschechisch");
        put("sam", "Samaritanisch");
        put("cr", "Cree");
        put("sal", "Salish-Sprachen");
        put("dua", "Duala");
        put("co", "Korsisch");
        put("sai", "Indianersprachen, S\u00fcdamerika (Andere)");
        put("mnc", "Mandschurisch");
        put("sah", "Jakutisch");
        put("kaw", "Altjavanisch");
        put("inh", "Ingush");
        put("gba", "Gbaya");
        put("sad", "Sandawe");
        put("ch", "Chamorro-Sprache");
        put("ine", "Indogermanische Sprachen (Andere)");
        put("bho", "Bhodschpuri");
        put("enm", "Mittelenglisch");
        put("kar", "Karenisch");
        put("inc", "Indoarische Sprachen");
        put("ce", "Tschetschenisch");
        put("gay", "Gayo");
        put("ca", "Katalanisch");
        put("umb", "Umbundu");
        put("syr", "Syrisch");
        put("kam", "Kamba");
        put("tsi", "Tsimshian");
        put("ang", "Altenglisch");
        put("kac", "Kachin");
        put("cau", "Kaukasische Sprachen (Andere)");
        put("kab", "Kabylisch");
        put("kaa", "Karakalpakisch");
        put("bs", "Bosnisch");
        put("car", "Karibische Sprachen");
        put("br", "Bretonisch");
        put("bo", "Tibetisch");
        put("bn", "Bengalisch");
        put("bm", "Bambara-Sprache");
        put("gaa", "Ga");
        put("cai", "Indianersprachen, Zentralamerika (Andere)");
        put("bi", "Bislama");
        put("bh", "Biharisch");
        put("bg", "Bulgarisch");
        put("be", "Wei\u00dfrussisch");
        put("cad", "Caddo");
        put("ba", "Baschkirisch");
        put("zu", "Zulu");
        put("zen", "Zenaga");
        put("pro", "Altprovenzalisch");
        put("hsb", "Obersorbisch");
        put("az", "Aserbaidschanisch");
        put("ay", "Aymar\u00e1-Sprache");
        put("av", "Awarisch");
        put("as", "Assamesisch");
        put("dsb", "Niedersorbisch");
        put("ar", "Arabisch");
        put("ilo", "Iloko");
        put("elx", "Elamisch");
        put("zh", "Chinesisch");
        put("an", "Aragonesisch");
        put("pra", "Prakrit");
        put("am", "Amharisch");
        put("new", "Newari");
        put("ak", "Akan");
        put("za", "Zhuang");
        put("af", "Afrikaans");
        put("ae", "Avestisch");
        put("ab", "Abchasisch");
        put("aa", "Afar");
        put("yo", "Joruba");
        put("alg", "Algonkin-Sprachen");
        put("ale", "Aleutisch");
        put("mkh", "Mon-Khmer-Sprachen");
        put("yi", "Jiddisch");
        put("dra", "Drawidische Sprachen (Andere)");
        put("ber", "Berbersprachen");
        put("nds", "Niederdeutsch");
        put("bem", "Bemba");
        put("bej", "Bedauye");
        put("tpi", "Neumelanesisch");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "shortMonths", shortMonths },
    { "collation_rules", collation_rules },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "ampms", ampms },
    { "shortDateFormat", "dd.MM.yy" },
    { "mediumDateFormat", "dd.MM.yyyy" },
    { "longDateFormat", "d. MMMM yyyy" },
    { "fullDateFormat", "EEEE, d. MMMM yyyy" },
    { "fullTimeFormat", "H:mm' Uhr 'z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
