/* LocaleInformation_ko.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_ko extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "1\uc6d4",
    "2\uc6d4",
    "3\uc6d4",
    "4\uc6d4",
    "5\uc6d4",
    "6\uc6d4",
    "7\uc6d4",
    "8\uc6d4",
    "9\uc6d4",
    "10\uc6d4",
    "11\uc6d4",
    "12\uc6d4",
    null,
  };

  private static final String[] months = {
    "1\uc6d4",
    "2\uc6d4",
    "3\uc6d4",
    "4\uc6d4",
    "5\uc6d4",
    "6\uc6d4",
    "7\uc6d4",
    "8\uc6d4",
    "9\uc6d4",
    "10\uc6d4",
    "11\uc6d4",
    "12\uc6d4",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "\uc77c",
    "\uc6d4",
    "\ud654",
    "\uc218",
    "\ubaa9",
    "\uae08",
    "\ud1a0",
  };

  private static final String[] weekdays = {
    null,
    "\uc77c\uc694\uc77c",
    "\uc6d4\uc694\uc77c",
    "\ud654\uc694\uc77c",
    "\uc218\uc694\uc77c",
    "\ubaa9\uc694\uc77c",
    "\uae08\uc694\uc77c",
    "\ud1a0\uc694\uc77c",
  };

  private static final String[] eras = {
    "\uae30\uc6d0\uc804",
    "\uc11c\uae30",
  };

  private static final String[] ampms = {
    "\uc624\uc804",
    "\uc624\ud6c4",
  };

  private static final String[][] zoneStrings =
  {
    { "PST", "\ud0dc\ud3c9\uc591 \ud45c\uc900\uc2dc", "PDT", "\ud0dc\ud3c9\uc591 \uae30\uc900\uc2dc",  "America/Los_Angeles" },
    { "HST", "\ud558\uc640\uc774 \ud45c\uc900\uc2dc", "HST", "\ud558\uc640\uc774 \ud45c\uc900\uc2dc",  "Pacific/Honolulu" },
    { "GMT", "\uadf8\ub9ac\ub2c8\uce58 \ud45c\uc900\uc2dc", "GMT", "\uadf8\ub9ac\ub2c8\uce58 \ud45c\uc900\uc2dc",  "Etc/GMT" },
    { "MST", "\uc0b0\uc545 \ud45c\uc900\uc2dc", "MST", "\uc0b0\uc545 \ud45c\uc900\uc2dc",  "America/Phoenix" },
    { "GMT", "\uadf8\ub9ac\ub2c8\uce58 \ud45c\uc900\uc2dc", "GMT", "\uadf8\ub9ac\ub2c8\uce58 \ud45c\uc900\uc2dc",  "Africa/Casablanca" },
    { "MST", "\uc0b0\uc545 \ud45c\uc900\uc2dc", "MDT", "\uc0b0\uc545 \uae30\uc900\uc2dc",  "America/Denver" },
    { "IST", "\uc774\uc2a4\ub77c\uc5d8 \ud45c\uc900\uc2dc", "IDT", "\uc774\uc2a4\ub77c\uc5d8 \uae30\uc900\uc2dc",  "Asia/Jerusalem" },
    { "AST", "\uc54c\ub798\uc2a4\uce74 \ud45c\uc900\uc2dc", "ADT", "\uc54c\ub798\uc2a4\uce74 \uae30\uc900\uc2dc",  "America/Anchorage" },
    { "CET", "\uc911\ubd80\uc720\ub7fd \ud45c\uc900\uc2dc", "CEST", "\uc911\ubd80\uc720\ub7fd \uae30\uc900\uc2dc",  "Europe/Paris" },
    { "EST", "\ub3d9\ubd80 \ud45c\uc900\uc2dc", "EST", "\ub3d9\ubd80 \ud45c\uc900\uc2dc",  "America/Indianapolis" },
    { "EET", "\ub3d9\ubd80\uc720\ub7fd \ud45c\uc900\uc2dc", "EEST", "\ub3d9\ubd80\uc720\ub7fd \uae30\uc900\uc2dc",  "Europe/Bucharest" },
    { "JST", "\uc77c\ubcf8 \ud45c\uc900\uc2dc", "JST", "\uc77c\ubcf8 \ud45c\uc900\uc2dc",  "Asia/Tokyo" },
    { "CTT", "\uc911\uad6d \ud45c\uc900\uc2dc", "CDT", "\uc911\uad6d \ud45c\uc900\uc2dc",  "Asia/Shanghai" },
    { "EST", "\ub3d9\ubd80 \ud45c\uc900\uc2dc", "EDT", "\ub3d9\ubd80 \uae30\uc900\uc2dc",  "America/New_York" },
    { "KST", "\ud55c\uad6d\ud45c\uc900\uc2dc", "KST", "\ud55c\uad6d\ud45c\uc900\uc2dc",  "Asia/Seoul" },
    { "AST", "\ub300\uc11c\uc591 \ud45c\uc900\uc2dc", "ADT", "\ub300\uc11c\uc591 \uae30\uc900\uc2dc",  "America/Halifax" },
    { "CNT", "\ub274\ud380\ub4e4\ub79c\ub4dc \ud45c\uc900\uc2dc", "CDT", "\ub274\ud380\ub4e4\ub79c\ub4dc \uae30\uc900\uc2dc",  "America/St_Johns" },
    { "CST", "\uc911\ubd80 \ud45c\uc900\uc2dc", "CDT", "\uc911\ubd80 \uae30\uc900\uc2dc",  "America/Chicago" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "\ub3d9\ud2f0\ubaa8\ub974");
        put("TK", "\ud1a0\ucf08\ub77c\uc6b0");
        put("TJ", "\ud0c0\uc9c0\ud0a4\uc2a4\ud0c4");
        put("TH", "\ud0dc\uad6d");
        put("TG", "\ud1a0\uace0");
        put("TF", "\ud504\ub791\uc2a4 \ub0a8\ubd80 \uc9c0\ubc29");
        put("GY", "\uac00\uc774\uc544\ub098");
        put("TD", "\ucc28\ub4dc");
        put("TC", "\ud130\ud06c\uc2a4\ucf00\uc774\ucee4\uc2a4\uc81c\ub3c4");
        put("GW", "\uae30\ub124\ube44\uc3d8");
        put("GU", "\uad0c");
        put("GT", "\uacfc\ud14c\ub9d0\ub77c");
        put("GS", "\uc0ac\uc6b0\uc2a4\uc870\uc9c0\uc544-\uc0ac\uc6b0\uc2a4\uc0cc\ub4dc\uc704\uce58\uc81c\ub3c4");
        put("GR", "\uadf8\ub9ac\uc2a4");
        put("GQ", "\uc801\ub3c4 \uae30\ub2c8");
        put("GP", "\uacfc\ub2ec\ub85c\ud504");
        put("SZ", "\uc2a4\uc640\uc9c8\ub79c\ub4dc");
        put("SY", "\uc2dc\ub9ac\uc544");
        put("GN", "\uae30\ub2c8");
        put("GM", "\uac10\ube44\uc544");
        put("GL", "\uadf8\ub9b0\ub780\ub4dc");
        put("SV", "\uc5d8\uc0b4\ubc14\ub3c4\ub974");
        put("ST", "\uc0c1\ud22c\uba54 \ud504\ub9b0\uc2dc\ud398");
        put("GI", "\uc9c0\ube0c\ub864\ud130");
        put("GH", "\uac00\ub098");
        put("SR", "\uc218\ub9ac\ub0a8");
        put("GF", "\ud504\ub791\uc2a4\ub839 \uae30\uc544\ub098");
        put("SP", "\uc138\ub974\ube44\uc544");
        put("GE", "\uadf8\ub8e8\uc9c0\uc57c");
        put("SO", "\uc18c\ub9d0\ub9ac\uc544");
        put("GD", "\uadf8\ub808\ub098\ub2e4");
        put("SN", "\uc138\ub124\uac08");
        put("SM", "\uc0b0\ub9c8\ub9ac\ub178");
        put("GB", "\uc601\uad6d");
        put("SL", "\uc2dc\uc5d0\ub77c\ub9ac\uc628");
        put("GA", "\uac00\ubd09");
        put("SK", "\uc2ac\ub85c\ubc14\ud0a4\uc544");
        put("SJ", "\uc2a4\ubc1c\ubc14\ub974\uc81c\ub3c4-\uc580\ub9c8\uc6ec\uc12c");
        put("SI", "\uc2ac\ub85c\ubca0\ub2c8\uc544");
        put("SH", "\uc138\uc778\ud2b8\ud5ec\ub808\ub098");
        put("SG", "\uc2f1\uac00\ud3ec\ub974");
        put("SE", "\uc2a4\uc6e8\ub374");
        put("SD", "\uc218\ub2e8");
        put("SC", "\uc250\uc774\uc258");
        put("SB", "\uc194\ub85c\ubaac");
        put("SA", "\uc0ac\uc6b0\ub514\uc544\ub77c\ube44\uc544");
        put("FR", "\ud504\ub791\uc2a4");
        put("FO", "\ud398\ub85c\uc81c\ub3c4");
        put("FM", "\ub9c8\uc774\ud06c\ub85c\ub124\uc2dc\uc544");
        put("RW", "\ub974\uc644\ub2e4");
        put("FK", "\ud3ec\ud074\ub79c\ub4dc\uc81c\ub3c4");
        put("RU", "\ub7ec\uc2dc\uc544");
        put("FJ", "\ud53c\uc9c0");
        put("FI", "\ud540\ub780\ub4dc");
        put("RO", "\ub8e8\ub9c8\ub2c8\uc544");
        put("RE", "\ub9ac\uc720\ub2c8\uc628");
        put("ET", "\uc774\ub514\uc624\ud53c\uc544");
        put("ES", "\uc2a4\ud398\uc778");
        put("ER", "\uc5d0\ub9ac\ud2b8\ub9ac\uc544");
        put("EH", "\uc11c\uc0ac\ud558\ub77c");
        put("EG", "\uc774\uc9d1\ud2b8");
        put("EE", "\uc5d0\uc2a4\ud1a0\ub2c8\uc544");
        put("EC", "\uc5d0\ucfe0\uc544\ub3c4\ub974");
        put("DZ", "\uc54c\uc81c\ub9ac");
        put("QA", "\uce74\ud0c0\ub974");
        put("DO", "\ub3c4\ubbf8\ub2c8\uce74 \uacf5\ud654\uad6d");
        put("PY", "\ud30c\ub77c\uacfc\uc774");
        put("DM", "\ub3c4\ubbf8\ub2c8\uce74");
        put("PW", "\ud314\ub77c\uc6b0");
        put("DK", "\ub374\ub9c8\ud06c");
        put("DJ", "\uc9c0\ubd80\ud2f0");
        put("PT", "\ud3ec\ub974\ud2b8\uce7c");
        put("PS", "\ud314\ub808\uc2a4\ud0c0\uc778 \uc9c0\uad6c");
        put("PR", "\ud478\uc5d0\ub974\ud1a0\ub9ac\ucf54");
        put("DE", "\ub3c5\uc77c");
        put("PN", "\ud54f\ucf00\uc5b8\uc12c");
        put("PM", "\uc138\uc778\ud2b8\ud53c\uc5d0\ub974-\ubbf8\ucf00\ub871");
        put("PL", "\ud3f4\ub780\ub4dc");
        put("PK", "\ud30c\ud0a4\uc2a4\ud0c4");
        put("PH", "\ud544\ub9ac\ud540");
        put("PG", "\ud30c\ud478\uc544\ub274\uae30\ub2c8");
        put("PF", "\ud504\ub791\uc2a4\ub839 \ud3f4\ub9ac\ub124\uc2dc\uc544");
        put("CZ", "\uccb4\ucf54");
        put("PE", "\ud398\ub8e8");
        put("CY", "\uc0ac\uc774\ud504\ub7ec\uc2a4");
        put("CX", "\ud06c\ub9ac\uc2a4\ub9c8\uc2a4\uc12c");
        put("CV", "\uae4c\ubf40\ubca0\ub974\ub370");
        put("PA", "\ud30c\ub098\ub9c8");
        put("CU", "\ucfe0\ubc14");
        put("CR", "\ucf54\uc2a4\ud0c0\ub9ac\uce74");
        put("CO", "\ucf5c\ub86c\ube44\uc544");
        put("CN", "\uc911\uad6d");
        put("CM", "\uce74\uba54\ub8ec");
        put("CL", "\uce60\ub808");
        put("CK", "\ucfe1\uc81c\ub3c4");
        put("CI", "\ucf54\ud2b8\ub514\ubd80\uc640\ub974");
        put("CH", "\uc2a4\uc704\uc2a4");
        put("CG", "\ucf69\uace0");
        put("CF", "\uc911\uc559 \uc544\ud504\ub9ac\uce74");
        put("CD", "\ucf69\uace0\ubbfc\uc8fc\uacf5\ud654\uad6d");
        put("CC", "\ucf54\ucf54\uc2a4\uc81c\ub3c4");
        put("OM", "\uc624\ub9cc");
        put("CA", "\uce90\ub098\ub2e4");
        put("BZ", "\ubca8\ub9ac\uc988");
        put("BY", "\ubca8\ub77c\ub8e8\uc2a4");
        put("BW", "\ubcf4\uce20\uc640\ub098");
        put("BV", "\ubd80\ubca0");
        put("BT", "\ubd80\ud0c4");
        put("BS", "\ubc14\ud558\ub9c8");
        put("BR", "\ube0c\ub77c\uc9c8");
        put("NZ", "\ub274\uc9c8\ub79c\ub4dc");
        put("BO", "\ubcfc\ub9ac\ube44\uc544");
        put("BN", "\ube0c\ub8e8\ub098\uc774");
        put("BM", "\ubc84\ubba4\ub2e4");
        put("NU", "\ub2c8\uc6b0\uc5d0");
        put("BJ", "\ubca0\ub139");
        put("BI", "\ubd80\ub8ec\ub514");
        put("BH", "\ubc14\ub808\uc778");
        put("NR", "\ub098\uc6b0\ub8e8");
        put("BG", "\ubd88\uac00\ub9ac\uc544");
        put("BF", "\ubd80\ub974\ud0a4\ub098\ud30c\uc18c");
        put("NP", "\ub124\ud314");
        put("BE", "\ubca8\uae30\uc5d0");
        put("NO", "\ub178\ub974\uc6e8\uc774");
        put("BD", "\ubc29\uae00\ub77c\ub370\uc2dc");
        put("BB", "\ubc14\ubca0\uc774\ub3c4\uc2a4");
        put("ZW", "\uc9d0\ubc14\ube0c\uc6e8");
        put("NL", "\ub124\ub35c\ub780\ub4dc");
        put("BA", "\ubcf4\uc2a4\ub2c8\uc544 \ud5e4\ub974\uccb4\uace0\ube44\ub098");
        put("NI", "\ub2c8\uce74\ub77c\uacfc");
        put("NG", "\ub098\uc774\uc9c0\ub9ac\uc544");
        put("NF", "\ub178\ud37d\uc12c");
        put("AZ", "\uc544\uc81c\ub974\ubc14\uc774\uc794");
        put("NE", "\ub2c8\uc81c\ub974");
        put("NC", "\ub274 \uce7c\ub808\ub3c4\ub2c8\uc544");
        put("AW", "\uc544\ub8e8\ubc14");
        put("ZM", "\uc7a0\ube44\uc544");
        put("NA", "\ub098\ubbf8\ube44\uc544");
        put("AU", "\uc624\uc2a4\ud2b8\ub808\uc77c\ub9ac\uc544");
        put("AT", "\uc624\uc2a4\ud2b8\ub9ac\uc544");
        put("AS", "\uc544\uba54\ub9ac\uce78 \uc0ac\ubaa8\uc544");
        put("AR", "\uc544\ub974\ud5e8\ud2f0\ub098");
        put("AQ", "\ub0a8\uadf9 \ub300\ub959");
        put("MZ", "\ubaa8\uc7a0\ube44\ud06c");
        put("AO", "\uc559\uace8\ub77c");
        put("MY", "\ub9d0\ub808\uc774\uc9c0\uc544");
        put("AN", "\ub124\ub35c\ub780\ub4dc\ub839 \uc548\ud2f8\ub808\uc2a4");
        put("MX", "\uba55\uc2dc\ucf54");
        put("AM", "\uc544\ub974\uba54\ub2c8\uc544");
        put("MW", "\ub9d0\ub77c\uc704");
        put("AL", "\uc54c\ubc14\ub2c8\uc544");
        put("MV", "\ubab0\ub514\ube0c");
        put("ZA", "\ub0a8\uc544\ud504\ub9ac\uce74");
        put("MU", "\ubaa8\ub9ac\uc154\uc2a4");
        put("MT", "\ubab0\ud0c0");
        put("AI", "\uc548\uae38\ub77c");
        put("MS", "\ubaac\ud2b8\uc138\ub77c\ud2b8");
        put("MR", "\ubaa8\ub9ac\ud0c0\ub2c8");
        put("AG", "\uc564\ud2f0\uac00 \ubc14\ubd80\ub2e4");
        put("MQ", "\ub9d0\ud2f0\ub2c8\ud06c");
        put("AF", "\uc544\ud504\uac00\ub2c8\uc2a4\ud0c4");
        put("MP", "\ubd81\ub9c8\ub9ac\uc544\ub098\uc81c\ub3c4");
        put("AE", "\uc544\ub78d\uc5d0\ubbf8\ub9ac\ud2b8");
        put("MO", "\ub9c8\uce74\uc624, \uc911\uad6d \ud2b9\ubcc4\ud589\uc815\uad6c");
        put("AD", "\uc548\ub3c4\ub77c");
        put("MN", "\ubabd\uace8");
        put("MM", "\ubbf8\uc580\ub9c8");
        put("ML", "\ub9d0\ub9ac");
        put("MK", "\ub9c8\ucf00\ub3c4\ub2c8\uc544\uc5b4");
        put("YU", "\uc720\uace0\uc2ac\ub77c\ube44\uc544");
        put("YT", "\ub9c8\uc694\ud2f0");
        put("MH", "\ub9c8\uc0ec \uad70\ub3c4");
        put("MG", "\ub9c8\ub2e4\uac00\uc2a4\uce74\ub974");
        put("MD", "\ubab0\ub3c4\ubc14");
        put("MC", "\ubaa8\ub098\ucf54");
        put("MA", "\ubaa8\ub85c\ucf54");
        put("YE", "\uc608\uba58");
        put("LY", "\ub9ac\ube44\uc544");
        put("LV", "\ub77c\ud2b8\ube44\uc544");
        put("LU", "\ub8e9\uc148\ubd80\ub974\ud06c");
        put("LT", "\ub9ac\ud22c\uc544\ub2c8\uc544");
        put("LS", "\ub808\uc18c\ud1a0");
        put("LR", "\ub77c\uc774\ubca0\ub9ac\uc544");
        put("LK", "\uc2a4\ub9ac\ub791\uce74");
        put("LI", "\ub9ac\ud788\ud150\uc288\ud0c0\uc778");
        put("LC", "\uc138\uc778\ud2b8\ub8e8\uc2dc\uc544");
        put("LB", "\ub808\ubc14\ub17c");
        put("LA", "\ub77c\uc624\uc2a4");
        put("KZ", "\uce74\uc790\ud750\uc2a4\ud0c4");
        put("KY", "\ucf00\uc774\ub9e8\uc81c\ub3c4");
        put("KW", "\ucfe0\uc6e8\uc774\ud2b8");
        put("KR", "\ub300\ud55c\ubbfc\uad6d");
        put("KP", "\uc870\uc120 \ubbfc\uc8fc\uc8fc\uc758 \uc778\ubbfc \uacf5\ud654\uad6d");
        put("KN", "\uc138\uc778\ud2b8\ud06c\ub9ac\uc2a4\ud1a0\ud37c \ub124\ube44\uc2a4");
        put("KM", "\ucf54\ubaa8\ub974");
        put("KI", "\ud0a4\ub9ac\ubc14\uc2dc");
        put("WS", "\uc0ac\ubaa8\uc544");
        put("KH", "\uce84\ubcf4\ub514\uc544");
        put("KG", "\ud0a4\ub974\uae30\uc2a4\uc2a4\ud0c4");
        put("KE", "\ucf00\ub0d0");
        put("WF", "\uc648\ub9ac\uc2a4-\ud478\ud22c\ub098 \uc81c\ub3c4");
        put("JP", "\uc77c\ubcf8");
        put("JO", "\uc694\ub974\ub2e8");
        put("JM", "\uc790\uba54\uc774\uce74");
        put("VU", "\ubc14\ub204\uc544\ud22c");
        put("VN", "\ubca0\ud2b8\ub0a8");
        put("VI", "\ubbf8\uad6d\ub839 \ubc84\uc9c4 \uc544\uc77c\ub79c\ub4dc");
        put("VG", "\uc601\uad6d\ub839 \ubc84\uc9c4 \uc544\uc77c\ub79c\ub4dc");
        put("VE", "\ubca0\ub124\uc218\uc5d8\ub77c");
        put("VC", "\uc138\uc778\ud2b8\ube48\uc13c\ud2b8\uadf8\ub808\ub098\ub518");
        put("VA", "\ubc14\ud2f0\uce78");
        put("IT", "\uc774\ud0c8\ub9ac\uc544");
        put("IS", "\uc544\uc774\uc2ac\ub780\ub4dc");
        put("IR", "\uc774\ub780");
        put("IQ", "\uc774\ub77c\ud06c");
        put("UZ", "\uc6b0\uc988\ubca0\ud0a4\uc2a4\ud0c4");
        put("IO", "\uc601\uad6d\ub839\uc778\ub3c4\uc591\uc2dd\ubbfc\uc9c0");
        put("UY", "\uc6b0\ub8e8\uacfc\uc774");
        put("IN", "\uc778\ub3c4");
        put("IL", "\uc774\uc2a4\ub77c\uc5d8");
        put("US", "\ubbf8\uad6d");
        put("IE", "\uc544\uc77c\ub79c\ub4dc");
        put("ID", "\uc778\ub3c4\ub124\uc2dc\uc544");
        put("UM", "\ubbf8\uad6d\ub839 \ud574\uc678 \uc81c\ub3c4");
        put("UG", "\uc6b0\uac04\ub2e4");
        put("UA", "\uc6b0\ud06c\ub77c\uc774\ub098");
        put("HU", "\ud5dd\uac00\ub9ac");
        put("HT", "\ud558\uc774\ud2f0");
        put("HR", "\ud06c\ub85c\uc544\ud2f0\uc544");
        put("TZ", "\ud0c4\uc790\ub2c8\uc544");
        put("HN", "\uc628\ub450\ub77c\uc2a4");
        put("HM", "\ud5c8\ub4dc\uc12c-\ub9e5\ub3c4\ub110\ub4dc\uc81c\ub3c4");
        put("TW", "\ub300\ub9cc");
        put("TV", "\ud22c\ubc1c\ub8e8");
        put("HK", "\ud64d\ucf69, \uc911\uad6d \ud2b9\ubcc4\ud589\uc815\uad6c");
        put("TT", "\ud2b8\ub9ac\ub2c8\ub2e4\ub4dc \ud1a0\ubc14\uace0");
        put("TR", "\ud130\ud0a4");
        put("TO", "\ud1b5\uac00");
        put("TN", "\ud280\ub2c8\uc9c0");
        put("TM", "\ud22c\ub974\ud06c\uba54\ub2c8\uc2a4\ud0c4");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("gwi", "\uadf8\uc704\uce5c\uc5b4");
        put("akk", "\uc544\uce74\ub4dc\uc5b4");
        put("eka", "\uc774\uce74\uc8fd\uc5b4");
        put("ijo", "\uc774\uc870\uc5b4");
        put("xh", "\ubc18\ud22c\uc5b4(\ub0a8\uc544\ud504\ub9ac\uce74)");
        put("sux", "\uc218\uba54\ub974\uc5b4");
        put("sus", "\uc218\uc218\uc5b4");
        put("mis", "\uae30\ud0c0 \uc5b8\uc5b4");
        put("loz", "\ub85c\uc9c0\uc5b4");
        put("tog", "\ud1b5\uac00\uc5b4 (\ub2c8\uc544\uc0b4\ub79c\ub4dc)");
        put("pon", "\ud3fc\ud398\uc774\uc5b4");
        put("min", "\ubbf8\ub0ad\uce74\ubc14\uc6b0");
        put("suk", "\uc218\ucfe0\ub9c8\uc871\uc5b4");
        put("wo", "\uc62c\ub85c\ud504\uc5b4");
        put("lol", "\ubabd\uad6c\uc5b4");
        put("kut", "\ucfe0\ud14c\ub124\uc5b4");
        put("mic", "\ubbf8\ud06c\ub9e5\uc5b4");
        put("wa", "\uc648\ub860\uc5b4");
        put("kum", "\ucfe0\ubbf9\uc5b4");
        put("zap", "\uc0ac\ud3ec\ud14c\ud06c\uc5b4");
        put("cus", "\ucfe0\uc2dc\ud2b8\uc81c\uc871\uc5b4 (\uae30\ud0c0)");
        put("jbo", "\ub85c\ubc18\uc5b4");
        put("doi", "\ub3c4\uadf8\ub9ac\uc5b4");
        put("vo", "\ubcfc\ub77c\ud4cc\ud06c\uc5b4");
        put("oto", "\uc624\ud1a0\ubbf8\uc548\uc5b4");
        put("vi", "\ubca0\ud2b8\ub0a8\uc5b4");
        put("vai", "\ubc14\uc774\uc5b4");
        put("rar", "\ud30c\ub85c\ud1a4\uac04\uc5b4");
        put("ve", "\ubca4\ub2e4\uc5b4");
        put("rap", "\ub77c\ud30c\ub274\uc774");
        put("raj", "\ub77c\uc790\uc2a4\ud0c4\uc5b4");
        put("ota", "\ud130\ud0a4\uc5b4, \uc624\uc2a4\ub9cc (1500-1928)");
        put("nzi", "\ub290\uc9c0\ub9c8\uc5b4");
        put("nap", "\ub098\ud3f4\ub9ac\uc5b4");
        put("uz", "\uc6b0\uc988\ubca0\ud06c\uc5b4");
        put("uga", "\uc720\uac00\ub9ac\ud2f1\uc5b4");
        put("tmh", "\ud0c0\ub9c8\uc139\uc5b4");
        put("nai", "\ubd81 \uc544\uba54\ub9ac\uce78 \uc778\ub514\uc5b8\uc5b4 (\uae30\ud0c0)");
        put("nah", "\ub098\uc6b0\uc544\ud2c0\uc5b4");
        put("ur", "\uc6b0\ub974\ub450\uc5b4");
        put("fat", "\ud310\ud2f0\uc5b4");
        put("uk", "\uc6b0\ud06c\ub77c\uc774\ub098\uc5b4");
        put("egy", "\uc774\uc9d1\ud2b8\uc5b4 (\uace0\ub300)");
        put("ug", "\uc704\uad6c\ub974\uc5b4");
        put("fan", "\ud321\uadf8\uc5b4");
        put("ssa", "\ub2c8\ub85c-\uc0ac\ud558\ub78c\uc5b4 (\uae30\ud0c0)");
        put("mga", "\uc544\uc77c\ub79c\ub4dc\uc5b4, \uc911\uc138 (900-1200)");
        put("bat", "\ubc1c\ud2b8\uc5b4 (\uae30\ud0c0)");
        put("nyo", "\ub274\ub85c\uc5b4");
        put("bas", "\ubc14\uc0ac\uc5b4");
        put("nyn", "\ub2c8\uc548\ucf5c\uc5b4");
        put("nym", "\ub2c8\uc554\uc6e8\uc9c0\uc5b4");
        put("hmn", "\ud788\ubab8\uc5b4");
        put("ban", "\ubc1c\ub9ac\uc5b4");
        put("osa", "\uc624\uc138\uc774\uc9c0\uc5b4");
        put("bal", "\ubc1c\ub8e8\uce58\uc5b4");
        put("ty", "\ud0c0\ud788\ud2f0\uc5b4");
        put("bai", "\ubc14\ubbf8\ub808\ucf00\uc5b4");
        put("tw", "\ud2b8\uc704\uc5b4");
        put("srr", "\uc138\uc140\uc5b4");
        put("tli", "\ud2c0\ub9c1\uae43\uc871\uc5b4");
        put("tt", "\ud0c0\ud0c0\ub974\uc5b4");
        put("ts", "\ud1b5\uac00\uc5b4");
        put("bad", "\ubc18\ub2e4\uc5b4");
        put("tr", "\ud130\ud0a4\uc5b4");
        put("to", "\ud1b5\uac00\uc5b4");
        put("tn", "\uc138\uce20\uc640\ub098\uc5b4");
        put("tl", "\ud0c0\uac08\ub85c\uadf8\uc5b4");
        put("tk", "\ud22c\ub974\ud06c\uba58\uc5b4");
        put("ti", "\ud2f0\uadf8\ub9ac\ub0d0\uc5b4");
        put("th", "\ud0dc\uad6d\uc5b4");
        put("kru", "\ucfe0\ub974\ud06c\uc5b4");
        put("tg", "\ud0c0\uc9c0\ud0a4\uc2a4\ud0c4\uc5b4");
        put("byn", "\ube0c\ub9b0\uc5b4");
        put("te", "\ud154\ub8e8\uad6c\uc5b4");
        put("kro", "\ud06c\ub8e8\uc5b4");
        put("csb", "\uce74\uc288\ube44\uc544\uc5b4");
        put("ta", "\ud0c0\ubc00\uc5b4");
        put("tkl", "\ud1a0\ucf08\ub77c\uc6b0\uc81c\ub3c4\uc5b4");
        put("efi", "\uc774\ud53d\uc5b4");
        put("sw", "\uc2a4\uc640\ud790\ub9ac\uc5b4");
        put("sv", "\uc2a4\uc6e8\ub374\uc5b4");
        put("su", "\uc21c\ub2e8\uc5b4");
        put("krc", "\uce74\ub77c\ucc60\uc774-\ubc1c\uce74\ub974\uc5b4");
        put("st", "\uc138\uc18c\ud1a0\uc5b4");
        put("ss", "\uc2dc\uc2a4\uc640\ud2f0\uc5b4");
        put("sr", "\uc138\ub974\ube44\uc544\uc5b4");
        put("sq", "\uc54c\ubc14\ub2c8\uc544\uc5b4");
        put("men", "\uba58\ub370\uc5b4");
        put("crp", "\ud06c\ub808\uc624\uc2a4\uc640 \ud53c\uae34\uc2a4\uc5b4 (\uae30\ud0c0)");
        put("so", "\uc18c\ub9d0\ub9ac\uc544\uc5b4");
        put("afh", "\uc544\ud504\ub9ac\ud788\ub9ac\uc5b4");
        put("sn", "\uc1fc\ub098\uc5b4");
        put("sm", "\uc0ac\ubaa8\uc544\uc5b4");
        put("sl", "\uc2ac\ub85c\ubca0\ub2c8\uc544\uc5b4");
        put("grc", "\uadf8\ub9ac\uc2a4\uc5b4, \uace0\ub300 (1453\ub144 \uae4c\uc9c0)");
        put("sk", "\uc2ac\ub85c\ubc14\ud0a4\uc544\uc5b4");
        put("grb", "\uac8c\ub974\ubcf4\uc5b4");
        put("si", "\uc2a4\ub9ac\ub791\uce74\uc5b4");
        put("sh", "\uc138\ub974\ubcf4\ud06c\ub85c\uc544\ud2f0\uc544\uc5b4");
        put("crh", "\ud06c\ub9ac\ubbfc \ud130\ud0a4\uc5b4; \ud06c\ub9ac\ubbfc \ud0c0\ud0c0\ub974\uc5b4");
        put("afa", "\uc544\uc2dc\uc544-\uc544\ud504\ub9ac\uce74\uc5b4 (\uae30\ud0c0)");
        put("sg", "\uc0b0\uace0\uc5b4");
        put("se", "\ubd81\ubd80 \uc0ac\ubbf8\uc5b4");
        put("sd", "\uc2e0\ub514\uc5b4");
        put("udm", "\uc6b0\ub4dc\ub9d0\ud2b8\uc5b4");
        put("sc", "\uc0ac\ub974\ub514\ub2c8\uc544\uc5b4");
        put("sa", "\uc0b0\uc2a4\ud06c\ub9ac\ud2b8\uc5b4");
        put("rw", "\ubc18\ud22c\uc5b4(\ub8e8\uc644\ub2e4)");
        put("ru", "\ub7ec\uc2dc\uc544\uc5b4");
        put("mdr", "\ub9cc\ub2e4\ub974\uc5b4");
        put("ro", "\ub8e8\ub9c8\ub2c8\uc544\uc5b4");
        put("rn", "\ubc18\ud22c\uc5b4(\ubd80\ub8ec\ub514)");
        put("rm", "\ub808\ud1a0\ub85c\ub9cc\uc5b4");
        put("mdf", "\ubaa8\ud06c\uc0e4\uc5b4");
        put("tiv", "\ud2f0\ube44\uc5b4");
        put("ady", "\uc544\ub2e5\ud5e4\uc5b4");
        put("zun", "\uc8fc\ub2c8\uc5b4");
        put("kpe", "\ucf54\ud3a0\ub808");
        put("qu", "\ucf00\ucd94\uc544\uc5b4");
        put("tig", "\ud2f0\uadf8\ub808\uc5b4");
        put("son", "\uc1a1\uac00\uc774\uc871\uc5b4");
        put("cpp", "\ud06c\ub808\uc624\ub9ac\uc2a4\uc640 \ud53c\uae34\uc2a4\uc5b4, \ud3ec\ub974\ud22c\uac08\uc5b4-\uae30\ubc18 (\uae30\ud0c0)");
        put("sog", "\uc18c\uadf8\ub514\uc5d4\uc5b4");
        put("ada", "\uc544\ub2f9\uba54\uc5b4");
        put("kos", "\ucf54\uc2a4\ub77c\uc774\uc5d4\uc5b4");
        put("hit", "\ud558\ud0c0\uc774\ud2b8\uc5b4");
        put("cpf", "\ud06c\ub808\uc624\ub9ac\uc2a4\uc640 \ud53c\uae34\uc2a4\uc5b4, \ud504\ub791\uc2a4\uc5b4-\uae30\ubc18 (\uae30\ud0c0)");
        put("cpe", "\ud06c\ub808\uc624\ub9ac\uc2a4\uc640 \ud53c\uae34\uc2a4\uc5b4, \uc601\uc5b4-\uae30\ubc18 (\uae30\ud0c0)");
        put("him", "\ud788\ub9c8\ucc28\ub9ac\uc5b4");
        put("kok", "\ucf54\uce74\ub2c8\uc5b4");
        put("hil", "\ud5e4\ub9ac\uac00\ub1ec\uc5b4");
        put("got", "\uace0\ud2b8\uc5b4");
        put("gor", "\uace0\ub860\ud0c8\ub85c\uc5b4");
        put("gon", "\uace4\ub514\uc5b4");
        put("din", "\ub529\uce74\uc5b4");
        put("nub", "\ub204\ube44\uc548\uc5b4");
        put("pt", "\ud3ec\ub974\ud22c\uce7c\uc5b4");
        put("ps", "\ud30c\uc2dc\ud1a0\uc5b4 (\ud478\uc2dc\ud1a0)");
        put("fur", "\ud504\ub9ac\uc6b0\ub9ac\uc548\uc5b4");
        put("phn", "\ud398\ub2c8\ud0a4\uc544\uc5b4");
        put("goh", "\ub3c5\uc77c\uc5b4, \uace0\ub300 \uc800\uae09 (ca.750-1050)");
        put("snk", "\uc18c\ub2cc\ucf00\uc5b4");
        put("cop", "\ucf65\ud2b8\uc5b4");
        put("yap", "\uc58d\ud398\uc138\uc5b4");
        put("ach", "\uc544\ucf5c\ub9ac\uc5b4");
        put("yao", "\uc57c\uc624\uc871\uc5b4");
        put("phi", "\ud544\ub9ac\ud540\uc5b4 (\uae30\ud0c0)");
        put("pl", "\ud3f4\ub780\ub4dc\uc5b4");
        put("ace", "\uc544\uccb4\uc5b4");
        put("pi", "\ud314\ub9ac\uc5b4");
        put("pa", "\ud380\uc7a1\uc5b4");
        put("bug", "\ubd80\uae30\uc5b4");
        put("iba", "\uc774\ubc18\uc5b4");
        put("sms", "\uc2a4\ucf5c\ud2b8 \uc0ac\ubbf8\uc5b4");
        put("bua", "\ubd80\ub9ac\uc544\ud0c0");
        put("mas", "\ub9c8\uc0ac\uc774\uc5b4");
        put("smn", "\uc774\ub098\ub9ac \uc0ac\ubbf8\uc5b4");
        put("os", "\uc624\uc138\ud2b8\uc5b4");
        put("map", "\ub0a8\ub3c4\uc5b4");
        put("or", "\uc624\ub9ac\uc57c\uc5b4");
        put("man", "\ub9cc\ub529\uace0\uc5b4");
        put("smj", "\ub8f0\ub808 \uc0ac\ubbf8\uc5b4");
        put("smi", "\uc0ac\ubbf8\uc5b4 (\uae30\ud0c0)");
        put("mak", "\ub9c8\uce74\uc0ac\uc5b4");
        put("om", "\uc624\ub85c\ubaa8\uc5b4 (\uc544\ud310)");
        put("mai", "\ub9c8\uc774\ud2f8\ub9ac");
        put("oj", "\uc624\uc9c0\ube0c\uc6e8\uc774\uc5b4");
        put("mag", "\ub9c8\uac00\ud788");
        put("mad", "\ub9c8\ub450\ub808\uc138");
        put("sma", "\ub0a8\ubd80 \uc0ac\ubbf8\uc5b4");
        put("oc", "\uc625\uc2dc\ud2b8\uc5b4");
        put("nso", "\uc18c\ud1a0\uc5b4, \ubd81\ubd80");
        put("btk", "\ubc14\ud0c0\ud06c\uc5b4");
        put("myv", "\uc5d8\uc988\uc57c\uc5b4");
        put("dgr", "\ub3c4\uadf8\ub9ac\ube0c\uc5b4");
        put("ny", "\ub2c8\uc548\uc790\uc5b4; \uce58\uce04\uc5b4; \uce04\uc5b4");
        put("myn", "\ub9c8\uc57c\uc5b4");
        put("nv", "\ub098\ubc14\ud638\uc5b4");
        put("kmb", "\ud0b4\ubd84\ub204\uc5b4");
        put("nr", "\uc740\ub370\ubca8\ub808\uc5b4, \ub0a8\ubd80");
        put("gmh", "\ub3c5\uc77c\uc5b4, \uc911\uc138 \uace0\uae09 (ca.1050-1500)");
        put("no", "\ub178\ub974\uc6e8\uc774\uc5b4");
        put("nn", "\ub258\ub178\ub974\uc2a4\ud06c \ub178\ub974\uc6e8\uc774\uc5b4");
        put("nl", "\ub124\ub35c\ub780\ub4dc\uc5b4");
        put("ng", "\ub290\ub3d9\uac00\uc5b4");
        put("sla", "\uc2ac\ub77c\ube0c\uc5b4 (\uae30\ud0c0)");
        put("ne", "\ub124\ud314\uc5b4");
        put("nd", "\uc740\ub370\ubca8\ub808\uc5b4, \ubd81\ubd80");
        put("cmc", "\uce74\ubbf9\uc5b4");
        put("tet", "\ud14c\ud23c\uc5b4");
        put("nb", "\ubcf4\ud06c\ub9d0 \ub178\ub974\uc6e8\uc774\uc5b4");
        put("na", "\ub098\uc6b0\ub8e8\uc5b4");
        put("ter", "\ud14c\ub808\ub178\uc5b4");
        put("tem", "\ud300\ub2c8\uc5b4");
        put("my", "\ubc84\ub9c8\uc5b4");
        put("lez", "\ub808\uc988\uae30\uc548\uc5b4");
        put("mt", "\ubab0\ud0c0\uc5b4");
        put("peo", "\ud398\ub974\uc2dc\uc548 \uace0\ub300\uc5b4 (ca.600-400 B.C.)");
        put("ms", "\ub9d0\ub808\uc774\uc5b4");
        put("mr", "\ub9c8\ub77c\ud2f0\uc5b4");
        put("fro", "\ud504\ub791\uc2a4\uc5b4, \uace0\ub300 (842-ca.1400)");
        put("mo", "\ubab0\ub2e4\ube44\uc544\uc5b4");
        put("frm", "\ud504\ub791\uc2a4\uc5b4, \uc911\uc138 (ca.1400-1600)");
        put("mn", "\ubabd\uace8\uc5b4");
        put("jrb", "\uc720\ub300-\uc544\ub77c\ube44\uc544\uc5b4");
        put("ml", "\ub9d0\ub77c\uc584\ub78c\uc5b4");
        put("mk", "\ub9c8\ucf00\ub3c4\ub2c8\uc544\uc5b4");
        put("mi", "\ub9c8\uc624\ub9ac\uc5b4");
        put("mh", "\ub9c8\uc15c\uc81c\ub3c4\uc5b4");
        put("mg", "\ub9c8\ub2e4\uac00\uc2a4\uce74\ub974\uc5b4");
        put("mwr", "\ub9c8\ub974\uc640\ub9ac\uc5b4");
        put("bra", "\ube0c\ub77c\uc5b4");
        put("den", "\uc2ac\ub77c\ube0c\uc5b4");
        put("lv", "\ub77c\ud2b8\ube44\uc544\uc5b4");
        put("lu", "\ub8e8\ubc14-\uce74\ud0c4\uac00\uc5b4");
        put("del", "\ub378\ub77c\uc6e8\uc5b4\uc5b4");
        put("lt", "\ub9ac\ud22c\uc544\ub2c8\uc544\uc5b4");
        put("lo", "\ub77c\uc624\uc5b4");
        put("ln", "\ub9c1\uac08\ub77c\uc5b4");
        put("li", "\ub9bc\ubc84\uac70\uc5b4");
        put("ewo", "\uc774\uc6d0\ub3c4\uc5b4");
        put("lg", "\uac04\ub2e4\uc5b4");
        put("lb", "\ub8e9\uc148\ubd80\ub974\ud06c\uc5b4");
        put("la", "\ub77c\ud2f4\uc5b4");
        put("jpr", "\uc720\ub300-\ud398\ub974\uc2dc\uc544\uc5b4");
        put("vot", "\ubcf4\ud2f1\uc5b4");
        put("sit", "\uc778\ub3c4\uc81c\uc5b8\uc5b4 (\uae30\ud0c0)");
        put("ky", "\ud0a4\ub974\uae30\uc2a4\uc5b4");
        put("kw", "\ucf58\uc6d4\uc5b4");
        put("kv", "\ucf54\ubbf8\uc5b4");
        put("ku", "\ud06c\ub974\ub4dc\uc5b4");
        put("sio", "\uc218\uc871\uc5b4");
        put("ks", "\uce74\uc288\ubbf8\ub974\uc5b4");
        put("kr", "\uce78\ub204\ub9ac\uc5b4");
        put("awa", "\uc544\uc640\ud788\uc5b4");
        put("ko", "\ud55c\uad6d\uc5b4");
        put("kn", "\uce74\ub098\ub2e4\uc5b4");
        put("km", "\uce84\ubcf4\ub514\uc544\uc5b4");
        put("kl", "\uadf8\ub9b0\ub79c\ub4dc\uc5b4");
        put("kk", "\uce74\uc790\ud750\uc5b4");
        put("rom", "\uc9d1\uc2dc\uc5b4");
        put("kj", "\ucfe0\uc548\uc57c\ub9c8\uc5b4");
        put("sid", "\uc2dc\ub2e4\ubaa8\uc5b4");
        put("ki", "\ud0a4\ucfe0\uc720\uc5b4");
        put("kg", "\ucf69\uace0\uc5b4");
        put("non", "\ub178\ub974\uc6e8\uc774, \uace0\ub300");
        put("ka", "\uadf8\ub8e8\uc9c0\uc57c\uc5b4");
        put("mus", "\ud06c\ub9ac\ud06c\uc5b4");
        put("roa", "\ub85c\ub9dd\uc2a4\uc5b4 (\uae30\ud0c0)");
        put("nog", "\ub178\uac00\uc774\uc5b4");
        put("mun", "\ubb38\ub2e4\uc5b4");
        put("mul", "\ub2e4\uc911 \uc5b8\uc5b4");
        put("jv", "\uc790\ubc14\uc5b4");
        put("gil", "\ud0a4\ub9ac\ubc14\uc2dc\uc5b4");
        put("znd", "\uc544\uc794\ub370\uc871\uc5b4");
        put("shn", "\uc0e8\uc5b4");
        put("fon", "\ud3f0\uc5b4");
        put("xal", "\uce7c\ubbf8\ud06c\uc5b4");
        put("aus", "\uc624\uc2a4\ud2b8\ub808\uc77c\ub9ac\uc544\uc5b4");
        put("kho", "\ucf54\ud0c4\uc2a4\uc5b4");
        put("ja", "\uc77c\ubcf8\uc5b4");
        put("khi", "\ucf54\uc774\uc0b0\uc5b4 (\uae30\ud0c0)");
        put("pau", "\ud30c\ub77c\uc6b0\uc548\uc5b4");
        put("chy", "\uc0e4\uc774\uc5d4\uc5b4");
        put("tai", "\ud0dc\uad6d\uc5b4 (\uae30\ud0c0)");
        put("iu", "\uc774\ub205\ud2f0\ud22c\ud2b8\uc5b4");
        put("pap", "\ud30c\ud53c\uc544\uba3c\ud1a0\uc5b4");
        put("it", "\uc774\ud0c8\ub9ac\uc544\uc5b4");
        put("sgn", "\uc218\ud654");
        put("is", "\uc544\uc774\uc2ac\ub780\ub4dc\uc5b4");
        put("kha", "\uce74\uc2dc\uc5b4");
        put("chr", "\uccb4\ub85c\ud0a4\uc5b4");
        put("pam", "\ud31c\ud321\uac00\uc5b4");
        put("pal", "\ud314\ube4c\ub808\uc5b4");
        put("chp", "\uce58\ud398\uc6b0\uc580");
        put("io", "\uc774\ub3c4\uc5b4");
        put("cho", "\ucd09\ud1a0\uc5b4");
        put("chn", "\uce58\ub204\ud06c\uc5b4\uc640 \uc601\uc5b4 \ud504\ub791\uc2a4\uc5b4\uc758 \ud63c\uc131\uc5b4");
        put("chm", "\ub9c8\ub9ac\uc5b4");
        put("tyv", "\ud22c\ube44\ub2c8\uc548\uc5b4");
        put("bnt", "\ubc18\ud22c\uc5b4");
        put("pag", "\ud310\uac00\uc2dc\ub09c\uc5b4");
        put("ik", "\uc774\ub204\ud53c\uc544\ud06c\uc5b4");
        put("chk", "\uce04\ucf00\uc2a4\uc5b4");
        put("ii", "\uc2dc\uce04\uc548 \uc774\uc5b4");
        put("haw", "\ud558\uc640\uc774\uc5b4");
        put("lam", "\ub78c\ubc14\uc5b4");
        put("ig", "\uc774\uadf8\ubcf4\uc5b4");
        put("chg", "\ucc28\uac00\ud0c0\uc774\uc5b4");
        put("sga", "\uc544\uc77c\ub79c\ub4dc, \uace0\ub300 (900\ub144 \uae4c\uc9c0)");
        put("paa", "\ud30c\ud478\uc544\uc5b4 (\uae30\ud0c0)");
        put("ie", "\uc778\ud130\ub9c1\uac8c\uc5b4");
        put("id", "\uc778\ub3c4\ub124\uc2dc\uc544\uc5b4");
        put("lah", "\ub77c\ud55c\ub2e4\uc5b4");
        put("day", "\ub2e4\uc57c\ud06c\uc5b4");
        put("chb", "\uce58\ube0c\ucc28\uc5b4");
        put("ia", "\uc778\ud130\ub9c1\uac70");
        put("lad", "\ub77c\ub514\ub178\uc5b4");
        put("hai", "\ud558\uc774\ub2e4\uc5b4");
        put("dar", "\ub2e4\ub974\uadf8\uc640\uc5b4");
        put("hy", "\uc544\ub974\uba54\ub2c8\uc544\uc5b4");
        put("ath", "\uc544\ud0c0\ubc14\uc2a4\uce74\uc5b4");
        put("hu", "\ud5dd\uac00\ub9ac\uc5b4");
        put("ht", "\uc544\uc774\ud2f0\uc5b4");
        put("dak", "\ub2e4\ucf54\ud0c0\uc5b4");
        put("hr", "\ud06c\ub85c\uc544\ud2f0\uc544\uc5b4");
        put("ho", "\ud788\ub9ac \ubaa8\ud22c\uc5b4");
        put("hi", "\ud78c\ub514\uc5b4");
        put("dyu", "\ub4dc\uc728\ub77c\uc5b4");
        put("he", "\ud788\ube0c\ub9ac\uc5b4");
        put("ast", "\uc544\uc2a4\ud22c\ub9ac\uc544\uc5b4");
        put("ha", "\ud558\uc6b0\uc790\uc5b4");
        put("wen", "\uc18c\ub974\ube0c\uc5b4");
        put("gv", "\ub9f9\ud06c\uc2a4\uc5b4");
        put("gu", "\uad6c\uc790\ub77c\ud2b8\uc5b4");
        put("sem", "\uc148\uc5b4 (\uae30\ud0c0)");
        put("sel", "\uc140\ucfe0\ud504\uc5b4");
        put("iro", "\uc774\ub7ec\ucffc\uc774\uc5b4");
        put("gn", "\uad6c\uc544\ub77c\ub2c8\uc5b4");
        put("gl", "\uac08\ub9ac\uc2dc\uc544\uc5b4");
        put("arw", "\uc544\ub77c\uc640\ud06c\uc5b4");
        put("gez", "\uac8c\uc774\uc988\uc5b4");
        put("art", "\uae30\uacc4\uc5b4 (\uae30\ud0c0)");
        put("gd", "\uc2a4\ucf54\uac24\ub9ad\uc5b4");
        put("ira", "\uc774\ub780\uc5b4");
        put("ga", "\uc544\uc77c\ub79c\ub4dc\uc5b4");
        put("arp", "\uc544\ub77c\ud30c\ud638\uc5b4");
        put("arn", "\uc544\ub77c\uc6b0\uce78\uc5b4");
        put("fy", "\ud504\ub9ac\uc9c0\uc544\uc5b4");
        put("bla", "\uc2dd\uc2dc\uce74\uc5b4");
        put("gem", "\ub3c5\uc77c\uc5b4 (\uae30\ud0c0)");
        put("ypk", "\uc57c\ud53d\uc5b4");
        put("arc", "\uc544\ub78c\uc5b4");
        put("fr", "\ud504\ub791\uc2a4\uc5b4");
        put("fo", "\ud398\ub85c\uc2a4\uc5b4");
        put("cel", "\ucf08\ud2b8\uc5b4 (\uae30\ud0c0)");
        put("fj", "\ud53c\uc9c0\uc5b4");
        put("fi", "\ud540\ub780\ub4dc\uc5b4");
        put("ff", "\ud480\ub77c\uc5b4");
        put("tvl", "\ud22c\ubc1c\ub8e8\uc5b4");
        put("ceb", "\uc138\ubd80\uc544\ub178\uc5b4");
        put("fa", "\uc774\ub780\uc5b4");
        put("eu", "\ubc14\uc2a4\ud06c\uc5b4");
        put("sco", "\uc2a4\ucf54\ud2c0\ub79c\ub4dc\uc5b4");
        put("et", "\uc5d0\uc2a4\ud1a0\ub2c8\uc544\uc5b4");
        put("es", "\uc2a4\ud398\uc778\uc5b4");
        put("eo", "\uc5d0\uc2a4\ud398\ub780\ud1a0\uc5b4");
        put("en", "\uc601\uc5b4");
        put("el", "\uadf8\ub9ac\uc2a4\uc5b4");
        put("tut", "\uc54c\ud0c0\uc774\uc5b4 (\uae30\ud0c0)");
        put("niu", "\ub2c8\uc6e8\uc5b8\uc5b4");
        put("tup", "\ud22c\ud53c\uc5b4");
        put("ee", "\uc5d0\uc6e8\uc5b4");
        put("tum", "\ud23c\ubd80\uce74\uc5b4");
        put("mos", "\ubaa8\uc2dc\uc5b4");
        put("dz", "\ubd80\ud0c4\uc5b4");
        put("nic", "\ub2c8\uc81c\ub974 - \ucf54\ub974\ub3c4\ud30c\ub2c8\uc544\uc5b4 (\uae30\ud0c0)");
        put("lus", "\ub8e8\uc0e4\uc774\uc5b4");
        put("fiu", "\ud53c\ub178\uc6b0\uadf8\ub9ac\uc544\uc5b4 (\uae30\ud0c0)");
        put("dv", "\ub514\ubca0\ud788\uc5b4");
        put("nia", "\ub2c8\uc544\uc2a4\uc5b4");
        put("moh", "\ubaa8\ud638\ud06c\uc5b4");
        put("luo", "\ub8e8\uc624\uc5b4");
        put("lun", "\ub8ec\ub2e4\uc5b4");
        put("apa", "\uc544\ud30c\uce58\uc5b4");
        put("lui", "\ub8e8\uc774\uc138\ub178\uc5b4");
        put("hup", "\ud6c4\ud30c\uc5b4");
        put("bin", "\ube44\ub2c8\uc5b4");
        put("de", "\ub3c5\uc77c\uc5b4");
        put("lua", "\ub8e8\ubc14-\ub8f0\ub8e8\uc544\uc5b4");
        put("bik", "\ube44\ucf5c\uc5b4");
        put("was", "\uc640\uc1fc\uc5b4");
        put("und", "\uacb0\uc815\ub418\uc9c0\uc54a\uc74c");
        put("war", "\uc640\ub77c\uc774\uc5b4");
        put("da", "\ub374\ub9c8\ud06c\uc5b4");
        put("dum", "\ub124\ub35c\ub780\ub4dc, \uc911\uc138 (ca. 1050-1350)");
        put("wal", "\uc640\ub77c\ubaa8\uc5b4");
        put("mno", "\ub9c8\ub178\ubcf4\uc5b4");
        put("wak", "\uc640\uce74\uc0e8\uc5b4");
        put("sat", "\uc0b0\ud0c8\ub9ac\uc5b4");
        put("cy", "\uc6e8\uc77c\uc2a4\uc5b4");
        put("sas", "\uc0ac\uc0ac\ud06c\uc5b4");
        put("kbd", "\uce74\ubc14\ub974\ub514\uc5b4");
        put("cv", "\ucd94\ubc14\uc2dc\uc5b4");
        put("cu", "\uad50\ud68c\uc2ac\ub77c\ube0c\uc5b4");
        put("mni", "\ub9c8\ub2c8\ud478\ub9ac\uc5b4");
        put("cs", "\uccb4\ucf54\uc5b4");
        put("sam", "\uc0ac\ub9c8\ub9ac\uc544 \uc544\ub78d\uc5b4");
        put("cr", "\ud06c\ub9ac\uc5b4");
        put("sal", "\uc0d0\ub9ac\uc2dc\uc5b4\uc5b4");
        put("dua", "\ub4dc\uc640\ub77c\uc5b4");
        put("co", "\ucf54\ub974\uc2dc\uce74\uc5b4");
        put("sai", "\ub0a8\uc544\uba54\ub9ac\uce74 \uc778\ub514\uc5b8\uc5b4 (\uae30\ud0c0)");
        put("mnc", "\ub9cc\uc8fc\uc5b4");
        put("sah", "\uc57c\ud050\ud2b8\uc5b4");
        put("kaw", "\uce74\uc704\uc5b4");
        put("inh", "\uc778\uadc0\uc2dc\uc5b4");
        put("gba", "\uadf8\ubc14\uc57c\uc5b4");
        put("sad", "\uc0b0\ub2e4\uc6e8\uc5b4");
        put("ch", "\ucc28\ubaa8\ub85c\uc5b4");
        put("ine", "\uc778\ub3c4\uc720\ub7fd\uc5b4 (\uae30\ud0c0)");
        put("bho", "\ud638\uc988\ud478\ub9ac\uc5b4");
        put("enm", "\uc601\uc5b4, \uc911\uc138 (1100-1500)");
        put("kar", "\uce74\ub80c\uc5b4");
        put("inc", "\uc778\ub3c4\uc5b4 (\uae30\ud0c0)");
        put("gay", "\uac00\uc694\uc5b4");
        put("ca", "\uce74\ud0c8\ub85c\ub2c8\uc544\uc5b4");
        put("umb", "\uc724\ubc88\ub450\uc5b4");
        put("syr", "\uc2dc\ub9ac\uc544\uc5b4");
        put("kam", "\uce84\ubc14\uc5b4");
        put("tsi", "\ud2b8\uc2ec\uc2dc\uc548\uc5b4");
        put("ang", "\uc774\uc804 \uc601\uc5b4 (ca.450-1100)");
        put("kac", "\uce74\uce5c\uc5b4");
        put("cau", "\uce74\ud504\uce74\uc2a4\uc5b4 (\uae30\ud0c0)");
        put("kab", "\ucee4\ubc14\uc77c\uc5b4");
        put("kaa", "\uce74\ub77c\uce7c\ud30c\ud06c\uc5b4");
        put("bs", "\ubcf4\uc2a4\ub2c8\uc544\uc5b4");
        put("car", "\uce74\ub9ac\ube0c\uc5b4");
        put("br", "\ube0c\ub974\ud0c0\ub274\uc5b4");
        put("bo", "\ud2f0\ubca0\ud2b8\uc5b4");
        put("bn", "\ubcb5\uace8\uc5b4");
        put("bm", "\ubc24\ubc14\ub77c\uc5b4");
        put("gaa", "\uac00\uc5b4");
        put("cai", "\uc911\uc559 \uc544\uba54\ub9ac\uce74 \uc778\ub514\uc548\uc5b4 (\uae30\ud0c0)");
        put("bi", "\ube44\uc2ac\ub77c\ub9c8\uc5b4");
        put("bh", "\ube44\ud558\ub974\uc5b4");
        put("bg", "\ubd88\uac00\ub9ac\uc544\uc5b4");
        put("be", "\ubca8\ub85c\ub8e8\uc2dc\uc5b4");
        put("cad", "\uce74\ub3c4\uc5b4");
        put("ba", "\ubc14\uc288\ud0a4\ub974\uc5b4");
        put("zu", "\uc904\ub8e8\uc5b4");
        put("zen", "\uc81c\ub098\uac00\uc5b4");
        put("pro", "\ud504\ub85c\ubca4\uce7c\uc5b4, \uace0\ub300 (1500\ub144 \uae4c\uc9c0)");
        put("hsb", "\uc704 \uc18c\ub974\ube44\uc548\uc5b4");
        put("az", "\uc544\uc81c\ub974\ubc14\uc774\uc794\uc5b4");
        put("ay", "\uc544\uc774\ub9c8\ub77c\uc5b4");
        put("av", "\uc544\ubc14\ub9ad\uc5b4");
        put("as", "\uc544\uc0d8\uc5b4");
        put("dsb", "\uc800\uae09 \uc18c\ub974\ube44\uc548\uc5b4");
        put("ar", "\uc544\ub78d\uc5b4");
        put("ilo", "\uc774\ub85c\ucf54\uc5b4");
        put("elx", "\uc5d8\ub78c\uc5b4");
        put("zh", "\uc911\uad6d\uc5b4");
        put("an", "\uc544\ub77c\uace4\uc5b4");
        put("pra", "\ud504\ub77c\ud06c\ub9ac\ud2b8\uc5b4");
        put("am", "\uc554\ud558\ub77c\uc5b4");
        put("new", "\ub124\uc640\ub9ac\uc5b4");
        put("ak", "\uc544\uce78\uc5b4");
        put("za", "\uc8fc\uc559\uc5b4");
        put("af", "\ub0a8\uc544\uacf5 \uacf5\uc6a9\uc5b4");
        put("ab", "\uc555\uce74\uc988\uc5b4");
        put("aa", "\uc544\ud30c\ub974\uc5b4");
        put("yo", "\uc694\ub8e8\ubc14\uc5b4");
        put("alg", "\uc54c\ucf58\ud0a8\uc5b4");
        put("ale", "\uc54c\ub958\ud2b8\uc5b4");
        put("mkh", "\ubaac\ud06c\uba54\ub974\uc5b4 (\uae30\ud0c0)");
        put("yi", "\uc774\ub514\uc2dc\uc5b4");
        put("dra", "\ub4dc\ub77c\ube44\ub2e4\uc5b4 (\uae30\ud0c0)");
        put("ber", "\ubca0\ub974\ubca0\ub974\uc5b4");
        put("nds", "\uc800\uae09 \ub3c5\uc77c\uc5b4; \uc800\uae09 \uc0c9\uc2a8\uc5b4");
        put("bem", "\ubcb0\ubc14\uc5b4");
        put("bej", "\ubca0\uc790\uc5b4");
        put("tpi", "\ud1a0\ud06c \ud53c\uc2e0\uc5b4");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final class Hashtablevariants extends java.util.Hashtable
  {
    public Hashtablevariants()
      {
        super();
        put("REVISED", "\uac1c\uc815");
      }
  }

  private static final Object variants = new Hashtablevariants();

  private static final Object[][] contents =
  {
    { "localPatternChars", "GanjkHmsSEDFwWxhKzAeugXZ" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "ampms", ampms },
    { "shortDateFormat", "yy-MM-dd" },
    { "mediumDateFormat", "yyyy-MM-dd" },
    { "longDateFormat", "yyyy'\ub144' M'\uc6d4' d'\uc77c' EE" },
    { "fullDateFormat", "yyyy'\ub144' M'\uc6d4' d'\uc77c' EEEE" },
    { "shortTimeFormat", "a hh'\uc2dc' mm'\ubd84'" },
    { "mediumTimeFormat", "a hh'\uc2dc' mm'\ubd84'" },
    { "longTimeFormat", "a hh'\uc2dc' mm'\ubd84' ss'\ucd08'" },
    { "fullTimeFormat", "a hh'\uc2dc' mm'\ubd84' ss'\ucd08' z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
    { "variants", variants },
  };

  public Object[][] getContents() { return contents; }
}
