/* LocaleInformation_cs.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_cs extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "1.",
    "2.",
    "3.",
    "4.",
    "5.",
    "6.",
    "7.",
    "8.",
    "9.",
    "10.",
    "11.",
    "12.",
    null,
  };

  private static final String[] months = {
    "Leden",
    "\u00danor",
    "B\u0159ezen",
    "Duben",
    "Kv\u011bten",
    "\u010cerven",
    "\u010cervenec",
    "Srpen",
    "Z\u00e1\u0159\u00ed",
    "\u0158\u00edjen",
    "Listopad",
    "Prosinec",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "ne",
    "po",
    "\u00fat",
    "st",
    "\u010dt",
    "p\u00e1",
    "so",
  };

  private static final String[] weekdays = {
    null,
    "ned\u011ble",
    "pond\u011bl\u00ed",
    "\u00fater\u00fd",
    "st\u0159eda",
    "\u010dtvrtek",
    "p\u00e1tek",
    "sobota",
  };

  private static final String[] eras = {
    "p\u0159.Kr.",
    "po Kr.",
  };

  private static final String[] ampms = {
    "dop.",
    "odp.",
  };

  private static final String[][] zoneStrings =
  {
    { "PST", "Pacifick\u00fd standardn\u00ed \u010das", "PDT", "Pacifick\u00fd letn\u00ed \u010das",  "America/Los_Angeles" },
    { "GMT", "Greenwichsk\u00fd st\u0159edn\u00ed \u010das", "GMT", "Greenwichsk\u00fd st\u0159edn\u00ed \u010das",  "Africa/Casablanca" },
    { "EST", "V\u00fdchodn\u00ed standardn\u00ed \u010das", "EDT", "V\u00fdchodn\u00ed letn\u00ed \u010das",  "America/New_York" },
    { "AST", "Alja\u0161sk\u00fd standardn\u00ed \u010das", "ADT", "Alja\u0161sk\u00fd letn\u00ed \u010das",  "America/Anchorage" },
    { "GMT", "Greenwichsk\u00fd st\u0159edn\u00ed \u010das", "GMT", "Greenwichsk\u00fd st\u0159edn\u00ed \u010das",  "Etc/GMT" },
    { "CTT", "\u010c\u00ednsk\u00fd standardn\u00ed \u010das", "CDT", "\u010c\u00ednsk\u00fd standardn\u00ed \u010das",  "Asia/Shanghai" },
    { "AST", "Atlantick\u00fd standardn\u00ed \u010das", "ADT", "Atlantick\u00fd letn\u00ed \u010das",  "America/Halifax" },
    { "CET", "St\u0159edoevropsk\u00fd standardn\u00ed \u010das", "CEST", "St\u0159edoevropsk\u00fd letn\u00ed \u010das",  "Europe/Paris" },
    { "MST", "Horsk\u00fd standardn\u00ed \u010das", "MDT", "Horsk\u00fd letn\u00ed \u010das",  "America/Denver" },
    { "IST", "Izraelsk\u00fd standardn\u00ed \u010das", "IDT", "Izraelsk\u00fd letn\u00ed \u010das",  "Asia/Jerusalem" },
    { "HST", "Havajsk\u00fd standardn\u00ed \u010das", "HST", "Havajsk\u00fd standardn\u00ed \u010das",  "Pacific/Honolulu" },
    { "CNT", "Newfoundlandsk\u00fd standardn\u00ed \u010das", "CDT", "Newfoundlandsk\u00fd letn\u00ed \u010das",  "America/St_Johns" },
    { "EST", "V\u00fdchodn\u00ed standardn\u00ed \u010das", "EST", "V\u00fdchodn\u00ed standardn\u00ed \u010das",  "America/Indianapolis" },
    { "CST", "Centr\u00e1ln\u00ed standardn\u00ed \u010das", "CDT", "Centr\u00e1ln\u00ed letn\u00ed \u010das",  "America/Chicago" },
    { "EET", "V\u00fdchodoevropsk\u00fd standardn\u00ed \u010das", "EEST", "V\u00fdchodoevropsk\u00fd letn\u00ed \u010das",  "Europe/Bucharest" },
    { "JST", "Japonsk\u00fd standardn\u00ed \u010das", "JST", "Japonsk\u00fd standardn\u00ed \u010das",  "Asia/Tokyo" },
    { "MST", "Horsk\u00fd standardn\u00ed \u010das", "MST", "Horsk\u00fd standardn\u00ed \u010das",  "America/Phoenix" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "V\u00fdchodn\u00ed Timor");
        put("TK", "Tokelau");
        put("TJ", "T\u00e1d\u017eikist\u00e1n");
        put("TH", "Thajsko");
        put("TG", "Togo");
        put("TF", "Francouzsk\u00e1 ji\u017en\u00ed teritoria");
        put("GY", "Guyana");
        put("TD", "\u010cad");
        put("TC", "Ostrovy Caicos a Turks");
        put("GW", "Guinea-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "Ji\u017en\u00ed Georgie a Ji\u017en\u00ed Sandwichovy ostrovy");
        put("GR", "\u0158ecko");
        put("GQ", "Rovn\u00edkov\u00e1 Guinea");
        put("GP", "Guadeloupe");
        put("SZ", "Svazijsko");
        put("SY", "S\u00fdrie");
        put("GN", "Guinea");
        put("GM", "Gambie");
        put("GL", "Gr\u00f3nsko");
        put("SV", "El Salvador");
        put("ST", "Svat\u00fd Tom\u00e1\u0161");
        put("GI", "Gibraltar");
        put("GH", "Ghana");
        put("SR", "Surinam");
        put("GF", "Francouzsk\u00e1 Guyana");
        put("SP", "Serbia");
        put("GE", "Gruzie");
        put("SO", "Som\u00e1lsko");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Velk\u00e1 Brit\u00e1nie");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Slovensko");
        put("SJ", "Svalbard a Jan Mayen");
        put("SI", "Slovinsko");
        put("SH", "Svat\u00e1 Helena");
        put("SG", "Singapur");
        put("SE", "\u0160v\u00e9dsko");
        put("SD", "S\u00fad\u00e1n");
        put("SC", "Seychely");
        put("SB", "\u0160alamounovy ostrovy");
        put("SA", "Sa\u00fadsk\u00e1 Ar\u00e1bie");
        put("FR", "Francie");
        put("FO", "Faersk\u00e9 ostrovy");
        put("FM", "Mikron\u00e9sie, federativn\u00ed st\u00e1t");
        put("RW", "Rwanda");
        put("FK", "Falklandsk\u00e9 ostrovy");
        put("RU", "Rusko");
        put("FJ", "Fid\u017ei");
        put("FI", "Finsko");
        put("RO", "Rumunsko");
        put("RE", "R\u00e9union");
        put("ET", "Etiopie");
        put("ES", "\u0160pan\u011blsko");
        put("ER", "Eritrea");
        put("EH", "Z\u00e1padn\u00ed Sahara");
        put("EG", "Egypt");
        put("EE", "Estonsko");
        put("EC", "Ekv\u00e1dor");
        put("DZ", "Al\u017e\u00edrsko");
        put("QA", "Katar");
        put("DO", "Dominik\u00e1nsk\u00e1 republika");
        put("PY", "Paraguay");
        put("DM", "Dominika");
        put("PW", "Palau");
        put("DK", "D\u00e1nsko");
        put("DJ", "D\u017eibuti");
        put("PT", "Portugalsko");
        put("PS", "Palestinian Territory");
        put("PR", "Portoriko");
        put("DE", "N\u011bmecko");
        put("PN", "Pitcairn");
        put("PM", "Svat\u00fd Pierre a Miquelon");
        put("PL", "Polsko");
        put("PK", "P\u00e1kist\u00e1n");
        put("PH", "Filip\u00edny");
        put("PG", "Papua-Nov\u00e1 Guinea");
        put("PF", "Francouzsk\u00e1 Polyn\u00e9sie");
        put("CZ", "\u010cesk\u00e1 republika");
        put("PE", "Peru");
        put("CY", "Kypr");
        put("CX", "V\u00e1no\u010dn\u00ed ostrovy");
        put("CV", "Kapverdy");
        put("PA", "Panama");
        put("CU", "Kuba");
        put("CR", "Kostarika");
        put("CO", "Kolumbie");
        put("CN", "\u010c\u00edna");
        put("CM", "Kamerun");
        put("CL", "Chile");
        put("CK", "Cookovy ostrovy");
        put("CI", "Pob\u0159e\u017e\u00ed slonoviny");
        put("CH", "\u0160v\u00fdcarsko");
        put("CG", "Kongo");
        put("CF", "St\u0159edoafrick\u00e1 republika");
        put("CD", "Kongo, demokratick\u00e1 republika");
        put("CC", "Kokosov\u00e9 ostrovy");
        put("OM", "Om\u00e1n");
        put("CA", "Kanada");
        put("BZ", "Belize");
        put("BY", "B\u011blorusko");
        put("BW", "Botswana");
        put("BV", "Ostrov Bouvet");
        put("BT", "Bh\u00fat\u00e1n");
        put("BS", "Bahamy");
        put("BR", "Braz\u00edlie");
        put("NZ", "Nov\u00fd Z\u00e9land");
        put("BO", "Bol\u00edvie");
        put("BN", "Brunej Darussalam");
        put("BM", "Bermudy");
        put("NU", "Niue");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrajn");
        put("NR", "Nauru");
        put("BG", "Bulharsko");
        put("BF", "Burkina Faso");
        put("NP", "Nep\u00e1l");
        put("BE", "Belgie");
        put("NO", "Norsko");
        put("BD", "Banglad\u00e9\u0161");
        put("BB", "Barbados");
        put("ZW", "Zimbabwe");
        put("NL", "Nizozemsko");
        put("BA", "Bosna a Hercegovina");
        put("NI", "Nikaragua");
        put("NG", "Nig\u00e9rie");
        put("NF", "Norfolk");
        put("AZ", "\u00c1zerb\u00e1jd\u017e\u00e1n");
        put("NE", "Niger");
        put("NC", "Nov\u00e1 Kaledonie");
        put("AW", "Aruba");
        put("ZM", "Zambie");
        put("NA", "Namibie");
        put("AU", "Austr\u00e1lie");
        put("AT", "Rakousko");
        put("AS", "Americk\u00e1 Samoa");
        put("AR", "Argentina");
        put("AQ", "Antarktida");
        put("MZ", "Mosambik");
        put("AO", "Angola");
        put("MY", "Malajsie");
        put("AN", "Nizozemsk\u00e9 Antily");
        put("MX", "Mexiko");
        put("AM", "Arm\u00e9nie");
        put("MW", "Malawi");
        put("AL", "Alb\u00e1nie");
        put("MV", "Maladivy");
        put("ZA", "Ji\u017en\u00ed Afrika");
        put("MU", "Mauricius");
        put("MT", "Malta");
        put("AI", "Anguila");
        put("MS", "Montserrat");
        put("MR", "Maurit\u00e1nie");
        put("AG", "Antigua a Barbuda");
        put("MQ", "Martinik");
        put("AF", "Afgh\u00e1nist\u00e1n");
        put("MP", "Severn\u00ed Mariany");
        put("AE", "Spojen\u00e9 arabsk\u00e9 emir\u00e1ty");
        put("MO", "Macao S.A.R., China");
        put("AD", "Andorra");
        put("MN", "Mongolsko");
        put("MM", "Myanmar (Burma)");
        put("ML", "Mali");
        put("MK", "Macedonia");
        put("YU", "Jugosl\u00e1vie");
        put("YT", "Mayotte");
        put("MH", "Marshallovy ostrovy");
        put("MG", "Madagaskar");
        put("MD", "Moldavsko, republika");
        put("MC", "Monako");
        put("MA", "Maroko");
        put("YE", "Jemen");
        put("LY", "Libye");
        put("LV", "Loty\u0161sko");
        put("LU", "Lucembursko");
        put("LT", "Litva");
        put("LS", "Lesotho");
        put("LR", "Lib\u00e9rie");
        put("LK", "Sr\u00ed Lanka");
        put("LI", "Lichten\u0161tejnsko");
        put("LC", "Svat\u00e1 Lucie");
        put("LB", "Libanon");
        put("LA", "Lidov\u011b demokratick\u00e1 republika Laos");
        put("KZ", "Kazachst\u00e1n");
        put("KY", "Kajmansk\u00e9 ostrovy");
        put("KW", "Kuvajt");
        put("KR", "Ji\u017en\u00ed Korea");
        put("KP", "Severn\u00ed Korea");
        put("KN", "Svat\u00fd Kitts a Nevis");
        put("KM", "Komory");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Kambod\u017ea");
        put("KG", "Kyrgyzst\u00e1n");
        put("KE", "Ke\u0148a");
        put("WF", "Wallis a Futuna");
        put("JP", "Japonsko");
        put("JO", "Jord\u00e1nsko");
        put("JM", "Jamajka");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "Americk\u00e9 Panensk\u00e9 ostrovy");
        put("VG", "Britsk\u00e9 Panensk\u00e9 ostrovy");
        put("VE", "Venezuela");
        put("VC", "Svat\u00fd Vincent a Grenadiny");
        put("VA", "Svat\u00fd stolec");
        put("IT", "It\u00e1lie");
        put("IS", "Island");
        put("IR", "\u00cdr\u00e1n");
        put("IQ", "Ir\u00e1k");
        put("UZ", "Uzbekist\u00e1n");
        put("IO", "Britsk\u00e9 \u00fazem\u00ed v Indick\u00e9m oce\u00e1nu");
        put("UY", "Uruguay");
        put("IN", "Indie");
        put("IL", "Izrael");
        put("US", "Spojen\u00e9 st\u00e1ty");
        put("IE", "Irsko");
        put("ID", "Indon\u00e9sie");
        put("UM", "Men\u0161\u00ed odlehl\u00e9 ostrovy USA");
        put("UG", "Uganda");
        put("UA", "Ukrajina");
        put("HU", "Ma\u010farsko");
        put("HT", "Haiti");
        put("HR", "Chorvatsko");
        put("TZ", "Tanzanie");
        put("HN", "Honduras");
        put("HM", "Ostrovy Heard a McDonald");
        put("TW", "Tchaj-wan");
        put("TV", "Tuvalu");
        put("HK", "Hongkong, zvl\u00e1\u0161tn\u00ed administrativn\u00ed oblast \u010c\u00edny");
        put("TT", "Trinidad a Tobago");
        put("TR", "Turecko");
        put("TO", "Tonga");
        put("TN", "Tunisko");
        put("TM", "Turkmenist\u00e1n");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("es", "\u0160pan\u011bl\u0161tina");
        put("ku", "Kurd\u0161tina");
        put("eo", "Esperanto");
        put("ks", "Ka\u0161m\u00edr\u0161tina");
        put("en", "Angli\u010dtina");
        put("el", "\u0158e\u010dtina");
        put("qu", "Ke\u010du\u00e1n\u0161tina");
        put("ko", "Korej\u0161tina");
        put("kn", "Kannad\u0161tina");
        put("km", "Kambod\u017e\u0161tina");
        put("kl", "Gr\u00f3n\u0161tina");
        put("kk", "Kazach\u0161tina");
        put("wo", "Wolof");
        put("ka", "Gruz\u00edn\u0161tina");
        put("dz", "Bh\u00fat\u00e1n\u0161tina");
        put("jv", "Jav\u00e1n\u0161tina");
        put("pt", "Portugal\u0161tina");
        put("ps", "Pashto (Pushto)");
        put("de", "N\u011bm\u010dina");
        put("pl", "Pol\u0161tina");
        put("da", "D\u00e1n\u0161tina");
        put("vo", "Volapuk");
        put("ja", "Japon\u0161tina");
        put("vi", "Vietnam\u0161tina");
        put("cy", "Vel\u0161tina");
        put("pa", "Pa\u0148d\u017e\u00e1b\u0161tina");
        put("cs", "\u010ce\u0161tina");
        put("iu", "Inuktitut\u0161tina");
        put("it", "Ital\u0161tina");
        put("co", "Korsi\u010dtina");
        put("is", "Island\u0161tina");
        put("uz", "Uzbe\u010dtina");
        put("or", "Oriya");
        put("ik", "Inupiak\u0161tina");
        put("ur", "Urd\u0161tina");
        put("om", "Oromo (Afan)");
        put("ca", "Katal\u00e1n\u0161tina");
        put("ie", "Interlingue");
        put("id", "Indon\u00e9\u0161tina");
        put("uk", "Ukrajin\u0161tina");
        put("ia", "Interlingua");
        put("oc", "Occitan");
        put("ug", "Uighur\u0161tina");
        put("hy", "Arm\u00e9n\u0161tina");
        put("br", "Breta\u0148\u0161tina");
        put("hu", "Ma\u010far\u0161tina");
        put("bo", "Tibet\u0161tina");
        put("bn", "Beng\u00e1l\u0161tina");
        put("hr", "Chorvat\u0161tina");
        put("bi", "Bisl\u00e1m\u0161tina");
        put("tw", "Twi");
        put("bh", "Bihar\u0161tina");
        put("bg", "Bulhar\u0161tina");
        put("tt", "Tatar\u0161tina");
        put("no", "Nor\u0161tina");
        put("be", "B\u011bloru\u0161tina");
        put("ts", "Tsonga");
        put("hi", "Hind\u0161tina");
        put("tr", "Ture\u010dtina");
        put("nl", "Holand\u0161tina");
        put("zu", "Zulu");
        put("ba", "Baskir\u0161tina");
        put("to", "Tonga");
        put("he", "Hebrej\u0161tina");
        put("tn", "Setswan\u0161tina");
        put("tl", "Tagalog");
        put("tk", "Turkmen\u0161tina");
        put("ha", "Hausa");
        put("ne", "Nep\u00e1l\u0161tina");
        put("az", "Azerbajd\u017e\u00e1n\u0161tina");
        put("ti", "Tigrinij\u0161tina");
        put("ay", "Aym\u00e1r\u0161tina");
        put("th", "Thaj\u0161tina");
        put("tg", "T\u00e1d\u017ei\u010dtina");
        put("na", "Nauru");
        put("te", "Telug\u0161tina");
        put("zh", "\u010c\u00edn\u0161tina");
        put("as", "Assam\u00e9\u0161tina");
        put("ar", "Arab\u0161tina");
        put("ta", "Tamil\u0161tina");
        put("gu", "Gujarat\u0161tina");
        put("my", "Barm\u0161tina");
        put("am", "Amhar\u0161tina");
        put("za", "Zhuang");
        put("mt", "Malt\u0161tina");
        put("ms", "Malaj\u0161tina");
        put("gn", "Guaran\u0161tina");
        put("sw", "Svahil\u0161tina");
        put("mr", "Marathi");
        put("sv", "\u0160v\u00e9d\u0161tina");
        put("gl", "Hali\u010d\u0161tina");
        put("su", "Sundan\u0161tina");
        put("af", "Afrik\u00e1n\u0161tina");
        put("st", "Sesotho");
        put("mo", "Moldav\u0161tina");
        put("ss", "Siswat\u0161tina");
        put("mn", "Mongol\u0161tina");
        put("sr", "Srb\u0161tina");
        put("sq", "Alb\u00e1n\u0161tina");
        put("ml", "Malabar\u0161tina");
        put("ab", "Abch\u00e1z\u0161tina");
        put("mk", "Makedon\u0161tina");
        put("aa", "Afar\u0161tina");
        put("so", "Som\u00e1l\u0161tina");
        put("sn", "Shona");
        put("mi", "Maor\u0161tina");
        put("gd", "Skotsk\u00e1 gal\u0161tina");
        put("sm", "Samoy\u0161tina");
        put("sl", "Slovin\u0161tina");
        put("mg", "Malga\u0161tina");
        put("sk", "Sloven\u0161tina");
        put("ga", "Ir\u0161tina");
        put("yo", "Yoruba");
        put("si", "Sinh\u00e1l\u0161tina");
        put("sh", "Srbochorvat\u0161tina");
        put("sg", "Sangho");
        put("yi", "Jidi\u0161");
        put("sd", "Sindhi");
        put("fy", "Fr\u00ed\u0161tina");
        put("sa", "Sanskrt");
        put("fr", "Francouz\u0161tina");
        put("lv", "Loty\u0161tina");
        put("lt", "Litev\u0161tina");
        put("fo", "Faer\u0161tina");
        put("rw", "Kinyarwand\u0161tina");
        put("ru", "Ru\u0161tina");
        put("lo", "Lao\u0161tina");
        put("fj", "Fid\u017ei");
        put("ln", "Lingal\u0161tina");
        put("fi", "Fin\u0161tina");
        put("ro", "Rumun\u0161tina");
        put("rn", "Kirundi");
        put("rm", "R\u00e9torom\u00e1n\u0161tina");
        put("fa", "Per\u0161tina");
        put("la", "Latina");
        put("xh", "Xhosa");
        put("eu", "Baski\u010dtina");
        put("ky", "Kirgiz\u0161tina");
        put("et", "Eston\u0161tina");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "\u00a0" },
    { "localPatternChars", "GuMtkHmsSEDFwWahKzUeygAZ" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "ampms", ampms },
    { "shortDateFormat", "d.M.yy" },
    { "mediumDateFormat", "d.M.yyyy" },
    { "longDateFormat", "d. MMMM yyyy" },
    { "fullDateFormat", "EEEE, d. MMMM yyyy" },
    { "shortTimeFormat", "H:mm" },
    { "mediumTimeFormat", "H:mm:ss" },
    { "longTimeFormat", "H:mm:ss z" },
    { "fullTimeFormat", "H:mm:ss z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
