/* LocaleInformation_nl.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_nl extends ListResourceBundle
{
  private static final String collation_rules = 
    "<0<1<2<3<4<5<6<7<8<9<A,a<b,B<c,C<d,D<e,E<f,F<g,G<h,H<i,I<j,J<k,K" +
    "<l,L<m,M<n,N<o,O<p,P<q,Q<r,R<s,S<t,T<u,U<v,V<w,W<x,X<y,Y<z,Z";

  private static final String[] shortMonths = {
    "jan",
    "feb",
    "mrt",
    "apr",
    "mei",
    "jun",
    "jul",
    "aug",
    "sep",
    "okt",
    "nov",
    "dec",
    null,
  };

  private static final String[] months = {
    "januari",
    "februari",
    "maart",
    "april",
    "mei",
    "juni",
    "juli",
    "augustus",
    "september",
    "oktober",
    "november",
    "december",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "zo",
    "ma",
    "di",
    "wo",
    "do",
    "vr",
    "za",
  };

  private static final String[] weekdays = {
    null,
    "zondag",
    "maandag",
    "dinsdag",
    "woensdag",
    "donderdag",
    "vrijdag",
    "zaterdag",
  };

  private static final String[] eras = {
    "v. Chr.",
    "n. Chr.",
  };

  private static final String[][] zoneStrings =
  {
    { "WET", "West Europese Tijd", "WET", "West Europese Zomertijd", "WEST", "London" },
    { "CET", "Centraal Europese Tijd", "CET", "Centraal Europese Zomertijd", "CEST", "Amsterdam" },
    { "EET", "Oost Europese Tijd", "EET", "Oost Europese Zomertijd", "EEST", "Istanbul" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Oost-Timor");
        put("TK", "Tokelau");
        put("TJ", "Tadzjikistan");
        put("TH", "Thailand");
        put("TG", "Togo");
        put("TF", "Franse Gebieden in de zuidelijke Indische Oceaan");
        put("GY", "Guyana");
        put("TD", "Tsjaad");
        put("TC", "Turks- en Caicoseilanden");
        put("GW", "Guinee-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "Zuid-Georgi\u00eb en Zuidelijke Sandwicheilanden");
        put("GR", "Griekenland");
        put("GQ", "Equatoriaal-Guinea");
        put("GP", "Guadeloupe");
        put("SZ", "Swaziland");
        put("SY", "Syri\u00eb");
        put("GN", "Guinea");
        put("GM", "Gambia");
        put("GL", "Groenland");
        put("SV", "El Salvador");
        put("ST", "Sao Tom\u00e9 en Principe");
        put("GI", "Gibraltar");
        put("GH", "Ghana");
        put("SR", "Suriname");
        put("GF", "Frans-Guyana");
        put("SP", "Servi\u00eb");
        put("GE", "Georgi\u00eb");
        put("SO", "Somali\u00eb");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Verenigd Koninkrijk");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Slowakije");
        put("SJ", "Svalbard en Jan Mayen");
        put("SI", "Sloveni\u00eb");
        put("SH", "Saint Helena");
        put("SG", "Singapore");
        put("SE", "Zweden");
        put("SD", "Soedan");
        put("SC", "Seychellen");
        put("SB", "Salomonseilanden");
        put("SA", "Saoedi-Arabi\u00eb");
        put("FR", "Frankrijk");
        put("FO", "Faer\u00f6er");
        put("FM", "Micronesia, Federale Staten van");
        put("RW", "Rwanda");
        put("FK", "Falklandeilanden");
        put("RU", "Russische Federatie");
        put("FJ", "Fiji");
        put("FI", "Finland");
        put("RO", "Roemeni\u00eb");
        put("RE", "R\u00e9union");
        put("ET", "Ethiopi\u00eb");
        put("ES", "Spanje");
        put("ER", "Eritrea");
        put("EH", "West-Sahara");
        put("EG", "Egypte");
        put("EE", "Estland");
        put("EC", "Ecuador");
        put("DZ", "Algerije");
        put("QA", "Qatar");
        put("DO", "Dominicaanse Republiek");
        put("PY", "Paraguay");
        put("DM", "Dominica");
        put("PW", "Palau");
        put("DK", "Denemarken");
        put("DJ", "Djibouti");
        put("PT", "Portugal");
        put("PS", "Palestijns Gebied");
        put("PR", "Puerto Rico");
        put("DE", "Duitsland");
        put("PN", "Pitcairn");
        put("PM", "Saint Pierre en Miquelon");
        put("PL", "Polen");
        put("PK", "Pakistan");
        put("PH", "Filipijnen");
        put("PG", "Papoea-Nieuw-Guinea");
        put("PF", "Frans-Polynesi\u00eb");
        put("CZ", "Tsjechi\u00eb");
        put("PE", "Peru");
        put("CY", "Cyprus");
        put("CX", "Christmaseiland");
        put("CV", "Kaapverdi\u00eb");
        put("PA", "Panama");
        put("CU", "Cuba");
        put("CR", "Costa Rica");
        put("CO", "Colombia");
        put("CN", "China");
        put("CM", "Kameroen");
        put("CL", "Chili");
        put("CK", "Cookeilanden");
        put("CI", "Ivoorkust");
        put("CH", "Zwitserland");
        put("CG", "Congo");
        put("CF", "Centraal-Afrikaanse Republiek");
        put("CD", "Congo, Democratische Republiek");
        put("CC", "Cocoseilanden");
        put("OM", "Oman");
        put("CA", "Canada");
        put("BZ", "Belize");
        put("BY", "Wit-Rusland");
        put("BW", "Botswana");
        put("BV", "Bouveteiland");
        put("BT", "Bhutan");
        put("BS", "Bahama\u2019s");
        put("BR", "Brazili\u00eb");
        put("NZ", "Nieuw-Zeeland");
        put("BO", "Bolivia");
        put("BN", "Brunei Darussalam");
        put("BM", "Bermuda");
        put("NU", "Niue");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrein");
        put("NR", "Nauru");
        put("BG", "Bulgarije");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "Belgi\u00eb");
        put("NO", "Noorwegen");
        put("BD", "Bangladesh");
        put("BB", "Barbados");
        put("ZW", "Zimbabwe");
        put("NL", "Nederland");
        put("BA", "Bosni\u00eb Herzegovina");
        put("NI", "Nicaragua");
        put("NG", "Nigeria");
        put("NF", "Norfolkeiland");
        put("AZ", "Azerbeidzjan");
        put("NE", "Niger");
        put("NC", "Nieuw-Caledoni\u00eb");
        put("AW", "Aruba");
        put("ZM", "Zambia");
        put("NA", "Namibi\u00eb");
        put("AU", "Australi\u00eb");
        put("AT", "Oostenrijk");
        put("AS", "Amerikaans Samoa");
        put("AR", "Argentini\u00eb");
        put("AQ", "Antarctica");
        put("MZ", "Mozambique");
        put("AO", "Angola");
        put("MY", "Maleisi\u00eb");
        put("AN", "Nederlandse Antillen");
        put("MX", "Mexico");
        put("AM", "Armeni\u00eb");
        put("MW", "Malawi");
        put("AL", "Albani\u00eb");
        put("MV", "Maldiven");
        put("ZA", "Zuid-Afrika");
        put("MU", "Mauritius");
        put("MT", "Malta");
        put("AI", "Anguilla");
        put("MS", "Montserrat");
        put("MR", "Mauritani\u00eb");
        put("AG", "Antigua en Barbuda");
        put("MQ", "Martinique");
        put("AF", "Afghanistan");
        put("MP", "Noordelijke Marianeneilanden");
        put("AE", "Verenigde Arabische Emiraten");
        put("MO", "Macao S.A.R. van China");
        put("AD", "Andorra");
        put("MN", "Mongoli\u00eb");
        put("MM", "Myanmar");
        put("ML", "Mali");
        put("MK", "Macedoni\u00eb, Republiek");
        put("YU", "Joegoslavi\u00eb");
        put("YT", "Mayotte");
        put("MH", "Marshalleilanden");
        put("MG", "Madagaskar");
        put("MD", "Republiek Moldavi\u00eb");
        put("MC", "Monaco");
        put("MA", "Marokko");
        put("YE", "Jemen");
        put("LY", "Libi\u00eb");
        put("LV", "Letland");
        put("LU", "Luxemburg");
        put("LT", "Litouwen");
        put("LS", "Lesotho");
        put("LR", "Liberia");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Saint Lucia");
        put("LB", "Libanon");
        put("LA", "Laos");
        put("KZ", "Kazachstan");
        put("KY", "Caymaneilanden");
        put("KW", "Koeweit");
        put("KR", "Zuid-Korea");
        put("KP", "Noord-Korea");
        put("KN", "Saint Kitts en Nevis");
        put("KM", "Comoren");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Cambodja");
        put("KG", "Kirgizstan");
        put("KE", "Kenia");
        put("WF", "Wallis en Futuna");
        put("JP", "Japan");
        put("JO", "Jordani\u00eb");
        put("JM", "Jamaica");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "Amerikaanse Maagdeneilanden");
        put("VG", "Britse Maagdeneilanden");
        put("VE", "Venezuela");
        put("VC", "Saint Vincent en de Grenadines");
        put("VA", "Vaticaanstad");
        put("IT", "Itali\u00eb");
        put("IS", "IJsland");
        put("IR", "Iran");
        put("IQ", "Irak");
        put("UZ", "Oezbekistan");
        put("IO", "Brits Territorium in de Indische Oceaan");
        put("UY", "Uruguay");
        put("IN", "India");
        put("IL", "Isra\u00ebl");
        put("US", "Verenigde Staten");
        put("IE", "Ierland");
        put("ID", "Indonesi\u00eb");
        put("UM", "Amerikaanse ondergeschikte afgelegen eilanden");
        put("UG", "Oeganda");
        put("UA", "Oekra\u00efne");
        put("HU", "Hongarije");
        put("HT", "Ha\u00efti");
        put("HR", "Kroati\u00eb");
        put("TZ", "Tanzania");
        put("HN", "Honduras");
        put("HM", "Heardeiland en McDonaldeiland");
        put("TW", "Taiwan");
        put("TV", "Tuvalu");
        put("HK", "Hongkong S.A.R. van China");
        put("TT", "Trinidad en Tobago");
        put("TR", "Turkije");
        put("TO", "Tonga");
        put("TN", "Tunesi\u00eb");
        put("TM", "Turkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();
  private static final String localPatternChars = "GyMdhHmsSEDFwWakKz"; // Not a mistake!

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("gwi", "Gwich\u02bbin");
        put("akk", "Akkadisch");
        put("eka", "Ekajuk");
        put("ijo", "Ijo");
        put("xh", "Xhosa");
        put("sux", "Soemerisch");
        put("sus", "Soesoe");
        put("mis", "Diverse talen");
        put("loz", "Lozi");
        put("tog", "Tonga (Nyasa)");
        put("pon", "Pohnpeiaans");
        put("min", "Minangkabau");
        put("suk", "Sukuma");
        put("wo", "Wolof");
        put("lol", "Mongo");
        put("kut", "Kutenai");
        put("mic", "Micmac");
        put("wa", "Wallonisch");
        put("kum", "Kumyk");
        put("zap", "Zapotec");
        put("cus", "Koesjitisch (overige)");
        put("jbo", "Lojban");
        put("doi", "Dogri");
        put("vo", "Volap\u00fck");
        put("oto", "Otomi-talen");
        put("vi", "Vietnamees");
        put("vai", "Vai");
        put("rar", "Rarotongan");
        put("ve", "Venda");
        put("rap", "Rapanui");
        put("raj", "Rajasthani");
        put("ota", "Turks, Ottomaans (1500-1928)");
        put("nzi", "Nzima");
        put("nap", "Napolitaans");
        put("uz", "Oezbeeks");
        put("uga", "Oegaritisch");
        put("tmh", "Tamashek");
        put("nai", "Noord-Amerikaans Indiaans (overige)");
        put("nah", "Nahuatl");
        put("ur", "Urdu");
        put("fat", "Fanti");
        put("uk", "Oekra\u00efens");
        put("egy", "Egyptisch (klassiek)");
        put("ug", "Uighur");
        put("fan", "Fang");
        put("ssa", "Nilo-Saharam (overige)");
        put("mga", "Iers, middel- (900-1200)");
        put("bat", "Baltisch (overige)");
        put("nyo", "Nyoro");
        put("bas", "Basa");
        put("nyn", "Nyankole");
        put("nym", "Nyamwezi");
        put("hmn", "Hmong");
        put("ban", "Balinees");
        put("osa", "Osage");
        put("bal", "Baloetsji");
        put("ty", "Tahitisch");
        put("bai", "Bamileke-talen");
        put("tw", "Twi");
        put("srr", "Serer");
        put("tli", "Tlingit");
        put("tt", "Tataars");
        put("ts", "Tsonga");
        put("bad", "Banda");
        put("tr", "Turks");
        put("to", "Tonga (Tonga-eilanden)");
        put("tn", "Tswana");
        put("tl", "Tagalog");
        put("tk", "Turkmeens");
        put("ti", "Tigrinya");
        put("th", "Thai");
        put("kru", "Kurukh");
        put("tg", "Tadzjik");
        put("byn", "Blin");
        put("te", "Teloegoe");
        put("kro", "Kru");
        put("csb", "Kasjoebisch");
        put("ta", "Tamil");
        put("tkl", "Tokelau");
        put("efi", "Efik");
        put("sw", "Swahili");
        put("sv", "Zweeds");
        put("su", "Sundanees");
        put("krc", "Karachay-Balkar");
        put("st", "Sotho, zuid");
        put("ss", "Swati");
        put("sr", "Servisch");
        put("sq", "Albanees");
        put("men", "Mende");
        put("crp", "Creools en Pidgin (overige)");
        put("so", "Somalisch");
        put("afh", "Afrihili");
        put("sn", "Shona");
        put("sm", "Samoaans");
        put("sl", "Sloveens");
        put("grc", "Grieks, klassiek (tot 1453)");
        put("sk", "Slowaaks");
        put("grb", "Gerbo");
        put("si", "Singalees");
        put("sh", "Servokroatisch");
        put("crh", "Krim-Turks; Krim-Tataars");
        put("afa", "Afro-aziatisch (overige)");
        put("sg", "Sango");
        put("se", "Noord-Samisch");
        put("sd", "Sindhi");
        put("udm", "Udmurt");
        put("sc", "Sardinisch");
        put("sa", "Sanskrit");
        put("rw", "Kinyarwanda");
        put("ru", "Russisch");
        put("mdr", "Mandar");
        put("ro", "Roemeens");
        put("rn", "Rundi");
        put("rm", "Retoromaans");
        put("mdf", "Moksha");
        put("tiv", "Tiv");
        put("ady", "Adyghe");
        put("zun", "Zuni");
        put("kpe", "Kpelle");
        put("qu", "Quechua");
        put("tig", "Tigre");
        put("son", "Songhai");
        put("cpp", "Creools en Pidgin, op Portugees gebaseerd (overige)");
        put("sog", "Sogdisch");
        put("ada", "Adangme");
        put("kos", "Kosreaans");
        put("hit", "Hittite");
        put("cpf", "Creools en Pidgin, op Frans gebaseerd (overige)");
        put("cpe", "Creools en Pidgin, op Engels gebaseerd (overige)");
        put("him", "Himachali");
        put("kok", "Konkani");
        put("hil", "Hiligaynon");
        put("got", "Gothisch");
        put("gor", "Gorontalo");
        put("gon", "Gondi");
        put("din", "Dinka");
        put("nub", "Nubische talen");
        put("pt", "Portugees");
        put("ps", "Pashto");
        put("fur", "Friulisch");
        put("phn", "Foenicisch");
        put("goh", "Duits, oudhoog- (ca. 750-1050)");
        put("snk", "Soninke");
        put("cop", "Koptisch");
        put("yap", "Yapees");
        put("ach", "Akoli");
        put("yao", "Yao");
        put("phi", "Filipijns (overige)");
        put("pl", "Pools");
        put("ace", "Atjehs");
        put("pi", "Pali");
        put("pa", "Punjabi");
        put("bug", "Buginees");
        put("iba", "Iban");
        put("sms", "Skolt Sami");
        put("bua", "Buriat");
        put("mas", "Masai");
        put("smn", "Inari Sami");
        put("os", "Ossetisch");
        put("map", "Austronesisch");
        put("or", "Oriya");
        put("man", "Mandingo");
        put("smj", "Lule Sami");
        put("smi", "Sami-talen (overige)");
        put("mak", "Makassaars");
        put("om", "Oromo");
        put("mai", "Maithili");
        put("oj", "Ojibwa");
        put("mag", "Magahi");
        put("mad", "Madurees");
        put("sma", "Zuid-Samisch");
        put("oc", "Langue d\u2019Oc (na 1500)");
        put("nso", "Sotho, noorderlijk");
        put("btk", "Batak");
        put("myv", "Erzya");
        put("dgr", "Dogrib");
        put("ny", "Nyanja");
        put("myn", "Mayan");
        put("nv", "Navajo");
        put("kmb", "Kimbundu");
        put("nr", "Ndebele, zuid-");
        put("gmh", "Duits, middelhoog- (ca. 1050-1500)");
        put("no", "Noors");
        put("nn", "Noors - Nynorsk");
        put("nl", "Nederlands");
        put("ng", "Ndonga");
        put("sla", "Slavisch (overige)");
        put("ne", "Nepalees");
        put("nd", "Ndebele, noord-");
        put("cmc", "Chamische talen");
        put("tet", "Tetum");
        put("nb", "Noors - Bokm\u00e5l");
        put("na", "Nauru");
        put("ter", "Tereno");
        put("tem", "Timne");
        put("my", "Birmees");
        put("lez", "Lezgisch");
        put("mt", "Maltees");
        put("peo", "Perzisch, oud- (ca. 600-400 B.C.)");
        put("ms", "Maleis");
        put("mr", "Marathi");
        put("fro", "Frans, oud (842-ca. 1400)");
        put("mo", "Moldavisch");
        put("frm", "Frans, middel (ca. 1400-1600)");
        put("mn", "Mongools");
        put("jrb", "Judeo-Arabisch");
        put("ml", "Malayalam");
        put("mk", "Macedonisch");
        put("mi", "Maori");
        put("mh", "Marshallees");
        put("mg", "Malagasisch");
        put("mwr", "Marwari");
        put("bra", "Braj");
        put("den", "Slave");
        put("lv", "Letlands");
        put("lu", "Luba-Katanga");
        put("del", "Delaware");
        put("lt", "Litouws");
        put("lo", "Lao");
        put("ln", "Lingala");
        put("li", "Limburgs");
        put("ewo", "Ewondo");
        put("lg", "Ganda");
        put("lb", "Luxemburgs");
        put("la", "Latijn");
        put("jpr", "Judeo-Perzisch");
        put("vot", "Votisch");
        put("sit", "Sino-Tibetaans (overige)");
        put("ky", "Kirgizisch");
        put("kw", "Cornish");
        put("kv", "Komi");
        put("ku", "Koerdisch");
        put("sio", "Siouaanse talen");
        put("ks", "Kashmiri");
        put("kr", "Kanuri");
        put("awa", "Awadhi");
        put("ko", "Koreaans");
        put("kn", "Kannada");
        put("km", "Khmer");
        put("kl", "Kalaallisut");
        put("kk", "Kazachs");
        put("rom", "Romani");
        put("kj", "Kuanyama");
        put("sid", "Sidamo");
        put("ki", "Kikuyu");
        put("kg", "Kongo");
        put("non", "Noors, oud-");
        put("ka", "Georgisch");
        put("mus", "Creek");
        put("roa", "Romaans (overige)");
        put("nog", "Nogai");
        put("mun", "Munda-talen");
        put("mul", "Meerdere talen");
        put("jv", "Javaans");
        put("gil", "Gilbertees");
        put("znd", "Zande");
        put("shn", "Shan");
        put("fon", "Fon");
        put("xal", "Kalmyk");
        put("aus", "Australische talen");
        put("kho", "Khotanees");
        put("ja", "Japans");
        put("khi", "Khoisan (overige)");
        put("pau", "Palauaans");
        put("chy", "Cheyenne");
        put("tai", "Tai (overige)");
        put("iu", "Inuktitut");
        put("pap", "Papiamento");
        put("it", "Italiaans");
        put("sgn", "Gebarentalen");
        put("is", "IJslands");
        put("kha", "Khasi");
        put("chr", "Cherokee");
        put("pam", "Pampanga");
        put("pal", "Pahlavi");
        put("chp", "Chipewyan");
        put("io", "Ido");
        put("cho", "Choctaw");
        put("chn", "Chinook-jargon");
        put("chm", "Mari");
        put("tyv", "Tuvinisch");
        put("bnt", "Bantu");
        put("pag", "Pangasinan");
        put("ik", "Inupiaq");
        put("chk", "Chuukees");
        put("ii", "Sichuan Yi");
        put("haw", "Hawa\u00efaans");
        put("lam", "Lamba");
        put("ig", "Igbo");
        put("chg", "Chagatai");
        put("sga", "Iers, oud- (tot 900)");
        put("paa", "Papoea (overige)");
        put("ie", "Interlingue");
        put("id", "Indonesisch");
        put("lah", "Lahnda");
        put("day", "Dajak");
        put("chb", "Chibcha");
        put("ia", "Interlingua");
        put("lad", "Ladino");
        put("hz", "Herero");
        put("hai", "Haida");
        put("dar", "Dargwa");
        put("hy", "Armeens");
        put("ath", "Athapascaanse talen");
        put("hu", "Hongaars");
        put("ht", "Ha\u00eftiaans");
        put("dak", "Dakota");
        put("hr", "Kroatisch");
        put("ho", "Hiri Motu");
        put("hi", "Hindi");
        put("dyu", "Dyula");
        put("he", "Hebreeuws");
        put("ast", "Asturisch");
        put("ha", "Hausa");
        put("wen", "Sorbische talen");
        put("gv", "Manx");
        put("gu", "Gujarati");
        put("sem", "Semitisch (overige)");
        put("sel", "Selkup");
        put("iro", "Irokese talen");
        put("gn", "Guarani");
        put("gl", "Galicisch");
        put("arw", "Arawak");
        put("gez", "Geez");
        put("art", "Kunsttalen (overige)");
        put("gd", "Schots Gaelic");
        put("ira", "Iraans");
        put("ga", "Iers");
        put("arp", "Arapaho");
        put("arn", "Araukaans");
        put("fy", "Fries");
        put("bla", "Siksika");
        put("gem", "Germaans (overige)");
        put("ypk", "Yupik-talen");
        put("arc", "Aramees");
        put("fr", "Frans");
        put("fo", "Faer\u00f6ers");
        put("cel", "Keltisch (overige)");
        put("fj", "Fijisch");
        put("fi", "Fins");
        put("ff", "Fulah");
        put("tvl", "Tuvalu");
        put("ceb", "Cebuano");
        put("fa", "Perzisch");
        put("eu", "Baskisch");
        put("sco", "Schots");
        put("et", "Estlands");
        put("es", "Spaans");
        put("eo", "Esperanto");
        put("en", "Engels");
        put("el", "Grieks");
        put("tut", "Alta\u00efsch (overige)");
        put("niu", "Niueaans");
        put("tup", "Tupi-talen");
        put("ee", "Ewe");
        put("tum", "Toemboeka");
        put("mos", "Mossi");
        put("dz", "Dzongkha");
        put("nic", "Niger - Kordofanisch (overige)");
        put("lus", "Lushai");
        put("fiu", "Fins-Oegrisch (overige)");
        put("dv", "Divehi");
        put("nia", "Nias");
        put("moh", "Mohawk");
        put("luo", "Luo");
        put("lun", "Lunda");
        put("apa", "Apache-talen");
        put("lui", "Luiseno");
        put("hup", "Hupa");
        put("bin", "Bini");
        put("de", "Duits");
        put("lua", "Luba-Lulua");
        put("bik", "Bikol");
        put("was", "Washo");
        put("und", "Onbepaald");
        put("war", "Waray");
        put("da", "Deens");
        put("dum", "Nederlands, middel- (ca. 1050-1350)");
        put("wal", "Walamo");
        put("mno", "Manobo-talen");
        put("wak", "Wakashan-talen");
        put("sat", "Santali");
        put("cy", "Welsh");
        put("sas", "Sasak");
        put("kbd", "Kabardisch");
        put("cv", "Tsjoevasjisch");
        put("cu", "Kerkslavisch");
        put("mni", "Manipoeri");
        put("cs", "Tsjechisch");
        put("sam", "Samaritaans Aramees");
        put("cr", "Cree");
        put("sal", "Salishan-talen");
        put("dua", "Duala");
        put("co", "Corsicaans");
        put("sai", "Zuid-Amerikaans Indiaans (overige)");
        put("mnc", "Mantsjoe");
        put("sah", "Yakut");
        put("kaw", "Kawi");
        put("inh", "Ingoesj");
        put("gba", "Gbaya");
        put("sad", "Sandawe");
        put("ch", "Chamorro");
        put("ine", "Indo-Europees (overige)");
        put("bho", "Bhojpuri");
        put("enm", "Engels, middel- (1100-1500)");
        put("kar", "Karen");
        put("inc", "Indisch (overige)");
        put("ce", "Chechen");
        put("gay", "Gayo");
        put("ca", "Catalaans");
        put("umb", "Umbundu");
        put("syr", "Syriac");
        put("kam", "Kamba");
        put("tsi", "Tsimshian");
        put("ang", "Engels, oud (ca. 450-1100)");
        put("kac", "Kachin");
        put("cau", "Kaukasisch (overige)");
        put("kab", "Kabyle");
        put("kaa", "Kara-Kalpaks");
        put("bs", "Bosnisch");
        put("car", "Caribisch");
        put("br", "Bretons");
        put("bo", "Tibetaans");
        put("bn", "Bengalees");
        put("bm", "Bambara");
        put("gaa", "Ga");
        put("cai", "Midden-Amerikaans Indiaans (overige)");
        put("bi", "Bislama");
        put("bh", "Bihari");
        put("bg", "Bulgaars");
        put("be", "Wit-Russisch");
        put("cad", "Caddo");
        put("ba", "Basjkiers");
        put("zu", "Zulu");
        put("zen", "Zenaga");
        put("pro", "Proven\u00e7aals, oud- (tot 1500)");
        put("hsb", "Oppersorbisch");
        put("az", "Azerbeidzjaans");
        put("ay", "Aymara");
        put("av", "Avarisch");
        put("as", "Assamees");
        put("dsb", "Nedersorbisch");
        put("ar", "Arabisch");
        put("ilo", "Iloko");
        put("elx", "Elamitisch");
        put("zh", "Chinees");
        put("an", "Aragonees");
        put("pra", "Prakrit-talen");
        put("am", "Amhaars");
        put("new", "Newari");
        put("ak", "Akan");
        put("za", "Zhuang");
        put("af", "Afrikaans");
        put("ae", "Avestisch");
        put("ab", "Abchazisch");
        put("aa", "Afar");
        put("yo", "Joruba");
        put("alg", "Algonkium-talen");
        put("ale", "Aleut");
        put("mkh", "Mon-Khmer (overige)");
        put("yi", "Jiddisch");
        put("dra", "Dravidisch (overige)");
        put("ber", "Berber");
        put("nds", "Laagduits; Laagsaxon");
        put("bem", "Bemba");
        put("bej", "Beja");
        put("tpi", "Tok Pisin");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final class Hashtablevariants extends java.util.Hashtable
  {
    public Hashtablevariants()
      {
        super();
        put("REVISED", "Gewijzigd");
      }
  }

  private static final Object variants = new Hashtablevariants();

  private static final Object[][] contents =
  {
    { "collation_rules", collation_rules },
    { "localPatternChars", localPatternChars },
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "shortDateFormat", "d-M-yy" },
    { "mediumDateFormat", "d-MMM-yyyy" },
    { "longDateFormat", "d MMMM yyyy" },
    { "fullDateFormat", "EEEE d MMMM yyyy" },
    { "shortTimeFormat", "H:mm" },
    { "mediumTimeFormat", "H:mm:ss" },
    { "longTimeFormat", "H:mm:ss z" },
    { "fullTimeFormat", "H:mm:ss' uur' z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
    { "variants", variants },
  };

  public Object[][] getContents() { return contents; }
}
