/* LocaleInformation_fi.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_fi extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "tammi",
    "helmi",
    "maalis",
    "huhti",
    "touko",
    "kes\u00e4",
    "hein\u00e4",
    "elo",
    "syys",
    "loka",
    "marras",
    "joulu",
    null,
  };

  private static final String[] months = {
    "tammikuu",
    "helmikuu",
    "maaliskuu",
    "huhtikuu",
    "toukokuu",
    "kes\u00e4kuu",
    "hein\u00e4kuu",
    "elokuu",
    "syyskuu",
    "lokakuu",
    "marraskuu",
    "joulukuu",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "su",
    "ma",
    "ti",
    "ke",
    "to",
    "pe",
    "la",
  };

  private static final String[] weekdays = {
    null,
    "sunnuntai",
    "maanantai",
    "tiistai",
    "keskiviikko",
    "torstai",
    "perjantai",
    "lauantai",
  };

  private static final String[] eras = {
    "eaa.",
    "jaa.",
  };

  private static final String[] ampms = {
    "ap.",
    "ip.",
  };

  private static final String[][] zoneStrings =
  {
    { "PST", "Tyynenmeren normaaliaika", "PDT", "Tyynenmeren kes\u00e4aika",  "America/Los_Angeles" },
    { "GMT", "Greenwichin aika", "GMT", "Greenwichin aika",  "Africa/Casablanca" },
    { "EST", "It\u00e4inen normaaliaika", "EDT", "It\u00e4inen kes\u00e4aika",  "America/New_York" },
    { "AST", "Alaskan normaaliaika", "ADT", "Alaskan kes\u00e4aika",  "America/Anchorage" },
    { "GMT", "Greenwichin aika", "GMT", "Greenwichin aika",  "Etc/GMT" },
    { "CTT", "Kiinan normaaliaika", "CDT", "Kiinan normaaliaika",  "Asia/Shanghai" },
    { "AST", "Atlantin normaaliaika", "ADT", "Atlantin kes\u00e4aika",  "America/Halifax" },
    { "CET", "Keski-Euroopan normaaliaika", "CEST", "Keski-Euroopan kes\u00e4aika",  "Europe/Paris" },
    { "MST", "Kalliovuorten normaaliaika", "MDT", "Kalliovuorten kes\u00e4aika",  "America/Denver" },
    { "IST", "Israelin normaaliaika", "IDT", "Israelin kes\u00e4aika",  "Asia/Jerusalem" },
    { "HST", "Havaijin normaaliaika", "HST", "Havaijin normaaliaika",  "Pacific/Honolulu" },
    { "CNT", "Newfoundlandin normaaliaika", "CDT", "Newfoundlandin kes\u00e4aika",  "America/St_Johns" },
    { "EST", "It\u00e4inen normaaliaika", "EST", "It\u00e4inen normaaliaika",  "America/Indianapolis" },
    { "CST", "Keskinen normaaliaika", "CDT", "Keskinen kes\u00e4aika",  "America/Chicago" },
    { "EET", "It\u00e4-Euroopan normaaliaika", "EEST", "It\u00e4-Euroopan kes\u00e4aika",  "Europe/Bucharest" },
    { "JST", "Japanin normaaliaika", "JST", "Japanin normaaliaika",  "Asia/Tokyo" },
    { "MST", "Kalliovuorten normaaliaika", "MST", "Kalliovuorten normaaliaika",  "America/Phoenix" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Timor-Leste");
        put("TK", "Tokelau");
        put("TJ", "Tad\u017eikistan");
        put("TH", "Thaimaa");
        put("TG", "Togo");
        put("TF", "Ranskan etel\u00e4iset alueet");
        put("GY", "Guyana");
        put("TD", "T\u0161ad");
        put("TC", "Turks- ja Caicossaaret");
        put("GW", "Guinea-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "Etel\u00e4-Georgia ja Etel\u00e4iset Sandwichsaaret");
        put("GR", "Kreikka");
        put("GQ", "P\u00e4iv\u00e4ntasaajan Guinea");
        put("GP", "Guadeloupe");
        put("SZ", "Swazimaa");
        put("SY", "Syyria");
        put("GN", "Guinea");
        put("GM", "Gambia");
        put("GL", "Gr\u00f6nlanti");
        put("SV", "El Salvador");
        put("ST", "S\u00e3o Tom\u00e9 ja Pr\u00edncipe");
        put("GI", "Gibraltar");
        put("GH", "Ghana");
        put("SR", "Suriname");
        put("GF", "Ranskan Guayana");
        put("SP", "Serbia");
        put("GE", "Georgia");
        put("SO", "Somalia");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Iso-Britannia");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Slovakia");
        put("SJ", "Huippuvuoret ja Jan Mayen");
        put("SI", "Slovenia");
        put("SH", "Saint Helena");
        put("SG", "Singapore");
        put("SE", "Ruotsi");
        put("SD", "Sudan");
        put("SC", "Seychellit");
        put("SB", "Salomonsaaret");
        put("SA", "Saudi-Arabia");
        put("FR", "Ranska");
        put("FO", "F\u00e4rsaaret");
        put("FM", "Mikronesia");
        put("RW", "Ruanda");
        put("FK", "Falklandinsaaret");
        put("RU", "Ven\u00e4j\u00e4");
        put("FJ", "Fid\u017ei");
        put("FI", "Suomi");
        put("RO", "Romania");
        put("RE", "R\u00e9union");
        put("ET", "Etiopia");
        put("ES", "Espanja");
        put("ER", "Eritrea");
        put("EH", "L\u00e4nsi-Sahara");
        put("EG", "Egypti");
        put("EE", "Viro");
        put("EC", "Ecuador");
        put("DZ", "Algeria");
        put("QA", "Qatar");
        put("DO", "Dominikaaninen tasavalta");
        put("PY", "Paraguay");
        put("DM", "Dominica");
        put("PW", "Palau");
        put("DK", "Tanska");
        put("DJ", "Djibouti");
        put("PT", "Portugali");
        put("PS", "Palestiina");
        put("PR", "Puerto Rico");
        put("DE", "Saksa");
        put("PN", "Pitcairn");
        put("PM", "Saint-Pierre ja Miquelon");
        put("PL", "Puola");
        put("PK", "Pakistan");
        put("PH", "Filippiinit");
        put("PG", "Papua-Uusi-Guinea");
        put("PF", "Ranskan Polynesia");
        put("CZ", "T\u0161ekki");
        put("PE", "Peru");
        put("CY", "Kypros");
        put("CX", "Joulusaari");
        put("CV", "Kap Verde");
        put("PA", "Panama");
        put("CU", "Kuuba");
        put("CR", "Costa Rica");
        put("CO", "Kolumbia");
        put("CN", "Kiina");
        put("CM", "Kamerun");
        put("CL", "Chile");
        put("CK", "Cookinsaaret");
        put("CI", "Norsunluurannikko");
        put("CH", "Sveitsi");
        put("CG", "Kongo");
        put("CF", "Keski-Afrikan tasavalta");
        put("CD", "Kongon demokraattinen tasavalta");
        put("CC", "Kookossaaret");
        put("OM", "Oman");
        put("CA", "Kanada");
        put("BZ", "Belize");
        put("BY", "Valko-Ven\u00e4j\u00e4");
        put("BW", "Botswana");
        put("BV", "Bouvet\u2019nsaari");
        put("BT", "Bhutan");
        put("BS", "Bahama");
        put("BR", "Brasilia");
        put("NZ", "Uusi-Seelanti");
        put("BO", "Bolivia");
        put("BN", "Brunei");
        put("BM", "Bermuda");
        put("NU", "Niue");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrain");
        put("NR", "Nauru");
        put("BG", "Bulgaria");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "Belgia");
        put("NO", "Norja");
        put("BD", "Bangladesh");
        put("BB", "Barbados");
        put("ZW", "Zimbabwe");
        put("NL", "Alankomaat");
        put("BA", "Bosnia ja Hertsegovina");
        put("NI", "Nicaragua");
        put("NG", "Nigeria");
        put("NF", "Norfolkinsaari");
        put("AZ", "Azerbaid\u017ean");
        put("NE", "Niger");
        put("NC", "Uusi-Kaledonia");
        put("AW", "Aruba");
        put("ZM", "Sambia");
        put("NA", "Namibia");
        put("AU", "Australia");
        put("AT", "It\u00e4valta");
        put("AS", "Amerikan Samoa");
        put("AR", "Argentiina");
        put("AQ", "Antarktis");
        put("MZ", "Mosambik");
        put("AO", "Angola");
        put("MY", "Malesia");
        put("AN", "Alankomaiden Antillit");
        put("MX", "Meksiko");
        put("AM", "Armenia");
        put("MW", "Malawi");
        put("AL", "Albania");
        put("MV", "Malediivit");
        put("ZA", "Etel\u00e4-Afrikka");
        put("MU", "Mauritius");
        put("MT", "Malta");
        put("AI", "Anguilla");
        put("MS", "Montserrat");
        put("MR", "Mauritania");
        put("AG", "Antigua ja Barbuda");
        put("MQ", "Martinique");
        put("AF", "Afganistan");
        put("MP", "Pohjois-Mariaanit");
        put("AE", "Arabiemiirikunnat");
        put("MO", "Macaon erityishallintoalue");
        put("AD", "Andorra");
        put("MN", "Mongolia");
        put("MM", "Myanmar");
        put("ML", "Mali");
        put("MK", "Makedonia");
        put("YU", "Jugoslavia");
        put("YT", "Mayotte");
        put("MH", "Marshallinsaaret");
        put("MG", "Madagaskar");
        put("MD", "Moldova");
        put("MC", "Monaco");
        put("MA", "Marokko");
        put("YE", "Jemen");
        put("LY", "Libya");
        put("LV", "Latvia");
        put("LU", "Luxemburg");
        put("LT", "Liettua");
        put("LS", "Lesotho");
        put("LR", "Liberia");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Saint Lucia");
        put("LB", "Libanon");
        put("LA", "Laos");
        put("KZ", "Kazakstan");
        put("KY", "Caymansaaret");
        put("KW", "Kuwait");
        put("KR", "Korean tasavalta");
        put("KP", "Pohjois-Korea");
        put("KN", "Saint Kitts ja Nevis");
        put("KM", "Komorit");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Kambod\u017ea");
        put("KG", "Kirgisia");
        put("KE", "Kenia");
        put("WF", "Wallis ja Futuna");
        put("JP", "Japani");
        put("JO", "Jordania");
        put("JM", "Jamaika");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "Yhdysvaltain Neitsytsaaret");
        put("VG", "Brittil\u00e4iset Neitsytsaaret");
        put("VE", "Venezuela");
        put("VC", "Saint Vincent ja Grenadiinit");
        put("VA", "Vatikaani");
        put("IT", "Italia");
        put("IS", "Islanti");
        put("IR", "Iran");
        put("IQ", "Irak");
        put("UZ", "Uzbekistan");
        put("IO", "Brittil\u00e4inen Intian valtameren alue");
        put("UY", "Uruguay");
        put("IN", "Intia");
        put("IL", "Israel");
        put("US", "Yhdysvallat");
        put("IE", "Irlanti");
        put("ID", "Indonesia");
        put("UM", "Yhdysvaltain pienet erillissaaret");
        put("UG", "Uganda");
        put("UA", "Ukraina");
        put("HU", "Unkari");
        put("HT", "Haiti");
        put("HR", "Kroatia");
        put("TZ", "Tansania");
        put("HN", "Honduras");
        put("HM", "Heard ja McDonaldinsaaret");
        put("TW", "Taiwan");
        put("TV", "Tuvalu");
        put("HK", "Hongkongin erityishallintoalue");
        put("TT", "Trinidad ja Tobago");
        put("TR", "Turkki");
        put("TO", "Tonga");
        put("TN", "Tunisia");
        put("TM", "Turkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("gwi", "gwit\u015fin");
        put("akk", "akkadi");
        put("eka", "ekajuk");
        put("xh", "kafferi");
        put("sux", "sumeri");
        put("sus", "susu");
        put("mis", "sekalaiset kielet");
        put("loz", "lozi");
        put("tog", "tonga");
        put("pon", "pohnpei");
        put("min", "minangkabau");
        put("suk", "sukuma");
        put("wo", "wolof");
        put("lol", "mongo");
        put("kut", "kutenai");
        put("mic", "micmac");
        put("wa", "valloni");
        put("kum", "kumukki");
        put("zap", "zapoteekki");
        put("cus", "muut kuusilaiset kielet");
        put("jbo", "lojba");
        put("doi", "dogri");
        put("vo", "volap\u00fck");
        put("oto", "otomangelaiset kielet");
        put("vi", "vietnam");
        put("rar", "rarotonga");
        put("ve", "venda");
        put("rap", "rapanui");
        put("raj", "rajasthani");
        put("ota", "osmani");
        put("nzi", "nzima");
        put("nap", "napolin italia");
        put("uz", "uzbekki");
        put("uga", "ugarit");
        put("tmh", "tama\u0161ek");
        put("nai", "muut Pohjois-Amerikan intiaanikielet");
        put("nah", "nahuatl");
        put("ur", "urdu");
        put("fat", "fanti");
        put("uk", "ukraina");
        put("egy", "muinaisegypti");
        put("ug", "uiguuri");
        put("fan", "fang");
        put("ssa", "muut nilosaharalaiset kielet");
        put("mga", "keski-iiri");
        put("bat", "muut balttilaiset kielet");
        put("nyo", "nyoro");
        put("bas", "basa");
        put("nyn", "nyankole");
        put("nym", "nyamwezi");
        put("hmn", "hmong");
        put("ban", "bali");
        put("osa", "osage");
        put("bal", "balut\u0161i");
        put("ty", "tahiti");
        put("bai", "bamileke");
        put("tw", "twi");
        put("srr", "serer");
        put("tli", "tlingit");
        put("tt", "tataari");
        put("ts", "tsonga");
        put("bad", "banda");
        put("tr", "turkki");
        put("to", "Tonga-saarten tonga");
        put("tn", "tswana");
        put("tl", "tagalog");
        put("tk", "turkmeeni");
        put("ti", "tigrinja");
        put("th", "thai");
        put("kru", "kurukh");
        put("tg", "tad\u017eikki");
        put("byn", "blin");
        put("te", "telugu");
        put("kro", "kru-kielet");
        put("csb", "kashubi");
        put("ta", "tamili");
        put("tkl", "tokelau");
        put("efi", "efik");
        put("sw", "suahili");
        put("sv", "ruotsi");
        put("su", "sunda");
        put("krc", "karachay-balkar");
        put("st", "etel\u00e4sotho");
        put("ss", "swazi");
        put("sr", "serbia");
        put("sq", "albania");
        put("men", "mende");
        put("crp", "muut kreolit ja pidginit");
        put("so", "somali");
        put("afh", "afrihili");
        put("sn", "shona");
        put("sm", "samoa");
        put("sl", "sloveeni");
        put("grc", "muinaiskreikka");
        put("sk", "slovakki");
        put("grb", "grebo");
        put("si", "singaleesi");
        put("sh", "serbokroatia");
        put("crh", "krimin turkki; krimin tataari");
        put("afa", "muut afroaasialaiset kielet");
        put("sg", "sango");
        put("se", "pohjoissaame");
        put("sd", "sindhi");
        put("udm", "udmurtti");
        put("sc", "sardi");
        put("sa", "sanskriitti");
        put("rw", "ruanda");
        put("ru", "ven\u00e4j\u00e4");
        put("mdr", "mandar");
        put("ro", "romania");
        put("rn", "rundi");
        put("rm", "retoromaani");
        put("mdf", "mok\u0161a");
        put("ady", "adyghe");
        put("zun", "zuni");
        put("kpe", "kpelle");
        put("qu", "ket\u0161ua");
        put("tig", "tigre");
        put("son", "songhai");
        put("cpp", "muut portugaliin perustuvat kreolit ja pidginit");
        put("sog", "sogdi");
        put("ada", "adangme");
        put("kos", "kosrae");
        put("hit", "heetti");
        put("cpf", "muut ranskaan perustuvat kreolit ja pidginit");
        put("cpe", "pidginenglanti");
        put("him", "himachali");
        put("kok", "konkani");
        put("hil", "ilongo");
        put("got", "gootti");
        put("gor", "gorontalo");
        put("gon", "gondi");
        put("din", "dinka");
        put("nub", "nuubialaiset kielet");
        put("pt", "portugali");
        put("ps", "pa\u0161to");
        put("fur", "friuli");
        put("phn", "foinikia");
        put("goh", "muinaisyl\u00e4saksa");
        put("snk", "soninke");
        put("cop", "kopti");
        put("yap", "jap");
        put("yao", "jao");
        put("phi", "muut filippiinil\u00e4iskielet");
        put("pl", "puola");
        put("ace", "aceh");
        put("pi", "pali");
        put("pa", "punjabi");
        put("bug", "bugi");
        put("iba", "iban");
        put("sms", "koltansaame");
        put("bua", "burjaatti");
        put("mas", "maasai");
        put("smn", "inarinsaame");
        put("os", "osseetti");
        put("map", "austronesia");
        put("or", "orija");
        put("man", "mandingo");
        put("smj", "luulajan saame");
        put("smi", "muut saamen kielet");
        put("mak", "makassar");
        put("om", "oromo");
        put("mai", "maithili");
        put("oj", "ojibwa");
        put("mag", "magahi");
        put("mad", "madura");
        put("sma", "etel\u00e4saame");
        put("oc", "oksitaani, provensaali");
        put("nso", "pedi");
        put("btk", "batakki");
        put("myv", "ers\u00e4");
        put("dgr", "dogrib");
        put("ny", "njand\u017ea, t\u0161ewa");
        put("myn", "maya");
        put("nv", "navaho");
        put("kmb", "kimbundu");
        put("nr", "etel\u00e4ndebele");
        put("gmh", "keskiyl\u00e4saksa");
        put("no", "norja");
        put("nn", "uusnorja");
        put("nl", "hollanti");
        put("ng", "ndonga");
        put("sla", "muut slaavilaiset kielet");
        put("ne", "nepali");
        put("nd", "pohjoisndebele");
        put("cmc", "t\u0161am");
        put("tet", "tetum");
        put("nb", "kirjanorja");
        put("na", "nauru");
        put("ter", "tereno");
        put("tem", "temne");
        put("my", "burma");
        put("lez", "lezgi");
        put("mt", "malta");
        put("peo", "muinaispersia");
        put("ms", "malaiji");
        put("mr", "marathi");
        put("fro", "muinaisranska");
        put("mo", "moldova");
        put("frm", "keskiranska");
        put("mn", "mongoli");
        put("jrb", "juutalaisarabia");
        put("ml", "malajalam");
        put("mk", "makedonia");
        put("mi", "maori");
        put("mh", "marshalli");
        put("mg", "malagasi");
        put("mwr", "marwari");
        put("bra", "brad\u017e");
        put("den", "slaavi");
        put("lv", "latvia");
        put("lu", "katangan luba");
        put("del", "delaware");
        put("lt", "liettua");
        put("lo", "lao");
        put("ln", "lingala");
        put("li", "limburgi");
        put("ewo", "ewondo");
        put("lg", "ganda");
        put("lb", "luxemburg");
        put("la", "latina");
        put("jpr", "juutalaispersia");
        put("vot", "vatja");
        put("sit", "muut sinotiibetil\u00e4iset kielet");
        put("ky", "kirgiisi");
        put("kw", "korni");
        put("kv", "komi");
        put("ku", "kurdi");
        put("sio", "siouxilaiset kielet");
        put("ks", "ka\u0161miri");
        put("kr", "kanuri");
        put("awa", "awadhi");
        put("ko", "korea");
        put("kn", "kannada");
        put("km", "khmer");
        put("kl", "gr\u00f6nlanti");
        put("kk", "kazakki");
        put("rom", "romani");
        put("kj", "kuanjama");
        put("sid", "sidamo");
        put("ki", "kikuju");
        put("kg", "kongo");
        put("non", "muinaisskandinaavi");
        put("ka", "georgia");
        put("mus", "muskogi");
        put("roa", "muut romaaniset kielet");
        put("nog", "nogai");
        put("mun", "mundakielet");
        put("mul", "monikielinen");
        put("jv", "jaava");
        put("gil", "kiribati");
        put("znd", "zande");
        put("shn", "\u0161an");
        put("fon", "fong");
        put("xal", "kalmukki");
        put("aus", "australialaiset kielet");
        put("kho", "khotani");
        put("ja", "japani");
        put("khi", "muut khoisankielet");
        put("pau", "palau");
        put("chy", "cheyenne");
        put("tai", "muut thaikielet");
        put("iu", "eskimo");
        put("pap", "papiamentu");
        put("it", "italia");
        put("sgn", "viittomakielet");
        put("is", "islanti");
        put("kha", "khasi");
        put("chr", "cherokee");
        put("pam", "pampanga");
        put("pal", "pahlavi");
        put("chp", "chipewya");
        put("io", "ido");
        put("cho", "choctaw");
        put("chn", "chinook");
        put("chm", "mari");
        put("tyv", "tuviini");
        put("bnt", "bantu");
        put("pag", "pangasinan");
        put("ik", "inupiak");
        put("chk", "truk");
        put("ii", "pohjois-ji");
        put("haw", "havaiji");
        put("lam", "lamba");
        put("ig", "igbo");
        put("chg", "t\u0161agatai");
        put("sga", "muinaisiiri");
        put("paa", "muut papualaiskielet");
        put("ie", "interlingue");
        put("id", "indonesia");
        put("lah", "lahnda");
        put("day", "dajakki");
        put("chb", "chibcha");
        put("ia", "interlingua");
        put("lad", "juutalaisespanja");
        put("hz", "herero");
        put("hai", "haida");
        put("dar", "dargva");
        put("hy", "armenia");
        put("ath", "athabasca-kielet");
        put("hu", "unkari");
        put("ht", "haiti");
        put("dak", "sioux");
        put("hr", "kroatia");
        put("ho", "hiri-motu");
        put("hi", "hindi");
        put("dyu", "djula");
        put("he", "heprea");
        put("ast", "astuuri");
        put("ha", "hausa");
        put("wen", "sorbi");
        put("gv", "manx");
        put("gu", "gud\u017earati");
        put("sem", "muut seemil\u00e4iset kielet");
        put("sel", "selkuppi");
        put("iro", "irokeesi");
        put("gn", "guarani");
        put("gl", "galicia");
        put("arw", "arawak");
        put("gez", "etiopia");
        put("art", "muut tekokielet");
        put("gd", "gaeli");
        put("ira", "iran");
        put("ga", "iiri");
        put("arp", "arapaho");
        put("arn", "araukaani");
        put("fy", "friisi");
        put("bla", "mustajalka");
        put("gem", "muut germaaniset kielet");
        put("ypk", "juppik-kielet");
        put("arc", "aramea");
        put("fr", "ranska");
        put("fo", "f\u00e4\u00e4ri");
        put("cel", "muut kelttil\u00e4iset kielet");
        put("fj", "fid\u017ei");
        put("fi", "suomi");
        put("ff", "fulani");
        put("tvl", "tuvalu");
        put("ceb", "sebuano");
        put("fa", "persia");
        put("eu", "baski");
        put("sco", "skotti");
        put("et", "eesti");
        put("es", "espanja");
        put("eo", "esperanto");
        put("en", "englanti");
        put("el", "kreikka");
        put("tut", "muut altailaiset kielet");
        put("niu", "niue");
        put("tup", "tupilaiset kielet");
        put("ee", "ewe");
        put("tum", "tumbuka");
        put("mos", "mosi");
        put("dz", "bhutani");
        put("nic", "muut nigeril\u00e4is-kongolaiset kielet");
        put("lus", "lushai");
        put("fiu", "muut suomalais-ugrilaiset kielet");
        put("dv", "malediivi");
        put("nia", "nias");
        put("moh", "mohawk");
        put("lun", "lunda");
        put("apa", "apassi");
        put("lui", "luiseno");
        put("hup", "hupa");
        put("bin", "bini");
        put("de", "saksa");
        put("lua", "luba");
        put("bik", "bicol");
        put("was", "washo");
        put("und", "m\u00e4\u00e4rittelem\u00e4t\u00f6n");
        put("war", "waray");
        put("da", "tanska");
        put("dum", "keskihollanti");
        put("wal", "walamo");
        put("mno", "manobo-kielet");
        put("wak", "wakasilaiset kielet");
        put("sat", "santali");
        put("cy", "kymri");
        put("sas", "sasak");
        put("kbd", "kabardi");
        put("cv", "t\u0161uvassi");
        put("cu", "kirkkoslaavi");
        put("mni", "manipuri");
        put("cs", "tsekki");
        put("sam", "l\u00e4nsiaramea");
        put("cr", "cree");
        put("sal", "sali\u0161");
        put("dua", "duala");
        put("co", "korsika");
        put("sai", "muut Etel\u00e4-Amerikan intiaanikielet");
        put("mnc", "mant\u0161u");
        put("sah", "jakuutti");
        put("kaw", "kavi");
        put("inh", "inguu\u0161i");
        put("gba", "gbaja");
        put("sad", "sandawe");
        put("ch", "chamorro");
        put("ine", "muut indoeurooppalaiset kielet");
        put("bho", "bhod\u017epuri");
        put("enm", "keskienglanti");
        put("kar", "karen");
        put("inc", "muut intialaiset kielet");
        put("ce", "t\u0161et\u0161eeni");
        put("gay", "gayo");
        put("ca", "katalaani");
        put("umb", "umbundu");
        put("syr", "syyria");
        put("kam", "kamba");
        put("tsi", "tsimshian");
        put("ang", "muinaisenglanti");
        put("kac", "d\u017eingpho");
        put("cau", "muut kaukasialaiset kielet");
        put("kab", "kabyyli");
        put("kaa", "karakalpakki");
        put("bs", "bosnia");
        put("car", "karib");
        put("br", "bretoni");
        put("bo", "tiibet");
        put("bn", "bengali");
        put("bm", "bambara");
        put("gaa", "ga");
        put("cai", "muut Keski-Amerikan intiaanikielet");
        put("bi", "bislama");
        put("bh", "bihari");
        put("bg", "bulgaria");
        put("be", "valkoven\u00e4j\u00e4");
        put("cad", "caddo");
        put("ba", "baski");
        put("zu", "zulu");
        put("zen", "zenaga");
        put("pro", "muinaisprovensaali");
        put("hsb", "yl\u00e4-sorbi");
        put("az", "azeri");
        put("ay", "aimara");
        put("av", "avaari");
        put("as", "assami");
        put("dsb", "ala-sorbi");
        put("ar", "arabia");
        put("ilo", "iloko");
        put("elx", "elami");
        put("zh", "kiina");
        put("an", "aragonia");
        put("pra", "prakriitit");
        put("am", "amhara");
        put("new", "newari");
        put("ak", "akan");
        put("za", "zhuang");
        put("af", "afrikaans");
        put("ae", "avesta");
        put("ab", "abhaasi");
        put("aa", "afar");
        put("yo", "joruba");
        put("alg", "algonkin-kielet");
        put("ale", "aleutti");
        put("mkh", "muut mon-khmer-kielet");
        put("yi", "jiddi");
        put("dra", "muut dravidakielet");
        put("ber", "berberi");
        put("nds", "alasaksa");
        put("bem", "bemba");
        put("bej", "bedauje");
        put("tpi", "tok-pisin");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "\u00a0" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "ampms", ampms },
    { "shortDateFormat", "d.M.yyyy" },
    { "mediumDateFormat", "d.M.yyyy" },
    { "longDateFormat", "d. MMMM'ta 'yyyy" },
    { "fullDateFormat", "d. MMMM'ta 'yyyy" },
    { "shortTimeFormat", "H.mm" },
    { "mediumTimeFormat", "H.mm.ss" },
    { "longTimeFormat", "H.mm.ss z" },
    { "fullTimeFormat", "H.mm.ss z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
