/* LocaleInformation_en.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_en extends ListResourceBundle
{
  private static final String collation_rules = 
  "<0<1<2<3<4<5<6<7<8<9<A,a<b,B<c,C<d,D<e,E<f,F<g,G<h,H<i,I<j,J<k,K" +
  "<l,L<m,M<n,N<o,O<p,P<q,Q<r,R<s,S<t,T<u,U<v,V<w,W<x,X<y,Y<z,Z";

  private static final String[] shortMonths = {
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
    null,
  };

  private static final String[] months = {
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "Sun",
    "Mon",
    "Tue",
    "Wed",
    "Thu",
    "Fri",
    "Sat",
  };

  private static final String[] weekdays = {
    null,
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  };

  private static final String[] ampms = { "AM", "PM" };

  private static final String[] eras = {
    "BC",
    "AD",
  };

  private static final String[][] zoneStrings =
  {
    { "PST", "Pacific Standard Time", "PDT", "Pacific Daylight Time",  "America/Los_Angeles" },
    { "HST", "Hawaii Standard Time", "HDT", "Hawaii Daylight Time",  "Pacific/Honolulu" },
    { "GMT", "Greenwich Mean Time", "GMT", "Greenwich Mean Time",  "Etc/GMT" },
    { "BST", "British Standard Time", "BDT", "British Daylight Time",  "Europe/London" },
    { "MST", "Mountain Standard Time", "MDT", "Mountain Daylight Time",  "America/Phoenix" },
    { "MST", "Mountain Standard Time", "MDT", "Mountain Daylight Time",  "America/Denver" },
    { "IST", "Israel Standard Time", "IDT", "Israel Daylight Time",  "Asia/Jerusalem" },
    { "MST (CA)", "Mountain Standard Time (CA)", "MDT (CA)", "Mountain Daylight Time (CA)",  "America/Edmonton" },
    { "AKST", "Alaska Standard Time", "AKDT", "Alaska Daylight Time",  "America/Anchorage" },
    { "CEST", "Central European Standard Time", "CEDT", "Central European Daylight Time",  "Europe/Paris" },
    { "EST", "Eastern Standard Time", "EDT", "Eastern Daylight Time",  "America/Indianapolis" },
    { "EET", "Eastern European Standard Time", "EEST", "Eastern European Daylight Time",  "Europe/Bucharest" },
    { "JST", "Japan Standard Time", "JDT", "Japan Daylight Time",  "Asia/Tokyo" },
    { "CST (CA)", "Central Standard Time (CA)", "CDT (CA)", "Central Daylight Time (CA)",  "America/Winnipeg" },
    { "CST", "China Standard Time", "CDT", "China Daylight Time",  "Asia/Shanghai" },
    { "PST (CA)", "Pacific Standard Time (CA)", "PDT (CA)", "Pacific Daylight Time (CA)",  "America/Vancouver" },
    { "EST", "Eastern Standard Time", "EDT", "Eastern Daylight Time",  "America/New_York" },
    { "EST (CA)", "Eastern Standard Time (CA)", "EDT (CA)", "Eastern Daylight Time (CA)",  "America/Montreal" },
    { "AST", "Atlantic Standard Time", "ADT", "Atlantic Daylight Time",  "America/Halifax" },
    { "NST", "Newfoundland Standard Time", "NDT", "Newfoundland Daylight Time",  "America/St_Johns" },
    { "CST", "Central Standard Time", "CDT", "Central Daylight Time",  "America/Chicago" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("GY", "Guyana");
        put("GW", "Guinea-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "South Georgia and the South Sandwich Islands");
        put("GR", "Greece");
        put("GQ", "Equatorial Guinea");
        put("GP", "Guadeloupe");
        put("GN", "Guinea");
        put("GM", "Gambia");
        put("GL", "Greenland");
        put("GI", "Gibraltar");
        put("GH", "Ghana");
        put("GF", "French Guiana");
        put("GE", "Georgia");
        put("GD", "Grenada");
        put("GB", "United Kingdom");
        put("GA", "Gabon");
        put("FX", "Metropolitan France");
        put("FR", "France");
        put("FQ", "French Southern and Antarctic Territories");
        put("FO", "Faroe Islands");
        put("FM", "Micronesia");
        put("FK", "Falkland Islands");
        put("FJ", "Fiji");
        put("FI", "Finland");
        put("ET", "Ethiopia");
        put("ES", "Spain");
        put("ER", "Eritrea");
        put("EH", "Western Sahara");
        put("EG", "Egypt");
        put("EE", "Estonia");
        put("EC", "Ecuador");
        put("DZ", "Algeria");
        put("DY", "Benin");
        put("DO", "Dominican Republic");
        put("DM", "Dominica");
        put("DK", "Denmark");
        put("DJ", "Djibouti");
        put("DE", "Germany");
        put("DD", "East Germany");
        put("CZ", "Czech Republic");
        put("CY", "Cyprus");
        put("CX", "Christmas Island");
        put("CV", "Cape Verde");
        put("CU", "Cuba");
        put("CT", "Canton and Enderbury Islands");
        put("CS", "Czechoslovakia");
        put("CR", "Costa Rica");
        put("CO", "Colombia");
        put("CN", "China");
        put("CM", "Cameroon");
        put("CL", "Chile");
        put("CK", "Cook Islands");
        put("CI", "C\u00f4te d\u2019Ivoire");
        put("CH", "Switzerland");
        put("CG", "Congo");
        put("CF", "Central African Republic");
        put("CD", "Democratic Republic of the Congo");
        put("CC", "Cocos (Keeling) Islands");
        put("CA", "Canada");
        put("BZ", "Belize");
        put("BY", "Belarus");
        put("BW", "Botswana");
        put("BV", "Bouvet Island");
        put("BU", "Myanmar");
        put("BT", "Bhutan");
        put("BS", "Bahamas");
        put("BR", "Brazil");
        put("BQ", "British Antarctic Territory");
        put("BO", "Bolivia");
        put("BN", "Brunei");
        put("BM", "Bermuda");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrain");
        put("BG", "Bulgaria");
        put("BF", "Burkina Faso");
        put("BE", "Belgium");
        put("BD", "Bangladesh");
        put("ZZ", "Outlying Oceania");
        put("BB", "Barbados");
        put("BA", "Bosnia and Herzegovina");
        put("ZW", "Zimbabwe");
        put("ZR", "Congo, The Democratic Republic of the");
        put("AZ", "Azerbaijan");
        put("AX", "Aland Islands");
        put("AW", "Aruba");
        put("ZM", "Zambia");
        put("AU", "Australia");
        put("AT", "Austria");
        put("AS", "American Samoa");
        put("AR", "Argentina");
        put("AQ", "Antarctica");
        put("AO", "Angola");
        put("AN", "Netherlands Antilles");
        put("AM", "Armenia");
        put("AL", "Albania");
        put("ZA", "South Africa");
        put("AI", "Anguilla");
        put("AG", "Antigua and Barbuda");
        put("AF", "Afghanistan");
        put("AE", "United Arab Emirates");
        put("AD", "Andorra");
        put("YU", "Serbia and Montenegro");
        put("YT", "Mayotte");
        put("YE", "Yemen");
        put("YD", "People's Democratic Republic of Yemen");
        put("172", "Commonwealth of Independent States");
        put("WS", "Samoa");
        put("WK", "Wake Island");
        put("WF", "Wallis and Futuna");
        put("155", "Western Europe");
        put("154", "Northern Europe");
        put("151", "Eastern Europe");
        put("150", "Europe");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "U.S. Virgin Islands");
        put("VG", "British Virgin Islands");
        put("VE", "Venezuela");
        put("145", "Western Asia");
        put("VD", "North Vietnam");
        put("VC", "Saint Vincent and the Grenadines");
        put("142", "Asia");
        put("VA", "Vatican");
        put("UZ", "Uzbekistan");
        put("UY", "Uruguay");
        put("US", "United States");
        put("UM", "United States Minor Outlying Islands");
        put("UG", "Uganda");
        put("UA", "Ukraine");
        put("TZ", "Tanzania");
        put("TW", "Taiwan");
        put("TV", "Tuvalu");
        put("TT", "Trinidad and Tobago");
        put("TR", "Turkey");
        put("TP", "Timor-Leste");
        put("TO", "Tonga");
        put("TN", "Tunisia");
        put("TM", "Turkmenistan");
        put("TL", "Timor-Leste");
        put("TK", "Tokelau");
        put("TJ", "Tajikistan");
        put("TH", "Thailand");
        put("TG", "Togo");
        put("TF", "French Southern Territories");
        put("TD", "Chad");
        put("TC", "Turks and Caicos Islands");
        put("SZ", "Swaziland");
        put("SY", "Syria");
        put("SV", "El Salvador");
        put("SU", "Union of Soviet Socialist Republics");
        put("ST", "Sao Tome and Principe");
        put("SR", "Suriname");
        put("SP", "Serbia");
        put("SO", "Somalia");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("SL", "Sierra Leone");
        put("SK", "Slovakia");
        put("SJ", "Svalbard and Jan Mayen");
        put("SI", "Slovenia");
        put("SH", "Saint Helena");
        put("SG", "Singapore");
        put("SE", "Sweden");
        put("SD", "Sudan");
        put("SC", "Seychelles");
        put("SB", "Solomon Islands");
        put("SA", "Saudi Arabia");
        put("RW", "Rwanda");
        put("RU", "Russia");
        put("RO", "Romania");
        put("RH", "Zimbabwe");
        put("RE", "R\u00e9union");
        put("062", "South-central Asia");
        put("061", "Polynesia");
        put("QA", "Qatar");
        put("057", "Micronesia");
        put("054", "Melanesia");
        put("PZ", "Panama Canal Zone");
        put("053", "Australia and New Zealand");
        put("PY", "Paraguay");
        put("PW", "Palau");
        put("PU", "U.S. Miscellaneous Pacific Islands");
        put("PT", "Portugal");
        put("PS", "Palestinian Territory");
        put("PR", "Puerto Rico");
        put("PN", "Pitcairn");
        put("PM", "Saint Pierre and Miquelon");
        put("PL", "Poland");
        put("PK", "Pakistan");
        put("PH", "Philippines");
        put("PG", "Papua New Guinea");
        put("PF", "French Polynesia");
        put("PE", "Peru");
        put("PC", "Pacific Islands Trust Territory");
        put("PA", "Panama");
        put("OM", "Oman");
        put("833", "Isle of Man");
        put("830", "Channel Islands");
        put("039", "Southern Europe");
        put("035", "South-eastern Asia");
        put("NZ", "New Zealand");
        put("030", "Eastern Asia");
        put("NU", "Niue");
        put("NT", "Neutral Zone");
        put("NR", "Nauru");
        put("NQ", "Dronning Maud Land");
        put("NP", "Nepal");
        put("NO", "Norway");
        put("NL", "Netherlands");
        put("NI", "Nicaragua");
        put("NH", "Vanuatu");
        put("NG", "Nigeria");
        put("NF", "Norfolk Island");
        put("NE", "Niger");
        put("NC", "New Caledonia");
        put("NA", "Namibia");
        put("029", "Caribbean");
        put("MZ", "Mozambique");
        put("MY", "Malaysia");
        put("MX", "Mexico");
        put("021", "Northern America");
        put("MW", "Malawi");
        put("MV", "Maldives");
        put("MU", "Mauritius");
        put("MT", "Malta");
        put("MS", "Montserrat");
        put("MR", "Mauritania");
        put("MQ", "Martinique");
        put("MP", "Northern Mariana Islands");
        put("MO", "Macao S.A.R., China");
        put("MN", "Mongolia");
        put("MM", "Myanmar");
        put("ML", "Mali");
        put("MK", "Macedonia");
        put("419", "Latin America and the Caribbean");
        put("MI", "Midway Islands");
        put("MH", "Marshall Islands");
        put("MG", "Madagascar");
        put("MD", "Moldova");
        put("MC", "Monaco");
        put("MA", "Morocco");
        put("019", "Americas");
        put("018", "Southern Africa");
        put("017", "Middle Africa");
        put("015", "Northern Africa");
        put("014", "Eastern Africa");
        put("013", "Central America");
        put("LY", "Libya");
        put("011", "Western Africa");
        put("LV", "Latvia");
        put("LU", "Luxembourg");
        put("LT", "Lithuania");
        put("LS", "Lesotho");
        put("LR", "Liberia");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Saint Lucia");
        put("LB", "Lebanon");
        put("LA", "Laos");
        put("009", "Oceania");
        put("005", "South America");
        put("KZ", "Kazakhstan");
        put("003", "North America");
        put("KY", "Cayman Islands");
        put("002", "Africa");
        put("001", "World");
        put("KW", "Kuwait");
        put("KR", "South Korea");
        put("KP", "North Korea");
        put("KN", "Saint Kitts and Nevis");
        put("KM", "Comoros");
        put("KI", "Kiribati");
        put("KH", "Cambodia");
        put("KG", "Kyrgyzstan");
        put("KE", "Kenya");
        put("JT", "Johnston Island");
        put("JP", "Japan");
        put("JO", "Jordan");
        put("JM", "Jamaica");
        put("IT", "Italy");
        put("IS", "Iceland");
        put("IR", "Iran");
        put("IQ", "Iraq");
        put("IO", "British Indian Ocean Territory");
        put("IN", "India");
        put("IL", "Israel");
        put("IE", "Ireland");
        put("ID", "Indonesia");
        put("HV", "Burkina Faso");
        put("HU", "Hungary");
        put("HT", "Haiti");
        put("HR", "Croatia");
        put("HN", "Honduras");
        put("HM", "Heard Island and McDonald Islands");
        put("HK", "Hong Kong S.A.R., China");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("gwi", "Gwich\u02bbin");
        put("akk", "Akkadian");
        put("eka", "Ekajuk");
        put("ijo", "Ijo");
        put("xh", "Xhosa");
        put("sux", "Sumerian");
        put("sus", "Susu");
        put("mis", "Miscellaneous Languages");
        put("loz", "Lozi");
        put("tog", "Tonga (Nyasa)");
        put("pon", "Pohnpeian");
        put("min", "Minangkabau");
        put("suk", "Sukuma");
        put("wo", "Wolof");
        put("lol", "Mongo");
        put("kut", "Kutenai");
        put("mic", "Micmac");
        put("wa", "Walloon");
        put("kum", "Kumyk");
        put("zap", "Zapotec");
        put("cus", "Cushitic (Other)");
        put("jbo", "Lojban");
        put("doi", "Dogri");
        put("vo", "Volap\u00fck");
        put("oto", "Otomian Languages");
        put("vi", "Vietnamese");
        put("vai", "Vai");
        put("rar", "Rarotongan");
        put("ve", "Venda");
        put("rap", "Rapanui");
        put("raj", "Rajasthani");
        put("ota", "Turkish, Ottoman (1500-1928)");
        put("nzi", "Nzima");
        put("nap", "Neapolitan");
        put("uz", "Uzbek");
        put("uga", "Ugaritic");
        put("tmh", "Tamashek");
        put("nai", "North American Indian (Other)");
        put("nah", "Nahuatl");
        put("ur", "Urdu");
        put("fat", "Fanti");
        put("uk", "Ukrainian");
        put("egy", "Egyptian (Ancient)");
        put("ug", "Uighur");
        put("fan", "Fang");
        put("ssa", "Nilo-Saharam (Other)");
        put("mga", "Irish, Middle (900-1200)");
        put("bat", "Baltic (Other)");
        put("nyo", "Nyoro");
        put("bas", "Basa");
        put("nyn", "Nyankole");
        put("nym", "Nyamwezi");
        put("hmn", "Hmong");
        put("ban", "Balinese");
        put("osa", "Osage");
        put("bal", "Baluchi");
        put("ty", "Tahitian");
        put("bai", "Bamileke Languages");
        put("tw", "Twi");
        put("srr", "Serer");
        put("tli", "Tlingit");
        put("tlh", "Klingon");
        put("tt", "Tatar");
        put("ts", "Tsonga");
        put("bad", "Banda");
        put("tr", "Turkish");
        put("to", "Tonga (Tonga Islands)");
        put("tn", "Tswana");
        put("tl", "Tagalog");
        put("tk", "Turkmen");
        put("ti", "Tigrinya");
        put("th", "Thai");
        put("kru", "Kurukh");
        put("tg", "Tajik");
        put("byn", "Blin");
        put("te", "Telugu");
        put("kro", "Kru");
        put("csb", "Kashubian");
        put("ta", "Tamil");
        put("tkl", "Tokelau");
        put("efi", "Efik");
        put("sw", "Swahili");
        put("sv", "Swedish");
        put("su", "Sundanese");
        put("krc", "Karachay-Balkar");
        put("st", "Sotho, Southern");
        put("ss", "Swati");
        put("sr", "Serbian");
        put("sq", "Albanian");
        put("men", "Mende");
        put("crp", "Creoles and Pidgins (Other)");
        put("so", "Somali");
        put("afh", "Afrihili");
        put("sn", "Shona");
        put("sm", "Samoan");
        put("sl", "Slovenian");
        put("grc", "Greek, Ancient (to 1453)");
        put("sk", "Slovak");
        put("grb", "Gerbo");
        put("si", "Sinhalese");
        put("sh", "Serbo-Croatian");
        put("crh", "Crimean Turkish; Crimean Tatar");
        put("afa", "Afro-Asiatic (Other)");
        put("sg", "Sango");
        put("se", "Northern Sami");
        put("sd", "Sindhi");
        put("udm", "Udmurt");
        put("sc", "Sardinian");
        put("sa", "Sanskrit");
        put("rw", "Kinyarwanda");
        put("nwc", "Classical Newari");
        put("ru", "Russian");
        put("mdr", "Mandar");
        put("ro", "Romanian");
        put("rn", "Rundi");
        put("rm", "Rhaeto-Romance");
        put("mdf", "Moksha");
        put("tiv", "Tiv");
        put("ady", "Adyghe");
        put("zun", "Zuni");
        put("kpe", "Kpelle");
        put("qu", "Quechua");
        put("tig", "Tigre");
        put("son", "Songhai");
        put("cpp", "Creoles and pidgins, Portuguese-based (Other)");
        put("sog", "Sogdien");
        put("ada", "Adangme");
        put("kos", "Kosraean");
        put("hit", "Hittite");
        put("cpf", "Creoles and Pidgins, French-based (Other)");
        put("cpe", "Creoles and Pidgins, English-based (Other)");
        put("him", "Himachali");
        put("kok", "Konkani");
        put("hil", "Hiligaynon");
        put("got", "Gothic");
        put("gor", "Gorontalo");
        put("gon", "Gondi");
        put("din", "Dinka");
        put("nub", "Nubian Languages");
        put("pt", "Portuguese");
        put("ps", "Pashto (Pushto)");
        put("fur", "Friulian");
        put("phn", "Phoenician");
        put("goh", "German, Old High (ca.750-1050)");
        put("snk", "Soninke");
        put("cop", "Coptic");
        put("yap", "Yapese");
        put("ach", "Acoli");
        put("yao", "Yao");
        put("phi", "Philippine (Other)");
        put("pl", "Polish");
        put("ace", "Achinese");
        put("pi", "Pali");
        put("pa", "Punjabi");
        put("bug", "Buginese");
        put("iba", "Iban");
        put("sms", "Skolt Sami");
        put("bua", "Buriat");
        put("mas", "Masai");
        put("smn", "Inari Sami");
        put("os", "Ossetic");
        put("map", "Austronesian");
        put("or", "Oriya");
        put("man", "Mandingo");
        put("smj", "Lule Sami");
        put("smi", "Sami languages (Other)");
        put("mak", "Makasar");
        put("om", "Oromo");
        put("mai", "Maithili");
        put("oj", "Ojibwa");
        put("mag", "Magahi");
        put("mad", "Madurese");
        put("sma", "Southern Sami");
        put("oc", "Occitan (post 1500); Proven\u00e7al");
        put("nso", "Sotho, Northern");
        put("btk", "Batak");
        put("myv", "Erzya");
        put("dgr", "Dogrib");
        put("ny", "Nyanja; Chichewa; Chewa");
        put("myn", "Mayan");
        put("nv", "Navajo");
        put("kmb", "Kimbundu");
        put("nr", "Ndebele, South");
        put("gmh", "German, Middle High (ca.1050-1500)");
        put("no", "Norwegian");
        put("nn", "Norwegian Nynorsk");
        put("nl", "Dutch");
        put("root", "Root");
        put("ng", "Ndonga");
        put("sla", "Slavic (Other)");
        put("ne", "Nepali");
        put("nd", "Ndebele, North");
        put("cmc", "Chamic Languages");
        put("tet", "Tetum");
        put("nb", "Norwegian Bokm\u00e5l");
        put("na", "Nauru");
        put("ter", "Tereno");
        put("tem", "Timne");
        put("my", "Burmese");
        put("lez", "Lezghian");
        put("mt", "Maltese");
        put("peo", "Persian Old (ca.600-400 B.C.)");
        put("ms", "Malay");
        put("mr", "Marathi");
        put("fro", "French, Old (842-ca.1400)");
        put("mo", "Moldavian");
        put("frm", "French, Middle (ca.1400-1600)");
        put("mn", "Mongolian");
        put("jrb", "Judeo-Arabic");
        put("ml", "Malayalam");
        put("mk", "Macedonian");
        put("mi", "Maori");
        put("mh", "Marshallese");
        put("mg", "Malagasy");
        put("mwr", "Marwari");
        put("bra", "Braj");
        put("mwl", "Mirandese");
        put("den", "Slave");
        put("lv", "Latvian");
        put("lu", "Luba-Katanga");
        put("del", "Delaware");
        put("lt", "Lithuanian");
        put("lo", "Lao");
        put("ln", "Lingala");
        put("li", "Limburgish");
        put("ewo", "Ewondo");
        put("lg", "Ganda");
        put("lb", "Luxembourgish");
        put("la", "Latin");
        put("jpr", "Judeo-Persian");
        put("vot", "Votic");
        put("sit", "Sino-Tibetan (Other)");
        put("ky", "Kirghiz");
        put("kw", "Cornish");
        put("kv", "Komi");
        put("ku", "Kurdish");
        put("sio", "Siouan Languages");
        put("ks", "Kashmiri");
        put("kr", "Kanuri");
        put("awa", "Awadhi");
        put("ko", "Korean");
        put("kn", "Kannada");
        put("km", "Khmer");
        put("kl", "Kalaallisut");
        put("kk", "Kazakh");
        put("rom", "Romany");
        put("kj", "Kuanyama");
        put("sid", "Sidamo");
        put("ki", "Kikuyu");
        put("kg", "Kongo");
        put("non", "Norse, Old");
        put("ka", "Georgian");
        put("mus", "Creek");
        put("roa", "Romance (Other)");
        put("nog", "Nogai");
        put("mun", "Munda Languages");
        put("mul", "Multiple Languages");
        put("jv", "Javanese");
        put("gil", "Gilbertese");
        put("znd", "Zande");
        put("shn", "Shan");
        put("fon", "Fon");
        put("ji", "Yiddish");
        put("xal", "Kalmyk");
        put("aus", "Australian Languages");
        put("kho", "Khotanese");
        put("ja", "Japanese");
        put("khi", "Khoisan (Other)");
        put("pau", "Palauan");
        put("chy", "Cheyenne");
        put("iw", "Hebrew");
        put("tai", "Tai (Other)");
        put("iu", "Inuktitut");
        put("pap", "Papiamento");
        put("it", "Italian");
        put("sgn", "Sign Languages");
        put("is", "Icelandic");
        put("kha", "Khasi");
        put("chr", "Cherokee");
        put("pam", "Pampanga");
        put("pal", "Pahlavi");
        put("chp", "Chipewyan");
        put("io", "Ido");
        put("cho", "Choctaw");
        put("in", "Indonesian");
        put("chn", "Chinook Jargon");
        put("chm", "Mari");
        put("tyv", "Tuvinian");
        put("bnt", "Bantu");
        put("pag", "Pangasinan");
        put("ik", "Inupiaq");
        put("chk", "Chuukese");
        put("ii", "Sichuan Yi");
        put("haw", "Hawaiian");
        put("lam", "Lamba");
        put("ig", "Igbo");
        put("chg", "Chagatai");
        put("sga", "Irish, Old (to 900)");
        put("paa", "Papuan (Other)");
        put("ie", "Interlingue");
        put("id", "Indonesian");
        put("lah", "Lahnda");
        put("day", "Dayak");
        put("chb", "Chibcha");
        put("ia", "Interlingua");
        put("lad", "Ladino");
        put("hz", "Herero");
        put("hai", "Haida");
        put("dar", "Dargwa");
        put("hy", "Armenian");
        put("ath", "Athapascan Languages");
        put("hu", "Hungarian");
        put("ht", "Haitian");
        put("dak", "Dakota");
        put("hr", "Croatian");
        put("ho", "Hiri Motu");
        put("hi", "Hindi");
        put("dyu", "Dyula");
        put("he", "Hebrew");
        put("ast", "Asturian");
        put("ha", "Hausa");
        put("wen", "Sorbian Languages");
        put("gv", "Manx");
        put("gu", "Gujarati");
        put("sem", "Semitic (Other)");
        put("sel", "Selkup");
        put("iro", "Iroquoian languages");
        put("gn", "Guarani");
        put("gl", "Gallegan");
        put("arw", "Arawak");
        put("gez", "Geez");
        put("art", "Artificial (Other)");
        put("gd", "Scottish Gaelic");
        put("ira", "Iranian");
        put("ga", "Irish");
        put("arp", "Arapaho");
        put("arn", "Araucanian");
        put("fy", "Frisian");
        put("bla", "Siksika");
        put("gem", "Germanic (Other)");
        put("ypk", "Yupik Languages");
        put("arc", "Aramaic");
        put("fr", "French");
        put("fo", "Faroese");
        put("cel", "Celtic (Other)");
        put("fj", "Fijian");
        put("fi", "Finnish");
        put("ff", "Fulah");
        put("tvl", "Tuvalu");
        put("ceb", "Cebuano");
        put("fa", "Persian");
        put("eu", "Basque");
        put("sco", "Scots");
        put("et", "Estonian");
        put("scn", "Sicilian");
        put("es", "Spanish");
        put("eo", "Esperanto");
        put("en", "English");
        put("el", "Greek");
        put("tut", "Altaic (Other)");
        put("niu", "Niuean");
        put("tup", "Tupi languages");
        put("ee", "Ewe");
        put("tum", "Tumbuka");
        put("mos", "Mossi");
        put("dz", "Dzongkha");
        put("nic", "Niger - Kordofanian (Other)");
        put("lus", "Lushai");
        put("fiu", "Finno - Ugrian (Other)");
        put("dv", "Divehi");
        put("nia", "Nias");
        put("moh", "Mohawk");
        put("luo", "Luo");
        put("lun", "Lunda");
        put("apa", "Apache Languages");
        put("fil", "Filipino");
        put("lui", "Luiseno");
        put("hup", "Hupa");
        put("bin", "Bini");
        put("de", "German");
        put("lua", "Luba-Lulua");
        put("bik", "Bikol");
        put("was", "Washo");
        put("und", "Undetermined");
        put("war", "Waray");
        put("da", "Danish");
        put("dum", "Dutch, Middle (ca. 1050-1350)");
        put("wal", "Walamo");
        put("mno", "Manobo Languages");
        put("wak", "Wakashan Languages");
        put("sat", "Santali");
        put("cy", "Welsh");
        put("sas", "Sasak");
        put("kbd", "Kabardian");
        put("cv", "Chuvash");
        put("cu", "Church Slavic");
        put("mni", "Manipuri");
        put("cs", "Czech");
        put("sam", "Samaritan Aramaic");
        put("cr", "Cree");
        put("sal", "Salishan languages");
        put("dua", "Duala");
        put("co", "Corsican");
        put("sai", "South American Indian (Other)");
        put("mnc", "Manchu");
        put("sah", "Yakut");
        put("kaw", "Kawi");
        put("inh", "Ingush");
        put("gba", "Gbaya");
        put("sad", "Sandawe");
        put("ch", "Chamorro");
        put("ine", "Indo-European (Other)");
        put("bho", "Bhojpuri");
        put("enm", "English, Middle (1100-1500)");
        put("kar", "Karen");
        put("inc", "Indic (Other)");
        put("ce", "Chechen");
        put("gay", "Gayo");
        put("ca", "Catalan");
        put("umb", "Umbundu");
        put("syr", "Syriac");
        put("kam", "Kamba");
        put("tsi", "Tsimshian");
        put("ang", "English, Old (ca.450-1100)");
        put("kac", "Kachin");
        put("cau", "Caucasian (Other)");
        put("kab", "Kabyle");
        put("kaa", "Kara-Kalpak");
        put("bs", "Bosnian");
        put("car", "Carib");
        put("br", "Breton");
        put("bo", "Tibetan");
        put("bn", "Bengali");
        put("bm", "Bambara");
        put("gaa", "Ga");
        put("cai", "Central American Indian (Other)");
        put("bi", "Bislama");
        put("bh", "Bihari");
        put("bg", "Bulgarian");
        put("be", "Belarusian");
        put("cad", "Caddo");
        put("ba", "Bashkir");
        put("zu", "Zulu");
        put("zen", "Zenaga");
        put("pro", "Proven\u00e7al, Old (to 1500)");
        put("hsb", "Upper Sorbian");
        put("az", "Azerbaijani");
        put("ay", "Aymara");
        put("av", "Avaric");
        put("as", "Assamese");
        put("dsb", "Lower Sorbian");
        put("ar", "Arabic");
        put("ilo", "Iloko");
        put("elx", "Elamite");
        put("zh", "Chinese");
        put("an", "Aragonese");
        put("pra", "Prakrit Languages");
        put("am", "Amharic");
        put("new", "Newari");
        put("ak", "Akan");
        put("za", "Zhuang");
        put("af", "Afrikaans");
        put("ae", "Avestan");
        put("alt", "Southern Altai");
        put("ab", "Abkhazian");
        put("aa", "Afar");
        put("yo", "Yoruba");
        put("alg", "Algonquian Languages");
        put("ale", "Aleut");
        put("mkh", "Mon-Khmer (Other)");
        put("yi", "Yiddish");
        put("dra", "Dravidian (Other)");
        put("ber", "Berber");
        put("nds", "Low German; Low Saxon");
        put("bem", "Bemba");
        put("bej", "Beja");
        put("tpi", "Tok Pisin");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final class Hashtablevariants extends java.util.Hashtable
  {
    public Hashtablevariants()
      {
        super();
        put("REVISED", "Revised Orthography");
        put("lojban", "Lojban");
        put("POSIX", "Computer");
        put("gaulish", "Gaulish");
        put("rozaj", "Resian");
        put("nedis", "Natisone dialect");
        put("boont", "Boontling");
        put("1996", "German orthography of 1996");
        put("guoyu", "Mandarin or Standard Chinese");
        put("hakka", "Hakka");
        put("xiang", "Xiang or Hunanese");
        put("1901", "Traditional German orthography");
        put("scouse", "Scouse");
      }
  }

  private static final Object variants = new Hashtablevariants();

  private static final Object[][] contents =
  {
    { "collation_rules", collation_rules },
    { "currencyFormat", "\u00a4#,##0.00;-\u00a4#,##0.00" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "ampms", ampms },
    { "eras", eras },
    { "shortDateFormat", "M/d/yy" },
    { "mediumDateFormat", "MMM d, yyyy" },
    { "localPatternChars", "GyMdkHmsSEDFwWahKz" },
    { "longDateFormat", "MMMM d, yyyy" },
    { "fullDateFormat", "EEEE, MMMM d, yyyy" },
    { "shortTimeFormat", "h:mm a" },
    { "mediumTimeFormat", "h:mm:ss a" },
    { "longTimeFormat", "h:mm:ss a z" },
    { "fullTimeFormat", "h:mm:ss a z" },
    { "zoneStrings", zoneStrings },
    { "decimalSeparator", "." },
    { "digit", "#" },
    { "exponential", "E" },
    { "groupingSeparator", "," },
    { "infinity", "\u221e" },
    { "NaN", "\ufffd" },
    { "minusSign", "-" },
    { "monetarySeparator", "." },
    { "patternSeparator", ";" },
    { "percent", "%" },
    { "perMill", "\u2030" },
    { "zeroDigit", "0" },
    { "numberFormat", "#,##0.###" },
    { "percentFormat", "#,##0%" },
    { "territories", territories },
    { "languages", languages },
    { "variants", variants },
  };

  public Object[][] getContents() { return contents; }
}
