/* LocaleInformation_sv.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_sv extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "jan",
    "feb",
    "mar",
    "apr",
    "maj",
    "jun",
    "jul",
    "aug",
    "sep",
    "okt",
    "nov",
    "dec",
    null,
  };

  private static final String[] months = {
    "januari",
    "februari",
    "mars",
    "april",
    "maj",
    "juni",
    "juli",
    "augusti",
    "september",
    "oktober",
    "november",
    "december",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "s\u00f6",
    "m\u00e5",
    "ti",
    "on",
    "to",
    "fr",
    "l\u00f6",
  };

  private static final String[] weekdays = {
    null,
    "s\u00f6ndag",
    "m\u00e5ndag",
    "tisdag",
    "onsdag",
    "torsdag",
    "fredag",
    "l\u00f6rdag",
  };

  private static final String[] eras = {
    "f.Kr.",
    "e.Kr.",
  };

  private static final String[] ampms = {
    "f.m.",
    "e.m.",
  };

  private static final String[][] zoneStrings =
  {
    { "PST", "Pacific, normaltid", "PDT", "Pacific, sommartid",  "America/Los_Angeles" },
    { "GMT", "Greenwichtid", "GMT", "Greenwichtid",  "Africa/Casablanca" },
    { "EST", "Eastern, normaltid", "EDT", "Eastern, sommartid",  "America/New_York" },
    { "AST", "Alaska, normaltid", "ADT", "Alaska, sommartid",  "America/Anchorage" },
    { "GMT", "Greenwichtid", "GMT", "Greenwichtid",  "Etc/GMT" },
    { "CTT", "Kina, normaltid", "CDT", "Kina, normaltid",  "Asia/Shanghai" },
    { "AST", "Atlantic, normaltid", "ADT", "Atlantic, sommartid",  "America/Halifax" },
    { "CET", "Centraleuropa, normaltid", "CEST", "Centraleuropa, sommartid",  "Europe/Paris" },
    { "MST", "Mountain, normaltid", "MDT", "Mountain, sommartid",  "America/Denver" },
    { "IST", "Israel, normaltid", "IDT", "Israel, sommartid",  "Asia/Jerusalem" },
    { "HST", "Hawaii, normaltid", "HST", "Hawaii, normaltid",  "Pacific/Honolulu" },
    { "CNT", "Newfoundland, normaltid", "CDT", "Newfoundland, sommartid",  "America/St_Johns" },
    { "EST", "Eastern, normaltid", "EST", "Eastern, normaltid",  "America/Indianapolis" },
    { "CST", "Central, normaltid", "CDT", "Central, sommartid",  "America/Chicago" },
    { "EET", "\u00d6steuropa, normaltid", "EEST", "\u00d6steuropa, sommartid",  "Europe/Bucharest" },
    { "JST", "Japan, normaltid", "JST", "Japan, normaltid",  "Asia/Tokyo" },
    { "MST", "Mountain, normaltid", "MST", "Mountain, sommartid",  "America/Phoenix" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "\u00d6sttimor");
        put("TK", "Tokelau\u00f6arna");
        put("TJ", "Tadzjikistan");
        put("TH", "Thailand");
        put("TG", "Togo");
        put("TF", "Franska Sydterritorierna");
        put("GY", "Guyana");
        put("TD", "Tchad");
        put("TC", "Turks- och Caicos\u00f6arna");
        put("GW", "Guinea-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "Sydgeorgien och S\u00f6dra Sandwich\u00f6arna");
        put("GR", "Grekland");
        put("GQ", "Ekvatorialguinea");
        put("GP", "Guadeloupe");
        put("SZ", "Swaziland");
        put("SY", "Syrien");
        put("GN", "Guinea");
        put("GM", "Gambia");
        put("GL", "Gr\u00f6nland");
        put("SV", "El Salvador");
        put("ST", "S\u00e3o Tom\u00e9 och Pr\u00edncipe");
        put("GI", "Gibraltar");
        put("GH", "Ghana");
        put("SR", "Surinam");
        put("GF", "Franska Guyana");
        put("SP", "Serbien");
        put("GE", "Georgien");
        put("SO", "Somalia");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Storbritannien");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Slovakien");
        put("SJ", "Svalbard och Jan Mayen");
        put("SI", "Slovenien");
        put("SH", "S:t Helena");
        put("SG", "Singapore");
        put("SE", "Sverige");
        put("SD", "Sudan");
        put("SC", "Seychellerna");
        put("SB", "Salomon\u00f6arna");
        put("SA", "Saudiarabien");
        put("FR", "Frankrike");
        put("FO", "F\u00e4r\u00f6arna");
        put("FM", "Mikronesien");
        put("RW", "Rwanda");
        put("FK", "Falklands\u00f6arna");
        put("RU", "Ryssland");
        put("FJ", "Fiji");
        put("FI", "Finland");
        put("RO", "Rum\u00e4nien");
        put("RE", "R\u00e9union");
        put("ET", "Etiopien");
        put("ES", "Spanien");
        put("ER", "Eritrea");
        put("EH", "V\u00e4stra Sahara");
        put("EG", "Egypten");
        put("EE", "Estland");
        put("EC", "Ecuador");
        put("DZ", "Algeriet");
        put("QA", "Qatar");
        put("DO", "Dominikanska republiken");
        put("PY", "Paraguay");
        put("DM", "Dominica");
        put("PW", "Palau");
        put("DK", "Danmark");
        put("DJ", "Djibouti");
        put("PT", "Portugal");
        put("PS", "Palestinska territoriet");
        put("PR", "Puerto Rico");
        put("DE", "Tyskland");
        put("PN", "Pitcairn");
        put("PM", "S:t Pierre och Miquelon");
        put("PL", "Polen");
        put("PK", "Pakistan");
        put("PH", "Filippinerna");
        put("PG", "Papua Nya Guinea");
        put("PF", "Franska Polynesien");
        put("CZ", "Tjeckien");
        put("PE", "Peru");
        put("CY", "Cypern");
        put("CX", "Jul\u00f6n");
        put("CV", "Kap Verde");
        put("PA", "Panama");
        put("CU", "Kuba");
        put("CR", "Costa Rica");
        put("CO", "Colombia");
        put("CN", "Kina");
        put("CM", "Kamerun");
        put("CL", "Chile");
        put("CK", "Cook\u00f6arna");
        put("CI", "Elfenbenskusten");
        put("CH", "Schweiz");
        put("CG", "Kongo-Brazzaville");
        put("CF", "Centralafrikanska republiken");
        put("CD", "Kongo-Kinshasa");
        put("CC", "Kokos\u00f6arna (Keeling\u00f6arna)");
        put("OM", "Oman");
        put("CA", "Kanada");
        put("BZ", "Belize");
        put("BY", "Vitryssland");
        put("BW", "Botswana");
        put("BV", "Bouvet\u00f6n");
        put("BT", "Bhutan");
        put("BS", "Bahamas");
        put("BR", "Brasilien");
        put("NZ", "Nya Zeeland");
        put("BO", "Bolivia");
        put("BN", "Brunei");
        put("BM", "Bermuda");
        put("NU", "Niue\u00f6n");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrain");
        put("NR", "Nauru");
        put("BG", "Bulgarien");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "Belgien");
        put("NO", "Norge");
        put("BD", "Bangladesh");
        put("BB", "Barbados");
        put("ZW", "Zimbabwe");
        put("NL", "Nederl\u00e4nderna");
        put("BA", "Bosnien och Hercegovina");
        put("NI", "Nicaragua");
        put("NG", "Nigeria");
        put("NF", "Norfolk\u00f6n");
        put("AZ", "Azerbajdzjan");
        put("NE", "Niger");
        put("NC", "Nya Kaledonien");
        put("AW", "Aruba");
        put("ZM", "Zambia");
        put("NA", "Namibia");
        put("AU", "Australien");
        put("AT", "\u00d6sterrike");
        put("AS", "Amerikanska Samoa");
        put("AR", "Argentina");
        put("AQ", "Antarktis");
        put("MZ", "Mo\u00e7ambique");
        put("AO", "Angola");
        put("MY", "Malaysia");
        put("AN", "Nederl\u00e4ndska Antillerna");
        put("MX", "Mexiko");
        put("AM", "Armenien");
        put("MW", "Malawi");
        put("AL", "Albanien");
        put("MV", "Maldiverna");
        put("ZA", "Sydafrika");
        put("MU", "Mauritius");
        put("MT", "Malta");
        put("AI", "Anguilla");
        put("MS", "Montserrat");
        put("MR", "Mauretanien");
        put("AG", "Antigua och Barbuda");
        put("MQ", "Martinique");
        put("AF", "Afghanistan");
        put("MP", "Nordmarianerna");
        put("AE", "F\u00f6renade Arabemiraten");
        put("MO", "Macao (S.A.R. Kina)");
        put("AD", "Andorra");
        put("MN", "Mongoliet");
        put("MM", "Myanmar");
        put("ML", "Mali");
        put("MK", "Makedonien");
        put("YU", "Jugoslavien");
        put("YT", "Mayotte");
        put("MH", "Marshall\u00f6arna");
        put("MG", "Madagaskar");
        put("MD", "Moldavien");
        put("MC", "Monaco");
        put("MA", "Marocko");
        put("YE", "Jemen");
        put("LY", "Libyen");
        put("LV", "Lettland");
        put("LU", "Luxemburg");
        put("LT", "Litauen");
        put("LS", "Lesotho");
        put("LR", "Liberia");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "S:t Lucia");
        put("LB", "Libanon");
        put("LA", "Laos");
        put("KZ", "Kazakstan");
        put("KY", "Cayman\u00f6arna");
        put("KW", "Kuwait");
        put("KR", "Sydkorea");
        put("KP", "Nordkorea");
        put("KN", "S:t Kitts och Nevis");
        put("KM", "Komorerna");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Kambodja");
        put("KG", "Kirgizistan");
        put("KE", "Kenya");
        put("WF", "Wallis- och Futuna\u00f6arna");
        put("JP", "Japan");
        put("JO", "Jordanien");
        put("JM", "Jamaica");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "Amerikanska Jungfru\u00f6arna");
        put("VG", "Brittiska Jungfru\u00f6arna");
        put("VE", "Venezuela");
        put("VC", "S:t Vincent och Grenadinerna");
        put("VA", "Vatikanstaten");
        put("IT", "Italien");
        put("IS", "Island");
        put("IR", "Iran");
        put("IQ", "Irak");
        put("UZ", "Uzbekistan");
        put("IO", "Brittiska Indiska ocean\u00f6arna");
        put("UY", "Uruguay");
        put("IN", "Indien");
        put("IL", "Israel");
        put("US", "USA");
        put("IE", "Irland");
        put("ID", "Indonesien");
        put("UM", "USAs yttre \u00f6ar");
        put("UG", "Uganda");
        put("UA", "Ukraina");
        put("HU", "Ungern");
        put("HT", "Haiti");
        put("HR", "Kroatien");
        put("TZ", "Tanzania");
        put("HN", "Honduras");
        put("HM", "Heard- och McDonald\u00f6arna");
        put("TW", "Taiwan");
        put("TV", "Tuvalu");
        put("HK", "Hongkong (S.A.R. Kina)");
        put("TT", "Trinidad och Tobago");
        put("TR", "Turkiet");
        put("TO", "Tonga");
        put("TN", "Tunisien");
        put("TM", "Turkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("gwi", "gwich\u02bbin");
        put("akk", "akkadiska");
        put("eka", "ekajuk");
        put("xh", "xhosa");
        put("sux", "sumeriska");
        put("sus", "susu");
        put("mis", "blandade spr\u00e5k");
        put("loz", "lozi");
        put("tog", "tonganska (Nyasa)");
        put("pon", "ponape");
        put("min", "minangkabau");
        put("suk", "sukuma");
        put("wo", "wolof");
        put("lol", "lolo; mongo");
        put("kut", "kutenai");
        put("mic", "mic-mac");
        put("wa", "walloon");
        put("kum", "kumyk");
        put("zap", "zapotek");
        put("cus", "kushitiska (annat)");
        put("jbo", "lojban");
        put("doi", "dogri");
        put("vo", "volap\u00fck");
        put("oto", "otomanguespr\u00e5k");
        put("vi", "vietnamesiska");
        put("rar", "rarotongan");
        put("ve", "venda");
        put("rap", "rapanui");
        put("raj", "rajasthani");
        put("ota", "ottomanturkiska (1500-1928)");
        put("nzi", "nzima");
        put("nap", "napolitanska");
        put("uz", "uzbekiska");
        put("uga", "ugaritiska");
        put("tmh", "tamashek");
        put("nai", "nordamerikanskt indianspr\u00e5k (annat)");
        put("nah", "nahuatl; aztekiska");
        put("ur", "urdu");
        put("fat", "fanti");
        put("uk", "ukrainska");
        put("egy", "fornegyptiska");
        put("ug", "uiguriska");
        put("fan", "fang");
        put("ssa", "nilosahariskt (annat)");
        put("mga", "medeliriska (900-1200)");
        put("bat", "baltiskt (annat)");
        put("nyo", "nyoro");
        put("bas", "basa");
        put("nyn", "nyankole");
        put("nym", "nyamwezi");
        put("hmn", "hmong");
        put("ban", "balinesiska");
        put("osa", "osage");
        put("bal", "baluchi");
        put("ty", "tahitiska");
        put("bai", "bamilekiska spr\u00e5k");
        put("tw", "twi");
        put("srr", "serer");
        put("tli", "tlingit");
        put("tt", "tatariska");
        put("ts", "tsonga");
        put("bad", "banda");
        put("tr", "turkiska");
        put("to", "tonganska");
        put("tn", "tswana");
        put("tl", "tagalog");
        put("tk", "turkmeniska");
        put("ti", "tigrinja");
        put("th", "thail\u00e4ndska");
        put("kru", "kurukh");
        put("tg", "tadzjikiska");
        put("byn", "blin");
        put("te", "telugu");
        put("kro", "kru");
        put("csb", "kasjubiska");
        put("ta", "tamil");
        put("tkl", "tokelauiska");
        put("efi", "efik");
        put("sw", "swahili");
        put("sv", "svenska");
        put("su", "sundanesiska");
        put("krc", "karachay-balkar");
        put("st", "syd\u00adsotho");
        put("ss", "swati");
        put("sr", "serbiska");
        put("sq", "albanska");
        put("men", "mende");
        put("crp", "kreolska och pidgin (annat)");
        put("so", "somaliska");
        put("afh", "afrihili");
        put("sn", "shona; manshona");
        put("sm", "samoanska");
        put("sl", "slovenska");
        put("grc", "forngrekiska (till 1453)");
        put("sk", "slovakiska");
        put("grb", "grebo");
        put("si", "singalesiska");
        put("sh", "serbokroatiska");
        put("crh", "krimturkiska; krimtatar");
        put("afa", "afro-asiatiskt (andra)");
        put("sg", "sango");
        put("se", "nord\u00adsamiska");
        put("sd", "sindhi");
        put("udm", "udmurtiska");
        put("sc", "sardiska");
        put("sa", "sanskrit");
        put("rw", "rwanda; kinjarwanda");
        put("ru", "ryska");
        put("mdr", "mandar");
        put("ro", "rum\u00e4nska");
        put("rn", "rundi");
        put("rm", "r\u00e4to\u00adromanska");
        put("mdf", "moksja");
        put("tiv", "tivi");
        put("ady", "adygeiska");
        put("zun", "zu\u00f1i");
        put("kpe", "kpelle");
        put("qu", "quechua");
        put("tig", "tigr\u00e9");
        put("son", "songhai");
        put("cpp", "kreolska och pidgin, portugisiskbaserade (\u00f6vriga)");
        put("sog", "sogdiska");
        put("ada", "adangme");
        put("kos", "kosreanska");
        put("hit", "hettitiska");
        put("cpf", "kreolska och pidgin, franskbaserade (\u00f6vriga)");
        put("cpe", "kreolska och pidgin, engelskbaserade (\u00f6vriga)");
        put("him", "himachali");
        put("kok", "konkani");
        put("hil", "hiligaynon");
        put("got", "gotiska");
        put("gor", "gorontalo");
        put("gon", "gondi");
        put("din", "dinka");
        put("nub", "nubiska spr\u00e5k");
        put("pt", "portugisiska");
        put("ps", "pashto; afghanska");
        put("fur", "friulianska");
        put("phn", "kananeiska; feniciska");
        put("goh", "fornh\u00f6gtyska (ca.750-1050)");
        put("snk", "soninke");
        put("cop", "koptiska");
        put("ach", "acholi");
        put("phi", "filippinskt spr\u00e5k (annat)");
        put("pl", "polska");
        put("ace", "achinese");
        put("pi", "pali");
        put("pa", "panjabi");
        put("bug", "buginesiska");
        put("iba", "iban");
        put("sms", "skoltsamiska");
        put("bua", "buriat");
        put("mas", "massajiska");
        put("smn", "enaresamiska");
        put("os", "ossetiska");
        put("map", "austronesiska");
        put("or", "oriya");
        put("man", "mande");
        put("smj", "lulesamiska");
        put("smi", "samiskt spr\u00e5k (annat)");
        put("mak", "makasar");
        put("om", "oromo");
        put("mai", "maithili");
        put("oj", "odjibwa; chippewa");
        put("mag", "magahi");
        put("mad", "madurese");
        put("sma", "sydsamiska");
        put("oc", "provensalska (efter 1500); occitanska");
        put("nso", "sotho, nord");
        put("btk", "batak");
        put("myv", "erjya");
        put("dgr", "dogrib");
        put("ny", "nyanja");
        put("myn", "maya");
        put("nv", "navaho");
        put("kmb", "kinbundu");
        put("nr", "syd\u00adndebele");
        put("gmh", "medelh\u00f6gtyska (ca.1050-1500)");
        put("no", "norska");
        put("nn", "ny\u00adnorsk");
        put("nl", "nederl\u00e4ndska");
        put("ng", "ndonga");
        put("sla", "slaviskt (annat)");
        put("ne", "nepalesisika");
        put("nd", "nord\u00adndebele");
        put("cmc", "chamispr\u00e5k");
        put("tet", "tetum");
        put("nb", "norskt bokm\u00e5l");
        put("na", "nauru");
        put("ter", "tereno");
        put("tem", "temne");
        put("my", "burmanska");
        put("lez", "lezghien");
        put("mt", "maltesiska");
        put("peo", "fornpersiska (ca 600-400 f.Kr.)");
        put("ms", "malajiska");
        put("mr", "marathi");
        put("fro", "fornfranska (842- ca 1400)");
        put("mo", "moldaviska");
        put("frm", "medelfranska (ca 1400-1600)");
        put("mn", "mongoliska");
        put("jrb", "judisk arabiska");
        put("ml", "malayalam");
        put("mk", "makedonska");
        put("mi", "maori");
        put("mh", "marshalliska");
        put("mg", "malagassiska");
        put("mwr", "marwari");
        put("bra", "braj");
        put("den", "slave");
        put("lv", "lettiska");
        put("lu", "luba-katanga");
        put("del", "delaware");
        put("lt", "litauiska");
        put("lo", "laotiska");
        put("ln", "lingala");
        put("li", "limburgiska");
        put("ewo", "ewondo");
        put("lg", "luganda");
        put("lb", "luxemburgiska");
        put("la", "latin");
        put("jpr", "judisk farsi");
        put("vot", "votiska");
        put("sit", "sinotibetanska spr\u00e5k");
        put("ky", "kirgisiska");
        put("kw", "korniska");
        put("kv", "kome");
        put("ku", "kurdiska");
        put("sio", "siouxspr\u00e5k");
        put("ks", "kashmiriska");
        put("kr", "kanuri");
        put("awa", "awadhi");
        put("ko", "koreanska");
        put("kn", "kanaresiska; kannada");
        put("km", "kambodjanska; khmeriska");
        put("kl", "gr\u00f6nl\u00e4ndska");
        put("kk", "kazakstanska");
        put("rom", "romani");
        put("kj", "kuanyama");
        put("sid", "sidamo");
        put("ki", "kikuyu");
        put("kg", "kikongo");
        put("non", "fornnordiska");
        put("ka", "georgiska");
        put("mus", "muskogee");
        put("roa", "romanskt (annat)");
        put("nog", "nogai");
        put("mun", "mundaspr\u00e5k");
        put("mul", "flera spr\u00e5k");
        put("jv", "javanesiska");
        put("gil", "gilbertesiska; kiribati");
        put("znd", "zand\u00e9");
        put("shn", "shan");
        put("xal", "kalmuckiska");
        put("aus", "australiska spr\u00e5k");
        put("kho", "khotanesiska");
        put("ja", "japanska");
        put("khi", "khoisan (annat)");
        put("pau", "palau");
        put("chy", "cheyenne");
        put("tai", "tai (annat)");
        put("iu", "inuktitut");
        put("pap", "papiamento");
        put("it", "italienska");
        put("sgn", "teckenspr\u00e5k");
        put("is", "isl\u00e4ndska");
        put("kha", "khasi");
        put("chr", "cherokesiska");
        put("pam", "pampanga");
        put("pal", "pahlavi");
        put("chp", "chipewyan");
        put("io", "ido");
        put("cho", "choctaw");
        put("chn", "chinook");
        put("chm", "mari");
        put("tyv", "tuviniska");
        put("bnt", "bantuspr\u00e5k");
        put("pag", "pangasinan");
        put("ik", "inupiaq");
        put("chk", "chuukesiska");
        put("ii", "sichuan yi");
        put("haw", "hawaiiska");
        put("lam", "lamba");
        put("ig", "ibo");
        put("chg", "chagatai");
        put("sga", "forniriska (till 900)");
        put("paa", "papuaspr\u00e5k (annat)");
        put("ie", "interlingue");
        put("id", "indonesiska");
        put("lah", "lahnda");
        put("day", "dayak");
        put("chb", "chibcha");
        put("ia", "interlingua");
        put("lad", "ladino");
        put("hz", "herero");
        put("hai", "haida");
        put("dar", "dargwa");
        put("hy", "armeniska");
        put("ath", "athapasiska spr\u00e5k");
        put("hu", "ungerska");
        put("ht", "haitiska");
        put("dak", "dakota");
        put("hr", "kroatiska");
        put("ho", "hiri motu");
        put("hi", "hindi");
        put("dyu", "dyula");
        put("he", "hebreiska");
        put("ast", "asturiska");
        put("ha", "haussa");
        put("wen", "sorbiska spr\u00e5k");
        put("gv", "manx gaeliska");
        put("gu", "gujarati");
        put("sem", "semitiskt (annat)");
        put("sel", "selkup");
        put("iro", "irokesiska");
        put("gn", "guaran\u00ed");
        put("gl", "galiciska");
        put("arw", "arawakiska");
        put("gez", "geez");
        put("art", "artificiellt (annat)");
        put("gd", "skotsk gaeliska");
        put("ira", "iranska");
        put("ga", "irl\u00e4ndsk gaeliska");
        put("arp", "arapaho");
        put("arn", "araukanska");
        put("fy", "frisiska");
        put("bla", "siksika");
        put("gem", "germanskt (annat)");
        put("ypk", "yupiska spr\u00e5k");
        put("arc", "arameiska");
        put("fr", "franska");
        put("fo", "f\u00e4r\u00f6iska");
        put("cel", "keltiskt (annat)");
        put("fj", "fidjianska");
        put("fi", "finska");
        put("ff", "fulani");
        put("tvl", "tuvaluanska");
        put("ceb", "cebuano");
        put("fa", "farsi");
        put("eu", "baskiska");
        put("sco", "skotska");
        put("et", "estniska");
        put("es", "spanska");
        put("eo", "esperanto");
        put("en", "engelska");
        put("el", "grekiska");
        put("tut", "altaiskt (annat)");
        put("niu", "niuean");
        put("tup", "tupispr\u00e5k");
        put("ee", "ewe");
        put("tum", "tumbuka");
        put("mos", "mossi");
        put("dz", "dzongkha");
        put("nic", "kordofanspr\u00e5k (annat)");
        put("lus", "lushai");
        put("fiu", "finskugriskt (annat)");
        put("dv", "divehi");
        put("nia", "nias");
        put("moh", "mohawk");
        put("lun", "lunda");
        put("apa", "apachespr\u00e5k");
        put("lui", "luise\u00f1o");
        put("hup", "hupa");
        put("bin", "bini");
        put("de", "tyska");
        put("lua", "luba-lulua");
        put("bik", "bikol");
        put("was", "washo");
        put("und", "obest\u00e4mt");
        put("war", "waray");
        put("da", "danska");
        put("dum", "medelnederl\u00e4ndska (ca 1050-1350)");
        put("wal", "walamo");
        put("mno", "manobospr\u00e5k");
        put("wak", "wakash");
        put("sat", "santali");
        put("cy", "walesiska");
        put("sas", "sasak");
        put("kbd", "kabardinska");
        put("cv", "tjuvasjiska");
        put("cu", "kyrkoslaviska");
        put("mni", "manipuri");
        put("cs", "tjeckiska");
        put("sam", "samariska");
        put("cr", "cree");
        put("sal", "salishspr\u00e5k");
        put("dua", "duala");
        put("co", "korsikanska");
        put("sai", "nordamerikanskt indianskt (annat)");
        put("mnc", "manchuriska");
        put("sah", "jakutiska");
        put("kaw", "kawi");
        put("inh", "ingusjiska");
        put("gba", "gbaya");
        put("sad", "sandawe");
        put("ch", "chamorro");
        put("ine", "indoeuropeiskt (annat)");
        put("bho", "bhojpuri");
        put("enm", "medelengelska (1100-1500)");
        put("kar", "karen");
        put("inc", "indiskt (annat)");
        put("ce", "tjetjenska");
        put("gay", "gayo");
        put("ca", "katalanska");
        put("umb", "umbundu");
        put("syr", "syriska");
        put("kam", "kamba");
        put("tsi", "tsimshian");
        put("ang", "fornengelska (ca 450-1100)");
        put("kac", "kachin");
        put("cau", "kaukasiskt (annat)");
        put("kab", "kabyliska");
        put("kaa", "karakalpakiska");
        put("bs", "bosniska");
        put("car", "karibiska");
        put("br", "bretonska");
        put("bo", "tibetanska");
        put("bn", "bengali");
        put("bm", "bambara");
        put("gaa", "ga");
        put("cai", "centralamerikanskt indianskt (annat)");
        put("bi", "bislama");
        put("bh", "bihari");
        put("bg", "bulgariska");
        put("be", "vitryska");
        put("cad", "caddo");
        put("ba", "basjkiriska");
        put("zu", "zulu");
        put("zen", "zenaga");
        put("pro", "fornprovensalska (till 1500)");
        put("hsb", "h\u00f6gsorbiska");
        put("az", "azerbajdzjanska");
        put("ay", "aymara");
        put("av", "avariska");
        put("as", "assami");
        put("dsb", "l\u00e5gsorbiska");
        put("ar", "arabiska");
        put("ilo", "iloko");
        put("elx", "elamitiska");
        put("zh", "kinesiska");
        put("an", "aragonesiska");
        put("pra", "prakrit");
        put("am", "amhariska");
        put("new", "newari");
        put("ak", "akan");
        put("za", "zhuang");
        put("af", "afrikaans");
        put("ae", "avestiska");
        put("ab", "abkhaziska");
        put("aa", "afar");
        put("yo", "yoruba");
        put("alg", "algonquinspr\u00e5k");
        put("ale", "aleutiska");
        put("mkh", "mon-khmeriska (annat)");
        put("yi", "jiddisch");
        put("dra", "dravidiskt (annat)");
        put("ber", "berber");
        put("nds", "l\u00e5gtyska; l\u00e5gsaxiska");
        put("bem", "bemba");
        put("bej", "beyja");
        put("tpi", "tok pisin");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final class Hashtablevariants extends java.util.Hashtable
  {
    public Hashtablevariants()
      {
        super();
        put("REVISED", "Reviderad");
      }
  }

  private static final Object variants = new Hashtablevariants();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "\u00a0" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "ampms", ampms },
    { "shortDateFormat", "yyyy-MM-dd" },
    { "mediumDateFormat", "yyyy-MM-dd" },
    { "longDateFormat", "'den 'd MMM yyyy" },
    { "fullDateFormat", "'den 'd MMMM yyyy" },
    { "shortTimeFormat", "HH.mm" },
    { "mediumTimeFormat", "HH.mm.ss" },
    { "longTimeFormat", "HH.mm.ss z" },
    { "fullTimeFormat", "'kl. 'HH.mm.ss z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
    { "variants", variants },
  };

  public Object[][] getContents() { return contents; }
}
