/* LocaleInformation_it.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_it extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "gen",
    "feb",
    "mar",
    "apr",
    "mag",
    "giu",
    "lug",
    "ago",
    "set",
    "ott",
    "nov",
    "dic",
    null,
  };

  private static final String[] months = {
    "gennaio",
    "febbraio",
    "marzo",
    "aprile",
    "maggio",
    "giugno",
    "luglio",
    "agosto",
    "settembre",
    "ottobre",
    "novembre",
    "dicembre",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "dom",
    "lun",
    "mar",
    "mer",
    "gio",
    "ven",
    "sab",
  };

  private static final String[] weekdays = {
    null,
    "domenica",
    "luned\u00ec",
    "marted\u00ec",
    "mercoled\u00ec",
    "gioved\u00ec",
    "venerd\u00ec",
    "sabato",
  };

  private static final String[] eras = {
    "aC",
    "dC",
  };

  private static final String[] ampms = {
    "m.",
    "p.",
  };

  private static final String[][] zoneStrings =
  {
    { "America/Los_Angeles", "Ora Standard Pacifico", "PST", "Ora Legale Pacifico", "PDT" },
    { "Africa/Casablanca", "Ora Meridiano Greenwich", "GMT", "Ora Meridiano Greenwich", "GMT" },
    { "America/New_York", "Ora Standard Orientale", "EST", "Ora Legale Orientale", "EDT" },
    { "America/Anchorage", "Ora Standard Alaska", "AST", "Ora Legale Alaska", "ADT" },
    { "Etc/GMT", "Ora Meridiano Greenwich", "GMT", "Ora Meridiano Greenwich", "GMT" },
    { "Asia/Shanghai", "Ora Standard Cina", "CTT", "Ora Standard Cina", "CDT" },
    { "America/Halifax", "Ora Standard Atlantico", "AST", "Ora Legale Atlantico", "ADT" },
    { "Europe/Paris", "Ora Standard Centrale Europeo", "CET", "Ora Legale Centrale Europeo", "CEST" },
    { "America/Denver", "Ora Standard Mountain", "MST", "Ora Legale Mountain", "MDT" },
    { "Asia/Jerusalem", "Ora Standard Israele", "IST", "Ora Legale Israele", "IDT" },
    { "Pacific/Honolulu", "Ora Standard Hawaii", "HST", "Ora Standard Hawaii", "HST" },
    { "America/St_Johns", "Ora Standard Newfoundland", "CNT", "Ora Legale Newfoundland", "CDT" },
    { "America/Indianapolis", "Ora Standard Orientale", "EST", "Ora Standard Orientale", "EST" },
    { "America/Chicago", "Ora Standard Centrale", "CST", "Ora Legale Centrale", "CDT" },
    { "Europe/Bucharest", "Ora Standard Europa Orientale", "EET", "Ora Legale Europa Orientale", "EEST" },
    { "Asia/Tokyo", "Ora Standard Giappone", "JST", "Ora Standard Giappone", "JST" },
    { "America/Phoenix", "Ora Standard Mountain", "MST", "Ora Standard Mountain", "MST" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Timor Est");
        put("TK", "Tokelau");
        put("TJ", "Tagikistan");
        put("TH", "Tailandia");
        put("TG", "Togo");
        put("TF", "Territori australi francesi");
        put("GY", "Guyana");
        put("TD", "Ciad");
        put("TC", "Isole Turks e Caicos");
        put("GW", "Guinea-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "Georgia del Sud e Isole Sandwich del Sud");
        put("GR", "Grecia");
        put("GQ", "Guinea Equatoriale");
        put("GP", "Guadalupa");
        put("SZ", "Swaziland");
        put("SY", "Siria");
        put("GN", "Guinea");
        put("GM", "Gambia");
        put("GL", "Groenlandia");
        put("SV", "El Salvador");
        put("ST", "S\u00e3o Tom\u00e9 e Pr\u00edncipe");
        put("GI", "Gibilterra");
        put("GH", "Ghana");
        put("SR", "Suriname");
        put("GF", "Guiana Francese");
        put("SP", "Serbia");
        put("GE", "Georgia");
        put("SO", "Somalia");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Regno Unito");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Slovacchia");
        put("SJ", "Svalbard e Jan Mayen");
        put("SI", "Slovenia");
        put("SH", "Sant\u2019Elena");
        put("SG", "Singapore");
        put("SE", "Svezia");
        put("SD", "Sudan");
        put("SC", "Seychelles");
        put("SB", "Isole Solomon");
        put("SA", "Arabia Saudita");
        put("FR", "Francia");
        put("FO", "Isole Faroe");
        put("FM", "Micronesia");
        put("RW", "Ruanda");
        put("FK", "Isole Falkland");
        put("RU", "Federazione Russa");
        put("FJ", "Fiji");
        put("FI", "Finlandia");
        put("RO", "Romania");
        put("RE", "R\u00e9union");
        put("ET", "Etiopia");
        put("ES", "Spagna");
        put("ER", "Eritrea");
        put("EH", "Sahara Occidentale");
        put("EG", "Egitto");
        put("EE", "Estonia");
        put("EC", "Ecuador");
        put("DZ", "Algeria");
        put("QA", "Qatar");
        put("DO", "Repubblica Dominicana");
        put("PY", "Paraguay");
        put("DM", "Dominica");
        put("PW", "Palau");
        put("DK", "Danimarca");
        put("DJ", "Gibuti");
        put("PT", "Portogallo");
        put("PS", "Palestina");
        put("PR", "Portorico");
        put("DE", "Germania");
        put("PN", "Pitcairn");
        put("PM", "Saint Pierre e Miquelon");
        put("PL", "Polonia");
        put("PK", "Pakistan");
        put("PH", "Filippine");
        put("PG", "Papua Nuova Guinea");
        put("PF", "Polinesia Francese");
        put("CZ", "Repubblica Ceca");
        put("PE", "Per\u00f9");
        put("CY", "Cipro");
        put("CX", "Isola Christmas");
        put("CV", "Capo Verde");
        put("PA", "Panama");
        put("CU", "Cuba");
        put("CR", "Costa Rica");
        put("CO", "Colombia");
        put("CN", "Cina");
        put("CM", "Camerun");
        put("CL", "Cile");
        put("CK", "Isole Cook");
        put("CI", "Costa d\u2019Avorio");
        put("CH", "Svizzera");
        put("CG", "Congo");
        put("CF", "Repubblica Centrafricana");
        put("CD", "Repubblica Democratica del Congo");
        put("CC", "Isole Cocos (Keeling)");
        put("OM", "Oman");
        put("CA", "Canada");
        put("BZ", "Belize");
        put("BY", "Bielorussia");
        put("BW", "Botswana");
        put("BV", "Isola Bouvet");
        put("BT", "Bhutan");
        put("BS", "Bahamas");
        put("BR", "Brasile");
        put("NZ", "Nuova Zelanda");
        put("BO", "Bolivia");
        put("BN", "Brunei");
        put("BM", "Bermuda");
        put("NU", "Niue");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrein");
        put("NR", "Nauru");
        put("BG", "Bulgaria");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "Belgio");
        put("NO", "Norvegia");
        put("BD", "Bangladesh");
        put("BB", "Barbados");
        put("ZW", "Zimbabwe");
        put("NL", "Paesi Bassi");
        put("BA", "Bosnia Erzegovina");
        put("NI", "Nicaragua");
        put("NG", "Nigeria");
        put("NF", "Isola Norfolk");
        put("AZ", "Azerbaigian");
        put("NE", "Niger");
        put("NC", "Nuova Caledonia");
        put("AW", "Aruba");
        put("ZM", "Zambia");
        put("NA", "Namibia");
        put("AU", "Australia");
        put("AT", "Austria");
        put("AS", "Samoa Americane");
        put("AR", "Argentina");
        put("AQ", "Antartide");
        put("MZ", "Mozambico");
        put("AO", "Angola");
        put("MY", "Malesia");
        put("AN", "Antille Olandesi");
        put("MX", "Messico");
        put("AM", "Armenia");
        put("MW", "Malawi");
        put("AL", "Albania");
        put("MV", "Maldive");
        put("ZA", "Sud Africa");
        put("MU", "Mauritius");
        put("MT", "Malta");
        put("AI", "Anguilla");
        put("MS", "Montserrat");
        put("MR", "Mauritania");
        put("AG", "Antigua e Barbuda");
        put("MQ", "Martinica");
        put("AF", "Afghanistan");
        put("MP", "Isole Marianne Settentrionali");
        put("AE", "Emirati Arabi Uniti");
        put("MO", "Regione Amministrativa Speciale di Macao, Cina");
        put("AD", "Andorra");
        put("MN", "Mongolia");
        put("MM", "Myanmar");
        put("ML", "Mali");
        put("MK", "Macedonia, Repubblica");
        put("YU", "Yugoslavia");
        put("YT", "Mayotte");
        put("MH", "Isole Marshall");
        put("MG", "Madagascar");
        put("MD", "Moldavia");
        put("MC", "Monaco");
        put("MA", "Marocco");
        put("YE", "Yemen");
        put("LY", "Libia");
        put("LV", "Lettonia");
        put("LU", "Lussemburgo");
        put("LT", "Lituania");
        put("LS", "Lesotho");
        put("LR", "Liberia");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Saint Lucia");
        put("LB", "Libano");
        put("LA", "Laos");
        put("KZ", "Kazakistan");
        put("KY", "Isole Cayman");
        put("KW", "Kuwait");
        put("KR", "Corea del Sud");
        put("KP", "Corea del Nord");
        put("KN", "Saint Kitts e Nevis");
        put("KM", "Comore");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Cambogia");
        put("KG", "Kirghizistan");
        put("KE", "Kenya");
        put("WF", "Wallis e Futuna");
        put("JP", "Giappone");
        put("JO", "Giordania");
        put("JM", "Giamaica");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "Isole Vergini Americane");
        put("VG", "Isole Vergini Britanniche");
        put("VE", "Venezuela");
        put("VC", "Saint Vincent e Grenadines");
        put("VA", "Vaticano");
        put("IT", "Italia");
        put("IS", "Islanda");
        put("IR", "Iran");
        put("IQ", "Iraq");
        put("UZ", "Uzbekistan");
        put("IO", "Territorio Britannico dell\u2019Oceano Indiano");
        put("UY", "Uruguay");
        put("IN", "India");
        put("IL", "Israele");
        put("US", "Stati Uniti");
        put("IE", "Irlanda");
        put("ID", "Indonesia");
        put("UM", "Isole Minori lontane dagli Stati Uniti");
        put("UG", "Uganda");
        put("UA", "Ucraina");
        put("HU", "Ungheria");
        put("HT", "Haiti");
        put("HR", "Croazia");
        put("TZ", "Tanzania");
        put("HN", "Honduras");
        put("HM", "Isole Heard ed Isole McDonald");
        put("TW", "Taiwan");
        put("TV", "Tuvalu");
        put("HK", "Regione Amministrativa Speciale di Hong Kong, Cina");
        put("TT", "Trinidad e Tobago");
        put("TR", "Turchia");
        put("TO", "Tonga");
        put("TN", "Tunisia");
        put("TM", "Turkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("gwi", "gwich\u02bbin");
        put("akk", "accado");
        put("eka", "ekajuka");
        put("xh", "xosa");
        put("sux", "sumero");
        put("sus", "susu");
        put("mis", "lingue diverse");
        put("loz", "lozi");
        put("tog", "tonga (nyasa)");
        put("pon", "ponape");
        put("min", "menangkabau");
        put("suk", "sukuma");
        put("wo", "volof");
        put("lol", "lolo (bantu)");
        put("kut", "kutenai");
        put("mic", "micmac");
        put("wa", "walloon");
        put("kum", "kumyk");
        put("zap", "zapotec");
        put("cus", "cuscitica (altra lingua)");
        put("jbo", "lojban");
        put("doi", "dogri");
        put("vo", "volap\u00fck");
        put("oto", "lingue otomi");
        put("vi", "vietnamita");
        put("rar", "rarotonga");
        put("ve", "venda");
        put("rap", "rapanui");
        put("raj", "rajasthani");
        put("ota", "turco ottomano (1500-1928)");
        put("nzi", "nzima");
        put("nap", "napoletano");
        put("uz", "usbeco");
        put("uga", "ugaritico");
        put("tmh", "tamashek");
        put("nai", "indiano del Nord America (altra lingua)");
        put("nah", "nahuatl");
        put("ur", "urdu");
        put("fat", "fanti");
        put("uk", "ucraino");
        put("egy", "egiziano (antico)");
        put("ug", "uigurico");
        put("ssa", "nilo-sahariana (altra lingua)");
        put("mga", "irlandese medio (900-1200)");
        put("bat", "baltica (altra lingua)");
        put("nyo", "nyoro");
        put("bas", "basa");
        put("nyn", "nyankole");
        put("nym", "nyamwezi");
        put("hmn", "hmong");
        put("ban", "balinese");
        put("osa", "osage");
        put("bal", "beluci");
        put("ty", "taitiano");
        put("bai", "lingue bamileke");
        put("tw", "ci");
        put("srr", "serer");
        put("tli", "tlingit");
        put("tt", "tatarico");
        put("ts", "tsonga");
        put("bad", "banda");
        put("tr", "turco");
        put("to", "tonga (Isole Tonga)");
        put("tn", "tswana");
        put("tl", "tagalog");
        put("tk", "turcomanno");
        put("ti", "tigrinya");
        put("th", "thai");
        put("kru", "kurukh");
        put("tg", "tagicco");
        put("byn", "blin");
        put("te", "telugu");
        put("kro", "kru");
        put("csb", "kashubian");
        put("ta", "tamil");
        put("tkl", "tokelau");
        put("efi", "efik");
        put("sw", "swahili");
        put("sv", "svedese");
        put("su", "sundanese");
        put("krc", "karachay-Balkar");
        put("st", "sotho del sud");
        put("ss", "swati");
        put("sr", "serbo");
        put("sq", "albanese");
        put("men", "mende");
        put("crp", "creola e Pidgins (altra lingua)");
        put("so", "somalo");
        put("afh", "afrihili");
        put("sn", "shona");
        put("sm", "samoano");
        put("sl", "sloveno");
        put("grc", "greco, antico (fino al 1453)");
        put("sk", "slovacco");
        put("grb", "gerbo");
        put("si", "singalese");
        put("sh", "serbo-croato");
        put("crh", "turco crimeo; tatar crimeo");
        put("afa", "afro-asiatica (altra lingua)");
        put("sg", "sango");
        put("se", "sami del nord");
        put("sd", "sindhi");
        put("udm", "udmurt");
        put("sc", "sardo");
        put("sa", "sanscrito");
        put("rw", "kinyarwanda");
        put("ru", "russo");
        put("mdr", "mandar");
        put("ro", "romeno");
        put("rn", "rundi");
        put("rm", "lingua rhaeto-romance");
        put("mdf", "moksha");
        put("ady", "adyghe");
        put("zun", "zuni");
        put("kpe", "kpelle");
        put("qu", "quechua");
        put("tig", "tigre");
        put("son", "songhai");
        put("cpp", "creolo e pidgins, basato sul portoghese (altra lingua)");
        put("sog", "sogdiano");
        put("ada", "adangme");
        put("kos", "Kosraean");
        put("hit", "hittite");
        put("cpf", "creolo e pidgins, basato sul francese (altra lingua)");
        put("cpe", "creolo e pidgins, basato sull\u2019inglese (altra lingua)");
        put("him", "himachali");
        put("kok", "konkani");
        put("hil", "hiligayna");
        put("got", "gotico");
        put("gor", "gorontalo");
        put("gon", "gondi");
        put("din", "dinca");
        put("nub", "nubiano");
        put("pt", "portoghese");
        put("ps", "pashto");
        put("fur", "friulano");
        put("phn", "fenicio");
        put("goh", "tedesco, antico alto (ca.750-1050)");
        put("snk", "soninke");
        put("cop", "copto");
        put("yap", "Yapese");
        put("ach", "acioli");
        put("yao", "yao (bantu)");
        put("phi", "filippino (altra lingua)");
        put("pl", "polacco");
        put("ace", "accinese");
        put("pi", "pali");
        put("pa", "punjabi");
        put("bug", "bugi");
        put("iba", "iban");
        put("sms", "sami skolt");
        put("bua", "buriat");
        put("mas", "masai");
        put("smn", "sami inari");
        put("os", "ossetico");
        put("map", "austronesiano");
        put("or", "oriya");
        put("man", "mandingo");
        put("smj", "sami lule");
        put("smi", "lingue sami (altra lingua)");
        put("mak", "makasar");
        put("om", "oromo");
        put("mai", "maithili");
        put("oj", "ojibwa");
        put("mag", "magahi");
        put("mad", "madurese");
        put("sma", "sami del sud");
        put("oc", "occitano (post 1500); provenzale");
        put("nso", "sotho del nord");
        put("btk", "batak");
        put("myv", "erzya");
        put("dgr", "dogrib");
        put("ny", "nyanja; chichewa; chewa");
        put("myn", "lingue maya");
        put("nv", "navajo");
        put("kmb", "kimbundu");
        put("nr", "ndebele del sud");
        put("gmh", "tedesco, medio alto (ca.1050-1500)");
        put("no", "norvegese");
        put("nn", "norvegese nynorsk");
        put("nl", "olandese");
        put("ng", "ndonga");
        put("sla", "slavo (altra lingua)");
        put("ne", "nepali");
        put("nd", "ndebele del nord");
        put("cmc", "lingue chamic");
        put("tet", "tetum");
        put("nb", "norvegese bokm\u00e5l");
        put("na", "nauru");
        put("ter", "tereno");
        put("tem", "temne");
        put("my", "burmese");
        put("lez", "lezghian");
        put("mt", "maltese");
        put("peo", "antico persiano (600-400 A.C.)");
        put("ms", "malay");
        put("mr", "marathi");
        put("fro", "francese, antico (842-ca.1400)");
        put("mo", "moldavo");
        put("frm", "francese, medio (ca.1400-1600)");
        put("mn", "mongolo");
        put("jrb", "giudeo arabo");
        put("ml", "malayalam");
        put("mk", "macedone");
        put("mi", "maori");
        put("mh", "marshallese");
        put("mg", "malagasy");
        put("mwr", "marwari");
        put("bra", "braj");
        put("den", "slave");
        put("lv", "lettone");
        put("lu", "luba-katanga");
        put("del", "delaware");
        put("lt", "lituano");
        put("lo", "lao");
        put("ln", "lingala");
        put("li", "limburgish");
        put("ewo", "ewondo");
        put("lg", "ganda");
        put("lb", "lussemburghese");
        put("la", "latino");
        put("jpr", "giudeo persiano");
        put("vot", "voto");
        put("sit", "sino-tibetano (altra lingua)");
        put("ky", "kirghiso");
        put("kw", "cornico");
        put("kv", "komi");
        put("ku", "curdo");
        put("sio", "lingue sioux");
        put("ks", "kashmiri");
        put("kr", "kanuri");
        put("awa", "awadhi");
        put("ko", "coreano");
        put("kn", "kannada");
        put("km", "khmer");
        put("kl", "kalaallisut");
        put("kk", "kazako");
        put("rom", "romani");
        put("kj", "kuanyama");
        put("sid", "sidamo");
        put("ki", "kikuyu");
        put("kg", "kongo");
        put("non", "norse antico");
        put("ka", "georgiano");
        put("mus", "creek");
        put("roa", "lingua romanza (altra lingua)");
        put("nog", "nogai");
        put("mun", "munda (altra lingua)");
        put("mul", "multilingua");
        put("jv", "giavanese");
        put("gil", "gilbertese");
        put("znd", "zande");
        put("shn", "shan");
        put("xal", "kalmyk");
        put("aus", "lingue australiane");
        put("kho", "khotanese");
        put("ja", "giapponese");
        put("khi", "khoisan (altra lingua)");
        put("pau", "palau");
        put("chy", "cheyenne");
        put("tai", "tailandese (altra lingua)");
        put("iu", "inuktitut");
        put("pap", "papiamento");
        put("it", "italiano");
        put("sgn", "lingue sign");
        put("is", "islandese");
        put("kha", "khasi");
        put("chr", "cherokee");
        put("pam", "pampanga");
        put("pal", "pahlavi");
        put("chp", "chipewyan");
        put("io", "ido");
        put("cho", "choctaw");
        put("chn", "gergo chinook");
        put("chm", "mari");
        put("tyv", "tuvinian");
        put("bnt", "bantu");
        put("pag", "pangasinan");
        put("ik", "inupiak");
        put("chk", "chuukese");
        put("ii", "sichuan yi");
        put("haw", "hawaiano");
        put("lam", "lamba");
        put("ig", "igbo");
        put("chg", "ciagataico");
        put("sga", "irlandese, antico (fino al \u2019900)");
        put("paa", "papuano-australiano (altra lingua)");
        put("ie", "interlingue");
        put("id", "indonesiano");
        put("lah", "lahnda");
        put("day", "dayak");
        put("chb", "chibcha");
        put("ia", "interlingua");
        put("lad", "ladino");
        put("hz", "herero");
        put("hai", "haida");
        put("dar", "dargwa");
        put("hy", "armeno");
        put("ath", "lingue athabaska");
        put("hu", "ungherese");
        put("ht", "haitian");
        put("dak", "dakota");
        put("hr", "croato");
        put("ho", "hiri motu");
        put("hi", "hindi");
        put("dyu", "diula");
        put("he", "ebraico");
        put("ast", "asturiano");
        put("ha", "haussa");
        put("wen", "sorabo");
        put("gv", "manx");
        put("gu", "gujarati");
        put("sem", "semitico (altra lingua)");
        put("sel", "selkup");
        put("iro", "lingue irochesi");
        put("gn", "guarana");
        put("gl", "galiziano");
        put("arw", "aruaco");
        put("gez", "geez");
        put("art", "artificiale (altra lingua)");
        put("gd", "gaelico scozzese");
        put("ira", "iraniana");
        put("ga", "irlandese");
        put("arp", "arapaho");
        put("arn", "araucano");
        put("fy", "frisone");
        put("bla", "siksika");
        put("gem", "germanica (altra lingua)");
        put("ypk", "lingue yupik");
        put("arc", "aramaico");
        put("fr", "francese");
        put("fo", "faroese");
        put("cel", "celtica altra lingua");
        put("fj", "figiano");
        put("fi", "finlandese");
        put("ff", "fulah");
        put("tvl", "tuvalu");
        put("ceb", "cebuano");
        put("fa", "persiano");
        put("eu", "basco");
        put("sco", "scozzese");
        put("et", "estone");
        put("es", "spagnolo");
        put("eo", "esperanto");
        put("en", "inglese");
        put("el", "greco");
        put("tut", "turco-tatarica (altra lingua)");
        put("niu", "niue");
        put("tup", "lingue tupi");
        put("ee", "ewe");
        put("tum", "tumbuka");
        put("mos", "mossi");
        put("dz", "dzongkha");
        put("nic", "niger - cordofan (altra lingua)");
        put("lus", "lushai");
        put("fiu", "ugrofinnica (altra lingua)");
        put("dv", "divehi");
        put("moh", "mohawk");
        put("luo", "luo (Kenia e Tanzania)");
        put("lun", "lunda");
        put("apa", "lingue apache");
        put("lui", "luiseno");
        put("hup", "hupa");
        put("bin", "bini");
        put("de", "tedesco");
        put("lua", "luba-lulua");
        put("bik", "bicol");
        put("was", "washo");
        put("und", "lingua imprecisata");
        put("war", "waray");
        put("da", "danese");
        put("dum", "olandese, medio (ca. 1050-1350)");
        put("wal", "walamo");
        put("mno", "manobo");
        put("wak", "lingue wakash");
        put("sat", "santali");
        put("cy", "gallese");
        put("sas", "sasak");
        put("kbd", "kabardia");
        put("cv", "chuvash");
        put("cu", "slavo della Chiesa");
        put("mni", "manipuri");
        put("cs", "ceco");
        put("sam", "aramaico samaritano");
        put("cr", "cree");
        put("sal", "lingue salish");
        put("dua", "duala");
        put("co", "corso");
        put("sai", "indiano del Sud America (altra lingua)");
        put("mnc", "manchu");
        put("sah", "yakut");
        put("kaw", "kawi");
        put("inh", "ingush");
        put("gba", "gbaya");
        put("sad", "sandawe");
        put("ch", "chamorro");
        put("ine", "indoeuropea (altra lingua)");
        put("bho", "bhojpuri");
        put("enm", "inglese, medio (1100-1500)");
        put("kar", "karen");
        put("inc", "indiana (altra lingua)");
        put("ce", "ceceno");
        put("gay", "gayo");
        put("ca", "catalano");
        put("umb", "mbundu");
        put("syr", "siriaco");
        put("kam", "kamba");
        put("tsi", "tsimshian");
        put("ang", "inglese, antico (ca.450-1100)");
        put("kac", "kachin");
        put("cau", "caucasica (altra lingua)");
        put("kab", "kabyle");
        put("kaa", "kara-kalpak");
        put("bs", "bosniaco");
        put("car", "caribico");
        put("br", "bretone");
        put("bo", "tibetano");
        put("bn", "bengalese");
        put("bm", "bambara");
        put("gaa", "ga");
        put("cai", "indiana dell\u2019America Centrale (altra lingua)");
        put("bi", "bislama");
        put("bh", "bihari");
        put("bg", "bulgaro");
        put("be", "bielorusso");
        put("cad", "caddo");
        put("ba", "baschiro");
        put("zu", "zulu");
        put("zen", "zenaga");
        put("pro", "provenzale, antico (fino al 1500)");
        put("hsb", "alto sorabo");
        put("az", "azerbaigiano");
        put("ay", "aymara");
        put("av", "avaro");
        put("as", "assamese");
        put("dsb", "basso sorabo");
        put("ar", "arabo");
        put("ilo", "ilocano");
        put("elx", "elamitico");
        put("zh", "cinese");
        put("an", "aragonese");
        put("pra", "pracrito");
        put("am", "amarico");
        put("new", "newari");
        put("ak", "akan");
        put("za", "zhuang");
        put("af", "afrikaans");
        put("ae", "avestan");
        put("ab", "abkhazian");
        put("aa", "afar");
        put("yo", "yoruba");
        put("alg", "lingue algonchine");
        put("ale", "aleuto");
        put("mkh", "mon-khmer (altra lingua)");
        put("yi", "yiddish");
        put("dra", "dravidica (altra lingua)");
        put("ber", "berbero");
        put("nds", "basso tedesco; basso sassone");
        put("bem", "wemba");
        put("bej", "begia");
        put("tpi", "tok pisin");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "ampms", ampms },
    { "shortDateFormat", "dd/MM/yy" },
    { "mediumDateFormat", "dd/MMM/yy" },
    { "longDateFormat", "dd MMMM yyyy" },
    { "fullDateFormat", "EEEE d MMMM yyyy" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
