/* LocaleInformation_da.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_da extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "jan",
    "feb",
    "mar",
    "apr",
    "maj",
    "jun",
    "jul",
    "aug",
    "sep",
    "okt",
    "nov",
    "dec",
    null,
  };

  private static final String[] months = {
    "januar",
    "februar",
    "marts",
    "april",
    "maj",
    "juni",
    "juli",
    "august",
    "september",
    "oktober",
    "november",
    "december",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "s\u00f8n",
    "man",
    "tir",
    "ons",
    "tor",
    "fre",
    "l\u00f8r",
  };

  private static final String[] weekdays = {
    null,
    "s\u00f8ndag",
    "mandag",
    "tirsdag",
    "onsdag",
    "torsdag",
    "fredag",
    "l\u00f8rdag",
  };

  private static final String[] eras = {
    "f.Kr.",
    "e.Kr.",
  };

  private static final String[][] zoneStrings =
  {
    { "PST", "Pacific-normaltid", "PDT", "Pacific-sommertid",  "America/Los_Angeles" },
    { "GMT", "Verdenstid", "GMT", "Verdenstid",  "Africa/Casablanca" },
    { "EST", "Eastern-normaltid", "EDT", "Eastern-sommertid",  "America/New_York" },
    { "AST", "Alaska-normaltid", "ADT", "Alaska-sommertid",  "America/Anchorage" },
    { "GMT", "Verdenstid", "GMT", "Verdenstid",  "Etc/GMT" },
    { "CTT", "Kinesisk normaltid", "CDT", "Kinesisk normaltid",  "Asia/Shanghai" },
    { "AST", "Atlantic-normaltid", "ADT", "Atlantic-sommertid",  "America/Halifax" },
    { "CET", "Mellemeurop\u00e6isk normaltid", "CEST", "Mellemeurop\u00e6isk sommertid",  "Europe/Paris" },
    { "MST", "Mountain-normaltid", "MDT", "Mountain-sommertid",  "America/Denver" },
    { "IST", "Israelsk normaltid", "IDT", "Israelsk sommertid",  "Asia/Jerusalem" },
    { "HST", "Hawaii-normaltid", "HST", "Hawaii-normaltid",  "Pacific/Honolulu" },
    { "CNT", "Newfoundland-normaltid", "CDT", "Newfoundland-sommertid",  "America/St_Johns" },
    { "EST", "Eastern-normaltid", "EST", "Eastern-normaltid",  "America/Indianapolis" },
    { "CST", "Central-normaltid", "CDT", "Central-sommertid",  "America/Chicago" },
    { "EET", "\u00d8steurop\u00e6isk normaltid", "EEST", "\u00d8steurop\u00e6isk sommertid",  "Europe/Bucharest" },
    { "JST", "Japansk normaltid", "JST", "Japansk normaltid",  "Asia/Tokyo" },
    { "MST", "Mountain-normaltid", "MST", "Mountain-normaltid",  "America/Phoenix" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Timor-Leste");
        put("TK", "Tokelau");
        put("TJ", "Tadsjikistan");
        put("TH", "Thailand");
        put("TG", "Togo");
        put("TF", "Franske Besiddelser i Det Sydlige Indiske Ocean");
        put("GY", "Guyana");
        put("TD", "Tchad");
        put("TC", "Turks- og Caicos\u00f8erne");
        put("GW", "Guinea-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "South Georgia og De Sydlige Sandwich\u00f8er");
        put("GR", "Gr\u00e6kenland");
        put("GQ", "\u00c6kvatorialguinea");
        put("GP", "Guadeloupe");
        put("SZ", "Swaziland");
        put("SY", "Syrien");
        put("GN", "Guinea");
        put("GM", "Gambia");
        put("GL", "Gr\u00f8nland");
        put("SV", "El Salvador");
        put("ST", "S\u00e3o Tom\u00e9 og Pr\u00edncipe");
        put("GI", "Gibraltar");
        put("GH", "Ghana");
        put("SR", "Surinam");
        put("GF", "Fransk Guyana");
        put("SP", "Serbien");
        put("GE", "Georgien");
        put("SO", "Somalia");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Storbritannien");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Slovakiet");
        put("SJ", "Svalbard og Jan Mayen");
        put("SI", "Slovenien");
        put("SH", "St. Helena");
        put("SG", "Singapore");
        put("SE", "Sverige");
        put("SD", "Sudan");
        put("SC", "Seychellerne");
        put("SB", "Salomon\u00f8erne");
        put("SA", "Saudi-Arabien");
        put("FR", "Frankrig");
        put("FO", "F\u00e6r\u00f8erne");
        put("FM", "Mikronesiens Forenede Stater");
        put("RW", "Rwanda");
        put("FK", "Falklands\u00f8erne");
        put("RU", "Rusland");
        put("FJ", "Fiji-\u00f8erne");
        put("FI", "Finland");
        put("RO", "Rum\u00e6nien");
        put("RE", "Reunion");
        put("ET", "Etiopien");
        put("ES", "Spanien");
        put("ER", "Eritrea");
        put("EH", "Vestsahara");
        put("EG", "Egypten");
        put("EE", "Estland");
        put("EC", "Ecuador");
        put("DZ", "Algeriet");
        put("QA", "Qatar");
        put("DO", "Den Dominikanske Republik");
        put("PY", "Paraguay");
        put("DM", "Dominica");
        put("PW", "Palau");
        put("DK", "Danmark");
        put("DJ", "Djibouti");
        put("PT", "Portugal");
        put("PS", "De pal\u00e6stinensiske omr\u00e5der");
        put("PR", "Puerto Rico");
        put("DE", "Tyskland");
        put("PN", "Pitcairn");
        put("PM", "Saint Pierre og Miquelon");
        put("PL", "Polen");
        put("PK", "Pakistan");
        put("PH", "Filippinerne");
        put("PG", "Papua Ny Guinea");
        put("PF", "Fransk Polynesien");
        put("CZ", "Tjekkiet");
        put("PE", "Peru");
        put("CY", "Cypern");
        put("CX", "Jule\u00f8en");
        put("CV", "Kap Verde");
        put("PA", "Panama");
        put("CU", "Cuba");
        put("CR", "Costa Rica");
        put("CO", "Colombia");
        put("CN", "Kina");
        put("CM", "Cameroun");
        put("CL", "Chile");
        put("CK", "Cook-\u00f8erne");
        put("CI", "Elfenbenskysten");
        put("CH", "Schweiz");
        put("CG", "Congo");
        put("CF", "Centralafrikanske Republik");
        put("CD", "Den Demokratiske Republik Congo");
        put("CC", "Cocos-\u00f8erne (Keeling\u00f8erne)");
        put("OM", "Oman");
        put("CA", "Canada");
        put("BZ", "Belize");
        put("BY", "Hviderusland");
        put("BW", "Botswana");
        put("BV", "Bouvet\u00f8");
        put("BT", "Bhutan");
        put("BS", "Bahamas");
        put("BR", "Brasilien");
        put("NZ", "New Zealand");
        put("BO", "Bolivia");
        put("BN", "Brunei Darussalam");
        put("BM", "Bermuda");
        put("NU", "Niue");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrain");
        put("NR", "Nauru");
        put("BG", "Bulgarien");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "Belgien");
        put("NO", "Norge");
        put("BD", "Bangladesh");
        put("BB", "Barbados");
        put("ZW", "Zimbabwe");
        put("NL", "Holland");
        put("BA", "Bosnien-Hercegovina");
        put("NI", "Nicaragua");
        put("NG", "Nigeria");
        put("NF", "Norfolk Island");
        put("AZ", "Aserbajdsjan");
        put("NE", "Niger");
        put("NC", "Ny Caledonien");
        put("AW", "Aruba");
        put("ZM", "Zambia");
        put("NA", "Namibia");
        put("AU", "Australien");
        put("AT", "\u00d8strig");
        put("AS", "Amerikansk Samoa");
        put("AR", "Argentina");
        put("AQ", "Antarktis");
        put("MZ", "Mozambique");
        put("AO", "Angola");
        put("MY", "Malaysia");
        put("AN", "Hollandske Antiller");
        put("MX", "Mexico");
        put("AM", "Armenien");
        put("MW", "Malawi");
        put("AL", "Albanien");
        put("MV", "Maldiverne");
        put("ZA", "Sydafrika");
        put("MU", "Mauritius");
        put("MT", "Malta");
        put("AI", "Anguilla");
        put("MS", "Montserrat");
        put("MR", "Mauretanien");
        put("AG", "Antigua og Barbuda");
        put("MQ", "Martinique");
        put("AF", "Afghanistan");
        put("MP", "Nordmarianerne");
        put("AE", "Forenede Arabiske Emirater");
        put("MO", "SAR Macao");
        put("AD", "Andorra");
        put("MN", "Mongoliet");
        put("MM", "Myanmar");
        put("ML", "Mali");
        put("MK", "Republikken Makedonien");
        put("YU", "Jugoslavien");
        put("YT", "Mayotte");
        put("MH", "Marshall\u00f8erne");
        put("MG", "Madagaskar");
        put("MD", "Republikken Moldova");
        put("MC", "Monaco");
        put("MA", "Marokko");
        put("YE", "Yemen");
        put("LY", "Libyen");
        put("LV", "Letland");
        put("LU", "Luxembourg");
        put("LT", "Litauen");
        put("LS", "Lesotho");
        put("LR", "Liberia");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Saint Lucia");
        put("LB", "Libanon");
        put("LA", "Laos");
        put("KZ", "Kasakhstan");
        put("KY", "Cayman\u00f8erne");
        put("KW", "Kuwait");
        put("KR", "Sydkorea");
        put("KP", "Nordkorea");
        put("KN", "Saint Kitts og Nevis");
        put("KM", "Comorerne");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Cambodja");
        put("KG", "Kirgisistan");
        put("KE", "Kenya");
        put("WF", "Wallis og Futuna\u00f8erne");
        put("JP", "Japan");
        put("JO", "Jordan");
        put("JM", "Jamaica");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "De amerikanske jomfru\u00f8er");
        put("VG", "De britiske jomfru\u00f8er");
        put("VE", "Venezuela");
        put("VC", "St. Vincent og Grenadinerne");
        put("VA", "Vatikanstaten");
        put("IT", "Italien");
        put("IS", "Island");
        put("IR", "Iran");
        put("IQ", "Irak");
        put("UZ", "Usbekistan");
        put("IO", "Det Britiske Territorium i Det Indiske Ocean");
        put("UY", "Uruguay");
        put("IN", "Indien");
        put("IL", "Israel");
        put("US", "USA");
        put("IE", "Irland");
        put("ID", "Indonesien");
        put("UM", "De Mindre Amerikanske Overs\u00f8iske \u00d8er");
        put("UG", "Uganda");
        put("UA", "Ukraine");
        put("HU", "Ungarn");
        put("HT", "Haiti");
        put("HR", "Kroatien");
        put("TZ", "Tanzania");
        put("HN", "Honduras");
        put("HM", "Heard- og McDonald-\u00f8erne");
        put("TW", "Taiwan");
        put("TV", "Tuvalu");
        put("HK", "SAR Hongkong");
        put("TT", "Trinidad og Tobago");
        put("TR", "Tyrkiet");
        put("TO", "Tonga");
        put("TN", "Tunesien");
        put("TM", "Turkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("gwi", "Gwich\u02bbin");
        put("akk", "Akkadisk");
        put("eka", "Ekajuk");
        put("ijo", "Ijo");
        put("xh", "Xhosa");
        put("sux", "Sumerisk");
        put("sus", "Susu");
        put("mis", "Diverse sprog");
        put("loz", "Lozi");
        put("tog", "Tonga (Nyasa)");
        put("pon", "Ponape");
        put("min", "Minangkabau");
        put("suk", "Sukuma");
        put("wo", "Wolof");
        put("lol", "Mongo");
        put("mic", "Micmac");
        put("wa", "Vallonsk");
        put("zap", "Zapotec");
        put("cus", "Kusjitiske sprog (\u00f8vrige)");
        put("jbo", "Lojban");
        put("doi", "Dogri");
        put("vo", "Volap\u00fck");
        put("oto", "Otomi sprog");
        put("vi", "Vietnamesisk");
        put("vai", "Vai");
        put("rar", "Rarotongan");
        put("ve", "Venda");
        put("rap", "Rapanui");
        put("raj", "Rajasthani");
        put("ota", "Osmannisk (1500-1928)");
        put("nzi", "Nzima");
        put("nap", "Neapolitansk");
        put("uz", "Usbekisk");
        put("uga", "Ugaristisk");
        put("tmh", "Tamashek");
        put("nai", "Nordamerikanske indianske sprog (\u00f8vrige)");
        put("nah", "Nahuatl");
        put("ur", "Urdu");
        put("fat", "Fanti");
        put("uk", "Ukrainsk");
        put("egy", "Egyptisk (oldtid)");
        put("ug", "Uigurisk");
        put("fan", "Fang");
        put("ssa", "Afrikanske sprog syd for Sahara (\u00f8vrige)");
        put("mga", "Irsk, Middel- (900-1200)");
        put("bat", "Baltiske sprog (\u00f8vrige)");
        put("nyo", "Nyoro sprog");
        put("bas", "Basa");
        put("nyn", "Nyankole");
        put("nym", "Nyamwezi");
        put("hmn", "Hmong");
        put("ban", "Balinesisk");
        put("osa", "Osage");
        put("bal", "Baluchi");
        put("ty", "Tahitiansk");
        put("tw", "Twi");
        put("srr", "Serer");
        put("tli", "Tlingit");
        put("tt", "Tatarisk");
        put("ts", "Tsonga");
        put("bad", "Banda");
        put("tr", "Tyrkisk");
        put("to", "Tonga (Tonga\u00f8erne)");
        put("tn", "Tswana");
        put("tl", "Tagalog");
        put("tk", "Turkmensk");
        put("ti", "Tigrinya");
        put("th", "Thailandsk");
        put("kru", "Kurukh");
        put("tg", "Tajik");
        put("byn", "Blin");
        put("te", "Telugu");
        put("kro", "Kru");
        put("csb", "Kashubian");
        put("ta", "Tamilsk");
        put("tkl", "Tokelau");
        put("efi", "Efik");
        put("sw", "Swahili");
        put("sv", "Svensk");
        put("su", "Sundanesisk");
        put("krc", "Karachay-Balkar");
        put("st", "Sotho, Southern");
        put("ss", "Swati");
        put("sr", "Serbisk");
        put("sq", "Albansk");
        put("men", "Mende");
        put("crp", "Kreolsk og pidgin (\u00f8vrige)");
        put("so", "Somalisk");
        put("afh", "Afrihili");
        put("sn", "Shona");
        put("sm", "Samoansk");
        put("sl", "Slovensk");
        put("grc", "Gr\u00e6sk, Old- (til 1453)");
        put("sk", "Slovakisk");
        put("grb", "Grebo");
        put("si", "Singalesisk");
        put("sh", "Serbokroatisk");
        put("crh", "Krim-tyrkisk; Krim-tatarisk");
        put("afa", "Afro-asiatisk (\u00f8vrige)");
        put("sg", "Sango");
        put("se", "Nordsamisk");
        put("sd", "Sindhi");
        put("udm", "Udmurt");
        put("sc", "Sardinsk");
        put("sa", "Sanskrit");
        put("rw", "Kinyarwanda");
        put("ru", "Russisk");
        put("mdr", "Mandar");
        put("ro", "Rum\u00e6nsk");
        put("rn", "Rundi");
        put("rm", "R\u00e6toromansk");
        put("mdf", "Moksha");
        put("tiv", "Tivi");
        put("ady", "Adyghe");
        put("zun", "Zuni");
        put("kpe", "Kpelle");
        put("qu", "Quechua");
        put("tig", "Tigre");
        put("son", "Songhai");
        put("cpp", "Kreolsk og pidgin, baseret p\u00e5 portugisisk (\u00f8vrige)");
        put("sog", "Sogdiansk");
        put("ada", "Adangme");
        put("kos", "Kosraean");
        put("hit", "Hittitisk");
        put("cpf", "Kreolsk og pidgin, baseret p\u00e5 fransk (\u00f8vrige)");
        put("cpe", "Kreolsk og pidgin, baseret p\u00e5 engelsk (\u00f8vrige)");
        put("him", "Himachali");
        put("kok", "Konkani");
        put("hil", "Hiligaynon");
        put("got", "Gotisk");
        put("gor", "Gorontalo");
        put("gon", "Gondi");
        put("din", "Dinka");
        put("nub", "Nubiske sprog");
        put("pt", "Portugisisk");
        put("ps", "Pashto (Pushto)");
        put("fur", "Friulian");
        put("phn", "F\u00f8nikisk");
        put("goh", "Tysk, Oldh\u00f8j- (ca.750-1050)");
        put("snk", "Soninke");
        put("cop", "Koptisk");
        put("yap", "Yap");
        put("ach", "Acoli");
        put("yao", "Yao");
        put("phi", "Filippinske sprog (\u00f8vrige)");
        put("pl", "Polsk");
        put("ace", "Achinesisk");
        put("pi", "Pali");
        put("pa", "Punjabi");
        put("bug", "Buginesisk");
        put("iba", "Iban");
        put("sms", "Skolt Sami");
        put("bua", "Buriat");
        put("mas", "Masai");
        put("smn", "Inari Sami");
        put("os", "Ossetisk");
        put("map", "Malajo-polynesiske sprog (\u00f8vrige)");
        put("or", "Oriya");
        put("man", "Mandingo");
        put("smj", "Lule Sami");
        put("smi", "Samiske sprog (\u00f8vrige)");
        put("mak", "Makasar");
        put("om", "Oromo");
        put("mai", "Maithili");
        put("oj", "Ojibwa");
        put("mag", "Magahi");
        put("mad", "Madurese");
        put("sma", "Sydsamisk");
        put("oc", "Occitansk (efter 1500); Provencalsk");
        put("nso", "Sotho, Nord");
        put("btk", "Batak");
        put("myv", "Erzya");
        put("dgr", "Dogrib");
        put("ny", "Nyanja; Chichewa; Chewa");
        put("myn", "Maya sprog");
        put("nv", "Navajo");
        put("kmb", "Kimbundu");
        put("nr", "Ndebele, Syd");
        put("gmh", "Tysk, Middelh\u00f8j- (ca.1050-1500)");
        put("no", "Norsk");
        put("nn", "Nynorsk");
        put("nl", "Hollandsk");
        put("ng", "Ndonga");
        put("sla", "Slaviske sprog (\u00f8vrige)");
        put("ne", "Nepalesisk");
        put("nd", "Ndebele, Nord");
        put("cmc", "Chamic sprog");
        put("tet", "Tetum");
        put("nb", "Norsk Bokm\u00e5l");
        put("na", "Nauru");
        put("ter", "Tereno");
        put("tem", "Temne");
        put("my", "Burmesisk");
        put("lez", "Lezghian");
        put("mt", "Maltesisk");
        put("peo", "Persisk, Old- (ca. 600-400 f. Kr.)");
        put("ms", "Malay");
        put("mr", "Marathisk");
        put("fro", "Fransk, Old- (842-ca.1400)");
        put("mo", "Moldovisk");
        put("frm", "Fransk, Middel- (ca.1400-1600)");
        put("mn", "Mongolsk");
        put("jrb", "J\u00f8disk-arabisk");
        put("ml", "Malayalam");
        put("mk", "Makedonsk");
        put("mi", "Maori");
        put("mh", "Marshallese");
        put("mg", "Malagasy");
        put("mwr", "Marwari");
        put("bra", "Braj");
        put("den", "Slave (Athapascan)");
        put("lv", "Lettisk");
        put("lu", "Luba-Katanga");
        put("del", "Delaware");
        put("lt", "Litauisk");
        put("lo", "Lao");
        put("ln", "Lingala");
        put("li", "Limburgsk");
        put("ewo", "Ewondo");
        put("lg", "Ganda");
        put("lb", "Luxembourgsk");
        put("la", "Latin");
        put("jpr", "J\u00f8disk-persisk");
        put("vot", "Votisk");
        put("sit", "Sino-tibetanske sprog (\u00f8vrige)");
        put("ky", "Kirgisisk");
        put("kw", "Cornisk");
        put("ku", "Kurdisk");
        put("ks", "Kashmiri");
        put("kr", "Kanuri");
        put("awa", "Awadhi");
        put("ko", "Koreansk");
        put("kn", "Kannaresisk");
        put("km", "Khmer");
        put("kl", "Kalaallisut");
        put("kk", "Kasakhisk");
        put("rom", "Romani");
        put("kj", "Kuanyama");
        put("sid", "Sidamo");
        put("ki", "Kikuyu");
        put("kg", "Kongo");
        put("non", "Islandsk, Old-");
        put("ka", "Georgisk");
        put("mus", "Creek");
        put("roa", "Romanske sprog (\u00f8vrige)");
        put("nog", "Nogai");
        put("mun", "Munda (\u00f8vrige)");
        put("mul", "Flere sprog");
        put("jv", "Javanesisk");
        put("gil", "Gilbertesisk");
        put("znd", "Zande");
        put("shn", "Shan");
        put("fon", "Fon");
        put("xal", "Kalmyk");
        put("aus", "Australske sprog");
        put("kho", "Khotanesisk");
        put("ja", "Japansk");
        put("khi", "Khoisan (\u00f8vrige)");
        put("pau", "Palauansk");
        put("chy", "Cheyenne");
        put("tai", "Tai (\u00f8vrige)");
        put("iu", "Inuktitut");
        put("pap", "Papiamento");
        put("it", "Italiensk");
        put("sgn", "Tegnsprog");
        put("is", "Islandsk");
        put("kha", "Khasi");
        put("chr", "Cherokee");
        put("pam", "Pampanga");
        put("pal", "Pahlavi");
        put("chp", "Chipewyan");
        put("io", "Ido");
        put("cho", "Choctaw");
        put("chn", "Chinook");
        put("chm", "Mari");
        put("tyv", "Tuvinian");
        put("bnt", "Bantu");
        put("pag", "Pangasinan");
        put("ik", "Inupiaq");
        put("chk", "Chuukese");
        put("ii", "Sichuan Yi");
        put("haw", "Hawaiiansk");
        put("lam", "Lamba");
        put("ig", "Igbo");
        put("chg", "Chagatai");
        put("sga", "Irsk, Old- (indtil 900)");
        put("paa", "Papua-australske sprog (\u00f8vrige)");
        put("ie", "Interlingue");
        put("id", "Indonesisk");
        put("lah", "Lahnda");
        put("day", "Dayak");
        put("chb", "Chibcha");
        put("ia", "Interlingua");
        put("lad", "Ladino");
        put("hz", "Herero");
        put("hai", "Haida");
        put("dar", "Dargwa");
        put("hy", "Armensk");
        put("hu", "Ungarsk");
        put("ht", "Haitisk");
        put("dak", "Dakota");
        put("hr", "Kroatisk");
        put("ho", "Hiri Motu");
        put("hi", "Hindi");
        put("dyu", "Dyula");
        put("he", "Hebraisk");
        put("ast", "Asturisk");
        put("ha", "Hausa");
        put("wen", "Vendiske sprog");
        put("gv", "Manx");
        put("gu", "Gujaratisk");
        put("sem", "Semitiske sprog (\u00f8vrige)");
        put("sel", "Selkupisk");
        put("iro", "Irokesiske sprog");
        put("gn", "Guarani");
        put("gl", "Galicisk");
        put("arw", "Arawak");
        put("gez", "Geez");
        put("art", "Kunstsprog (\u00f8vrige)");
        put("gd", "G\u00e6lisk (skotsk)");
        put("ira", "Iranske sprog (\u00f8vrige)");
        put("ga", "Irsk");
        put("arp", "Arapaho");
        put("arn", "Araukansk");
        put("fy", "Frisisk");
        put("bla", "Siksika");
        put("gem", "Germanske sprog (\u00f8vrige)");
        put("arc", "Aram\u00e6isk");
        put("fr", "Fransk");
        put("fo", "F\u00e6r\u00f8sk");
        put("cel", "Keltiske sprog (\u00f8vrige)");
        put("fj", "Fijian");
        put("fi", "Finsk");
        put("ff", "Fulah");
        put("tvl", "Tuvalu");
        put("ceb", "Cebuano");
        put("fa", "Persisk");
        put("eu", "Baskisk");
        put("sco", "Skotsk");
        put("et", "Estisk");
        put("es", "Spansk");
        put("eo", "Esperanto");
        put("en", "Engelsk");
        put("el", "Gr\u00e6sk");
        put("tut", "Tyrkisk-tatariske sprog (\u00f8vrige)");
        put("niu", "Niuean");
        put("ee", "Ewe");
        put("tum", "Tumbuka");
        put("mos", "Mossi");
        put("dz", "Dzongkha");
        put("nic", "Niger-Congo sprog (\u00f8vrige)");
        put("lus", "Lushai");
        put("fiu", "Finsk-ugriske sprog (\u00f8vrige)");
        put("dv", "Divehi");
        put("nia", "Nias");
        put("moh", "Mohawk");
        put("luo", "Luo");
        put("lun", "Lunda");
        put("apa", "Apache sprog");
        put("lui", "Luiseno");
        put("hup", "Hupa");
        put("bin", "Bini");
        put("de", "Tysk");
        put("lua", "Luba-Lulua");
        put("bik", "Bikol");
        put("was", "Washo");
        put("und", "Sproget kan ikke bestemmes");
        put("war", "Waray");
        put("da", "Dansk");
        put("dum", "Hollandsk (ca. 1050-1350)");
        put("wal", "Walamo");
        put("sat", "Santali");
        put("cy", "Walisisk");
        put("sas", "Sasak");
        put("kbd", "Kabardian");
        put("cv", "Chuvash");
        put("cu", "Kirkeslavisk");
        put("mni", "Manipuri");
        put("cs", "Tjekkisk");
        put("sam", "Samaritansk");
        put("cr", "Cree");
        put("dua", "Duala");
        put("co", "Korsikansk");
        put("sai", "Sydamerikanske indianske sprog (\u00f8vrige)");
        put("mnc", "Manchu");
        put("sah", "Yakut");
        put("kaw", "Kawi");
        put("inh", "Ingush");
        put("gba", "Gbaya");
        put("sad", "Sandawe");
        put("ch", "Chamorro");
        put("ine", "Indoeurop\u00e6iske sprog (\u00f8vrige)");
        put("bho", "Bhojpuri");
        put("enm", "Engelsk, Middel- (1100-1500)");
        put("kar", "Karen");
        put("inc", "Indiske sprog (\u00f8vrige)");
        put("ce", "Tjetjensk");
        put("gay", "Gayo");
        put("ca", "Katalansk");
        put("umb", "Umbundu");
        put("syr", "Syrisk");
        put("kam", "Kamba");
        put("tsi", "Tsimshisk");
        put("ang", "Angelsaksisk (ca.450-1100)");
        put("kac", "Kachin");
        put("cau", "Kaukasiske sprog (\u00f8vrige)");
        put("kab", "Kabyle");
        put("kaa", "Karakalpakisk");
        put("bs", "Bosnisk");
        put("car", "Caribisk");
        put("br", "Bretonsk");
        put("bo", "Tibetansk");
        put("bn", "Bengalsk");
        put("bm", "Bambara");
        put("gaa", "Ga");
        put("cai", "Mellemamerikanske indianske sprog (\u00f8vrige)");
        put("bi", "Bislama");
        put("bh", "Bihari");
        put("bg", "Bulgarsk");
        put("be", "Hviderussisk");
        put("cad", "Caddo");
        put("ba", "Bashkir");
        put("zu", "Zulu");
        put("zen", "Zenaga");
        put("pro", "Provencalsk (f\u00f8r 1500)");
        put("hsb", "\u00d8vre sorbisk");
        put("az", "Aserbajdsjan");
        put("ay", "Aymara");
        put("av", "Avarisk");
        put("as", "Assamesisk");
        put("dsb", "Nedre sorbisk");
        put("ar", "Arabisk");
        put("ilo", "Iloko");
        put("elx", "Elamitisk");
        put("zh", "Kinesisk");
        put("an", "Aragonesisk");
        put("am", "Amharisk");
        put("new", "Newari");
        put("ak", "Akan");
        put("za", "Zhuang");
        put("af", "Afrikaans");
        put("ae", "Avestan");
        put("ab", "Abkhasisk");
        put("aa", "Afar");
        put("yo", "Yoruba");
        put("alg", "Algonkiske sprog");
        put("ale", "Aleutiske sprog");
        put("mkh", "Mon-khmer (\u00f8vrige)");
        put("yi", "Jiddisch");
        put("dra", "Dravidiske sprog (\u00f8vrige)");
        put("ber", "Berberiske sprog");
        put("nds", "Nedertysk; nedersachsisk");
        put("bem", "Bemba");
        put("bej", "Beja");
        put("tpi", "Tok Pisin");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "localPatternChars", "GuMtkHmsSEDFwWahKzUeygAZ" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "shortDateFormat", "dd-MM-yy" },
    { "mediumDateFormat", "dd-MM-yyyy" },
    { "longDateFormat", "d. MMM yyyy" },
    { "fullDateFormat", "EEEE dd MMMM yyyy" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
