/* LocaleInformation_es.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_es extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "ene",
    "feb",
    "mar",
    "abr",
    "may",
    "jun",
    "jul",
    "ago",
    "sep",
    "oct",
    "nov",
    "dic",
    null,
  };

  private static final String[] months = {
    "enero",
    "febrero",
    "marzo",
    "abril",
    "mayo",
    "junio",
    "julio",
    "agosto",
    "septiembre",
    "octubre",
    "noviembre",
    "diciembre",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "dom",
    "lun",
    "mar",
    "mi\u00e9",
    "jue",
    "vie",
    "s\u00e1b",
  };

  private static final String[] weekdays = {
    null,
    "domingo",
    "lunes",
    "martes",
    "mi\u00e9rcoles",
    "jueves",
    "viernes",
    "s\u00e1bado",
  };

  private static final String[] eras = {
    "a.C.",
    "d.C.",
  };

  private static final String[][] zoneStrings =
  {
    { "America/Los_Angeles", "Hora est\u00e1ndar del Pac\u00edfico", "PST", "Hora de verano del Pac\u00edfico", "PDT" },
    { "Africa/Casablanca", "Hora media de Greenwich", "GMT", "Hora media de Greenwich", "GMT" },
    { "America/New_York", "Hora est\u00e1ndar oriental", "EST", "Hora de verano oriental", "EDT" },
    { "America/Anchorage", "Hora est\u00e1ndar de Alaska", "AST", "Hora de verano de Alaska", "ADT" },
    { "Etc/GMT", "Hora media de Greenwich", "GMT", "Hora media de Greenwich", "GMT" },
    { "Asia/Shanghai", "Hora est\u00e1ndar de China", "CTT", "Hora est\u00e1ndar de China", "CDT" },
    { "America/Halifax", "Hora est\u00e1ndar del Atl\u00e1ntico", "AST", "Hora de verano del Atl\u00e1ntico", "ADT" },
    { "Europe/Paris", "Hora est\u00e1ndar de Europa Central", "CET", "Hora de verano de Europa Central", "CEST" },
    { "America/Denver", "Hora est\u00e1ndar de Monta\u00f1a", "MST", "Hora de verano de Monta\u00f1a", "MDT" },
    { "Asia/Jerusalem", "Hora est\u00e1ndar de Israel", "IST", "Hora de verano de Israel", "IDT" },
    { "Pacific/Honolulu", "Hora est\u00e1ndar de Hawai", "HST", "Hora est\u00e1ndar de Hawai", "HST" },
    { "America/St_Johns", "Hora est\u00e1ndar de Newfoundland", "CNT", "Hora de verano de Newfoundland", "CDT" },
    { "America/Indianapolis", "Hora est\u00e1ndar oriental", "EST", "Hora est\u00e1ndar oriental", "EST" },
    { "America/Chicago", "Hora est\u00e1ndar central", "CST", "Hora de verano central", "CDT" },
    { "Europe/Bucharest", "Hora est\u00e1ndar de Europa del Este", "EET", "Hora de verano de Europa del Este", "EEST" },
    { "Asia/Tokyo", "Hora est\u00e1ndar de Jap\u00f3n", "JST", "Hora est\u00e1ndar de Jap\u00f3n", "JST" },
    { "America/Phoenix", "Hora est\u00e1ndar de Monta\u00f1a", "MST", "Hora est\u00e1ndar de Monta\u00f1a", "MST" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Timor Oriental");
        put("TK", "Islas Tokelau");
        put("TJ", "Tayikist\u00e1n");
        put("TH", "Tailandia");
        put("TG", "Togo");
        put("TF", "Territorios Australes Franceses");
        put("GY", "Guyana");
        put("TD", "Chad");
        put("TC", "Islas Turcas y Caicos");
        put("GW", "Guinea-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "Islas Georgia del Sur y Sandwich del Sur");
        put("GR", "Grecia");
        put("GQ", "Guinea Ecuatorial");
        put("GP", "Guadalupe");
        put("SZ", "Suazilandia");
        put("SY", "Siria");
        put("GN", "Guinea");
        put("GM", "Gambia");
        put("GL", "Groenlandia");
        put("SV", "El Salvador");
        put("ST", "Santo Tom\u00e9 y Pr\u00edncipe");
        put("GI", "Gibraltar");
        put("GH", "Ghana");
        put("SR", "Suriname");
        put("GF", "Guayana Francesa");
        put("SP", "Serbia");
        put("GE", "Georgia");
        put("SO", "Somalia");
        put("GD", "Granada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Reino Unido");
        put("SL", "Sierra Leona");
        put("GA", "Gab\u00f3n");
        put("SK", "Eslovaquia");
        put("SJ", "Svalbard y Jan Mayen");
        put("SI", "Eslovenia");
        put("SH", "Santa Elena");
        put("SG", "Singapur");
        put("SE", "Suecia");
        put("SD", "Sud\u00e1n");
        put("SC", "Seychelles");
        put("SB", "Islas Salom\u00f3n");
        put("SA", "Arabia Saud\u00ed");
        put("FR", "Francia");
        put("FO", "Islas Feroe");
        put("FM", "Micronesia");
        put("RW", "Ruanda");
        put("FK", "Islas Falkland (Malvinas)");
        put("RU", "Rusia");
        put("FJ", "Fiyi");
        put("FI", "Finlandia");
        put("RO", "Ruman\u00eda");
        put("RE", "R\u00e9union");
        put("ET", "Etiop\u00eda");
        put("ES", "Espa\u00f1a");
        put("ER", "Eritrea");
        put("EH", "S\u00e1hara Occidental");
        put("EG", "Egipto");
        put("EE", "Estonia");
        put("EC", "Ecuador");
        put("DZ", "Argelia");
        put("QA", "Qatar");
        put("DO", "Rep\u00fablica Dominicana");
        put("PY", "Paraguay");
        put("DM", "Dominica");
        put("PW", "Palau");
        put("DK", "Dinamarca");
        put("DJ", "Yibuti");
        put("PT", "Portugal");
        put("PS", "Territorios Palestinos");
        put("PR", "Puerto Rico");
        put("DE", "Alemania");
        put("PN", "Pitcairn");
        put("PM", "San Pedro y Miquel\u00f3n");
        put("PL", "Polonia");
        put("PK", "Pakist\u00e1n");
        put("PH", "Filipinas");
        put("PG", "Pap\u00faa Nueva Guinea");
        put("PF", "Polinesia Francesa");
        put("CZ", "Rep\u00fablica Checa");
        put("PE", "Per\u00fa");
        put("CY", "Chipre");
        put("CX", "Isla Navidad");
        put("CV", "Cabo Verde");
        put("PA", "Panam\u00e1");
        put("CU", "Cuba");
        put("CR", "Costa Rica");
        put("CO", "Colombia");
        put("CN", "China");
        put("CM", "Camer\u00fan");
        put("CL", "Chile");
        put("CK", "Islas Cook");
        put("CI", "Costa de Marfil");
        put("CH", "Suiza");
        put("CG", "Congo");
        put("CF", "Rep\u00fablica Centroafricana");
        put("CD", "Rep\u00fablica Democr\u00e1tica del Congo");
        put("CC", "Islas Cocos (Keeling)");
        put("OM", "Om\u00e1n");
        put("CA", "Canad\u00e1");
        put("BZ", "Belice");
        put("BY", "Bielorrusia");
        put("BW", "Botsuana");
        put("BV", "Isla Bouvet");
        put("BT", "But\u00e1n");
        put("BS", "Bahamas");
        put("BR", "Brasil");
        put("NZ", "Nueva Zelanda");
        put("BO", "Bolivia");
        put("BN", "Brun\u00e9i");
        put("BM", "Bermudas");
        put("NU", "Isla Niue");
        put("BJ", "Ben\u00edn");
        put("BI", "Burundi");
        put("BH", "Bahr\u00e1in");
        put("NR", "Nauru");
        put("BG", "Bulgaria");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "B\u00e9lgica");
        put("NO", "Noruega");
        put("BD", "Bangladesh");
        put("BB", "Barbados");
        put("ZW", "Zimbabue");
        put("NL", "Pa\u00edses Bajos");
        put("BA", "Bosnia-Herzegovina");
        put("NI", "Nicaragua");
        put("NG", "Nigeria");
        put("NF", "Isla Norfolk");
        put("AZ", "Azerbaiy\u00e1n");
        put("NE", "N\u00edger");
        put("NC", "Nueva Caledonia");
        put("AW", "Aruba");
        put("ZM", "Zambia");
        put("NA", "Namibia");
        put("AU", "Australia");
        put("AT", "Austria");
        put("AS", "Samoa Americana");
        put("AR", "Argentina");
        put("AQ", "Ant\u00e1rtida");
        put("MZ", "Mozambique");
        put("AO", "Angola");
        put("MY", "Malasia");
        put("AN", "Antillas Neerlandesas");
        put("MX", "M\u00e9xico");
        put("AM", "Armenia");
        put("MW", "Malawi");
        put("AL", "Albania");
        put("MV", "Maldivas");
        put("ZA", "Sud\u00e1frica");
        put("MU", "Mauricio");
        put("MT", "Malta");
        put("AI", "Anguila");
        put("MS", "Montserrat");
        put("MR", "Mauritania");
        put("AG", "Antigua y Barbuda");
        put("MQ", "Martinica");
        put("AF", "Afganist\u00e1n");
        put("MP", "Islas Marianas del Norte");
        put("AE", "Emiratos \u00c1rabes Unidos");
        put("MO", "Macao, Regi\u00f3n administrativa especial de China");
        put("AD", "Andorra");
        put("MN", "Mongolia");
        put("MM", "Myanmar");
        put("ML", "Mal\u00ed");
        put("MK", "Macedonia");
        put("YU", "Yugoslavia");
        put("YT", "Mayotte");
        put("MH", "Islas Marshall");
        put("MG", "Madagascar");
        put("MD", "Moldova");
        put("MC", "M\u00f3naco");
        put("MA", "Marruecos");
        put("YE", "Yemen");
        put("LY", "Libia");
        put("LV", "Letonia");
        put("LU", "Luxemburgo");
        put("LT", "Lituania");
        put("LS", "Lesotho");
        put("LR", "Liberia");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Saint Lucia");
        put("LB", "L\u00edbano");
        put("LA", "Laos");
        put("KZ", "Kazajst\u00e1n");
        put("KY", "Islas Caim\u00e1n");
        put("KW", "Kuwait");
        put("KR", "Corea del Sur");
        put("KP", "Corea del Norte");
        put("KN", "San Crist\u00f3bal y Nieves");
        put("KM", "Comoras");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Camboya");
        put("KG", "Kirguizist\u00e1n");
        put("KE", "Kenia");
        put("WF", "Wallis y Futuna");
        put("JP", "Jap\u00f3n");
        put("JO", "Jordania");
        put("JM", "Jamaica");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "Islas V\u00edrgenes de los Estados Unidos");
        put("VG", "Islas V\u00edrgenes Brit\u00e1nicas");
        put("VE", "Venezuela");
        put("VC", "San Vicente y las Granadinas");
        put("VA", "Ciudad del Vaticano");
        put("IT", "Italia");
        put("IS", "Islandia");
        put("IR", "Ir\u00e1n");
        put("IQ", "Iraq");
        put("UZ", "Uzbekist\u00e1n");
        put("IO", "Territorios Brit\u00e1nico del Oc\u00e9ano \u00cdndico");
        put("UY", "Uruguay");
        put("IN", "India");
        put("IL", "Israel");
        put("US", "Estados Unidos");
        put("IE", "Irlanda");
        put("ID", "Indonesia");
        put("UM", "Islas menores alejadas de los Estados Unidos");
        put("UG", "Uganda");
        put("UA", "Ucrania");
        put("HU", "Hungr\u00eda");
        put("HT", "Hait\u00ed");
        put("HR", "Croacia");
        put("TZ", "Tanzania");
        put("HN", "Honduras");
        put("HM", "Islas Heard y McDonald");
        put("TW", "Taiw\u00e1n");
        put("TV", "Tuvalu");
        put("HK", "Hong-Kong, Regi\u00f3n administrativa especial de China");
        put("TT", "Trinidad y Tabago");
        put("TR", "Turqu\u00eda");
        put("TO", "Tonga");
        put("TN", "T\u00fanez");
        put("TM", "Turkmenist\u00e1n");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("gwi", "kutchin");
        put("akk", "acadio");
        put("eka", "ekajuk");
        put("ijo", "ijo");
        put("xh", "xhosa");
        put("sux", "sumerio");
        put("sus", "susu");
        put("mis", "lenguas varias");
        put("loz", "lozi");
        put("tog", "tonga (Niasa)");
        put("pon", "pohnpeiano");
        put("min", "minangkabau");
        put("suk", "sukuma");
        put("wo", "uolof");
        put("lol", "mongo");
        put("kut", "kutenai");
        put("mic", "micmac");
        put("wa", "val\u00f3n");
        put("kum", "kumyk");
        put("zap", "zapoteco");
        put("cus", "cusitas (otras)");
        put("jbo", "lojban");
        put("doi", "dogri");
        put("vo", "volapuk");
        put("oto", "lenguas otomanas");
        put("vi", "vietnamita");
        put("vai", "vai");
        put("rar", "rarotongano");
        put("ve", "venda");
        put("rap", "rapanui");
        put("raj", "rajasthani");
        put("ota", "turco otomano (1500-1928)");
        put("nzi", "nzima");
        put("nap", "napolitano");
        put("uz", "uzbeko");
        put("uga", "ugar\u00edtico");
        put("tmh", "tamashek");
        put("nai", "indias norteamericanas (otras)");
        put("nah", "n\u00e1huatl");
        put("ur", "urdu");
        put("fat", "fanti");
        put("uk", "ucraniano");
        put("egy", "egipcio (antiguo)");
        put("ug", "uigur");
        put("fan", "fang");
        put("ssa", "nilosaharianas (otras)");
        put("mga", "irland\u00e9s medieval (900-1200)");
        put("bat", "b\u00e1lticas (otras)");
        put("nyo", "nyoro");
        put("bas", "basa");
        put("nyn", "nyankole");
        put("nym", "nyamwezi");
        put("hmn", "hmong");
        put("ban", "balin\u00e9s");
        put("osa", "osage");
        put("bal", "baluchi");
        put("ty", "tahitiano");
        put("bai", "lenguas bamileke");
        put("tw", "twi");
        put("srr", "serer");
        put("tli", "tlingit");
        put("tt", "tatar");
        put("ts", "tsonga");
        put("bad", "banda");
        put("tr", "turco");
        put("to", "tonga (Islas Tonga)");
        put("tn", "setchwana");
        put("tl", "tagalo");
        put("tk", "turkmeno");
        put("ti", "tigrinya");
        put("th", "tailand\u00e9s");
        put("kru", "kurukh");
        put("tg", "tayiko");
        put("byn", "blin");
        put("te", "telugu");
        put("kro", "kru");
        put("csb", "casubio");
        put("ta", "tamil");
        put("tkl", "tokelauano");
        put("efi", "efik");
        put("sw", "swahili");
        put("sv", "sueco");
        put("su", "sundan\u00e9s");
        put("krc", "karachay-balkar");
        put("st", "sesotho");
        put("ss", "siswati");
        put("sr", "serbio");
        put("sq", "alban\u00e9s");
        put("men", "mende");
        put("crp", "criollas y pidgins (otras)");
        put("so", "somal\u00ed");
        put("afh", "afrihili");
        put("sn", "shona");
        put("sm", "samoano");
        put("sl", "esloveno");
        put("grc", "griego antiguo (hasta el 1453)");
        put("sk", "eslovaco");
        put("grb", "gerbo");
        put("si", "singal\u00e9s");
        put("sh", "serbo-croata");
        put("crh", "turco de Crimea; t\u00e1rtaro de Crimea");
        put("afa", "afroasi\u00e1tica (otra)");
        put("sg", "sango");
        put("se", "sami septentrional");
        put("sd", "sindhi");
        put("udm", "udmurt");
        put("sc", "sardo");
        put("sa", "s\u00e1nscrito");
        put("rw", "kinyarwanda");
        put("ru", "ruso");
        put("mdr", "mandar");
        put("ro", "rumano");
        put("rn", "kiroundi");
        put("rm", "reto-romance");
        put("mdf", "moksha");
        put("tiv", "tiv");
        put("ady", "adigeo");
        put("zun", "zuni");
        put("kpe", "kpelle");
        put("qu", "quechua");
        put("tig", "tigr\u00e9");
        put("son", "songhai");
        put("cpp", "criollas y pidgins, basadas en el portugu\u00e9s (otras)");
        put("sog", "sogdiano");
        put("ada", "adangme");
        put("kos", "kosraeano");
        put("hit", "hitita");
        put("cpe", "criollas y pidgins, basadas en el ingl\u00e9s (otras)");
        put("him", "himachali");
        put("kok", "konkani");
        put("hil", "hiligaynon");
        put("got", "g\u00f3tico");
        put("gor", "gorontalo");
        put("gon", "gondi");
        put("din", "dinka");
        put("nub", "lenguas nubias");
        put("pt", "portugu\u00e9s");
        put("ps", "pashto");
        put("fur", "friulano");
        put("phn", "fenicio");
        put("goh", "alem\u00e1n de la alta edad antigua (750-1050 aprox.)");
        put("snk", "sonink\u00e9");
        put("cop", "copto");
        put("yap", "yap\u00e9s");
        put("ach", "acoli");
        put("yao", "yao");
        put("phi", "filipinas (otras)");
        put("pl", "polaco");
        put("ace", "acehn\u00e9s");
        put("pi", "pali");
        put("pa", "punjab\u00ed");
        put("bug", "bugin\u00e9s");
        put("iba", "iban");
        put("sms", "sami sklot");
        put("bua", "buriat");
        put("mas", "masai");
        put("smn", "sami inari");
        put("os", "os\u00e9tico");
        put("map", "austronesio");
        put("or", "oriya");
        put("man", "mandingo");
        put("smj", "sami lule");
        put("smi", "lenguas sami (otras)");
        put("mak", "macasar");
        put("om", "oromo");
        put("mai", "maithili");
        put("oj", "ojibwa");
        put("mag", "magahi");
        put("mad", "madur\u00e9s");
        put("sma", "sami meridional");
        put("oc", "occitano (despu\u00e9s del 1500)");
        put("nso", "sesotho septentrional");
        put("btk", "batak");
        put("myv", "erzya");
        put("dgr", "dogrib");
        put("ny", "nyanja");
        put("myn", "maya");
        put("nv", "navajo");
        put("kmb", "kimbundu");
        put("nr", "ndebele meridional");
        put("gmh", "alem\u00e1n de la alta edad media (1050-1500 aprox.)");
        put("no", "noruego");
        put("nn", "nynorsk noruego");
        put("nl", "holand\u00e9s");
        put("root", "ra\u00edz");
        put("ng", "ndonga");
        put("sla", "eslavas (otras)");
        put("ne", "nepal\u00ed");
        put("nd", "ndebele septentrional");
        put("cmc", "lenguas ch\u00e1micas");
        put("tet", "tet\u00fan");
        put("nb", "bokmal noruego");
        put("na", "nauruano");
        put("ter", "tereno");
        put("tem", "temne");
        put("my", "birmano");
        put("lez", "lezgiano");
        put("mt", "malt\u00e9s");
        put("peo", "persa antiguo (600-400 a.C. aprox.)");
        put("ms", "malayo");
        put("mr", "marathi");
        put("fro", "franc\u00e9s antiguo (842-1400 aprox.)");
        put("mo", "moldavo");
        put("frm", "franc\u00e9s medieval (1400-1600 aprox.)");
        put("mn", "mongol");
        put("jrb", "judeo-\u00e1rabe");
        put("ml", "malayalam");
        put("mk", "macedonio");
        put("mi", "maor\u00ed");
        put("mh", "marshal\u00e9s");
        put("mg", "malgache");
        put("mwr", "marwari");
        put("bra", "braj");
        put("den", "slave");
        put("lv", "let\u00f3n");
        put("lu", "luba-katanga");
        put("del", "delaware");
        put("lt", "lituano");
        put("lo", "laosiano");
        put("ln", "lingala");
        put("li", "limburgu\u00e9s");
        put("ewo", "ewondo");
        put("lg", "ganda");
        put("lb", "luxemburgu\u00e9s");
        put("la", "lat\u00edn");
        put("jpr", "judeo-persa");
        put("vot", "v\u00f3tico");
        put("sit", "sino-tibetanas (otras)");
        put("ky", "kirghiz");
        put("kw", "c\u00f3rnico");
        put("kv", "komi");
        put("ku", "kurdo");
        put("sio", "lenguas siouan");
        put("ks", "cachemiro");
        put("kr", "kanuri");
        put("awa", "avadhi");
        put("ko", "coreano");
        put("kn", "canar\u00e9s");
        put("km", "jemer");
        put("kl", "groenland\u00e9s");
        put("kk", "kazajo");
        put("rom", "roman\u00ed");
        put("kj", "kuanyama");
        put("sid", "sidamo");
        put("ki", "kikuyu");
        put("kg", "kongo");
        put("non", "norse antiguo");
        put("ka", "georgiano");
        put("mus", "creek");
        put("roa", "rom\u00e1nicas (otras)");
        put("nog", "nogai");
        put("mun", "lenguas munda");
        put("mul", "lenguas m\u00faltiples");
        put("jv", "javan\u00e9s");
        put("gil", "gilbert\u00e9s");
        put("znd", "zande");
        put("shn", "shan");
        put("fon", "fon");
        put("xal", "kalmyk");
        put("aus", "lenguas australianas");
        put("kho", "kotan\u00e9s");
        put("ja", "japon\u00e9s");
        put("khi", "khoisan (otras)");
        put("pau", "palavano");
        put("chy", "cheyene");
        put("tai", "tai (otras)");
        put("iu", "inuktitut");
        put("pap", "papiamento");
        put("it", "italiano");
        put("sgn", "lenguajes de signos");
        put("is", "island\u00e9s");
        put("kha", "khasi");
        put("chr", "cherokee");
        put("pam", "pampanga");
        put("pal", "pahlavi");
        put("chp", "chipewyan");
        put("io", "ido");
        put("cho", "choctaw");
        put("chn", "jerga chinuk");
        put("chm", "mar\u00ed");
        put("tyv", "tuviniano");
        put("bnt", "bant\u00fa");
        put("pag", "pangasin\u00e1n");
        put("ik", "inupiak");
        put("chk", "truk\u00e9s");
        put("ii", "sichuan yi");
        put("haw", "hawaiano");
        put("lam", "lamba");
        put("ig", "igbo");
        put("chg", "chagat\u00e1i");
        put("sga", "irland\u00e9s antiguo (hasta 900)");
        put("paa", "pap\u00faes (otras)");
        put("ie", "interlingue");
        put("id", "indonesio");
        put("lah", "lahnda");
        put("day", "dayak");
        put("chb", "chibcha");
        put("ia", "interlingua");
        put("lad", "ladino");
        put("hz", "herero");
        put("hai", "haida");
        put("dar", "dargva");
        put("hy", "armenio");
        put("ath", "lenguas atabascas");
        put("hu", "h\u00fangaro");
        put("ht", "haitiano");
        put("dak", "dakota");
        put("hr", "croata");
        put("ho", "hiri motu");
        put("hi", "hindi");
        put("dyu", "diula");
        put("he", "hebreo");
        put("ast", "asturiano");
        put("ha", "hausa");
        put("wen", "lenguas sorbias");
        put("gv", "ga\u00e9lico man\u00e9s");
        put("gu", "gujarati");
        put("sem", "sem\u00edticas (otras)");
        put("sel", "selkup");
        put("iro", "lenguas iroquesas");
        put("gn", "guaran\u00ed");
        put("gl", "gallego");
        put("arw", "arahuaco");
        put("gez", "geez");
        put("art", "artificiales (otras)");
        put("gd", "ga\u00e9lico escoc\u00e9s");
        put("ira", "iranio");
        put("ga", "irland\u00e9s");
        put("arp", "arapaho");
        put("arn", "araucano");
        put("fy", "fris\u00f3n");
        put("bla", "siksika");
        put("gem", "germ\u00e1nicas (otras)");
        put("ypk", "lenguas yupik");
        put("arc", "arameo");
        put("fr", "franc\u00e9s");
        put("fo", "fero\u00e9s");
        put("cel", "celtas (otras)");
        put("fj", "fidji");
        put("fi", "finland\u00e9s");
        put("ff", "fula");
        put("tvl", "tuvaluano");
        put("ceb", "cebuano");
        put("fa", "farsi");
        put("eu", "vasco");
        put("sco", "escoc\u00e9s");
        put("et", "estonio");
        put("es", "espa\u00f1ol");
        put("eo", "esperanto");
        put("en", "ingl\u00e9s");
        put("el", "griego");
        put("tut", "altaicas (otras)");
        put("niu", "niueano");
        put("tup", "lenguas tup\u00ed");
        put("ee", "ewe");
        put("tum", "tumbuka");
        put("mos", "mossi");
        put("dz", "bhutan\u00ed");
        put("nic", "n\u00edger-kordofanianas (otras)");
        put("lus", "lushai");
        put("fiu", "finougrias (otras)");
        put("dv", "divehi");
        put("nia", "nias");
        put("moh", "mohawk");
        put("luo", "luo");
        put("lun", "lunda");
        put("apa", "lenguas apache");
        put("lui", "luise\u00f1o");
        put("hup", "hupa");
        put("bin", "bini");
        put("de", "alem\u00e1n");
        put("lua", "luba-lulua");
        put("bik", "bicol");
        put("was", "washo");
        put("und", "indeterminada");
        put("war", "waray");
        put("da", "dan\u00e9s");
        put("dum", "neerland\u00e9s medio (1050-1350 aprox.)");
        put("wal", "walamo");
        put("mno", "lenguas manobo");
        put("wak", "lenguas wakasha");
        put("sat", "santali");
        put("cy", "gal\u00e9s");
        put("sas", "sasak");
        put("kbd", "kabardiana");
        put("cv", "chuvash");
        put("cu", "eslavo eclesi\u00e1stico");
        put("mni", "manipuri");
        put("cs", "checo");
        put("sam", "arameo samaritano");
        put("cr", "cree");
        put("sal", "lenguas salishan");
        put("dua", "duala");
        put("co", "corso");
        put("sai", "indias sudamericanas (otras)");
        put("mnc", "manch\u00fa");
        put("sah", "yakut");
        put("kaw", "kawi");
        put("inh", "ingush");
        put("gba", "gbaya");
        put("sad", "sandawe");
        put("ch", "chamorro");
        put("ine", "indoeuropeas (otras)");
        put("bho", "bhojpuri");
        put("enm", "ingl\u00e9s medieval (1100-1500)");
        put("kar", "karen");
        put("inc", "\u00edndicas (otras)");
        put("ce", "checheno");
        put("gay", "gayo");
        put("ca", "catal\u00e1n");
        put("umb", "umbundu");
        put("syr", "siriaco");
        put("kam", "kamba");
        put("tsi", "tsimshiano");
        put("ang", "ingl\u00e9s antiguo (450-1100 aprox.)");
        put("kac", "kachin");
        put("cau", "cauc\u00e1sicas (otras)");
        put("kab", "cabila");
        put("kaa", "karakalpako");
        put("bs", "bosnio");
        put("car", "caribe");
        put("br", "bret\u00f3n");
        put("bo", "tibetano");
        put("bn", "bengal\u00ed");
        put("bm", "bambara");
        put("gaa", "ga");
        put("cai", "indias centroamericanas (otras)");
        put("bi", "bislama");
        put("bh", "bihari");
        put("bg", "b\u00falgaro");
        put("be", "bielorruso");
        put("cad", "caddo");
        put("ba", "bashkir");
        put("zu", "zul\u00fa");
        put("zen", "zenaga");
        put("pro", "provenzal antiguo (hasta el 1500)");
        put("hsb", "sorbio superior");
        put("az", "azer\u00ed");
        put("ay", "aymara");
        put("av", "avar");
        put("as", "asam\u00e9s");
        put("dsb", "sorbio inferior");
        put("ar", "\u00e1rabe");
        put("ilo", "ilocano");
        put("elx", "elamita");
        put("zh", "chino");
        put("an", "aragon\u00e9s");
        put("pra", "lenguas prakrit");
        put("am", "am\u00e1rico");
        put("new", "newari");
        put("ak", "akan");
        put("za", "zhuang");
        put("af", "afrikaans");
        put("ae", "av\u00e9stico");
        put("ab", "abkhaziano");
        put("aa", "afar");
        put("yo", "yoruba");
        put("alg", "lenguas algonquinas");
        put("ale", "aleutiano");
        put("mkh", "mon-jemer (otras)");
        put("yi", "yidish");
        put("dra", "drav\u00eddicas (otras)");
        put("ber", "bereber");
        put("nds", "bajo alem\u00e1n; bajo saj\u00f3n");
        put("bem", "bemba");
        put("bej", "beja");
        put("tpi", "tok pisin");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final class Hashtablevariants extends java.util.Hashtable
  {
    public Hashtablevariants()
      {
        super();
        put("REVISED", "Revisado");
      }
  }

  private static final Object variants = new Hashtablevariants();

  private static final Object[][] contents =
  {
    { "currencyFormat", "\u00a4#,##0.00;(\u00a4#,##0.00)" },
    { "localPatternChars", "GuMtkHmsSEDFwWahKzUeygAZ" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "shortDateFormat", "d/MM/yy" },
    { "mediumDateFormat", "dd-MMM-yy" },
    { "longDateFormat", "d' de 'MMMM' de 'yyyy" },
    { "fullDateFormat", "EEEE d' de 'MMMM' de 'yyyy" },
    { "fullTimeFormat", "HH'H'mm''ss\" z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
    { "variants", variants },
  };

  public Object[][] getContents() { return contents; }
}
