/* LocaleInformation_zh.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_zh extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "\u4e00\u6708",
    "\u4e8c\u6708",
    "\u4e09\u6708",
    "\u56db\u6708",
    "\u4e94\u6708",
    "\u516d\u6708",
    "\u4e03\u6708",
    "\u516b\u6708",
    "\u4e5d\u6708",
    "\u5341\u6708",
    "\u5341\u4e00\u6708",
    "\u5341\u4e8c\u6708",
    null,
  };

  private static final String[] months = {
    "\u4e00\u6708",
    "\u4e8c\u6708",
    "\u4e09\u6708",
    "\u56db\u6708",
    "\u4e94\u6708",
    "\u516d\u6708",
    "\u4e03\u6708",
    "\u516b\u6708",
    "\u4e5d\u6708",
    "\u5341\u6708",
    "\u5341\u4e00\u6708",
    "\u5341\u4e8c\u6708",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "\u65e5",
    "\u4e00",
    "\u4e8c",
    "\u4e09",
    "\u56db",
    "\u4e94",
    "\u516d",
  };

  private static final String[] weekdays = {
    null,
    "\u661f\u671f\u65e5",
    "\u661f\u671f\u4e00",
    "\u661f\u671f\u4e8c",
    "\u661f\u671f\u4e09",
    "\u661f\u671f\u56db",
    "\u661f\u671f\u4e94",
    "\u661f\u671f\u516d",
  };

  private static final String[] eras = {
    "\u516c\u5143\u524d",
    "\u516c\u5143",
  };

  private static final String[] ampms = {
    "\u4e0a\u5348",
    "\u4e0b\u5348",
  };

  private static final String[][] zoneStrings =
  {
    { "America/Los_Angeles", "\u592a\u5e73\u6d0b\u6807\u51c6\u65f6\u95f4", "PST", "\u592a\u5e73\u6d0b\u590f\u4ee4\u65f6\u95f4", "PDT" },
    { "Africa/Casablanca", "\u683c\u6797\u5a01\u6cbb\u6807\u51c6\u65f6\u95f4", "GMT", "\u683c\u6797\u5a01\u6cbb\u6807\u51c6\u65f6\u95f4", "GMT" },
    { "America/New_York", "\u4e1c\u90e8\u6807\u51c6\u65f6\u95f4", "EST", "\u4e1c\u90e8\u590f\u4ee4\u65f6\u95f4", "EDT" },
    { "America/Anchorage", "\u963f\u62c9\u65af\u52a0\u6807\u51c6\u65f6\u95f4", "AST", "\u963f\u62c9\u65af\u52a0\u590f\u4ee4\u65f6\u95f4", "ADT" },
    { "Etc/GMT", "\u683c\u6797\u5a01\u6cbb\u6807\u51c6\u65f6\u95f4", "GMT", "\u683c\u6797\u5a01\u6cbb\u6807\u51c6\u65f6\u95f4", "GMT" },
    { "Asia/Shanghai", "\u4e2d\u56fd\u6807\u51c6\u65f6\u95f4", "CTT", "\u4e2d\u56fd\u6807\u51c6\u65f6\u95f4", "CDT" },
    { "America/Halifax", "\u5927\u897f\u6d0b\u6807\u51c6\u65f6\u95f4", "AST", "\u5927\u897f\u6d0b\u590f\u4ee4\u65f6\u95f4", "ADT" },
    { "Europe/Paris", "\u4e2d\u6b27\u6807\u51c6\u65f6\u95f4", "CET", "\u4e2d\u6b27\u590f\u4ee4\u65f6\u95f4", "CEST" },
    { "America/Denver", "\u5c71\u533a\u6807\u51c6\u65f6\u95f4", "MST", "\u5c71\u533a\u590f\u4ee4\u65f6\u95f4", "MDT" },
    { "Asia/Jerusalem", "\u4ee5\u8272\u5217\u6807\u51c6\u65f6\u95f4", "IST", "\u4ee5\u8272\u5217\u590f\u4ee4\u65f6\u95f4", "IDT" },
    { "Pacific/Honolulu", "\u590f\u5a01\u5937\u6807\u51c6\u65f6\u95f4", "HST", "\u590f\u5a01\u5937\u6807\u51c6\u65f6\u95f4", "HST" },
    { "America/St_Johns", "\u7ebd\u82ac\u5170\u6807\u51c6\u65f6\u95f4", "CNT", "\u7ebd\u82ac\u5170\u590f\u4ee4\u65f6\u95f4", "CDT" },
    { "America/Indianapolis", "\u4e1c\u90e8\u6807\u51c6\u65f6\u95f4", "EST", "\u4e1c\u90e8\u6807\u51c6\u65f6\u95f4", "EST" },
    { "America/Chicago", "\u4e2d\u592e\u6807\u51c6\u65f6\u95f4", "CST", "\u4e2d\u592e\u590f\u4ee4\u65f6\u95f4", "CDT" },
    { "Europe/Bucharest", "\u4e1c\u6b27\u6807\u51c6\u65f6\u95f4", "EET", "\u4e1c\u6b27\u590f\u4ee4\u65f6\u95f4", "EEST" },
    { "Asia/Tokyo", "\u65e5\u672c\u6807\u51c6\u65f6\u95f4", "JST", "\u65e5\u672c\u6807\u51c6\u65f6\u95f4", "JST" },
    { "America/Phoenix", "\u5c71\u533a\u6807\u51c6\u65f6\u95f4", "MST", "\u5c71\u533a\u6807\u51c6\u65f6\u95f4", "MST" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "\u4e1c\u5e1d\u6c76");
        put("TK", "\u6258\u514b\u52b3");
        put("TJ", "\u5854\u5409\u514b\u65af\u5766");
        put("TH", "\u6cf0\u56fd");
        put("TG", "\u591a\u54e5");
        put("TF", "\u6cd5\u5c5e\u5357\u534a\u7403\u9886\u5730");
        put("GY", "\u572d\u4e9a\u90a3");
        put("TD", "\u4e4d\u5f97");
        put("TC", "\u7279\u514b\u65af\u548c\u51ef\u79d1\u65af\u7fa4\u5c9b");
        put("GW", "\u51e0\u5185\u4e9a\u6bd4\u7ecd");
        put("GU", "\u5173\u5c9b");
        put("GT", "\u5371\u5730\u9a6c\u62c9");
        put("GS", "\u5357\u4f50\u6cbb\u4e9a\u548c\u5357\u4e09\u660e\u6cbb\u7fa4\u5c9b");
        put("GR", "\u5e0c\u814a");
        put("GQ", "\u8d64\u9053\u51e0\u5185\u4e9a");
        put("GP", "\u74dc\u5fb7\u7f57\u666e\u5c9b");
        put("SZ", "\u65af\u5a01\u58eb\u5170");
        put("SY", "\u53d9\u5229\u4e9a");
        put("GN", "\u51e0\u5185\u4e9a");
        put("GM", "\u5188\u6bd4\u4e9a");
        put("GL", "\u683c\u9675\u5170");
        put("SV", "\u8428\u5c14\u74e6\u591a");
        put("ST", "\u5723\u591a\u7f8e\u548c\u666e\u6797\u897f\u6bd4");
        put("GI", "\u76f4\u5e03\u7f57\u9640");
        put("GH", "\u52a0\u7eb3");
        put("SR", "\u82cf\u91cc\u5357");
        put("GF", "\u6cd5\u5c5e\u572d\u4e9a\u90a3");
        put("SP", "\u585e\u5c14\u7ef4\u4e9a");
        put("GE", "\u683c\u9c81\u5409\u4e9a");
        put("SO", "\u7d22\u9a6c\u91cc");
        put("GD", "\u683c\u6797\u7eb3\u8fbe");
        put("SN", "\u585e\u5185\u52a0\u5c14");
        put("SM", "\u5723\u9a6c\u529b\u8bfa");
        put("GB", "\u82f1\u56fd");
        put("SL", "\u585e\u62c9\u5229\u6602");
        put("GA", "\u52a0\u84ec");
        put("SK", "\u65af\u6d1b\u4f10\u514b");
        put("SJ", "\u65af\u74e6\u5c14\u5df4\u7279\u548c\u626c\u9a6c\u5ef6");
        put("SI", "\u65af\u6d1b\u6587\u5c3c\u4e9a");
        put("SH", "\u5723\u8d6b\u52d2\u62ff");
        put("SG", "\u65b0\u52a0\u5761");
        put("SE", "\u745e\u5178");
        put("SD", "\u82cf\u4e39");
        put("SC", "\u585e\u820c\u5c14");
        put("SB", "\u6240\u7f57\u95e8\u7fa4\u5c9b");
        put("SA", "\u6c99\u7279\u963f\u62c9\u4f2f");
        put("FR", "\u6cd5\u56fd");
        put("FO", "\u6cd5\u7f57\u7fa4\u5c9b");
        put("FM", "\u5bc6\u514b\u7f57\u5c3c\u897f\u4e9a\u8054\u90a6");
        put("RW", "\u5362\u65fa\u8fbe");
        put("FK", "\u798f\u514b\u5170\u7fa4\u5c9b");
        put("RU", "\u4fc4\u7f57\u65af\u8054\u90a6");
        put("FJ", "\u6590\u6d4e");
        put("FI", "\u82ac\u5170");
        put("RO", "\u7f57\u9a6c\u5c3c\u4e9a");
        put("RE", "\u7559\u5c3c\u6c6a");
        put("ET", "\u57c3\u585e\u4fc4\u6bd4\u4e9a");
        put("ES", "\u897f\u73ed\u7259");
        put("ER", "\u5384\u7acb\u7279\u91cc\u4e9a");
        put("EH", "\u897f\u6492\u54c8\u62c9");
        put("EG", "\u57c3\u53ca");
        put("EE", "\u7231\u6c99\u5c3c\u4e9a");
        put("EC", "\u5384\u74dc\u591a\u5c14");
        put("DZ", "\u963f\u5c14\u53ca\u5229\u4e9a");
        put("QA", "\u5361\u5854\u5c14");
        put("DO", "\u591a\u7c73\u5c3c\u52a0\u5171\u548c\u56fd");
        put("PY", "\u5df4\u62c9\u572d");
        put("DM", "\u591a\u7c73\u5c3c\u52a0\u5c98");
        put("PW", "\u5e15\u52b3");
        put("DK", "\u4e39\u9ea6");
        put("DJ", "\u5409\u5e03\u63d0");
        put("PT", "\u8461\u8404\u7259");
        put("PS", "\u5df4\u52d2\u65af\u5766\u9886\u571f");
        put("PR", "\u6ce2\u591a\u9ece\u5404");
        put("DE", "\u5fb7\u56fd");
        put("PN", "\u76ae\u7279\u51ef\u6069");
        put("PM", "\u5723\u76ae\u57c3\u5c14\u548c\u5bc6\u514b\u9686");
        put("PL", "\u6ce2\u5170");
        put("PK", "\u5df4\u57fa\u65af\u5766");
        put("PH", "\u83f2\u5f8b\u5bbe");
        put("PG", "\u5df4\u5e03\u4e9a\u65b0\u51e0\u5185\u4e9a");
        put("PF", "\u6cd5\u5c5e\u6ce2\u5229\u5c3c\u897f\u4e9a");
        put("CZ", "\u6377\u514b\u5171\u548c\u56fd");
        put("PE", "\u79d8\u9c81");
        put("CY", "\u585e\u6d66\u8def\u65af");
        put("CX", "\u5723\u8bde\u5c9b");
        put("CV", "\u4f5b\u5f97\u89d2");
        put("PA", "\u5df4\u62ff\u9a6c");
        put("CU", "\u53e4\u5df4");
        put("CR", "\u54e5\u65af\u8fbe\u9ece\u52a0");
        put("CO", "\u54e5\u4f26\u6bd4\u4e9a");
        put("CN", "\u4e2d\u56fd");
        put("CM", "\u5580\u9ea6\u9686");
        put("CL", "\u667a\u5229");
        put("CK", "\u5e93\u514b\u7fa4\u5c9b");
        put("CI", "\u8c61\u7259\u6d77\u5cb8");
        put("CH", "\u745e\u58eb");
        put("CG", "\u521a\u679c");
        put("CF", "\u4e2d\u975e\u5171\u548c\u56fd");
        put("CD", "\u521a\u679c\u6c11\u4e3b\u5171\u548c\u56fd");
        put("CC", "\u79d1\u79d1\u65af\u7fa4\u5c9b");
        put("OM", "\u963f\u66fc");
        put("CA", "\u52a0\u62ff\u5927");
        put("BZ", "\u4f2f\u5229\u5179");
        put("BY", "\u767d\u4fc4\u7f57\u65af");
        put("BW", "\u535a\u8328\u74e6\u7eb3");
        put("BV", "\u5e03\u7ef4\u7279\u5c9b");
        put("BT", "\u4e0d\u4e39");
        put("BS", "\u5df4\u54c8\u9a6c");
        put("BR", "\u5df4\u897f");
        put("NZ", "\u65b0\u897f\u5170");
        put("BO", "\u73bb\u5229\u7ef4\u4e9a");
        put("BN", "\u6587\u83b1");
        put("BM", "\u767e\u6155\u5927");
        put("NU", "\u7ebd\u57c3");
        put("BJ", "\u8d1d\u5b81");
        put("BI", "\u5e03\u9686\u8fea");
        put("BH", "\u5df4\u6797");
        put("NR", "\u7459\u9c81");
        put("BG", "\u4fdd\u52a0\u5229\u4e9a");
        put("BF", "\u5e03\u57fa\u7eb3\u6cd5\u7d22");
        put("NP", "\u5c3c\u6cca\u5c14");
        put("BE", "\u6bd4\u5229\u65f6");
        put("NO", "\u632a\u5a01");
        put("BD", "\u5b5f\u52a0\u62c9\u56fd");
        put("BB", "\u5df4\u5df4\u591a\u65af");
        put("ZW", "\u6d25\u5df4\u5e03\u97e6");
        put("NL", "\u8377\u5170");
        put("BA", "\u6ce2\u65af\u5c3c\u4e9a\u548c\u9ed1\u5c71\u5171\u548c\u56fd");
        put("NI", "\u5c3c\u52a0\u62c9\u74dc");
        put("NG", "\u5c3c\u65e5\u5229\u4e9a");
        put("NF", "\u8bfa\u798f\u514b\u5c9b");
        put("AZ", "\u963f\u585e\u62dc\u7586");
        put("NE", "\u5c3c\u65e5\u5c14");
        put("NC", "\u65b0\u5580\u91cc\u591a\u5c3c\u4e9a");
        put("AW", "\u963f\u9c81\u5df4");
        put("ZM", "\u8d5e\u6bd4\u4e9a");
        put("NA", "\u7eb3\u7c73\u6bd4\u4e9a");
        put("AU", "\u6fb3\u5927\u5229\u4e9a");
        put("AT", "\u5965\u5730\u5229");
        put("AS", "\u7f8e\u5c5e\u8428\u6469\u4e9a");
        put("AR", "\u963f\u6839\u5ef7");
        put("AQ", "\u5357\u6781\u6d32");
        put("MZ", "\u83ab\u6851\u6bd4\u514b");
        put("AO", "\u5b89\u54e5\u62c9");
        put("MY", "\u9a6c\u6765\u897f\u4e9a");
        put("AN", "\u8377\u5c5e\u5b89\u7684\u5217\u65af\u7fa4\u5c9b");
        put("MX", "\u58a8\u897f\u54e5");
        put("AM", "\u4e9a\u7f8e\u5c3c\u4e9a");
        put("MW", "\u9a6c\u62c9\u7ef4");
        put("AL", "\u963f\u5c14\u5df4\u5c3c\u4e9a");
        put("MV", "\u9a6c\u5c14\u4ee3\u592b");
        put("ZA", "\u5357\u975e");
        put("MU", "\u6bdb\u91cc\u6c42\u65af");
        put("MT", "\u9a6c\u8033\u4ed6");
        put("AI", "\u5b89\u572d\u62c9");
        put("MS", "\u8499\u7279\u585e\u62c9\u7fa4\u5c9b");
        put("MR", "\u6bdb\u91cc\u5854\u5c3c\u4e9a");
        put("AG", "\u5b89\u63d0\u74dc\u548c\u5df4\u5e03\u8fbe");
        put("MQ", "\u9a6c\u63d0\u5c3c\u514b\u5c9b");
        put("AF", "\u963f\u5bcc\u6c57");
        put("MP", "\u5317\u9a6c\u91cc\u4e9a\u7eb3\u7fa4\u5c9b");
        put("AE", "\u963f\u62c9\u4f2f\u8054\u5408\u914b\u957f\u56fd");
        put("MO", "\u4e2d\u56fd\u6fb3\u95e8\u7279\u522b\u884c\u653f\u533a");
        put("AD", "\u5b89\u9053\u5c14");
        put("MN", "\u8499\u53e4");
        put("MM", "\u7f05\u7538");
        put("ML", "\u9a6c\u91cc");
        put("MK", "\u9a6c\u5176\u987f\u738b\u56fd");
        put("YU", "\u5357\u65af\u62c9\u592b");
        put("YT", "\u9a6c\u7ea6\u7279");
        put("MH", "\u9a6c\u7ecd\u5c14\u7fa4\u5c9b");
        put("MG", "\u9a6c\u8fbe\u52a0\u65af\u52a0");
        put("MD", "\u6469\u5c14\u591a\u74e6\u5171\u548c\u56fd");
        put("MC", "\u6469\u7eb3\u54e5");
        put("MA", "\u6469\u6d1b\u54e5");
        put("YE", "\u4e5f\u95e8");
        put("LY", "\u5229\u6bd4\u4e9a");
        put("LV", "\u62c9\u8131\u7ef4\u4e9a");
        put("LU", "\u5362\u68ee\u5821");
        put("LT", "\u7acb\u9676\u5b9b");
        put("LS", "\u83b1\u7d22\u6258");
        put("LR", "\u5229\u6bd4\u91cc\u4e9a");
        put("LK", "\u65af\u91cc\u5170\u5361");
        put("LI", "\u5217\u652f\u6566\u58eb\u767b");
        put("LC", "\u5723\u5362\u897f\u4e9a");
        put("LB", "\u9ece\u5df4\u5ae9");
        put("LA", "\u8001\u631d\u4eba\u6c11\u6c11\u4e3b\u5171\u548c\u56fd");
        put("KZ", "\u54c8\u8428\u514b\u65af\u5766");
        put("KY", "\u5f00\u66fc\u7fa4\u5c9b");
        put("KW", "\u79d1\u5a01\u7279");
        put("KR", "\u97e9\u56fd");
        put("KP", "\u5317\u671d\u9c9c");
        put("KN", "\u5723\u57fa\u8328\u548c\u5c3c\u7ef4\u65af");
        put("KM", "\u79d1\u6469\u7f57");
        put("KI", "\u57fa\u91cc\u5df4\u65af");
        put("WS", "\u8428\u6469\u4e9a");
        put("KH", "\u67ec\u57d4\u5be8");
        put("KG", "\u5409\u5c14\u5409\u514b\u65af\u5766");
        put("KE", "\u80af\u5c3c\u4e9a");
        put("WF", "\u74e6\u5229\u65af\u548c\u5bcc\u56fe\u7eb3");
        put("JP", "\u65e5\u672c");
        put("JO", "\u7ea6\u65e6");
        put("JM", "\u7259\u4e70\u52a0");
        put("VU", "\u74e6\u52aa\u963f\u56fe");
        put("VN", "\u8d8a\u5357");
        put("VI", "\u7f8e\u5c5e\u7ef4\u4eac\u7fa4\u5c9b");
        put("VG", "\u82f1\u5c5e\u7ef4\u4eac\u7fa4\u5c9b");
        put("VE", "\u59d4\u5185\u745e\u62c9");
        put("VC", "\u5723\u6587\u68ee\u7279\u548c\u683c\u6797\u7eb3\u4e01\u65af");
        put("VA", "\u68b5\u8482\u5188");
        put("IT", "\u610f\u5927\u5229");
        put("IS", "\u51b0\u5c9b");
        put("IR", "\u4f0a\u6717");
        put("IQ", "\u4f0a\u62c9\u514b");
        put("UZ", "\u4e4c\u5179\u522b\u514b\u65af\u5766");
        put("IO", "\u82f1\u5c5e\u5370\u5ea6\u6d0b\u9886\u5730");
        put("UY", "\u4e4c\u62c9\u572d");
        put("IN", "\u5370\u5ea6");
        put("IL", "\u4ee5\u8272\u5217");
        put("US", "\u7f8e\u56fd");
        put("IE", "\u7231\u5c14\u5170");
        put("ID", "\u5370\u5ea6\u5c3c\u897f\u4e9a");
        put("UM", "\u7f8e\u56fd\u8fb9\u8fdc\u5c0f\u5c9b");
        put("UG", "\u4e4c\u5e72\u8fbe");
        put("UA", "\u4e4c\u514b\u5170");
        put("HU", "\u5308\u7259\u5229");
        put("HT", "\u6d77\u5730");
        put("HR", "\u514b\u7f57\u5730\u4e9a");
        put("TZ", "\u5766\u6851\u5c3c\u4e9a");
        put("HN", "\u6d2a\u90fd\u62c9\u65af");
        put("HM", "\u8d6b\u5fb7\u4e0e\u9ea6\u514b\u5510\u7eb3\u7fa4\u5c9b");
        put("TW", "\u53f0\u6e7e");
        put("TV", "\u56fe\u74e6\u5362");
        put("HK", "\u4e2d\u56fd\u9999\u6e2f\u7279\u522b\u884c\u653f\u533a");
        put("TT", "\u7279\u7acb\u5c3c\u8fbe\u548c\u591a\u5df4\u54e5");
        put("TR", "\u571f\u8033\u5176");
        put("TO", "\u6c64\u52a0");
        put("TN", "\u7a81\u5c3c\u65af");
        put("TM", "\u571f\u5e93\u66fc\u65af\u5766");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final class Hashtablelanguages extends java.util.Hashtable
  {
    public Hashtablelanguages()
      {
        super();
        put("gwi", "\u5409\u7ef4\u514b\u7434\u6587");
        put("akk", "\u963f\u5361\u5fb7\u6587");
        put("ijo", "\u4f0a\u4e54\u6587");
        put("xh", "\u73ed\u56fe\u6587");
        put("sux", "\u82cf\u9a6c\u6587");
        put("sus", "\u82cf\u82cf\u6587");
        put("mis", "\u5404\u79cd\u4e0d\u540c\u8bed\u8a00");
        put("loz", "\u6d1b\u5179\u6587");
        put("tog", "\u6c64\u52a0\u6587\uff08\u5c3c\u4e9a\u8428\u5730\u533a\uff09");
        put("pon", "\u6ce2\u90a3\u8d1d\u6587");
        put("min", "\u7c73\u5357\u5361\u4fdd\u6587");
        put("suk", "\u82cf\u5e93\u9a6c\u6587");
        put("wo", "\u6c83\u5c14\u592b\u6587");
        put("lol", "\u8499\u53e4\u6587");
        put("kut", "\u5e93\u7279\u5185\u6587");
        put("mic", "\u7c73\u514b\u9a6c\u514b\u6587");
        put("wa", "\u83ef\u9686\u6587");
        put("kum", "\u5e93\u6885\u514b\u6587");
        put("zap", "\u8428\u6ce2\u8482\u514b\u6587");
        put("cus", "\u5176\u4ed6\u5e93\u65bd\u7279\u8bed\u7cfb");
        put("jbo", "\u6d1b\u5409\u822c\uff08\u4eba\u5de5\u8bed\u8a00\uff09");
        put("doi", "\u591a\u683c\u6765\u6587");
        put("vo", "\u6c83\u62c9\u666e\u514b\u6587");
        put("oto", "\u5965\u6258\u7c73\u8bed\u7cfb");
        put("vi", "\u8d8a\u5357\u6587");
        put("vai", "\u74e6\u4f0a\u6587");
        put("rar", "\u62c9\u7f57\u6c64\u52a0\u6587");
        put("ve", "\u6587\u8fbe\u6587");
        put("rap", "\u62c9\u5e15\u52aa\u6587");
        put("raj", "\u62c9\u8d3e\u65af\u5766\u6587");
        put("ota", "\u5965\u6258\u66fc\u571f\u8033\u5176\u6587");
        put("nzi", "\u5c3c\u5179\u739b\u6587");
        put("nap", "\u62ff\u6ce2\u91cc\u6587");
        put("uz", "\u4e4c\u5179\u522b\u514b\u6587");
        put("uga", "\u4e4c\u52a0\u91cc\u7279\u6587");
        put("tmh", "\u5854\u739b\u538d\u514b\u6587");
        put("nai", "\u5176\u4ed6\u5317\u7f8e\u5370\u7b2c\u5b89\u8bed\u7cfb");
        put("nah", "\u7eb3\u74e6\u7279\u5c14\u6587");
        put("ur", "\u4e4c\u5c14\u90fd\u6587");
        put("fat", "\u82b3\u8482\u6587");
        put("uk", "\u4e4c\u514b\u5170\u6587");
        put("ug", "\u7ef4\u543e\u5c14\u6587");
        put("fan", "\u82b3\u683c\u6587");
        put("ssa", "\u5176\u4ed6\u5c3c\u7f57\u8428\u54c8\u5170\u6587");
        put("mga", "\u4e2d\u53e4\u7231\u5c14\u5170\u6587");
        put("bat", "\u6ce2\u7f57\u7684\u6d77\u5730\u533a\u4e4b\u8bed\u8a00");
        put("nyo", "\u5c3c\u7ea6\u7f57\u8bed\u65cf");
        put("bas", "\u5df4\u8428\u6587");
        put("nyn", "\u5c3c\u6602\u79d1\u52d2\u6587");
        put("nym", "\u5c3c\u4e9a\u59c6\u97e6\u9f50\u6587");
        put("hmn", "\u8d6b\u8499\u6587");
        put("ban", "\u5df4\u91cc\u6587");
        put("osa", "\u5965\u8428\u54f2\u6587");
        put("bal", "\u4ffe\u8def\u652f\u6587");
        put("ty", "\u5854\u897f\u63d0\u6587");
        put("bai", "\u5df4\u7c73\u7d2f\u514b\u6587");
        put("tw", "\u53f0\u6e7e\u6587");
        put("srr", "\u8c22\u5217\u5c14\u6587");
        put("tli", "\u7279\u6797\u5409\u7279\u6587");
        put("tt", "\u9791\u977c\u6587");
        put("ts", "\u7279\u677e\u52a0\u6587");
        put("bad", "\u73ed\u8fbe\u6587");
        put("tr", "\u571f\u8033\u5176\u6587");
        put("to", "\u6c64\u52a0\u6587");
        put("tn", "\u7a81\u5c3c\u65af\u6587");
        put("tl", "\u5854\u52a0\u8def\u65cf\u6587");
        put("tk", "\u571f\u5e93\u66fc\u6587");
        put("ti", "\u63d0\u683c\u91cc\u5c3c\u4e9a\u6587");
        put("th", "\u6cf0\u6587");
        put("kru", "\u5e93\u9c81\u514b\u6587");
        put("tg", "\u5854\u5409\u514b\u6587");
        put("byn", "\u5e03\u6797\u6587");
        put("te", "\u6cf0\u5362\u56fa\u6587");
        put("kro", "\u514b\u9c81\u6587");
        put("csb", "\u5361\u8212\u6587");
        put("ta", "\u6cf0\u7c73\u5c14\u6587");
        put("tkl", "\u9640\u514b\u5a04\u6587");
        put("sw", "\u65af\u74e6\u5e0c\u91cc\u6587");
        put("sv", "\u745e\u5178\u6587");
        put("su", "\u82cf\u4e39\u6587");
        put("krc", "\u5361\u62c9\u5361\u5c14\u5e15\u514b\u6587");
        put("st", "\u585e\u7d22\u6258\u6587");
        put("ss", "\u8f9b\u8f9b\u90a3\u63d0\u6587");
        put("sr", "\u585e\u5c14\u7ef4\u4e9a\u6587");
        put("sq", "\u963f\u5c14\u5df4\u5c3c\u4e9a\u6587");
        put("men", "\u95e8\u8fea\u6587");
        put("crp", "\u514b\u91cc\u5965\u5c14\u8bed\u548c\u76ae\u94a6\u6587");
        put("so", "\u7d22\u9a6c\u91cc\u6587");
        put("afh", "\u963f\u5f17\u91cc\u5e0c\u5229\u6587");
        put("sn", "\u585e\u5185\u52a0\u5c14\u6587");
        put("sm", "\u8428\u6469\u4e9a\u6587");
        put("sl", "\u65af\u6d1b\u6587\u5c3c\u4e9a\u6587");
        put("grc", "\u53e4\u5e0c\u814a\u6587");
        put("sk", "\u65af\u6d1b\u4f10\u514b\u6587");
        put("grb", "\u683c\u5217\u535a\u6587");
        put("si", "\u50e7\u4f3d\u7f57\u6587");
        put("sh", "\u585e\u6ce2\u5c3c\u65af-\u514b\u7f57\u5730\u4e9a\u6587");
        put("crh", "\u514b\u91cc\u7c73\u4e9a\u571f\u8033\u5176\u6587\uff1b\u514b\u91cc\u7c73\u4e9a\u5854\u5854\u6587");
        put("afa", "\u5176\u4ed6\u4e9a\u975e\u8bed\u7cfb");
        put("sg", "\u6851\u6208\u6587");
        put("se", "\u5317\u8428\u8ff7\u6587");
        put("sd", "\u82cf\u4e39\u6587");
        put("udm", "\u4e4c\u5fb7\u7a46\u5c14\u7279\u6587");
        put("sc", "\u8428\u4e01\u6587");
        put("sa", "\u68b5\u6587");
        put("rw", "\u5362\u65fa\u8fbe\u6587");
        put("ru", "\u4fc4\u6587");
        put("mdr", "\u66fc\u8fbe\u5c14");
        put("ro", "\u7f57\u9a6c\u5c3c\u4e9a\u6587");
        put("rn", "\u57fa\u9686\u8fea\u6587");
        put("rm", "\u91cc\u6258\u7f57\u66fc\u65af\u6587");
        put("mdf", "\u83ab\u514b\u6c99\u6587");
        put("tiv", "\u8482\u592b\u6587");
        put("ady", "\u963f\u8fea\u4f55\u6587");
        put("zun", "\u7956\u5c3c\u8bed");
        put("kpe", "\u514b\u4f69\u5217\u6587");
        put("qu", "\u76d6\u4e18\u4e9a\u6587");
        put("tig", "\u63d0\u683c\u96f7\u6587");
        put("son", "\u6851\u6d77\u6587");
        put("cpp", "\u4e0d\u7eaf\u7cb9\u4e4b\u8461\u56fd\u65b9\u8a00");
        put("sog", "\u7d22\u683c\u8fea\u4e9a\u6587");
        put("ada", "\u963f\u5f53\u6885\u6587");
        put("kos", "\u67ef\u53f8\u745e\u6069\u6587");
        put("hit", "\u897f\u53f0\u6587");
        put("cpf", "\u4e0d\u7eaf\u7cb9\u4e4b\u6cd5\u56fd\u65b9\u8a00");
        put("cpe", "\u4e0d\u7eaf\u7cb9\u4e4b\u82f1\u56fd\u65b9\u8a00");
        put("him", "\u8d6b\u9a6c\u67e5\u5229\u6587");
        put("kok", "\u521a\u5361\u5c3c\u6587");
        put("hil", "\u5e0c\u5229\u76d6\u519c\u6587");
        put("got", "\u54e5\u8fbe\u6587");
        put("gor", "\u79d1\u6d1b\u6d85\u8fbe\u7f57\u6587");
        put("gon", "\u5c97\u5fb7\u6587");
        put("din", "\u4e01\u5361\u6587");
        put("nub", "\u52aa\u6bd4\u4e9a\u6587");
        put("pt", "\u8461\u8404\u7259\u6587");
        put("ps", "\u666e\u4ec0\u56fe\u6587");
        put("fur", "\u5f17\u7559\u5229\u6587");
        put("phn", "\u8153\u5229\u57fa\u6587");
        put("goh", "\u53e4\u4ee3\u9ad8\u5730\u5fb7\u6587");
        put("snk", "\u7d22\u5c3c\u57fa\u6587");
        put("cop", "\u79d1\u666e\u7279\u6587");
        put("yap", "\u96c5\u6d66\u6587");
        put("ach", "\u963f\u4e54\u5229\u6587");
        put("yao", "\u7476\u65cf\u6587");
        put("phi", "\u5176\u4ed6\u83f2\u5f8b\u5bbe\u8bed\u7cfb");
        put("pl", "\u6ce2\u5170\u6587");
        put("ace", "\u4e9a\u9f50\u6587");
        put("pi", "\u5e15\u5229\u6587");
        put("pa", "\u65c1\u906e\u666e\u6587");
        put("bug", "\u5e03\u5409\u6587");
        put("iba", "\u4f0a\u73ed\u6587");
        put("sms", "\u53f8\u5bc7\u7279\u8428\u8ff7\u6587");
        put("bua", "\u5e03\u91cc\u4e9a\u7279\u6587");
        put("mas", "\u8428\u4f0a\u8bed");
        put("smn", "\u4f9d\u7eb3\u65e5\u8428\u8ff7\u6587");
        put("os", "\u5965\u585e\u63d0\u6587");
        put("map", "\u9a6c\u6765\u4e9a\u73bb\u91cc\u5c3c\u897f\u4e9a\u8bed\u7cfb");
        put("or", "\u6b27\u91cc\u4e9a\u6587");
        put("man", "\u66fc\u4e01\u54e5\u6587");
        put("smj", "\u5362\u4e50\u8428\u8ff7\u6587");
        put("smi", "\u5176\u4ed6\u8428\u8ff7\u6587");
        put("mak", "\u671b\u52a0\u9521\u6587");
        put("om", "\u963f\u66fc\u6587");
        put("mai", "\u8fc8\u8482\u5229\u6587");
        put("oj", "\u5965\u5b63\u5e03\u74e6\u6587");
        put("mag", "\u9a6c\u52a0\u4f0a\u6587");
        put("mad", "\u9a6c\u90fd\u62c9\u6587");
        put("sma", "\u5357\u8428\u8ff7\u6587");
        put("oc", "\u5965\u897f\u5766\u6587");
        put("nso", "\u5317\u7d22\u6258\u6587");
        put("btk", "\u5df4\u5854\u514b\u6587");
        put("myv", "\u4fc4\u65e5\u4e9a\u6587");
        put("dgr", "\u591a\u683c\u6765\u6587");
        put("ny", "\u5c3c\u6602\u52a0\u6587\uff1b\u5207\u74e6\u6587\uff1b\u5207\u74e6\u6587");
        put("myn", "\u739b\u96c5\u6587");
        put("nv", "\u7eb3\u74e6\u970d\u6587");
        put("kmb", "\u91d1\u90a6\u675c\u6587");
        put("nr", "\u5357\u90e8\u6069\u5fb7\u8d1d\u52d2\u6587");
        put("gmh", "\u4e2d\u53e4\u9ad8\u5730\u5fb7\u6587");
        put("no", "\u632a\u5a01\u6587");
        put("nn", "\u632a\u5a01\u5c3c\u8bfa\u65af\u514b\u6587");
        put("nl", "\u8377\u5170\u6587");
        put("ng", "\u6069\u4e1c\u52a0\u6587");
        put("sla", "\u5176\u4ed6\u65af\u62c9\u592b\u8bed\u7cfb");
        put("ne", "\u5c3c\u6cca\u5c14\u6587");
        put("nd", "\u5317\u6069\u5fb7\u8d1d\u52d2\u6587");
        put("cmc", "\u67e5\u7c73\u514b\u6587");
        put("tet", "\u7279\u56fe\u4eec\u6587");
        put("nb", "\u632a\u5a01\u535a\u514b\u9a6c\u5c14\u6587");
        put("na", "\u7459\u9c81\u6587");
        put("ter", "\u7279\u558f\u8bfa\u6587");
        put("tem", "\u4f53\u59c6\u5450\u6587");
        put("my", "\u7f05\u7538\u6587");
        put("lez", "\u83b1\u5179\u4f9d\u6602\u6587");
        put("mt", "\u9a6c\u8033\u4ed6\u6587");
        put("peo", "\u53e4\u8001\u6ce2\u65af\u8bed");
        put("ms", "\u9a6c\u6765\u6587");
        put("mr", "\u9a6c\u62c9\u5730\u6587");
        put("fro", "\u53e4\u6cd5\u6587");
        put("mo", "\u6469\u5c14\u591a\u74e6\u6587");
        put("frm", "\u4e2d\u53e4\u6cd5\u6587");
        put("mn", "\u8499\u53e4\u6587");
        put("jrb", "\u72b9\u592a\u963f\u62c9\u4f2f\u8bed\u7cfb");
        put("ml", "\u9a6c\u6765\u4e9a\u62c9\u59c6\u6587");
        put("mk", "\u9a6c\u5176\u987f\u6587");
        put("mi", "\u6bdb\u5229\u6587");
        put("mh", "\u9a6c\u7ecd\u5c14\u6587");
        put("mg", "\u9a6c\u5c14\u52a0\u4ec0\u6587");
        put("mwr", "\u9a6c\u5c14\u5c3c\u91cc\u6587");
        put("bra", "\u5e03\u62c9\u6770\u6587");
        put("den", "\u53f8\u96f7\u592b\u6587");
        put("lv", "\u62c9\u812b\u7dad\u4e9e\u6587");
        put("lu", "\u9c81\u5df4\u52a0\u4e39\u52a0\u6587");
        put("del", "\u7279\u62c9\u74e6\u5370\u7b2c\u5b89\u4eba\u6587");
        put("lt", "\u7acb\u9676\u5b9b\u6587");
        put("lo", "\u8001\u631d\u6587");
        put("ln", "\u6797\u52a0\u62c9\u6587");
        put("li", "\u6dcb\u5e03\u5c14\u5409\u6587");
        put("ewo", "\u65fa\u675c\u6587");
        put("lg", "\u5362\u5e72\u8fbe\u6587");
        put("lb", "\u5362\u68ee\u5821\u6587");
        put("la", "\u62c9\u4e01\u6587");
        put("jpr", "\u72b9\u592a\u6ce2\u65af\u8bed\u7cfb");
        put("vot", "\u6c83\u63d0\u514b\u6587");
        put("sit", "\u5176\u4ed6\u6c49\u85cf\u8bed\u7cfb");
        put("ky", "\u5409\u5c14\u5409\u65af\u6587");
        put("kw", "\u51ef\u5c14\u7279\u6587");
        put("kv", "\u79d1\u7c73\u6587");
        put("ku", "\u5e93\u5c14\u5fb7\u6587");
        put("sio", "\u82cf\u8bed\u8bf8\u8bed\u8a00");
        put("ks", "\u514b\u4ec0\u7c73\u5c14\u6587");
        put("kr", "\u5361\u52aa\u91cc\u6587");
        put("awa", "\u963f\u74e6\u4e54\u6587");
        put("ko", "\u97e9\u6587");
        put("kn", "\u57c3\u7eb3\u5fb7\u6587");
        put("km", "\u67ec\u57d4\u5be8\u6587");
        put("kl", "\u683c\u9675\u5170\u6587");
        put("kk", "\u54c8\u8428\u514b\u6587");
        put("rom", "\u5409\u666e\u8d5b\u6587");
        put("kj", "\u5173\u740a\u739b\u6587");
        put("sid", "\u6089\u8fbe\u6469\u6587");
        put("ki", "\u5409\u5e93\u5c24\u6587");
        put("kg", "\u521a\u679c\u6587");
        put("non", "\u53e4\u8bfa\u5c14\u65af\u6587");
        put("ka", "\u683c\u9c81\u5409\u4e9a\u6587");
        put("mus", "\u6469\u65af\u79d1\u683c\u6587");
        put("roa", "\u5176\u4ed6\u62c9\u4e01\u8bed\u7cfb");
        put("nog", "\u8bfa\u76d6\u6587");
        put("mun", "\u8499\u8fbe\u6587");
        put("mul", "\u591a\u79cd\u8bed\u8a00");
        put("jv", "\u722a\u54c7\u6587");
        put("gil", "\u5409\u5c14\u4f2f\u7279\u65af\u6587");
        put("znd", "\u8d5e\u5fb7\u6587");
        put("shn", "\u63b8\u6587");
        put("fon", "\u4e30\u6587");
        put("xal", "\u5361\u5566\u8ff7\u514b\u6587");
        put("aus", "\u6fb3\u5927\u5229\u4e9a\u8bed\u7cfb");
        put("kho", "\u548c\u7530\u6587");
        put("ja", "\u65e5\u6587");
        put("khi", "\u5176\u4ed6\u79d1\u4f0a\u6851\u6587");
        put("pau", "\u5e15\u52b3\u6587");
        put("chy", "\u590f\u5ef6\u6587");
        put("tai", "\u5176\u4ed6\u6cf0\u6587");
        put("iu", "\u7231\u65af\u57fa\u6469\u6587");
        put("pap", "\u5e15\u76ae\u4e9a\u5185\u6258\u6587");
        put("it", "\u610f\u5927\u5229\u6587");
        put("sgn", "\u624b\u8bed");
        put("is", "\u51b0\u5c9b\u6587");
        put("kha", "\u5361\u897f\u6587");
        put("chr", "\u5f7b\u7f57\u57fa\u6587");
        put("pam", "\u90a6\u677f\u7259\u6587");
        put("pal", "\u5e15\u62c9\u7ef4\u6587");
        put("chp", "\u4f69\u74e6\u626c\u6587");
        put("io", "\u7231\u5fb7\u83aa\u6587\uff08\u4eba\u5de5\u8bed\u8a00\uff09");
        put("cho", "\u4e54\u514b\u6258\u6587");
        put("chn", "\u5951\u52aa\u514b\u6587");
        put("chm", "\u9a6c\u91cc\u6587");
        put("tyv", "\u56fe\u74e6\u6587");
        put("bnt", "\u73ed\u56fe\u6587");
        put("pag", "\u90a6\u963f\u897f\u5357\u6587");
        put("ik", "\u4f9d\u5974\u76ae\u7ef4\u514b\u6587");
        put("chk", "\u695a\u543e\u514b\u6587");
        put("ii", "\u56db\u5ddd\u8bdd");
        put("haw", "\u590f\u5a01\u5937\u6587");
        put("lam", "\u5170\u5df4\u6587");
        put("ig", "\u4f0a\u683c\u535a\u6587");
        put("chg", "\u67e5\u52a0\u6587");
        put("sga", "\u53e4\u7231\u5c14\u5170\u6587");
        put("paa", "\u5176\u4ed6\u5df4\u5e03\u4e9a\u6587");
        put("ie", "\u62c9\u4e01\u56fd\u9645\u6587");
        put("id", "\u5370\u5ea6\u5c3c\u897f\u4e9a\u6587");
        put("lah", "\u62c9\u4ea8\u8fbe\u6587");
        put("day", "\u8fbe\u96c5\u514b\u6587");
        put("chb", "\u5951\u5e03\u5361\u6587");
        put("ia", "\u62c9\u4e01\u56fd\u9645\u6587");
        put("lad", "\u62c9\u8fea\u8bfa\u6587");
        put("hz", "\u8d6b\u96f7\u7f57\u6587");
        put("hai", "\u6d77\u8fbe\u6587");
        put("dar", "\u8fbe\u5c14\u683c\u74e6\u6587");
        put("hy", "\u4e9a\u7f8e\u5c3c\u4e9a\u6587");
        put("ath", "\u5176\u4ed6\u963f\u6492\u5df4\u65af\u5361\u8bed\u7cfb");
        put("hu", "\u5308\u7259\u5229\u6587");
        put("dak", "\u8fbe\u79d1\u4ed6\u6587");
        put("hr", "\u514b\u7f57\u5730\u4e9a\u6587");
        put("ho", "\u65b0\u91cc\u6728\u6258\u6587");
        put("hi", "\u5370\u5730\u6587");
        put("dyu", "\u8fea\u5c24\u62c9\u6587");
        put("he", "\u5e0c\u4f2f\u6765\u6587");
        put("ast", "\u963f\u65af\u56fe\u91cc\u4e9a\u601d\u7279\u8bed");
        put("ha", "\u8c6a\u6492\u6587");
        put("wen", "\u7d22\u5e03\u8bf8\u8bed\u8a00");
        put("gv", "\u9a6c\u6069\u5c9b\u6587");
        put("gu", "\u53e4\u52a0\u62c9\u63d0\u6587");
        put("sem", "\u5176\u4ed6\u95ea\u65cf\u8bed\u7cfb");
        put("sel", "\u585e\u5c14\u5e93\u666e\u6587");
        put("iro", "\u4f0a\u6d1b\u90ed\u4f0a\u8d39\u6587");
        put("gn", "\u74dc\u62c9\u5c3c\u6587");
        put("gl", "\u52a0\u5229\u897f\u4e9a\u6587");
        put("arw", "\u963f\u62c9\u74e6\u514b\u6587");
        put("gez", "\u5409\u5179\u6587");
        put("art", "\u5176\u4ed6\u4eba\u5de5\u8bed\u8a00");
        put("gd", "\u82cf\u683c\u5170- \u76d6\u5c14\u6587");
        put("ira", "\u4f0a\u6717\u6587");
        put("ga", "\u7231\u5c14\u5170\u6587");
        put("arp", "\u963f\u62c9\u5e15\u970d\u6587");
        put("arn", "\u963f\u52b3\u574e\u6587");
        put("fy", "\u5f17\u91cc\u65af\u5170\u6587");
        put("bla", "\u53f8\u514b\u53f8\u5361\u6587");
        put("ypk", "\u55bb\u76ae\u514b\u6587");
        put("arc", "\u963f\u62c9\u7c73\u6587");
        put("fr", "\u6cd5\u6587");
        put("fo", "\u6cd5\u7f57\u6587");
        put("cel", "\u5176\u4ed6\u51ef\u5c14\u7279\u8bed\u7cfb");
        put("fj", "\u6590\u6d4e\u6587");
        put("fi", "\u82ac\u5170\u6587");
        put("ff", "\u592b\u62c9\u6587");
        put("tvl", "\u56fe\u74e6\u5362\u6587");
        put("ceb", "\u5bbf\u52a1\u6587");
        put("fa", "\u6ce2\u65af\u6587");
        put("eu", "\u5df4\u65af\u514b\u6587");
        put("sco", "\u82cf\u683c\u5170\u6587");
        put("et", "\u7231\u6c99\u5c3c\u4e9a\u6587");
        put("es", "\u897f\u73ed\u7259\u6587");
        put("eo", "\u4e16\u754c\u6587");
        put("en", "\u82f1\u6587");
        put("el", "\u5e0c\u814a\u6587");
        put("tut", "\u5176\u4ed6\u963f\u5c14\u6cf0\u8bed\u7cfb");
        put("niu", "\u7ebd\u57c3\u6587");
        put("tup", "\u56fe\u5339\u6587");
        put("ee", "\u5e7d\u6587");
        put("tum", "\u901a\u5e03\u5361\u6587");
        put("mos", "\u83ab\u897f\u6587");
        put("dz", "\u4e0d\u4e39\u6587");
        put("nic", "\u5176\u4ed6\u5c3c\u65e5\u5c14\u521a\u679c\u8bed\u7cfb");
        put("lus", "\u5362\u6652\u6587");
        put("fiu", "\u82ac\u5308\u6587\uff08\u5176\u4ed6\uff09");
        put("dv", "\u8fea\u7ef4\u5e0c\u6587");
        put("nia", "\u5c3c\u5c14\u53f8\u6587");
        put("moh", "\u6469\u970d\u514b\u6587");
        put("luo", "\u5362\u5965\u6587");
        put("lun", "\u9686\u8fbe\u6587");
        put("apa", "\u963f\u5e15\u5207\u6587");
        put("lui", "\u8def\u6613\u585e\u8bfa\u6587");
        put("hup", "\u80e1\u5e15\u6587");
        put("bin", "\u6bd4\u5c3c\u6587");
        put("de", "\u5fb7\u6587");
        put("lua", "\u9c81\u5df4\u9c81\u74e6\u6587");
        put("bik", "\u6bd5\u5e93\u5c14\u6587");
        put("was", "\u74e6\u7ecd\u6587");
        put("und", "\u672a\u5b9a\u8bed\u79cd");
        put("war", "\u4f64\u745e\u6587");
        put("da", "\u4e39\u9ea6\u6587");
        put("dum", "\u4e2d\u53e4\u8377\u5170\u6587");
        put("wal", "\u74e6\u62c9\u83ab\u6587");
        put("mno", "\u9a6c\u8bfa\u535a\u6c61\u6587");
        put("wak", "\u74e6\u5580\u5c71\u6587");
        put("sat", "\u6851\u55d2\u5229\u6587");
        put("cy", "\u5a01\u5c14\u58eb\u6587");
        put("sas", "\u585e\u585e\u5361\u6587");
        put("kbd", "\u5361\u5df4\u5c14\u8fbe\u6587");
        put("cv", "\u695a\u74e6\u4ec0\u6587");
        put("cu", "\u5b97\u6559\u65af\u62c9\u592b\u6587");
        put("mni", "\u66fc\u5c3c\u666e\u91cc\u6587");
        put("cs", "\u6377\u514b\u6587");
        put("sam", "\u8428\u739b\u5229\u4e9a\u6587");
        put("cr", "\u514b\u91cc\u65cf\u6587");
        put("sal", "\u8428\u5229\u4ec0\u6587");
        put("dua", "\u90fd\u963f\u62c9\u6587");
        put("co", "\u79d1\u897f\u5609\u6587");
        put("sai", "\u5176\u4ed6\u5357\u7f8e\u5370\u7b2c\u5b89\u6587");
        put("mnc", "\u6ee1\u6587");
        put("sah", "\u96c5\u5e93\u7279\u6587");
        put("kaw", "\u5361\u5a01\u6587");
        put("inh", "\u5370\u53e4\u4ec0\u6587");
        put("gba", "\u845b\u5df4\u4e9a\u6587");
        put("sad", "\u6563\u8fbe\u7ef4\u6587");
        put("ch", "\u67e5\u83ab\u7f57\u6587");
        put("ine", "\u5176\u4ed6\u5370\u6b27\u8bed\u7cfb");
        put("bho", "\u535a\u6770\u666e\u5c14\u6587");
        put("enm", "\u4e2d\u53e4\u82f1\u6587");
        put("kar", "\u5580\u4f26\u6587");
        put("inc", "\u5370\u5ea6\u6587\uff08\u5176\u4ed6\uff09");
        put("ce", "\u8f66\u81e3\u6587");
        put("gay", "\u8fe6\u7ea6\u6587");
        put("ca", "\u52a0\u6cf0\u7f57\u5c3c\u4e9a\u6587");
        put("umb", "\u59c6\u5d29\u675c\u6587");
        put("syr", "\u53d9\u5229\u4e9a\u6587");
        put("kam", "\u5361\u59c6\u5df4\u6587");
        put("tsi", "\u8482\u59c6\u897f\u4e9a\u6587");
        put("ang", "\u4e2d\u53e4\u82f1\u8bed");
        put("kac", "\u5361\u7434\u6587");
        put("cau", "\u5176\u4ed6\u9ad8\u52a0\u7d22\u8bed\u7cfb");
        put("kab", "\u5361\u6bd4\u5c14\u6587");
        put("kaa", "\u5361\u62c9\u5361\u5c14\u5e15\u514b\u6587");
        put("bs", "\u6ce2\u65af\u5c3c\u4e9a\u6587");
        put("car", "\u5df4\u52d2\u6bd4\u6587");
        put("br", "\u5e03\u91cc\u591a\u5c3c\u6587");
        put("bo", "\u897f\u85cf\u6587");
        put("bn", "\u5b5f\u52a0\u62c9\u6587");
        put("bm", "\u73ed\u5df4\u62c9\u6587");
        put("gaa", "\u52a0\u6587");
        put("cai", "\u5176\u4ed6\u4e2d\u7f8e\u5370\u7b2c\u5b89\u8bed\u7cfb");
        put("bi", "\u6bd4\u65af\u62c9\u9a6c\u6587");
        put("bh", "\u6bd4\u54c8\u5c14\u6587");
        put("bg", "\u4fdd\u52a0\u5229\u4e9a\u6587");
        put("be", "\u767d\u4fc4\u7f57\u65af\u6587");
        put("cad", "\u5361\u591a\u6587");
        put("ba", "\u5df4\u4ec0\u5ba2\u5c14\u6587");
        put("zu", "\u7956\u9c81\u6587");
        put("zen", "\u6cfd\u7eb3\u52a0\u6587");
        put("pro", "\u666e\u7f57\u6587\u65af\u6587");
        put("hsb", "\u4e0a\u7d22\u5e03\u6587");
        put("az", "\u963f\u585e\u62dc\u7586\u6587");
        put("ay", "\u827e\u9a6c\u62c9\u6587");
        put("av", "\u963f\u74e6\u5c14\u6587");
        put("as", "\u963f\u8428\u59c6\u6587");
        put("dsb", "\u4e0b\u585e\u5c14\u7ef4\u4e9a\u6587");
        put("ar", "\u963f\u62c9\u4f2f\u6587");
        put("ilo", "\u4f0a\u6d1b\u5e72\u8bfa\u6587");
        put("elx", "\u827e\u62c9\u7c73\u7279\u6587");
        put("zh", "\u4e2d\u6587");
        put("pra", "\u5370\u5ea6\u53e4\u4ee3\u53ca\u4e2d\u4e16\u7eaa\u4e4b\u4e2d\u90e8\u53ca\u5317\u90e8\u65b9\u8a00");
        put("am", "\u963f\u59c6\u54c8\u62c9\u6587");
        put("new", "\u5c3c\u74e6\u5c14\u6587");
        put("ak", "\u963f\u80af\u6587");
        put("za", "\u85cf\u6587");
        put("af", "\u5357\u975e\u8377\u5170\u6587");
        put("ae", "\u963f\u7ef4\u65af\u5854\u6587");
        put("ab", "\u963f\u5e03\u54c8\u897f\u4e9a\u6587");
        put("aa", "\u963f\u6cd5\u6587");
        put("yo", "\u7ea6\u9c81\u5df4\u6587");
        put("alg", "\u5176\u4ed6\u963f\u5c14\u8d21\u8bed\u7cfb");
        put("ale", "\u963f\u7559\u7533\u7fa4\u5c9b\u4e4b\u571f\u8bed");
        put("mkh", "\u5176\u4ed6\u8499\u5409\u8511\u6587");
        put("yi", "\u4f9d\u5730\u6587");
        put("dra", "\u5176\u4ed6\u5fb7\u62c9\u7ef4\u8bed\u7cfb");
        put("ber", "\u5317\u975e\u56de\u6559\u571f\u65cf\u4e4b\u8bed\u8a00");
        put("nds", "\u5fb7\u56fd\u5317\u90e8\u7684\u5fb7\u6587\uff1b\u4f4e\u5730\u8428\u514b\u900a\u6587");
        put("bem", "\u522b\u59c6\u5df4\u6587");
        put("bej", "\u522b\u672d\u6587");
        put("tpi", "\u6258\u514b\u76ae\u8f9b\u6587");
      }
  }

  private static final Object languages = new Hashtablelanguages();

  private static final class Hashtablevariants extends java.util.Hashtable
  {
    public Hashtablevariants()
      {
        super();
        put("REVISED", "\u5df2\u4fee\u8ba2");
      }
  }

  private static final Object variants = new Hashtablevariants();

  private static final Object[][] contents =
  {
    { "localPatternChars", "GanjkHmsSEDFwWxhKzAeugXZ" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "ampms", ampms },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
    { "variants", variants },
  };

  public Object[][] getContents() { return contents; }
}
