/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_PlainSocketImpl */

#ifndef _Included_java_net_PlainSocketImpl
#define _Included_java_net_PlainSocketImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_net_PlainSocketImpl
 * Method:    accept
 * Signature: (Ljava/net/SocketImpl;)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_accept
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    bind
 * Signature: (Ljava/net/InetAddress;I)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_bind
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_close
  (JNIEnv *, jobject);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    connect
 * Signature: (Ljava/net/InetAddress;I)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_connect
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    create
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_create
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    listen
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_listen
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_java_net_PlainSocketImpl_read
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    write
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_write
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    setOption
 * Signature: (ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_setOption
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    getOption
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_net_PlainSocketImpl_getOption
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
