/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_InetAddress */

#ifndef _Included_java_net_InetAddress
#define _Included_java_net_InetAddress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_net_InetAddress
 * Method:    getLocalHostName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_net_InetAddress_getLocalHostName
  (JNIEnv *, jclass);

/*
 * Class:     java_net_InetAddress
 * Method:    lookupInaddrAny
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_java_net_InetAddress_lookupInaddrAny
  (JNIEnv *, jclass);

/*
 * Class:     java_net_InetAddress
 * Method:    getHostByAddr
 * Signature: ([I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_net_InetAddress_getHostByAddr
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     java_net_InetAddress
 * Method:    getHostByName
 * Signature: (Ljava/lang/String;)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_java_net_InetAddress_getHostByName
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
