/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_xml_libxmlj_dom_GnomeNamedNodeMap
#define _Included_gnu_xml_libxmlj_dom_GnomeNamedNodeMap

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNamedNodeMap_getNamedItem(JNIEnv*, jobject, jstring);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNamedNodeMap_setNamedItem(JNIEnv*, jobject, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNamedNodeMap_removeNamedItem(JNIEnv*, jobject, jstring);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNamedNodeMap_item(JNIEnv*, jobject, jint);
JNIEXPORT jint JNICALL Java_gnu_xml_libxmlj_dom_GnomeNamedNodeMap_getLength(JNIEnv*, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNamedNodeMap_getNamedItemNS(JNIEnv*, jobject, jstring, jstring);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNamedNodeMap_setNamedItemNS(JNIEnv*, jobject, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNamedNodeMap_removeNamedItemNS(JNIEnv*, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif

#endif
