/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_qt_QtFontPeer
#define _Included_gnu_java_awt_peer_qt_QtFontPeer

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtFontPeer_create(JNIEnv*, jobject, jstring, jint, jint);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtFontPeer_dispose(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif

#endif
