/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __gnu_java_awt_peer_gtk_GdkClasspathFontPeerMetrics__
#define __gnu_java_awt_peer_gtk_GdkClasspathFontPeerMetrics__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jintArray JNICALL Java_gnu_java_awt_peer_gtk_GdkClasspathFontPeerMetrics_initState (JNIEnv *env, jobject, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __gnu_java_awt_peer_gtk_GdkClasspathFontPeerMetrics__ */
