/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_qt_QtPopupMenuPeer
#define _Included_gnu_java_awt_peer_qt_QtPopupMenuPeer

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtPopupMenuPeer_showNative(JNIEnv*, jobject, jint, jint);

#ifdef __cplusplus
}
#endif

#endif
