/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __gnu_java_nio_NIOServerSocket__
#define __gnu_java_nio_NIOServerSocket__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern JNIEXPORT jobject JNICALL Java_gnu_java_nio_NIOServerSocket_getPlainSocketImpl (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __gnu_java_nio_NIOServerSocket__ */
