/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_xml_libxmlj_dom_GnomeEntity
#define _Included_gnu_xml_libxmlj_dom_GnomeEntity

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeEntity_getPublicId(JNIEnv*, jobject);
JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeEntity_getSystemId(JNIEnv*, jobject);
JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeEntity_getNotationName(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif

#endif
