/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_gtk_GtkSelection
#define _Included_gnu_java_awt_peer_gtk_GtkSelection

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkSelection_requestText(JNIEnv*, jobject, jboolean);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkSelection_requestImage(JNIEnv*, jobject, jboolean);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkSelection_requestURIs(JNIEnv*, jobject, jboolean);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkSelection_requestBytes(JNIEnv*, jobject, jboolean, jstring);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkSelection_requestMimeTypes(JNIEnv*, jobject, jboolean);

#ifdef __cplusplus
}
#endif

#endif
