/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_gtk_CairoGraphics2D */

#ifndef _Included_gnu_java_awt_peer_gtk_CairoGraphics2D
#define _Included_gnu_java_awt_peer_gtk_CairoGraphics2D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    init
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    disposeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_disposeNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    drawPixels
 * Signature: (J[IIII[D)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_drawPixels
  (JNIEnv *, jobject, jlong, jintArray, jint, jint, jint, jdoubleArray);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    setGradient
 * Signature: (JDDDDIIIIIIIIZ)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_setGradient
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jdouble, jint, jint, jint, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    setTexturePixels
 * Signature: (J[IIII)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_setTexturePixels
  (JNIEnv *, jobject, jlong, jintArray, jint, jint, jint);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoSetMatrix
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoSetMatrix
  (JNIEnv *, jobject, jlong, jdoubleArray);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoSetOperator
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoSetOperator
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoSetRGBAColor
 * Signature: (JDDDD)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoSetRGBAColor
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoSetFillRule
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoSetFillRule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoSetLine
 * Signature: (JDIID)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoSetLine
  (JNIEnv *, jobject, jlong, jdouble, jint, jint, jdouble);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoSetDash
 * Signature: (J[DID)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoSetDash
  (JNIEnv *, jobject, jlong, jdoubleArray, jint, jdouble);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoDrawGlyphVector
 * Signature: (JLgnu/java/awt/peer/gtk/GdkFontPeer;FFI[I[F)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoDrawGlyphVector
  (JNIEnv *, jobject, jlong, jobject, jfloat, jfloat, jint, jintArray, jfloatArray);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoRelCurveTo
 * Signature: (JDDDDDD)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoRelCurveTo
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoRectangle
 * Signature: (JDDDD)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoRectangle
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoNewPath
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoNewPath
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoClosePath
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoClosePath
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoMoveTo
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoMoveTo
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoRelMoveTo
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoRelMoveTo
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoLineTo
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoLineTo
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoRelLineTo
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoRelLineTo
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoCurveTo
 * Signature: (JDDDDDD)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoCurveTo
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoStroke
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoStroke
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoFill
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoFill
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoClip
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoClip
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoPreserveClip
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoPreserveClip
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoResetClip
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoResetClip
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoGraphics2D
 * Method:    cairoSurfaceSetFilter
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoGraphics2D_cairoSurfaceSetFilter
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
