/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_xml_libxmlj_dom_GnomeElement
#define _Included_gnu_xml_libxmlj_dom_GnomeElement

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeElement_getAttribute(JNIEnv*, jobject, jstring);
JNIEXPORT void JNICALL Java_gnu_xml_libxmlj_dom_GnomeElement_setAttribute(JNIEnv*, jobject, jstring, jstring);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeElement_getAttributeNode(JNIEnv*, jobject, jstring);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeElement_setAttributeNode(JNIEnv*, jobject, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeElement_removeAttributeNode(JNIEnv*, jobject, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeElement_getElementsByTagName(JNIEnv*, jobject, jstring);
JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeElement_getAttributeNS(JNIEnv*, jobject, jstring, jstring);
JNIEXPORT void JNICALL Java_gnu_xml_libxmlj_dom_GnomeElement_setAttributeNS(JNIEnv*, jobject, jstring, jstring, jstring);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeElement_getAttributeNodeNS(JNIEnv*, jobject, jstring, jstring);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeElement_setAttributeNodeNS(JNIEnv*, jobject, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeElement_getElementsByTagNameNS(JNIEnv*, jobject, jstring, jstring);
JNIEXPORT jboolean JNICALL Java_gnu_xml_libxmlj_dom_GnomeElement_hasAttribute(JNIEnv*, jobject, jstring);
JNIEXPORT jboolean JNICALL Java_gnu_xml_libxmlj_dom_GnomeElement_hasAttributeNS(JNIEnv*, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif

#endif
