/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __gnu_java_awt_EmbeddedWindow__
#define __gnu_java_awt_EmbeddedWindow__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern JNIEXPORT void JNICALL Java_gnu_java_awt_EmbeddedWindow_setWindowPeer (JNIEnv *env, jobject, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __gnu_java_awt_EmbeddedWindow__ */
