/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_qt_QtMenuPeer */

#ifndef _Included_gnu_java_awt_peer_qt_QtMenuPeer
#define _Included_gnu_java_awt_peer_qt_QtMenuPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gnu_java_awt_peer_qt_QtMenuPeer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtMenuPeer_init
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtMenuPeer
 * Method:    allowTearOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtMenuPeer_allowTearOff
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtMenuPeer
 * Method:    insertSeperator
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_gnu_java_awt_peer_qt_QtMenuPeer_insertSeperator
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtMenuPeer
 * Method:    insertItem
 * Signature: (Lgnu/java/awt/peer/qt/QtMenuItemPeer;)J
 */
JNIEXPORT jlong JNICALL Java_gnu_java_awt_peer_qt_QtMenuPeer_insertItem
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtMenuPeer
 * Method:    insertMenu
 * Signature: (Lgnu/java/awt/peer/qt/QtMenuPeer;)J
 */
JNIEXPORT jlong JNICALL Java_gnu_java_awt_peer_qt_QtMenuPeer_insertMenu
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtMenuPeer
 * Method:    delItem
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtMenuPeer_delItem
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gnu_java_awt_peer_qt_QtMenuPeer
 * Method:    setEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtMenuPeer_setEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     gnu_java_awt_peer_qt_QtMenuPeer
 * Method:    setLabel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtMenuPeer_setLabel
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
