/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_qt_QtMenuComponentPeer
#define _Included_gnu_java_awt_peer_qt_QtMenuComponentPeer

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtMenuComponentPeer_callInit(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtMenuComponentPeer_dispose(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif

#endif
