/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_xml_libxmlj_sax_GnomeXMLReader
#define _Included_gnu_xml_libxmlj_sax_GnomeXMLReader

#ifdef __cplusplus
extern "C" {
#endif

#undef gnu_xml_libxmlj_sax_GnomeXMLReader_FEATURES_PREFIX
#define gnu_xml_libxmlj_sax_GnomeXMLReader_FEATURES_PREFIX "http://xml.org/sax/features/"
#undef gnu_xml_libxmlj_sax_GnomeXMLReader_PROPERTIES_PREFIX
#define gnu_xml_libxmlj_sax_GnomeXMLReader_PROPERTIES_PREFIX "http://xml.org/sax/properties/"
JNIEXPORT void JNICALL Java_gnu_xml_libxmlj_sax_GnomeXMLReader_parseStream(JNIEnv*, jobject, jobject, jbyteArray, jstring, jstring, jstring, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

#ifdef __cplusplus
}
#endif

#endif
