/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_xml_libxmlj_dom_GnomeNode
#define _Included_gnu_xml_libxmlj_dom_GnomeNode

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_getNodeName(JNIEnv*, jobject);
JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_getNodeValue(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_setNodeValue(JNIEnv*, jobject, jstring);
JNIEXPORT jshort JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_getNodeType(JNIEnv*, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_getParentNode(JNIEnv*, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_getFirstChild(JNIEnv*, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_getLastChild(JNIEnv*, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_getPreviousSibling(JNIEnv*, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_getNextSibling(JNIEnv*, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_getOwnerDocument(JNIEnv*, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_xmljInsertBefore(JNIEnv*, jobject, jobject, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_xmljReplaceChild(JNIEnv*, jobject, jobject, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_xmljRemoveChild(JNIEnv*, jobject, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_xmljAppendChild(JNIEnv*, jobject, jobject);
JNIEXPORT jboolean JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_hasChildNodes(JNIEnv*, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_xmljCloneNode(JNIEnv*, jobject, jboolean);
JNIEXPORT void JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_normalize(JNIEnv*, jobject);
JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_getNamespaceURI(JNIEnv*, jobject);
JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_getPrefix(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_setPrefix(JNIEnv*, jobject, jstring);
JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_getLocalName(JNIEnv*, jobject);
JNIEXPORT jboolean JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_hasAttributes(JNIEnv*, jobject);
JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_getBaseURI(JNIEnv*, jobject);
JNIEXPORT jint JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_xmljCompareTo(JNIEnv*, jobject, jobject);
JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_lookupPrefix(JNIEnv*, jobject, jstring);
JNIEXPORT jboolean JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_isDefaultNamespace(JNIEnv*, jobject, jstring);
JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_lookupNamespaceURI(JNIEnv*, jobject, jstring);
JNIEXPORT jboolean JNICALL Java_gnu_xml_libxmlj_dom_GnomeNode_isEqualNode(JNIEnv*, jobject, jobject);

#ifdef __cplusplus
}
#endif

#endif
