/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_gtk_GtkClipboard
#define _Included_gnu_java_awt_peer_gtk_GtkClipboard

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkClipboard_advertiseContent(JNIEnv*, jobject, jobjectArray, jboolean, jboolean, jboolean);
JNIEXPORT jboolean JNICALL Java_gnu_java_awt_peer_gtk_GtkClipboard_initNativeState(JNIEnv*, jclass, jobject, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif

#endif
