/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_qt_QtScrollPanePeer */

#ifndef _Included_gnu_java_awt_peer_qt_QtScrollPanePeer
#define _Included_gnu_java_awt_peer_qt_QtScrollPanePeer
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_java_awt_peer_qt_QtScrollPanePeer_POPUP_TRIGGER
#define gnu_java_awt_peer_qt_QtScrollPanePeer_POPUP_TRIGGER 3L
/*
 * Class:     gnu_java_awt_peer_qt_QtScrollPanePeer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtScrollPanePeer_init
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtScrollPanePeer
 * Method:    setPolicy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtScrollPanePeer_setPolicy
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_java_awt_peer_qt_QtScrollPanePeer
 * Method:    childResized
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtScrollPanePeer_childResized
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gnu_java_awt_peer_qt_QtScrollPanePeer
 * Method:    getHScrollbarHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gnu_java_awt_peer_qt_QtScrollPanePeer_getHScrollbarHeight
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtScrollPanePeer
 * Method:    getVScrollbarWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gnu_java_awt_peer_qt_QtScrollPanePeer_getVScrollbarWidth
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtScrollPanePeer
 * Method:    setScrollPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtScrollPanePeer_setScrollPosition
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
