/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_qt_QtCheckboxPeer
#define _Included_gnu_java_awt_peer_qt_QtCheckboxPeer

#ifdef __cplusplus
extern "C" {
#endif

#undef gnu_java_awt_peer_qt_QtCheckboxPeer_POPUP_TRIGGER
#define gnu_java_awt_peer_qt_QtCheckboxPeer_POPUP_TRIGGER 3L
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtCheckboxPeer_init(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtCheckboxPeer_setLabel(JNIEnv*, jobject, jstring);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtCheckboxPeer_setState(JNIEnv*, jobject, jboolean);

#ifdef __cplusplus
}
#endif

#endif
