/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_qt_QtFramePeer
#define _Included_gnu_java_awt_peer_qt_QtFramePeer

#ifdef __cplusplus
extern "C" {
#endif

#undef gnu_java_awt_peer_qt_QtFramePeer_POPUP_TRIGGER
#define gnu_java_awt_peer_qt_QtFramePeer_POPUP_TRIGGER 3L
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtFramePeer_init(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtFramePeer_setIcon(JNIEnv*, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtFramePeer_setMaximizedBounds(JNIEnv*, jobject, jint, jint);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtFramePeer_setMenu(JNIEnv*, jobject, jobject);
JNIEXPORT jint JNICALL Java_gnu_java_awt_peer_qt_QtFramePeer_menuBarHeight(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif

#endif
