/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_qt_QtFileDialogPeer */

#ifndef _Included_gnu_java_awt_peer_qt_QtFileDialogPeer
#define _Included_gnu_java_awt_peer_qt_QtFileDialogPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_java_awt_peer_qt_QtFileDialogPeer_POPUP_TRIGGER
#define gnu_java_awt_peer_qt_QtFileDialogPeer_POPUP_TRIGGER 3L
/*
 * Class:     gnu_java_awt_peer_qt_QtFileDialogPeer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtFileDialogPeer_init
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtFileDialogPeer
 * Method:    setMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtFileDialogPeer_setMode
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
