/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_gtk_GdkGraphicsEnvironment
#define _Included_gnu_java_awt_peer_gtk_GdkGraphicsEnvironment

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_gnu_java_awt_peer_gtk_GdkGraphicsEnvironment_nativeGetNumFontFamilies(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GdkGraphicsEnvironment_nativeGetFontFamilies(JNIEnv*, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif

#endif
