/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_gtk_GtkCheckboxGroupPeer
#define _Included_gnu_java_awt_peer_gtk_GtkCheckboxGroupPeer

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkCheckboxGroupPeer_dispose(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkCheckboxGroupPeer_remove(JNIEnv*, jobject, jobject);

#ifdef __cplusplus
}
#endif

#endif
