/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_qt_QtFontPeer */

#ifndef _Included_gnu_java_awt_peer_qt_QtFontPeer
#define _Included_gnu_java_awt_peer_qt_QtFontPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gnu_java_awt_peer_qt_QtFontPeer
 * Method:    create
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtFontPeer_create
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     gnu_java_awt_peer_qt_QtFontPeer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtFontPeer_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
