/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_qt_QtComponentPeer */

#ifndef _Included_gnu_java_awt_peer_qt_QtComponentPeer
#define _Included_gnu_java_awt_peer_qt_QtComponentPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_java_awt_peer_qt_QtComponentPeer_POPUP_TRIGGER
#define gnu_java_awt_peer_qt_QtComponentPeer_POPUP_TRIGGER 3L
/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    callInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_callInit
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    QtUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_QtUpdate
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    QtUpdateArea
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_QtUpdateArea
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_disposeNative
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    setGround
 * Signature: (IIIZ)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_setGround
  (JNIEnv *, jobject, jint, jint, jint, jboolean);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    setBoundsNative
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_setBoundsNative
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    setCursor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_setCursor
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    getNativeBackground
 * Signature: ()Ljava/awt/Color;
 */
JNIEXPORT jobject JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_getNativeBackground
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    setFontNative
 * Signature: (Lgnu/java/awt/peer/qt/QtFontPeer;)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_setFontNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    whichScreen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_whichScreen
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    getMinimumSizeNative
 * Signature: ()Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_getMinimumSizeNative
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    getPreferredSizeNative
 * Signature: ()Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_getPreferredSizeNative
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    getLocationOnScreen
 * Signature: ()Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_getLocationOnScreen
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    handlesWheelScrolling
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_handlesWheelScrolling
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    isFocusable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_isFocusable
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    isObscured
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_isObscured
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    requestFocus
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_requestFocus
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    setEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_setEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     gnu_java_awt_peer_qt_QtComponentPeer
 * Method:    setVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtComponentPeer_setVisible
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
