/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_xml_libxmlj_dom_GnomeXPathResult
#define _Included_gnu_xml_libxmlj_dom_GnomeXPathResult

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_gnu_xml_libxmlj_dom_GnomeXPathResult_free(JNIEnv*, jobject, jobject);
JNIEXPORT jshort JNICALL Java_gnu_xml_libxmlj_dom_GnomeXPathResult_getResultType(JNIEnv*, jobject);
JNIEXPORT jdouble JNICALL Java_gnu_xml_libxmlj_dom_GnomeXPathResult_getNumberValue(JNIEnv*, jobject);
JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeXPathResult_getStringValue(JNIEnv*, jobject);
JNIEXPORT jboolean JNICALL Java_gnu_xml_libxmlj_dom_GnomeXPathResult_getBooleanValue(JNIEnv*, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeXPathResult_getSingleNodeValue(JNIEnv*, jobject);
JNIEXPORT jboolean JNICALL Java_gnu_xml_libxmlj_dom_GnomeXPathResult_getInvalidIteratorState(JNIEnv*, jobject);
JNIEXPORT jint JNICALL Java_gnu_xml_libxmlj_dom_GnomeXPathResult_getSnapshotLength(JNIEnv*, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeXPathResult_iterateNext(JNIEnv*, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_dom_GnomeXPathResult_snapshotItem(JNIEnv*, jobject, jint);

#ifdef __cplusplus
}
#endif

#endif
