/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_qt_QtGraphics
#define _Included_gnu_java_awt_peer_qt_QtGraphics

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_delete(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_initImage(JNIEnv*, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_initVolatileImage(JNIEnv*, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_cloneNativeContext(JNIEnv*, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_setColor(JNIEnv*, jobject, jint, jint, jint, jint);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_drawNative(JNIEnv*, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_fillNative(JNIEnv*, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_setClipNative(JNIEnv*, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_setClipRectNative(JNIEnv*, jobject, jint, jint, jint, jint);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_intersectClipNative(JNIEnv*, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_intersectClipRectNative(JNIEnv*, jobject, jint, jint, jint, jint);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_setQtTransform(JNIEnv*, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_setNativeStroke(JNIEnv*, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_setNativeComposite(JNIEnv*, jobject, jint);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_drawStringNative(JNIEnv*, jobject, jstring, jdouble, jdouble);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_setLinearGradient(JNIEnv*, jobject, jint, jint, jint, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jboolean);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_setAlphaNative(JNIEnv*, jobject, jdouble);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_setFontNative(JNIEnv*, jobject, jobject);
JNIEXPORT jobject JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_getClipNative(JNIEnv*, jobject);
JNIEXPORT jobject JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_getClipBounds(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_fill3DRect(JNIEnv*, jobject, jint, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtGraphics_draw3DRect(JNIEnv*, jobject, jint, jint, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif

#endif
