/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_qt_QtPanelPeer
#define _Included_gnu_java_awt_peer_qt_QtPanelPeer

#ifdef __cplusplus
extern "C" {
#endif

#undef gnu_java_awt_peer_qt_QtPanelPeer_POPUP_TRIGGER
#define gnu_java_awt_peer_qt_QtPanelPeer_POPUP_TRIGGER 3L
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtPanelPeer_init(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif

#endif
