/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_xml_libxmlj_dom_GnomeAttr
#define _Included_gnu_xml_libxmlj_dom_GnomeAttr

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_gnu_xml_libxmlj_dom_GnomeAttr_getSpecified(JNIEnv*, jobject);
JNIEXPORT jstring JNICALL Java_gnu_xml_libxmlj_dom_GnomeAttr_getValue(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_xml_libxmlj_dom_GnomeAttr_setValue(JNIEnv*, jobject, jstring);
JNIEXPORT jboolean JNICALL Java_gnu_xml_libxmlj_dom_GnomeAttr_xmljIsId(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif

#endif
