/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_qt_QtChoicePeer */

#ifndef _Included_gnu_java_awt_peer_qt_QtChoicePeer
#define _Included_gnu_java_awt_peer_qt_QtChoicePeer
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_java_awt_peer_qt_QtChoicePeer_POPUP_TRIGGER
#define gnu_java_awt_peer_qt_QtChoicePeer_POPUP_TRIGGER 3L
/*
 * Class:     gnu_java_awt_peer_qt_QtChoicePeer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtChoicePeer_init
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtChoicePeer
 * Method:    add
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtChoicePeer_add
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     gnu_java_awt_peer_qt_QtChoicePeer
 * Method:    remove
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtChoicePeer_remove
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_java_awt_peer_qt_QtChoicePeer
 * Method:    select
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtChoicePeer_select
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
