/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_gtk_GtkCheckboxMenuItemPeer
#define _Included_gnu_java_awt_peer_gtk_GtkCheckboxMenuItemPeer

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkCheckboxMenuItemPeer_create(JNIEnv*, jobject, jstring);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkCheckboxMenuItemPeer_setState(JNIEnv*, jobject, jboolean);

#ifdef __cplusplus
}
#endif

#endif
