/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_gtk_CairoSurface */

#ifndef _Included_gnu_java_awt_peer_gtk_CairoSurface
#define _Included_gnu_java_awt_peer_gtk_CairoSurface
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_java_awt_peer_gtk_CairoSurface_TYPE_BYTE
#define gnu_java_awt_peer_gtk_CairoSurface_TYPE_BYTE 0L
#undef gnu_java_awt_peer_gtk_CairoSurface_TYPE_USHORT
#define gnu_java_awt_peer_gtk_CairoSurface_TYPE_USHORT 1L
#undef gnu_java_awt_peer_gtk_CairoSurface_TYPE_SHORT
#define gnu_java_awt_peer_gtk_CairoSurface_TYPE_SHORT 2L
#undef gnu_java_awt_peer_gtk_CairoSurface_TYPE_INT
#define gnu_java_awt_peer_gtk_CairoSurface_TYPE_INT 3L
#undef gnu_java_awt_peer_gtk_CairoSurface_TYPE_FLOAT
#define gnu_java_awt_peer_gtk_CairoSurface_TYPE_FLOAT 4L
#undef gnu_java_awt_peer_gtk_CairoSurface_TYPE_DOUBLE
#define gnu_java_awt_peer_gtk_CairoSurface_TYPE_DOUBLE 5L
#undef gnu_java_awt_peer_gtk_CairoSurface_TYPE_UNDEFINED
#define gnu_java_awt_peer_gtk_CairoSurface_TYPE_UNDEFINED 32L
/*
 * Class:     gnu_java_awt_peer_gtk_CairoSurface
 * Method:    create
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoSurface_create
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoSurface
 * Method:    destroy
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoSurface_destroy
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoSurface
 * Method:    nativeGetElem
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_gnu_java_awt_peer_gtk_CairoSurface_nativeGetElem
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoSurface
 * Method:    nativeSetElem
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoSurface_nativeSetElem
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoSurface
 * Method:    nativeDrawSurface
 * Signature: (JJ[D)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoSurface_nativeDrawSurface
  (JNIEnv *, jobject, jlong, jlong, jdoubleArray);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoSurface
 * Method:    nativeGetPixels
 * Signature: (JI)[I
 */
JNIEXPORT jintArray JNICALL Java_gnu_java_awt_peer_gtk_CairoSurface_nativeGetPixels
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoSurface
 * Method:    nativeSetPixels
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoSurface_nativeSetPixels
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoSurface
 * Method:    getFlippedBuffer
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_gnu_java_awt_peer_gtk_CairoSurface_getFlippedBuffer
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoSurface
 * Method:    nativeNewCairoContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_gnu_java_awt_peer_gtk_CairoSurface_nativeNewCairoContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     gnu_java_awt_peer_gtk_CairoSurface
 * Method:    copyAreaNative2
 * Signature: (JIIIIIII)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_CairoSurface_copyAreaNative2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
