/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_qt_QtImage
#define _Included_gnu_java_awt_peer_qt_QtImage

#ifdef __cplusplus
extern "C" {
#endif

#undef gnu_java_awt_peer_qt_QtImage_SCALE_DEFAULT
#define gnu_java_awt_peer_qt_QtImage_SCALE_DEFAULT 1L
#undef gnu_java_awt_peer_qt_QtImage_SCALE_FAST
#define gnu_java_awt_peer_qt_QtImage_SCALE_FAST 2L
#undef gnu_java_awt_peer_qt_QtImage_SCALE_SMOOTH
#define gnu_java_awt_peer_qt_QtImage_SCALE_SMOOTH 4L
#undef gnu_java_awt_peer_qt_QtImage_SCALE_REPLICATE
#define gnu_java_awt_peer_qt_QtImage_SCALE_REPLICATE 8L
#undef gnu_java_awt_peer_qt_QtImage_SCALE_AREA_AVERAGING
#define gnu_java_awt_peer_qt_QtImage_SCALE_AREA_AVERAGING 16L
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtImage_clear(JNIEnv*, jobject);
JNIEXPORT jintArray JNICALL Java_gnu_java_awt_peer_qt_QtImage_getPixels(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtImage_setPixels(JNIEnv*, jobject, jintArray);
JNIEXPORT jboolean JNICALL Java_gnu_java_awt_peer_qt_QtImage_loadImage(JNIEnv*, jobject, jstring);
JNIEXPORT jboolean JNICALL Java_gnu_java_awt_peer_qt_QtImage_loadImageFromData(JNIEnv*, jobject, jbyteArray);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtImage_createImage(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtImage_freeImage(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtImage_createScaledImage(JNIEnv*, jobject, jobject, jint);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtImage_drawPixels(JNIEnv*, jobject, jobject, jint, jint, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtImage_drawPixelsScaled(JNIEnv*, jobject, jobject, jint, jint, jint, jint, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtImage_drawPixelsTransformed(JNIEnv*, jobject, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtImage_drawPixelsScaledFlipped(JNIEnv*, jobject, jobject, jint, jint, jint, jboolean, jboolean, jint, jint, jint, jint, jint, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtImage_copyArea(JNIEnv*, jobject, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif

#endif
