/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_xml_libxmlj_transform_GnomeTransformer
#define _Included_gnu_xml_libxmlj_transform_GnomeTransformer

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_transform_GnomeTransformer_newStylesheet(JNIEnv*, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_transform_GnomeTransformer_newStylesheetFromStream(JNIEnv*, jobject, jobject, jbyteArray, jstring, jstring, jstring, jboolean, jboolean);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_transform_GnomeTransformer_newStylesheetFromDoc(JNIEnv*, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_xml_libxmlj_transform_GnomeTransformer_transformStreamToStream(JNIEnv*, jobject, jobject, jbyteArray, jstring, jstring, jstring, jboolean, jboolean, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_transform_GnomeTransformer_transformStreamToDoc(JNIEnv*, jobject, jobject, jbyteArray, jstring, jstring, jstring, jboolean, jboolean);
JNIEXPORT void JNICALL Java_gnu_xml_libxmlj_transform_GnomeTransformer_transformStreamToSAX(JNIEnv*, jobject, jobject, jbyteArray, jstring, jstring, jstring, jboolean, jboolean, jobject);
JNIEXPORT void JNICALL Java_gnu_xml_libxmlj_transform_GnomeTransformer_transformDocToStream(JNIEnv*, jobject, jobject, jobject);
JNIEXPORT jobject JNICALL Java_gnu_xml_libxmlj_transform_GnomeTransformer_transformDocToDoc(JNIEnv*, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_xml_libxmlj_transform_GnomeTransformer_transformDocToSAX(JNIEnv*, jobject, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_xml_libxmlj_transform_GnomeTransformer_free(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif

#endif
