/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_gtk_GtkGenericPeer
#define _Included_gnu_java_awt_peer_gtk_GtkGenericPeer

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkGenericPeer_dispose(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_gtk_GtkGenericPeer_gtkWidgetModifyFont(JNIEnv*, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif

#endif
