/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_qt_QPen */

#ifndef _Included_gnu_java_awt_peer_qt_QPen
#define _Included_gnu_java_awt_peer_qt_QPen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gnu_java_awt_peer_qt_QPen
 * Method:    init
 * Signature: (DIID)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QPen_init
  (JNIEnv *, jobject, jdouble, jint, jint, jdouble);

/*
 * Class:     gnu_java_awt_peer_qt_QPen
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QPen_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
