/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_qt_QtCheckboxPeer */

#ifndef _Included_gnu_java_awt_peer_qt_QtCheckboxPeer
#define _Included_gnu_java_awt_peer_qt_QtCheckboxPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_java_awt_peer_qt_QtCheckboxPeer_POPUP_TRIGGER
#define gnu_java_awt_peer_qt_QtCheckboxPeer_POPUP_TRIGGER 3L
/* Inaccessible static: groupMap */
/*
 * Class:     gnu_java_awt_peer_qt_QtCheckboxPeer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtCheckboxPeer_init
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtCheckboxPeer
 * Method:    setLabel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtCheckboxPeer_setLabel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gnu_java_awt_peer_qt_QtCheckboxPeer
 * Method:    setState
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtCheckboxPeer_setState
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
