/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_qt_QtChoicePeer
#define _Included_gnu_java_awt_peer_qt_QtChoicePeer

#ifdef __cplusplus
extern "C" {
#endif

#undef gnu_java_awt_peer_qt_QtChoicePeer_POPUP_TRIGGER
#define gnu_java_awt_peer_qt_QtChoicePeer_POPUP_TRIGGER 3L
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtChoicePeer_init(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtChoicePeer_add(JNIEnv*, jobject, jstring, jint);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtChoicePeer_remove(JNIEnv*, jobject, jint);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtChoicePeer_select(JNIEnv*, jobject, jint);

#ifdef __cplusplus
}
#endif

#endif
