/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_awt_peer_qt_QtVolatileImage
#define _Included_gnu_java_awt_peer_qt_QtVolatileImage

#ifdef __cplusplus
extern "C" {
#endif

#undef gnu_java_awt_peer_qt_QtVolatileImage_SCALE_DEFAULT
#define gnu_java_awt_peer_qt_QtVolatileImage_SCALE_DEFAULT 1L
#undef gnu_java_awt_peer_qt_QtVolatileImage_SCALE_FAST
#define gnu_java_awt_peer_qt_QtVolatileImage_SCALE_FAST 2L
#undef gnu_java_awt_peer_qt_QtVolatileImage_SCALE_SMOOTH
#define gnu_java_awt_peer_qt_QtVolatileImage_SCALE_SMOOTH 4L
#undef gnu_java_awt_peer_qt_QtVolatileImage_SCALE_REPLICATE
#define gnu_java_awt_peer_qt_QtVolatileImage_SCALE_REPLICATE 8L
#undef gnu_java_awt_peer_qt_QtVolatileImage_SCALE_AREA_AVERAGING
#define gnu_java_awt_peer_qt_QtVolatileImage_SCALE_AREA_AVERAGING 16L
#undef gnu_java_awt_peer_qt_QtVolatileImage_IMAGE_OK
#define gnu_java_awt_peer_qt_QtVolatileImage_IMAGE_OK 0L
#undef gnu_java_awt_peer_qt_QtVolatileImage_IMAGE_RESTORED
#define gnu_java_awt_peer_qt_QtVolatileImage_IMAGE_RESTORED 1L
#undef gnu_java_awt_peer_qt_QtVolatileImage_IMAGE_INCOMPATIBLE
#define gnu_java_awt_peer_qt_QtVolatileImage_IMAGE_INCOMPATIBLE 2L
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtVolatileImage_clear(JNIEnv*, jobject);
JNIEXPORT jintArray JNICALL Java_gnu_java_awt_peer_qt_QtVolatileImage_getPixels(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtVolatileImage_createImage(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtVolatileImage_freeImage(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtVolatileImage_blit__Lgnu_java_awt_peer_qt_QtImage_2(JNIEnv*, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtVolatileImage_blit__Lgnu_java_awt_peer_qt_QtImage_2IIII(JNIEnv*, jobject, jobject, jint, jint, jint, jint);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtVolatileImage_createScaledImage(JNIEnv*, jobject, jobject, jint);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtVolatileImage_drawPixels(JNIEnv*, jobject, jobject, jint, jint, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtVolatileImage_drawPixelsScaled(JNIEnv*, jobject, jobject, jint, jint, jint, jint, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtVolatileImage_drawPixelsTransformed(JNIEnv*, jobject, jobject, jobject);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtVolatileImage_drawPixelsScaledFlipped(JNIEnv*, jobject, jobject, jint, jint, jint, jboolean, jboolean, jint, jint, jint, jint, jint, jint, jint, jint, jboolean);
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtVolatileImage_copyArea(JNIEnv*, jobject, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif

#endif
