/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_java_awt_peer_qt_QtTextAreaPeer */

#ifndef _Included_gnu_java_awt_peer_qt_QtTextAreaPeer
#define _Included_gnu_java_awt_peer_qt_QtTextAreaPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_java_awt_peer_qt_QtTextAreaPeer_POPUP_TRIGGER
#define gnu_java_awt_peer_qt_QtTextAreaPeer_POPUP_TRIGGER 3L
/*
 * Class:     gnu_java_awt_peer_qt_QtTextAreaPeer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtTextAreaPeer_init
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtTextAreaPeer
 * Method:    getSelection
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_gnu_java_awt_peer_qt_QtTextAreaPeer_getSelection
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     gnu_java_awt_peer_qt_QtTextAreaPeer
 * Method:    getCaretPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gnu_java_awt_peer_qt_QtTextAreaPeer_getCaretPosition
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtTextAreaPeer
 * Method:    getIndexAtPoint
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gnu_java_awt_peer_qt_QtTextAreaPeer_getIndexAtPoint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gnu_java_awt_peer_qt_QtTextAreaPeer
 * Method:    getText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gnu_java_awt_peer_qt_QtTextAreaPeer_getText
  (JNIEnv *, jobject);

/*
 * Class:     gnu_java_awt_peer_qt_QtTextAreaPeer
 * Method:    insert
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtTextAreaPeer_insert
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     gnu_java_awt_peer_qt_QtTextAreaPeer
 * Method:    setText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtTextAreaPeer_setText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gnu_java_awt_peer_qt_QtTextAreaPeer
 * Method:    select
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtTextAreaPeer_select
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gnu_java_awt_peer_qt_QtTextAreaPeer
 * Method:    setEditable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtTextAreaPeer_setEditable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     gnu_java_awt_peer_qt_QtTextAreaPeer
 * Method:    setCaretPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gnu_java_awt_peer_qt_QtTextAreaPeer_setCaretPosition
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
