/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_lang_Class__
#define __java_lang_Class__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jstring Java_java_lang_Class_getName (JNIEnv *env, jobject);
extern jboolean Java_java_lang_Class_isInterface (JNIEnv *env, jobject);
extern jclass Java_java_lang_Class_getSuperclass (JNIEnv *env, jobject);
extern jobjectArray Java_java_lang_Class_getInterfaces (JNIEnv *env, jobject);
extern jobject Java_java_lang_Class_getClassLoader (JNIEnv *env, jobject);
extern jclass Java_java_lang_Class_forName__Ljava_lang_String_2 (JNIEnv *env, jclass, jstring);
extern jboolean Java_java_lang_Class_isInstance (JNIEnv *env, jobject, jobject);
extern jboolean Java_java_lang_Class_isAssignableFrom (JNIEnv *env, jobject, jclass);
extern jboolean Java_java_lang_Class_isPrimitive (JNIEnv *env, jobject);
extern jint Java_java_lang_Class_getModifiers (JNIEnv *env, jobject);
extern jclass Java_java_lang_Class_getDeclaringClass (JNIEnv *env, jobject);
extern jobjectArray Java_java_lang_Class_getClasses (JNIEnv *env, jobject);
extern jobjectArray Java_java_lang_Class_getDeclaredClasses (JNIEnv *env, jobject);
extern jobject Java_java_lang_Class_getConstructor (JNIEnv *env, jobject, jobjectArray);
extern jobject Java_java_lang_Class_getDeclaredConstructor (JNIEnv *env, jobject, jobjectArray);
extern jobjectArray Java_java_lang_Class_getConstructors (JNIEnv *env, jobject);
extern jobjectArray Java_java_lang_Class_getDeclaredConstructors (JNIEnv *env, jobject);
extern jobject Java_java_lang_Class_getMethod (JNIEnv *env, jobject, jstring, jobjectArray);
extern jobject Java_java_lang_Class_getDeclaredMethod (JNIEnv *env, jobject, jstring, jobjectArray);
extern jobjectArray Java_java_lang_Class_getMethods (JNIEnv *env, jobject);
extern jobjectArray Java_java_lang_Class_getDeclaredMethods (JNIEnv *env, jobject);
extern jobject Java_java_lang_Class_getField (JNIEnv *env, jobject, jstring);
extern jobject Java_java_lang_Class_getDeclaredField (JNIEnv *env, jobject, jstring);
extern jobjectArray Java_java_lang_Class_getFields (JNIEnv *env, jobject);
extern jobjectArray Java_java_lang_Class_getDeclaredFields (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __java_lang_Class__ */
