/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_io_FileDescriptor__
#define __java_io_FileDescriptor__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern void Java_java_io_FileDescriptor_syncInternal (JNIEnv *env, jobject, jint);
extern jboolean Java_java_io_FileDescriptor_validInternal (JNIEnv *env, jobject, jint);

#ifdef __cplusplus
}
#endif

#endif /* __java_io_FileDescriptor__ */
