/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_nio_MappedByteBufferImpl__
#define __java_nio_MappedByteBufferImpl__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern JNIEXPORT void JNICALL Java_java_nio_MappedByteBufferImpl_unmapImpl (JNIEnv *env, jobject);
extern JNIEXPORT jboolean JNICALL Java_java_nio_MappedByteBufferImpl_isLoadedImpl (JNIEnv *env, jobject);
extern JNIEXPORT void JNICALL Java_java_nio_MappedByteBufferImpl_loadImpl (JNIEnv *env, jobject);
extern JNIEXPORT void JNICALL Java_java_nio_MappedByteBufferImpl_forceImpl (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __java_nio_MappedByteBufferImpl__ */
