/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_net_InetAddress__
#define __java_net_InetAddress__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jstring JNICALL Java_java_net_InetAddress_getLocalHostname (JNIEnv *env, jclass);
JNIEXPORT jbyteArray JNICALL Java_java_net_InetAddress_lookupInaddrAny (JNIEnv *env, jclass);
JNIEXPORT jstring JNICALL Java_java_net_InetAddress_getHostByAddr (JNIEnv *env, jclass, jbyteArray);
JNIEXPORT jobjectArray JNICALL Java_java_net_InetAddress_getHostByName (JNIEnv *env, jclass, jstring);

#ifdef __cplusplus
}
#endif

#endif /* __java_net_InetAddress__ */
