/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_io_FileInputStream__
#define __java_io_FileInputStream__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jlong Java_java_io_FileInputStream_getFileLength (JNIEnv *env, jobject, jint);
extern jlong Java_java_io_FileInputStream_skipInternal (JNIEnv *env, jobject, jint, jlong);
extern jint Java_java_io_FileInputStream_readInternal (JNIEnv *env, jobject, jint, jbyteArray, jint, jint);
extern jint Java_java_io_FileInputStream_open (JNIEnv *env, jobject, jstring);
extern void Java_java_io_FileInputStream_closeInternal (JNIEnv *env, jobject, jint);

#ifdef __cplusplus
}
#endif

#endif /* __java_io_FileInputStream__ */
