/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_lang_VMClassLoader__
#define __java_lang_VMClassLoader__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jclass Java_java_lang_VMClassLoader_defineClass (JNIEnv *env, jclass, jobject, jstring, jbyteArray, jint, jint);
extern void Java_java_lang_VMClassLoader_resolveClass (JNIEnv *env, jclass, jclass);
extern jclass Java_java_lang_VMClassLoader_getPrimitiveClass__Ljava_lang_String_2 (JNIEnv *env, jclass, jstring);

#ifdef __cplusplus
}
#endif

#endif /* __java_lang_VMClassLoader__ */
