/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_io_ObjectOutputStream__
#define __java_io_ObjectOutputStream__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern void Java_java_io_ObjectOutputStream_callWriteMethod (JNIEnv *env, jobject, jobject);
extern jboolean Java_java_io_ObjectOutputStream_getBooleanField (JNIEnv *env, jobject, jobject, jstring);
extern jbyte Java_java_io_ObjectOutputStream_getByteField (JNIEnv *env, jobject, jobject, jstring);
extern jchar Java_java_io_ObjectOutputStream_getCharField (JNIEnv *env, jobject, jobject, jstring);
extern jdouble Java_java_io_ObjectOutputStream_getDoubleField (JNIEnv *env, jobject, jobject, jstring);
extern jfloat Java_java_io_ObjectOutputStream_getFloatField (JNIEnv *env, jobject, jobject, jstring);
extern jint Java_java_io_ObjectOutputStream_getIntField (JNIEnv *env, jobject, jobject, jstring);
extern jlong Java_java_io_ObjectOutputStream_getLongField (JNIEnv *env, jobject, jobject, jstring);
extern jshort Java_java_io_ObjectOutputStream_getShortField (JNIEnv *env, jobject, jobject, jstring);
extern jobject Java_java_io_ObjectOutputStream_getObjectField (JNIEnv *env, jobject, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif

#endif /* __java_io_ObjectOutputStream__ */
